# -*- coding: utf-8 -*-
"""Cisco + GCP course data (CCNA, CCNP Enterprise, GCP Cloud Architect)."""
from _course_data import HERO_IMG, common_meta

BATCH = []

# 1. CCNA
BATCH.append(dict(
    slug="ccna",
    title="CCNA",
    title_html='Cisco Certified<br><em>Network Associate</em>',
    vendor_short="Cisco", watermark="CCNA", crumb_vendor="Cisco",
    subtitle="The most-trusted enterprise networking credential. Routing, switching, automation, security and AI-driven networking on Cisco IOS \u2014 the standard most MY ISPs and enterprises hire on.",
    badges=[("cb-vendor","Cisco Authorized"),("cb-level","Associate"),("cb-new","200-301 v1.1 \u00b7 2026"),("cb-hot","Top Network Hire")],
    hero_meta=common_meta("5 days / 40 hrs","Instructor-Led + Cisco Live Rack","On-site \u00b7 Hybrid",96,"1 September 2026"),
    hero_img=HERO_IMG,
    quick_wins=[
        ("\U0001F310","IOS fluency","Drive Catalyst switches and ISR routers from console"),
        ("\U0001F510","Network security baked in","ACLs, NAT, port security, AAA, DHCP snooping, Zero Trust"),
        ("\U0001F916","Automation & DevOps","Python with Netmiko, Ansible, REST APIs, NETCONF/RESTCONF"),
        ("\U0001F4E1","Wireless & WAN","WLAN controller fundamentals, SD-WAN intro, MPLS"),
    ],
    overview_eyebrow="What this course is",
    overview_head=("CCNA is","the network credential."),
    overview_p1="Cisco CCNA (200-301) is the most widely held enterprise networking certification globally. Almost every Malaysian ISP, telco and enterprise lists CCNA as a baseline expectation for network and infrastructure roles.",
    overview_p2="Nexperts CCNA is taught against a real Cisco rack \u2014 4 Catalyst switches, 2 ISR routers, a 9800-CL wireless controller and a Linux automation host. You don't simulate. You drive Cisco gear.",
    overview_quote="The CCNA exam is timed. Eighteen seconds per question average. We drill speed and accuracy together \u2014 because both are tested.",
    overview_p3="The 200-301 v1.1 update adds AI-driven networking, machine reasoning, automation depth and Wi-Fi 7 wireless. We teach all four with current Malaysian telco and enterprise WAN context.",
    who_for=[
        ("\U0001F4E1","Network+ holders","The natural Cisco-specific specialisation. Network+ taught vendor-neutral. CCNA goes Cisco-deep."),
        ("\U0001F4BB","Junior network engineers","Already in NOC / network ops without certification. CCNA formalises and grows the role."),
        ("\u2601\uFE0F","Cloud engineers","Modern cloud is networked. CCNA gives you the routing, switching and security depth cloud assumes."),
        ("\U0001F50D","ISP / telco staff","Maxis, CelcomDigi, TM, Time \u2014 CCNA is the credential their network engineers hold."),
        ("\U0001F3DB\uFE0F","Govt / GLC IT","Most MY government and GLC network teams require CCNA for advancement."),
        ("\U0001F4DA","Pre-CCNP candidates","CCNA is the prerequisite for the Professional-tier Cisco track."),
    ],
    prereqs=[
        "Network+ or 1+ year of networking experience",
        "Comfort with command-line interfaces",
        "Understanding of TCP/IP and subnetting",
        "Familiarity with Windows and Linux basics",
    ],
    prereqs_note="No Network+? CCNA is still accessible. Ask us about our pre-CCNA primer.",
    curriculum_eyebrow="Course Curriculum",
    curriculum_head=("Six domains.","Cisco end-to-end."),
    curriculum_intro="200-301 v1.1 covers Network Fundamentals, Network Access, IP Connectivity, IP Services, Security Fundamentals and Automation & Programmability. We sequence by real-world build order.",
    modules=[
        ("01","Network Fundamentals & IOS",[
            "Cisco IOS modes, config files, copy commands",
            "Switching fundamentals \u2014 MAC tables, frames, VLANs",
            "IPv4 / IPv6 addressing and subnetting",
            "Ethernet, fibre, wireless interfaces",
            "Cabling and hardware troubleshooting",
            "Lab: Bring a stack of switches up from factory default",
        ]),
        ("02","Switching, VLANs & Spanning Tree",[
            "VLAN configuration and trunking (802.1Q, DTP)",
            "Inter-VLAN routing on a Layer-3 switch",
            "Spanning Tree \u2014 RSTP, MSTP, root bridge tuning",
            "EtherChannel and LACP",
            "Port security and DHCP snooping",
            "Lab: Build a 4-VLAN office on a real switch stack",
        ]),
        ("03","Routing \u2014 Static, OSPFv2, OSPFv3",[
            "Static routes, default routes, summary routes",
            "OSPFv2 single-area and multi-area",
            "OSPFv3 for IPv6",
            "Routing decision logic and metrics",
            "First-Hop Redundancy \u2014 HSRP, VRRP",
            "Lab: Build a 3-area OSPFv2 + OSPFv3 dual-stack network",
        ]),
        ("04","IP Services, NAT & Wireless",[
            "DHCP, DNS, NTP and SNMP",
            "NAT \u2014 static, dynamic, PAT",
            "Wireless architecture and WLC fundamentals",
            "AAA \u2014 RADIUS and TACACS+",
            "Syslog and centralised logging",
            "Lab: Configure a wireless network with AAA",
        ]),
        ("05","Security & Automation",[
            "Access Control Lists (ACLs) \u2014 standard and extended",
            "Layer-2 security best practices",
            "Site-to-Site VPN concepts (IPsec)",
            "REST APIs and JSON for network automation",
            "Python with Netmiko, Ansible introduction",
            "Lab: Automate VLAN provisioning across 4 switches with Python",
        ]),
    ],
    labs_eyebrow="Hands-On Cisco Live Rack",
    labs_head=("40+ rack labs.","Real Cisco IOS."),
    labs_intro="Two Cisco Catalyst 9300 switches, two Catalyst 9200 access switches, two ISR 4321 routers, a Catalyst 9800-CL wireless controller and a Linux automation host. Every lab below runs against this rack.",
    labs=[
        ("01","Console Day 1","Bring 4 factory-default switches up. Stack them. Verify console.","lt-recon","Foundation"),
        ("02","VLANs & Trunks","Build a 4-VLAN office across the stack with 802.1Q trunks.","lt-attack","Switching"),
        ("03","Spanning Tree Tuning","Force STP root bridge selection. Validate with show commands.","lt-attack","STP"),
        ("04","OSPF Multi-Area","Build a 3-area OSPF topology. Tune metrics. Force convergence.","lt-attack","Routing"),
        ("05","HSRP Redundancy","Configure HSRP between two L3 switches. Test failover.","lt-attack","HA"),
        ("06","Wireless WLC","Bring up the 9800-CL. Onboard 2 APs. Configure 3 SSIDs.","lt-recon","Wireless"),
        ("07","ACL Hardening","Lock down sensitive subnets with extended ACLs.","lt-defend","Security"),
        ("08","Python Netmiko","Provision VLANs across 4 switches via Python script.","lt-attack","Automation"),
        ("09","RESTCONF Inventory","Pull inventory from 6 devices via RESTCONF and JSON.","lt-recon","API"),
    ],
    labs_footer="+ 31 additional rack tasks. Rack-time access for 60 days post-course.",
    exam_eyebrow="Exam Information",
    exam_head=("One exam.","Speed and breadth."),
    exam_intro="CCNA 200-301 is a 120-minute exam with 100\u2013120 questions covering all six domains. Time pressure is the real challenge \u2014 eighteen seconds per question average, with simulator items eating extra time.",
    exam_main=dict(name="CCNA 200-301 v1.1 Exam",rows=[
        ("Questions","100\u2013120 multi-format incl. simulators"),
        ("Duration","120 minutes"),
        ("Passing score",'<span class="pass-highlight">Variable (~825 / 1000)</span>'),
        ("Format","Pearson VUE / Online proctor"),
        ("Validity","3 years (CE renewal)"),
        ("Industry avg pass rate",'<span class="fail-note">~68% first attempt</span>'),
        ("Nexperts pass rate",'<span class="pass-highlight">96% first attempt</span>'),
    ]),
    exam_optional=dict(name="Cisco Career Trajectory",rows=[
        ("Stacks with","CCNA \u2192 CCNP \u2192 CCIE"),
        ("MY salary uplift","Average +RM 1,500/mo post-cert"),
        ("Voucher","Bundled \u2014 Cisco voucher included"),
        ("CE programme","CE points renew CCNA without re-exam"),
        ("Pre-bridge","Required for any CCNP track"),
        ("Career fit","Network engineer, NOC engineer, telco support"),
        ("Most-hired","#1 enterprise networking credential globally"),
    ]),
    mock_title="Our CCNA 3-Mock Programme",
    mock_programme=[
        ("01","Diagnostic Mock","Day 2. Maps weak domains. Average score: 64%."),
        ("02","Simulator Mock","Day 4. Sim-only practice on real Cisco gear. Average score: 78%."),
        ("03","Final Clearance","Day 5. Full timed simulation. 84%+ before booking. Average score: 87%."),
    ],
    pass_rate=96,
    pass_head_html='96% of our CCNA candidates<br>pass <em>on first attempt.</em>',
    pass_intro="The global CCNA first-attempt rate is around 68%. Our 96% comes from a real Cisco rack, dedicated simulator-question coaching, and an instructor who has run network operations for two MY ISPs across the past 12 years.",
    pass_pills=["Real Cisco rack","Simulator coaching","96% first attempt","Python automation playbook","Free retake voucher"],
    pass_compare=[
        ("Industry average: ~68%","Most candidates fail on simulator items. They know the answer; they cannot configure it on a Cisco IOS prompt under time pressure."),
        ("Nexperts: 96%","We make you configure it on real Cisco IOS \u2014 not a simulator simulator. We drill speed. We hard-gate on a 84% mock before booking."),
    ],
    next_eyebrow="Your Certification Journey",
    next_head=("CCNA opens","every Cisco track."),
    next_steps_intro="From CCNA you specialise into Enterprise (CCNP Enterprise), Security (CCNP Security), Service Provider, Data Center, or Collaboration tracks.",
    next_steps=[
        ("Before this","Network+","Network+ provides the vendor-neutral fluency CCNA assumes.","View Network+ \u2192"),
        ("You are here","CCNA 200-301 v1.1","Cisco's enterprise networking associate credential. Routing, switching, wireless, security, automation.","Currently viewing \u2192"),
        ("Recommended next","CCNP Enterprise","Enterprise networking depth \u2014 the natural next step for routing/switching engineers.","View CCNP Enterprise \u2192"),
    ],
    path_name="Cisco network engineer",
    path_chips=[("Network+","prev"),("CCNA","you"),("CCNP Enterprise","next"),("CCIE Enterprise","prev"),("CCDE","prev")],
    salary_html='Expected salary range after CCNA: <strong style="color:#86efac">RM 5,500 \u2013 RM 9,500/month</strong> for network engineer and NOC roles in Malaysian enterprises and ISPs.',
    reviews_eyebrow="Student Reviews",
    reviews_head=("What our CCNA","graduates say."),
    reviews_summary=("4.9",91,7,2,231),
    reviews=[
        ("\u2605\u2605\u2605\u2605\u2605","Real Cisco rack made the difference. Other CCNA prep is Packet Tracer. Nexperts gave me real IOS console under real time pressure. Sim section was familiar territory.","rav-b","HF","Hisham Faizal","Network Engineer \u00b7 TM Wholesale","\u2713 Passed first attempt \u00b7 911 / 825"),
        ("\u2605\u2605\u2605\u2605\u2605","OSPF made finally clicked when I had to debug my own broken topology at 11pm. The instructor's patience drilling 'show ip ospf neighbor' into me paid off in spades.","rav-m","JV","Jeevan Vasanthan","NOC Engineer \u00b7 CelcomDigi","\u2713 Passed first attempt \u00b7 871 / 825"),
        ("\u2605\u2605\u2605\u2605\u2605","Python automation module was unexpected and timely. Three weeks later I automated VLAN provisioning at my company \u2014 saved 4 hours per week immediately.","rav-g","NL","Norhayati Latif","Senior Engineer \u00b7 Maxis","\u2713 Passed first attempt \u00b7 851 / 825"),
        ("\u2605\u2605\u2605\u2605\u2605","Simulator drills were brutal. Five sims on day four, all with timer running. The real exam felt slower than the practice.","rav-a","KW","Kar Wei Tan","Junior NOC \u00b7 Time dotCom","\u2713 Passed first attempt \u00b7 891 / 825"),
    ],
    price="RM 3,300", price_orig="RM 3,900", price_save="Save 15%",
    price_note="Per person \u00b7 Includes Cisco voucher, rack-time, courseware",
    sidebar_meta=[
        ("Duration","5 days / 40 hrs"),
        ("Next intake","1 September 2026"),
        ("Format","On-site (rack lab)"),
        ("Level","Associate"),
        ("Language","English \u00b7 BM available"),
        ("Cert body","Cisco"),
        ("Exam",'<span class="smeta-badge">Included</span>'),
    ],
    whats_included=[
        "Cisco official 200-301 courseware",
        "Cisco exam voucher",
        "Rack-time access (real IOS) for 60 days",
        "3 full timed mock exams",
        "Simulator-question coaching workshop",
        "Python automation playbook",
        "Post-course instructor access (45 days)",
        "Free retake voucher (conditions apply)",
        "Digital badge via Cisco Certifications",
    ],
    verify_items=[
        "Verifiable on Cisco Certifications portal",
        "Digital badge via Credly",
        "Recognised globally and across MY ISPs/telcos",
        "Stacks toward CCNP and CCIE",
    ],
    guarantee_text="Hit the 84% mock threshold and don't pass first attempt? Cisco retake voucher on us.",
))


# 2. CCNP Enterprise
BATCH.append(dict(
    slug="ccnp-enterprise",
    title="CCNP Enterprise",
    title_html='Cisco Certified Network<br><em>Professional Enterprise</em>',
    vendor_short="Cisco", watermark="CCNP", crumb_vendor="Cisco",
    subtitle="Cisco's professional-tier enterprise networking credential. Advanced routing, SD-WAN, automation, virtualisation and infrastructure security \u2014 senior engineer territory.",
    badges=[("cb-vendor","Cisco Authorized"),("cb-level","Professional"),("cb-new","350-401 + concentration \u00b7 2026"),("cb-hot","Senior Hire")],
    hero_meta=common_meta("8 days / 64 hrs","Instructor-Led + Live Rack","On-site \u00b7 Hybrid",93,"8 September 2026"),
    hero_img=HERO_IMG,
    quick_wins=[
        ("\U0001F310","Advanced routing depth","BGP, EIGRP, advanced OSPF, route-maps and policy"),
        ("\u2601\uFE0F","SD-WAN mastery","Cisco SD-WAN architecture, vManage, vSmart, vBond, edge"),
        ("\U0001F916","Programmability deep","NETCONF, RESTCONF, YANG, Cisco DNAC, model-driven telemetry"),
        ("\U0001F510","Infrastructure security","DMVPN, GETVPN, CoPP, port security at scale"),
    ],
    overview_eyebrow="What this course is",
    overview_head=("CCNP Enterprise is","senior network territory."),
    overview_p1="CCNP Enterprise (350-401 ENCOR + concentration exam) validates that you can design, implement, operate and troubleshoot enterprise networks at scale. It is the credential that distinguishes senior network engineers in Malaysian banks, telcos and large enterprises.",
    overview_p2="At Nexperts, CCNP Enterprise is delivered against a multi-rack lab including Cisco SD-WAN edges and vManage. We focus on the four highest-value concentrations \u2014 ENCOR core plus your choice of Advanced Routing (300-410), SD-WAN (300-415) or Wireless (300-430).",
    overview_quote="CCNP is not a single exam. It is a body of work \u2014 ENCOR plus a concentration. We coach the body of work, not just two exams.",
    overview_p3="The 2026 curriculum strengthens cloud-edge integration, modern automation (Cisco DNAC, ThousandEyes), zero-trust enforcement and Wi-Fi 7. We teach with current MY service-provider and enterprise WAN context.",
    who_for=[
        ("\U0001F4E1","CCNA-certified engineers","The natural progression. CCNA proved you can run a network. CCNP proves you can design it."),
        ("\u2601\uFE0F","Senior NOC / network engineers","Move from operations into design and architecture credibly."),
        ("\U0001F3DB\uFE0F","Banking infrastructure leads","BNM RMiT alignment requires advanced network design discipline."),
        ("\U0001F4CA","Pre-CCIE candidates","CCNP Enterprise is the runway for the CCIE Enterprise lab exam."),
        ("\U0001F50D","Network architects pivoting","Enterprise architects formalising into Cisco-specific credentials."),
        ("\U0001F4DA","ISP senior engineers","Maxis, TM, CelcomDigi, Time \u2014 CCNP is widely required for L3/L4 ops roles."),
    ],
    prereqs=[
        "CCNA 200-301 or equivalent advanced network experience",
        "3+ years of Cisco network experience",
        "Strong routing fluency \u2014 OSPF, EIGRP at minimum",
        "Comfort with Python and Linux command-line",
    ],
    prereqs_note="Don't have CCNA? Ask us about our 13-day combined CCNA \u2192 CCNP Enterprise track.",
    curriculum_eyebrow="Course Curriculum",
    curriculum_head=("ENCOR + concentration.","The full senior path."),
    curriculum_intro="CCNP Enterprise = ENCOR (350-401) plus one concentration. We deliver ENCOR comprehensively and offer concentration depth in Advanced Routing, SD-WAN, or Wireless \u2014 your choice.",
    modules=[
        ("01","Architecture & Virtualisation",[
            "Enterprise network architecture \u2014 hierarchical, spine-leaf",
            "Hardware virtualisation \u2014 VRF, VLAN, virtual switches",
            "Cisco SD-Access architecture",
            "Hypervisor-aware networking \u2014 vSwitch, NSX-T integration",
            "Cloud connectivity options \u2014 Direct Connect, ExpressRoute, Cloud OnRamp",
            "Lab: Design a hybrid cloud-on-prem topology",
        ]),
        ("02","Advanced Routing & BGP",[
            "OSPF advanced features \u2014 LSA filtering, summaries, virtual links",
            "EIGRP advanced features \u2014 metric tuning, stub, route-maps",
            "BGP fundamentals \u2014 iBGP, eBGP, attributes, path selection",
            "Route maps and route filtering at scale",
            "Multicast routing introduction",
            "Lab: Build an iBGP/eBGP scenario with route policy",
        ]),
        ("03","Infrastructure Services & QoS",[
            "DHCP at scale, DHCPv6, IPv6 features",
            "QoS \u2014 marking, queueing, shaping, policing",
            "FHRP advanced \u2014 HSRP, VRRP, GLBP",
            "Multicast \u2014 PIM, IGMP",
            "Network services \u2014 SNMPv3, NetFlow, IPSLA",
            "Lab: Build an enterprise QoS profile end-to-end",
        ]),
        ("04","Infrastructure Security",[
            "Control Plane Policing (CoPP)",
            "Site-to-Site VPN advanced \u2014 DMVPN, GETVPN",
            "AAA \u2014 RADIUS, TACACS+, ISE integration",
            "Wireless security \u2014 WPA3-Enterprise, EAP-TLS",
            "Layer-2 security at scale \u2014 DAI, IPSG, BPDU Guard",
            "Lab: Build DMVPN with hub-and-spoke encryption",
        ]),
        ("05","Automation & Programmability",[
            "NETCONF, RESTCONF and YANG models",
            "Cisco DNAC fundamentals",
            "Model-driven telemetry vs SNMP",
            "Python automation with NAPALM",
            "Ansible playbooks for network ops",
            "Lab: Automate config rollouts with Ansible across 12 devices",
        ]),
    ],
    labs_eyebrow="Hands-On Multi-Rack",
    labs_head=("64 advanced labs.","Plus a 4-day SD-WAN sim."),
    labs_intro="The Nexperts CCNP Enterprise environment includes two Cisco racks plus a virtual SD-WAN setup with vManage, vSmart, vBond and 6 edge routers. You drive the architecture daily.",
    labs=[
        ("01","BGP Path Selection","Force traffic through a specific iBGP path using LOCAL_PREF and AS_PATH prepending.","lt-attack","BGP"),
        ("02","DMVPN Hub-Spoke","Build DMVPN phase 3 with EIGRP across encrypted spokes.","lt-defend","VPN"),
        ("03","SD-WAN vManage","Onboard 6 edge routers. Configure SLA-based policies.","lt-recon","SD-WAN"),
        ("04","Cisco ISE AAA","Integrate ISE with switches. Enforce per-port 802.1X.","lt-defend","Identity"),
        ("05","Multicast PIM","Build PIM sparse-mode multicast across 4 routers.","lt-attack","Multicast"),
        ("06","QoS End-to-End","Build LLQ + CBWFQ for voice/video/data across an MPLS WAN.","lt-attack","QoS"),
        ("07","DNAC Provisioning","Provision a new branch through Cisco DNAC templates.","lt-recon","DNAC"),
        ("08","Telemetry Pipeline","Build model-driven telemetry into a Grafana dashboard.","lt-defend","Telemetry"),
        ("09","Ansible at Scale","Roll out 200 lines of config across 12 devices via Ansible.","lt-attack","Automation"),
    ],
    labs_footer="+ 55 additional rack tasks. Rack-time access for 90 days post-course.",
    exam_eyebrow="Exam Information",
    exam_head=("Two exams.","ENCOR + concentration."),
    exam_intro="CCNP Enterprise requires passing ENCOR (350-401) plus one concentration exam (300-410, 300-415, 300-420 etc). Most students choose Advanced Routing or SD-WAN as their concentration.",
    exam_main=dict(name="ENCOR 350-401 v1.1 Exam",rows=[
        ("Questions","90\u2013110 multi-format incl. simulators"),
        ("Duration","120 minutes"),
        ("Passing score",'<span class="pass-highlight">Variable (~825 / 1000)</span>'),
        ("Format","Pearson VUE"),
        ("Validity","3 years (CE renewal)"),
        ("Industry avg pass rate",'<span class="fail-note">~61% first attempt</span>'),
        ("Nexperts pass rate",'<span class="pass-highlight">93% first attempt</span>'),
    ]),
    exam_optional=dict(name="Concentration Exam (Choose One)",rows=[
        ("300-410 ENARSI","Advanced Routing focus \u2014 BGP, route policy"),
        ("300-415 ENSDWI","SD-WAN focus \u2014 Cisco SD-WAN architecture"),
        ("300-420 ENSLD","Enterprise Design focus"),
        ("300-425 ENWLSD","Wireless Design focus"),
        ("300-430 ENWLSI","Wireless Implementation focus"),
        ("Voucher","Both exams bundled in this course"),
        ("Pre-bridge","Required for CCIE Enterprise lab exam"),
    ]),
    mock_title="Our CCNP Enterprise 4-Mock Programme",
    mock_programme=[
        ("01","Diagnostic ENCOR Mock","Day 2. Maps weak ENCOR areas. Average score: 58%."),
        ("02","Simulator-Heavy ENCOR Mock","Day 4. Real-rack simulator practice. Average score: 73%."),
        ("03","ENCOR Final Clearance","Day 6. Full timed simulation. 80%+ before booking. Average score: 86%."),
        ("04","Concentration Mock","Day 8. Concentration-specific simulation. 80%+ before booking. Average score: 84%."),
    ],
    pass_rate=93,
    pass_head_html='93% of our CCNP Enterprise<br>candidates pass <em>both exams.</em>',
    pass_intro="The combined first-attempt rate for CCNP Enterprise (ENCOR + concentration) is around 61%. Our 93% comes from multi-rack labs, dedicated SD-WAN simulation and an instructor who maintains active CCIE Enterprise lab credentials.",
    pass_pills=["Multi-rack lab","SD-WAN simulation","93% combined pass","CCIE-track instructor","90-day rack access"],
    pass_compare=[
        ("Industry average: ~61%","Most candidates pass one exam (usually ENCOR) and stall on the concentration. They underestimate the depth required for the second exam."),
        ("Nexperts: 93%","We treat both exams as one body of work. We schedule them within 30 days. We hard-gate at 80% on both mocks before booking either."),
    ],
    next_eyebrow="Your Certification Journey",
    next_head=("CCNP is the","CCIE runway."),
    next_steps_intro="From CCNP Enterprise you go laterally into other professional tracks (CCNP Security, CCNP Service Provider) or vertically into CCIE Enterprise.",
    next_steps=[
        ("Before this","CCNA 200-301","CCNA fluency is the prerequisite. Without it, CCNP feels overwhelming.","View CCNA \u2192"),
        ("You are here","CCNP Enterprise","Senior Cisco enterprise engineer. Advanced routing, SD-WAN, automation, security, design.","Currently viewing \u2192"),
        ("Recommended next","CCIE Enterprise or CCNP Security","CCIE is the expert lab exam. CCNP Security pivots into security architecture.","View CCIE \u2192"),
    ],
    path_name="Cisco enterprise architect",
    path_chips=[("CCNA","prev"),("CCNP Enterprise","you"),("CCIE Enterprise","next"),("CCDE","prev"),("Cisco Champion","prev")],
    salary_html='Expected salary range after CCNP Enterprise: <strong style="color:#86efac">RM 9,500 \u2013 RM 16,500/month</strong> for senior network engineer and architect roles in Malaysian enterprises.',
    reviews_eyebrow="Student Reviews",
    reviews_head=("What our CCNP","graduates say."),
    reviews_summary=("4.9",90,8,2,107),
    reviews=[
        ("\u2605\u2605\u2605\u2605\u2605","Multi-rack environment was unique. SD-WAN with vManage was something I'd only seen in Cisco demos. Nexperts let me drive it. Six weeks later, I led an SD-WAN rollout at my company.","rav-b","SI","Sivakumar Iyer","Senior Network Engineer \u00b7 CIMB","\u2713 Passed both exams (ENCOR + ENSDWI)"),
        ("\u2605\u2605\u2605\u2605\u2605","BGP path selection finally clicked through hands-on debugging. Three months later I'm troubleshooting our ISP peering issues confidently.","rav-m","HM","Hadi Mansor","Network Architect \u00b7 Maxis","\u2713 Passed both exams (ENCOR + ENARSI)"),
        ("\u2605\u2605\u2605\u2605\u2605","DNAC + telemetry into Grafana was forward-looking. Built that exact stack at my GLC last month. Visibility is night and day.","rav-g","CL","Cheng Loon Wong","Lead Engineer \u00b7 PETRONAS Digital","\u2713 Passed both exams"),
        ("\u2605\u2605\u2605\u2605\u2605","Eight days of intensive coaching and a real-rack environment. Zero regret. Now starting CCIE Enterprise prep.","rav-a","RA","Razlin Ahmad","Network Architect \u00b7 Bank Islam","\u2713 Passed both exams (ENCOR + ENARSI)"),
    ],
    price="RM 5,200", price_orig="RM 6,200", price_save="Save 16%",
    price_note="Per person \u00b7 Includes both Cisco vouchers, rack + SD-WAN sim, courseware",
    sidebar_meta=[
        ("Duration","8 days / 64 hrs"),
        ("Next intake","8 September 2026"),
        ("Format","On-site (multi-rack)"),
        ("Level","Professional"),
        ("Language","English"),
        ("Cert body","Cisco"),
        ("Exam",'<span class="smeta-badge">Bundled x2</span>'),
    ],
    whats_included=[
        "Cisco official ENCOR + concentration courseware",
        "Cisco exam vouchers (ENCOR + 1 concentration)",
        "90-day rack-time + SD-WAN sim access",
        "4 full timed mock exams",
        "Concentration choice \u2014 ENARSI / ENSDWI / ENWLSI",
        "Cisco DNAC + automation playbook",
        "Post-course instructor access (60 days)",
        "Free retake voucher (conditions apply)",
        "Digital badge via Cisco Certifications",
    ],
    verify_items=[
        "Verifiable on Cisco Certifications portal",
        "Digital badge via Credly",
        "Recognised across MY banks, telcos and ISPs",
        "Pathway to CCIE Enterprise lab exam",
    ],
    guarantee_text="Hit the 80% mock threshold on both exams and don't pass either first attempt? Cisco retake voucher on us.",
))


# 3. GCP Professional Cloud Architect
BATCH.append(dict(
    slug="gcp-professional-cloud-architect",
    title="GCP Professional Cloud Architect",
    title_html='Google Cloud<br><em>Professional Cloud Architect</em>',
    vendor_short="Google Cloud", watermark="GCP", crumb_vendor="Google Cloud",
    subtitle="The highest-value GCP credential. Design and build secure, scalable, highly available cloud architectures on Google Cloud \u2014 the architect role most-hired by GCP-using MY enterprises.",
    badges=[("cb-vendor","Google Cloud Authorized"),("cb-level","Professional"),("cb-new","2026 Updated"),("cb-hot","Top GCP Hire")],
    hero_meta=common_meta("5 days / 40 hrs","Instructor-Led + GCP Sandbox","On-site \u00b7 Hybrid",94,"15 September 2026"),
    hero_img=HERO_IMG,
    quick_wins=[
        ("\U0001F30E","Cross-region design","Multi-region failover, global load balancing, traffic steering"),
        ("\U0001F510","IAM & security architecture","Resource hierarchy, IAM, VPC Service Controls, Beyond Corp"),
        ("\U0001F4DA","Migration & modernisation","Anthos, Migrate to Containers, Database Migration Service"),
        ("\U0001F4CA","Data + AI integration","BigQuery, Vertex AI, Pub/Sub \u2014 modern data-first architecture"),
    ],
    overview_eyebrow="What this course is",
    overview_head=("GCP PCA is","architect leadership."),
    overview_p1="The Google Cloud Professional Cloud Architect (PCA) is GCP's flagship architecture credential. It validates that you can design and operate secure, scalable, highly available cloud solutions on Google Cloud \u2014 spanning identity, networking, data, ML and migration domains.",
    overview_p2="At Nexperts, PCA is delivered against a multi-project GCP organisation with VPC Service Controls, Anthos and BigQuery pre-loaded. You architect across two MY case studies \u2014 a fintech and a healthcare provider.",
    overview_quote="GCP architecture is opinionated \u2014 Google has clear preferences about how to do things. PCA tests whether you align with those preferences. We coach the alignment, not just the services.",
    overview_p3="The 2026 update emphasises Vertex AI, Gemini integration, modern data-mesh architectures and Anthos hybrid patterns. We teach with current MY GCP deployments \u2014 banking analytics, public-sector data residency, healthcare sovereignty.",
    who_for=[
        ("\u2601\uFE0F","AWS / Azure architects","Multi-cloud architects adding GCP to their toolkit."),
        ("\U0001F4CA","Data engineers going architect","BigQuery and Vertex AI fluency naturally extends into PCA."),
        ("\U0001F3DB\uFE0F","Public-sector cloud leads","MyDigital's emphasis on multi-cloud means GCP literacy is increasingly required."),
        ("\U0001F4BC","Solutions consultants","Big-4 consultancies require multi-cloud architects \u2014 PCA fills the GCP gap."),
        ("\U0001F50D","Pre-Hero candidates","PCA is the credible base for Google Cloud Champion innovator recognition."),
        ("\U0001F4DA","Senior cloud engineers","Move from operations into architecture credibly."),
    ],
    prereqs=[
        "Associate Cloud Engineer (recommended)",
        "3+ years of GCP or cross-cloud architecture experience",
        "Strong networking, IAM and DR design fluency",
        "Familiarity with BigQuery, GKE, IAM, VPC",
    ],
    prereqs_note="Don't have ACE? PCA is open without it but more demanding. Ask us about our combined ACE \u2192 PCA track.",
    curriculum_eyebrow="Course Curriculum",
    curriculum_head=("Six domains.","GCP architecture mastery."),
    curriculum_intro="PCA covers Designing and Planning, Managing and Provisioning, Designing for Security and Compliance, Analysing and Optimising, Managing Implementation, and Reliability Engineering. We deliver via two MY case studies.",
    modules=[
        ("01","Resource Hierarchy & Identity",[
            "Organisation \u2192 Folder \u2192 Project hierarchy",
            "IAM principles \u2014 primitive, predefined, custom",
            "Service accounts and workload identity federation",
            "VPC Service Controls and Beyond Corp",
            "Identity-Aware Proxy (IAP) for app access",
            "Lab: Build a 4-folder Org with IAM hierarchy",
        ]),
        ("02","Networking & Connectivity",[
            "Shared VPC, peering, VPN, Interconnect",
            "Global vs regional load balancing",
            "Cloud Armor and Cloud CDN",
            "Service Networking and Private Service Connect",
            "Anthos Service Mesh (Istio) fundamentals",
            "Lab: Architect cross-region connectivity for a fintech",
        ]),
        ("03","Compute, Storage & Data",[
            "Compute Engine, GKE, Cloud Run, Functions",
            "Storage tiers \u2014 Standard, Nearline, Coldline, Archive",
            "Cloud SQL, Spanner, Firestore, Bigtable",
            "BigQuery architecture and slot reservations",
            "Pub/Sub, Dataflow, Dataproc patterns",
            "Lab: Architect a healthcare data platform",
        ]),
        ("04","Security & Compliance",[
            "Encryption \u2014 default, CMEK, CSEK, Cloud HSM",
            "Security Command Center and Chronicle",
            "Data Loss Prevention (DLP) for sensitive data",
            "Compliance \u2014 ISO 27001, PCI, MyDigital, BNM RMiT",
            "Confidential VMs and confidential GKE",
            "Lab: Lock down a banking data pipeline to BNM-grade",
        ]),
        ("05","Reliability, Migration & AI",[
            "SRE principles \u2014 SLOs, SLIs, error budgets",
            "Cloud Monitoring, Logging, Trace, Profiler",
            "Migration paths \u2014 lift, modernise, refactor",
            "Anthos for hybrid and multi-cloud",
            "Vertex AI, Gemini and AI architecture patterns",
            "Lab: Migrate a fictional MY hospital workload to GCP",
        ]),
    ],
    labs_eyebrow="Hands-On Multi-Project GCP Org",
    labs_head=("40 architect labs.","Two MY case studies."),
    labs_intro="The Nexperts PCA environment is a multi-project GCP organisation with VPC Service Controls, Anthos cluster and BigQuery pre-loaded. You architect a fintech and a healthcare case across the 5 days.",
    labs=[
        ("01","Org & IAM Hierarchy","Build a 4-folder Org. Apply IAM at folder vs project scope.","lt-defend","Identity"),
        ("02","Shared VPC + Service Controls","Design Shared VPC across 3 projects with VPC SC perimeter.","lt-defend","Networking"),
        ("03","Global Load Balancer","Build a multi-region GLB with traffic steering.","lt-recon","Networking"),
        ("04","BigQuery Slot Architecture","Design BigQuery slot reservations for a fintech analytics workload.","lt-recon","Data"),
        ("05","Anthos Hybrid Cluster","Onboard a simulated on-prem cluster to Anthos. Apply policy.","lt-recon","Hybrid"),
        ("06","CMEK Banking Pipeline","Encrypt a banking data pipeline with CMEK and DLP.","lt-defend","Security"),
        ("07","Cloud SQL HA + DR","Design a multi-region Cloud SQL with read replicas.","lt-defend","DR"),
        ("08","Vertex AI Workflow","Architect a Vertex AI training + serving workflow with monitoring.","lt-recon","AI"),
        ("09","Final Capstone","Present full architecture to a fictional CIO. Defend trade-offs.","lt-recon","Capstone"),
    ],
    labs_footer="+ 31 additional architect tasks. Sandbox access for 90 days post-course.",
    exam_eyebrow="Exam Information",
    exam_head=("One exam.","Case-study heavy."),
    exam_intro="PCA is built around 4 case studies. Each case study has 5\u20137 design questions where you must choose the best GCP service combination from 4\u20135 plausible options. Theory alone won't pass.",
    exam_main=dict(name="GCP Professional Cloud Architect Exam",rows=[
        ("Questions","50\u201360 incl. case studies"),
        ("Duration","120 minutes"),
        ("Passing score","Pass / Fail (Google does not publish scaled score)"),
        ("Format","Pearson VUE / Online"),
        ("Validity","2 years"),
        ("Industry avg pass rate",'<span class="fail-note">~60% first attempt</span>'),
        ("Nexperts pass rate",'<span class="pass-highlight">94% first attempt</span>'),
    ]),
    exam_optional=dict(name="GCP Career Trajectory",rows=[
        ("Stacks with","ACE \u2192 PCA \u2192 PCSE / PCNE / PDE"),
        ("MY salary uplift","Average +RM 2,500/mo post-cert"),
        ("Voucher","Bundled \u2014 Google Cloud voucher included"),
        ("Renewal","2-year cycle via re-exam"),
        ("Champion track","Pathway to Google Cloud Champion innovator"),
        ("Most-paid","Top-3 GCP credential by salary in MY"),
        ("Career fit","Cloud architect, GCP CCoE lead, principal architect"),
    ]),
    mock_title="Our PCA 3-Mock Programme",
    mock_programme=[
        ("01","Diagnostic Mock","Day 2. Maps weak architecture areas. Average score: 56%."),
        ("02","Case-Study Mock","Day 4. Two-case scenario simulation. Average score: 71%."),
        ("03","Final Clearance","Day 5. Full timed simulation. 82%+ before booking. Average score: 85%."),
    ],
    pass_rate=94,
    pass_head_html='94% of our GCP PCA<br>candidates pass <em>on first attempt.</em>',
    pass_intro="The global PCA first-attempt rate is around 60%. Our 94% comes from two MY-grounded case studies, instructor stand-up reviews of every design decision, and a hard 82% mock-clearance gate.",
    pass_pills=["Two MY case studies","Architect stand-ups","94% first attempt","BNM/PDPA design overlay","90-day sandbox"],
    pass_compare=[
        ("Industry average: ~60%","Most candidates know GCP services but cannot articulate trade-offs in case-study scenarios. They also under-prepare for VPC Service Controls and Anthos depth."),
        ("Nexperts: 94%","We force you to defend every design decision in stand-ups. We coach trade-off articulation. We hard-gate at 82% mock before booking."),
    ],
    next_eyebrow="Your Certification Journey",
    next_head=("PCA is","GCP architect apex."),
    next_steps_intro="From PCA you specialise into Security (PCSE), Networking (PCNE), Data Engineer (PDE) or Machine Learning (PMLE).",
    next_steps=[
        ("Before this","Associate Cloud Engineer","ACE provides the operational fluency PCA assumes. Without it, PCA is steep.","View ACE \u2192"),
        ("You are here","GCP Professional Cloud Architect","GCP architect mastery. Identity, networking, data, AI, migration and hybrid covered end-to-end.","Currently viewing \u2192"),
        ("Recommended next","PCSE or PDE","PCSE specialises into security architecture. PDE pivots into data engineering depth.","View PCSE \u2192"),
    ],
    path_name="GCP architect",
    path_chips=[("ACE","prev"),("PCA","you"),("PCSE / PDE","next"),("Champion Innovator","prev"),("Principal Cloud Architect","prev")],
    salary_html='Expected salary range after PCA: <strong style="color:#86efac">RM 12,500 \u2013 RM 21,000/month</strong> for cloud architect and CCoE lead roles in Malaysian GCP-using enterprises.',
    reviews_eyebrow="Student Reviews",
    reviews_head=("What our PCA","graduates say."),
    reviews_summary=("4.9",92,7,1,76),
    reviews=[
        ("\u2605\u2605\u2605\u2605\u2605","Two MY case studies grounded everything. Other PCA prep is generic. Nexperts forced trade-offs through BNM and PDPA constraints \u2014 the way real MY architecture decisions actually work.","rav-b","DN","Dilip Naidu","Principal Architect \u00b7 Allianz Malaysia","\u2713 Passed first attempt"),
        ("\u2605\u2605\u2605\u2605\u2605","VPC Service Controls finally clicked. I'd been avoiding them for a year. Nexperts forced me to architect with them. Six weeks later we deployed VPC SC at our fintech.","rav-m","WL","Wei Lin Goh","Cloud Architect \u00b7 BigPay","\u2713 Passed first attempt"),
        ("\u2605\u2605\u2605\u2605\u2605","Anthos hybrid module was forward-looking. We're rolling Anthos out at our hospital network and the course made me the technical lead.","rav-g","DR","Dr Rafiqah Hassan","Healthcare CIO \u00b7 IHH Malaysia","\u2713 Passed first attempt"),
        ("\u2605\u2605\u2605\u2605\u2605","Stand-up defences were brutal but transformative. Each case study question on the exam felt like another stand-up. Nothing surprised me.","rav-a","JT","Jasmine Tan","Senior Cloud Consultant \u00b7 PwC MY","\u2713 Passed first attempt"),
    ],
    price="RM 5,400", price_orig="RM 6,400", price_save="Save 16%",
    price_note="Per person \u00b7 Includes Google Cloud voucher, multi-project sandbox, courseware",
    sidebar_meta=[
        ("Duration","5 days / 40 hrs"),
        ("Next intake","15 September 2026"),
        ("Format","On-site \u00b7 Hybrid"),
        ("Level","Professional"),
        ("Language","English"),
        ("Cert body","Google Cloud"),
        ("Exam",'<span class="smeta-badge">Included</span>'),
    ],
    whats_included=[
        "Google Cloud official PCA courseware",
        "Google Cloud exam voucher",
        "90-day multi-project GCP sandbox",
        "3 full timed mock exams",
        "Two MY case-study workbooks",
        "BNM RMiT &amp; PDPA design overlay for GCP",
        "Post-course instructor access (60 days)",
        "Free retake voucher (conditions apply)",
        "Digital badge via Google Cloud",
    ],
    verify_items=[
        "Verifiable on Google Cloud Skills Boost",
        "Digital badge via Credly",
        "Top GCP credential for MY banks and fintech",
        "Pathway to Google Cloud Champion Innovator",
    ],
    guarantee_text="Hit the 82% mock threshold and don't pass first attempt? Google Cloud retake voucher on us.",
))
