# -*- coding: utf-8 -*-
"""AI Field + Data Science short programmes (2026 catalogue expansion)."""
from _course_data import HERO_IMG, common_meta

BATCH = []


def _course(
    *,
    slug,
    title,
    title_html,
    watermark,
    subtitle,
    level,
    badge_extra,
    duration,
    intake,
    price,
    price_orig,
    price_save,
    overview_head,
    overview_p1,
    overview_p2,
    modules,
    labs,
    quick_wins,
    who_for,
    prereqs,
    path_chips,
    path_name,
    salary_html,
    pass_rate=94,
    format_label="Instructor-Led + Labs",
    delivery="On-site · Virtual · Hybrid",
    next_steps=None,
    crumb="Skill Programs",
    vendor_short="Nexperts Skill",
):
    pills = [w[1] for w in quick_wins[:3]] + [f"{pass_rate}% pass", "Mentors"]
    return dict(
        slug=slug,
        title=title,
        title_html=title_html,
        vendor_short=vendor_short,
        watermark=watermark,
        crumb_vendor=crumb,
        subtitle=subtitle,
        badges=[
            ("cb-vendor", "Nexperts Skill"),
            ("cb-level", level),
            ("cb-new", "2026"),
            ("cb-hot", badge_extra),
        ],
        hero_meta=common_meta(duration, format_label, delivery, pass_rate, intake),
        hero_img=HERO_IMG,
        quick_wins=quick_wins,
        overview_eyebrow="What this programme is",
        overview_head=overview_head,
        overview_p1=overview_p1,
        overview_p2=overview_p2,
        overview_p3="Delivered by Nexperts Academy trainers with Malaysian enterprise examples, HRD Corp claim support available for eligible employers.",
        who_for=who_for,
        prereqs=prereqs,
        prereqs_note="Ask enrolment for a free readiness checklist before class.",
        curriculum_eyebrow="Curriculum",
        curriculum_head=("Structured modules.", "Lab checkpoints."),
        curriculum_intro="Concept briefings, guided labs and a practical deliverable you can show at work.",
        modules=modules,
        labs_eyebrow="Hands-on Labs",
        labs_head=("Practice.", "Reviewed."),
        labs_intro="Labs run on managed environments — minimal local setup required.",
        labs=labs,
        labs_footer="+ Mentor office hours for sticky blockers.",
        exam_eyebrow="Assessment",
        exam_head=("Practical checkpoint.", "Certificate."),
        exam_intro="Complete the guided labs and final mini-project to earn your Nexperts Academy certificate.",
        exam_main=dict(
            name="Completion rubric",
            rows=[
                ("Labs", "Core labs completed with tutor sign-off"),
                ("Project", "Mini-project meets the published checklist"),
                ("Attendance", "Minimum attendance threshold met"),
                ("Passing", '<span class="pass-highlight">Certificate issued</span>'),
                ("Resit", "One remediation session included"),
            ],
        ),
        exam_optional=None,
        mock_programme=[
            ("01", "Concept check", "Quick quiz after each module."),
            ("02", "Lab review", "Peer + tutor feedback."),
            ("03", "Project dry-run", "Present before final submit."),
        ],
        pass_rate=pass_rate,
        pass_head_html=f"{pass_rate}% complete labs<br><em>on schedule.</em>",
        pass_intro="We keep cohorts small enough for real feedback — not slide-only delivery.",
        pass_pills=pills,
        pass_compare=[
            ("Self-paced video only", "No reviewed artefact."),
            ("Nexperts", "Lab sign-off + mentor feedback."),
        ],
        next_eyebrow="Your next step",
        next_head=("Keep building", "the pathway."),
        next_steps_intro="Stack related AI and data programmes once foundations are solid.",
        next_steps=next_steps
        or [
            ("Before this", "Basics ready", "Meet the published prerequisites.", "Prep →"),
            ("You are here", title[:42], "Current programme.", "Currently viewing →"),
            ("Recommended next", "Related track", "Ask us for a learning path.", "Talk to us →"),
        ],
        path_name=path_name,
        path_chips=path_chips,
        salary_html=salary_html,
        reviews_eyebrow="Learner feedback",
        reviews_head=("What participants", "say."),
        reviews_summary=("4.8", 48, 12, 6, 54),
        reviews=[
            (
                "★★★★★",
                "Clear labs and practical examples — usable at work the same week.",
                "rav-b",
                "AS",
                "Aina S.",
                "Analyst",
                "✓ Completed",
            ),
            (
                "★★★★★",
                "Instructors answered real project questions, not just textbook ones.",
                "rav-m",
                "KT",
                "Kevin T.",
                "Engineer",
                "✓ Completed",
            ),
            (
                "★★★★",
                "Well paced — arrive with the prerequisites done.",
                "rav-g",
                "LM",
                "Li Mei",
                "Consultant",
                "✓ Completed",
            ),
            (
                "★★★★★",
                "HRD Corp paperwork was handled smoothly for our team cohort.",
                "rav-a",
                "NR",
                "Nabil R.",
                "L&D lead",
                "✓ Completed",
            ),
        ],
        price=price,
        price_orig=price_orig,
        price_save=price_save,
        price_note="Per person · HRD Corp claim support available",
        sidebar_meta=[
            ("Duration", duration),
            ("Next intake", intake),
            ("Format", "Hybrid"),
            ("Level", level),
            ("Language", "English"),
            ("Cert body", vendor_short),
            ("Exam", '<span class="smeta-badge">Labs + Project</span>'),
        ],
        whats_included=[
            "Lab environment",
            "Course materials",
            "Mentor support",
            "Certificate of completion",
        ],
        verify_items=["Nexperts Academy verification ID"],
        guarantee_text="Follow the lab checklist and attend office hours — we help you finish the mini-project.",
        faqs=[
            (
                f"Who is {title} for?",
                "Professionals and students who want practical, instructor-led skills with Malaysian workplace examples.",
            ),
            (
                "Is this online or classroom?",
                "Both — on-site, virtual and hybrid cohorts are scheduled. Ask enrolment for the next intake format.",
            ),
            (
                "Do I get a certificate?",
                "Yes. Complete labs and the mini-project to receive a Nexperts Academy certificate of completion.",
            ),
            (
                "Can my company claim HRD Corp?",
                "Eligible employers can request claim support — share your company details with our enrolment team.",
            ),
        ],
    )


# ── AI Field ──────────────────────────────────────────────────────────────────

BATCH.append(
    _course(
        slug="introduction-to-machine-learning",
        title="Introduction to Machine Learning",
        title_html="Introduction to<br><em>Machine Learning</em>",
        watermark="ML Intro",
        subtitle="Core ML concepts, supervised workflows, evaluation basics and a first model lab — the practical starting point before deeper AI or cloud ML certifications.",
        level="Beginner",
        badge_extra="AI Track",
        duration="3 days / 24 hrs",
        intake="12 Oct 2026",
        price="RM 1,800",
        price_orig="RM 2,200",
        price_save="Save 18%",
        overview_head=("ML without", "the fog."),
        overview_p1="Learn how machine learning problems are framed, how data becomes features, and how to train and evaluate simple models with confidence.",
        overview_p2="Ideal before AI/ML Bootcamp, DP-100 or cloud ML specialty tracks.",
        modules=[
            ("01", "ML mindset", ["Supervised vs unsupervised", "Train/test split", "Lab: baseline classifier"]),
            ("02", "Features & data", ["Cleaning basics", "Encoding", "Lab: prepare a tabular set"]),
            ("03", "Models & metrics", ["Trees & linear models", "Precision/recall", "Lab: compare two models"]),
            ("04", "Storytelling", ["Explain results to stakeholders", "Common pitfalls", "Lab: mini presentation"]),
        ],
        labs=[
            ("01", "Baseline", "First model in under 90 minutes.", "lt-recon", "ML"),
            ("02", "Features", "Clean and encode.", "lt-defend", "Data"),
            ("03", "Compare", "Pick a winner with evidence.", "lt-attack", "Eval"),
            ("04", "Present", "Stakeholder-ready summary.", "lt-recon", "Story"),
        ],
        quick_wins=[
            ("🧠", "ML vocabulary", "Speak confidently with data teams"),
            ("📊", "First model", "Train and evaluate a real dataset"),
            ("🧭", "Path clarity", "Know what to learn next"),
            ("🛡️", "Pitfalls", "Avoid leakage and vanity metrics"),
        ],
        who_for=[
            ("📊", "Analysts", "Excel/SQL users exploring ML."),
            ("💻", "Developers", "New to model workflows."),
            ("🎓", "Students", "Foundation before bootcamps."),
            ("📈", "Managers", "Literacy for AI initiatives."),
            ("🏢", "Teams", "Shared vocabulary for pilots."),
            ("🧪", "Career switchers", "Portfolio-ready first project."),
        ],
        prereqs=["Basic Python helpful but not mandatory", "Comfort with spreadsheets"],
        path_chips=[("ML Intro", "you"), ("AI/ML Bootcamp", "next"), ("DP-100", "next")],
        path_name="machine learning",
        salary_html='Junior data & ML roles in KL often start around <strong style="color:#86efac">RM 4,000 – RM 7,500/month</strong> with a growing portfolio.',
        next_steps=[
            ("Before this", "Python basics", "Optional refresher available.", "Prep →"),
            ("You are here", "Intro to Machine Learning", "Foundation track.", "Currently viewing →"),
            ("Recommended next", "AI/ML Bootcamp", "Deeper practitioner path.", "View Bootcamp →"),
        ],
    )
)

BATCH.append(
    _course(
        slug="building-a-chatbot-using-python",
        title="Building a Chatbot Using Python",
        title_html="Building a Chatbot<br><em>Using Python</em>",
        watermark="Chatbot",
        subtitle="Design and ship a conversational assistant with Python — intents, state, APIs and a deployable demo you can show stakeholders.",
        level="Beginner+",
        badge_extra="AI Apps",
        duration="3 days / 24 hrs",
        intake="19 Oct 2026",
        price="RM 1,900",
        price_orig="RM 2,400",
        price_save="Save 21%",
        overview_head=("From script", "to conversation."),
        overview_p1="Build a working chatbot using Python patterns used in support, FAQ and internal-assistant pilots.",
        overview_p2="Covers rule-based and LLM-assisted approaches so you understand when each is appropriate.",
        modules=[
            ("01", "Conversation design", ["Intents & entities", "Happy paths", "Lab: dialogue map"]),
            ("02", "Python bot core", ["Handlers & state", "Validation", "Lab: FAQ bot"]),
            ("03", "APIs & tools", ["Webhooks", "Knowledge lookup", "Lab: connect a data source"]),
            ("04", "Polish & demo", ["Logging", "Guardrails", "Lab: stakeholder demo"]),
        ],
        labs=[
            ("01", "Map", "Design the conversation tree.", "lt-recon", "UX"),
            ("02", "Core", "Python handler loop.", "lt-defend", "Code"),
            ("03", "API", "Fetch live answers.", "lt-attack", "API"),
            ("04", "Demo", "Present the bot live.", "lt-recon", "Ship"),
        ],
        quick_wins=[
            ("💬", "Working bot", "Demo-ready assistant"),
            ("🐍", "Python patterns", "Handlers, state, APIs"),
            ("🔗", "Integrations", "Connect knowledge sources"),
            ("🛡️", "Guardrails", "Safer replies for work use"),
        ],
        who_for=[
            ("💻", "Developers", "First conversational app."),
            ("📊", "Analysts", "Automate FAQ workflows."),
            ("🏢", "Support leads", "Prototype internal bots."),
            ("🎓", "Students", "Portfolio project."),
            ("🧪", "Innovation teams", "Fast PoC."),
            ("📈", "PMs", "Hands-on chatbot literacy."),
        ],
        prereqs=["Python basics (functions, dictionaries)", "Laptop with VS Code or Jupyter"],
        path_chips=[("Python", "prev"), ("Chatbot", "you"), ("Gen AI", "next")],
        path_name="conversational AI",
        salary_html='Automation and AI-app builders in MY commonly earn <strong style="color:#86efac">RM 5,000 – RM 10,000/month</strong> with shipping experience.',
        next_steps=[
            ("Before this", "Python basics", "Bootcamp day 1–2 is enough.", "Prep →"),
            ("You are here", "Chatbot with Python", "Conversational apps track.", "Currently viewing →"),
            ("Recommended next", "Gen AI", "LLM + RAG patterns.", "View Gen AI →"),
        ],
    )
)

BATCH.append(
    _course(
        slug="ai-fundamentals-for-beginners",
        title="AI Fundamentals Course — Introduction to Artificial Intelligence for Beginners",
        title_html="AI Fundamentals<br><em>for Beginners</em>",
        watermark="AI Fund",
        subtitle="A friendly, non-vendor introduction to artificial intelligence — concepts, real-world use cases, ethics and how to start a practical learning path.",
        level="Beginner",
        badge_extra="AI Intro",
        duration="2 days / 16 hrs",
        intake="5 Oct 2026",
        price="RM 1,200",
        price_orig="RM 1,500",
        price_save="Save 20%",
        overview_head=("AI literacy", "without the hype."),
        overview_p1="Understand what AI can and cannot do, how machine learning and generative AI differ, and where organisations in Malaysia are applying them today.",
        overview_p2="Perfect for professionals who need vocabulary and judgement before choosing a deeper technical track (AI-900, Gen AI, ML).",
        modules=[
            ("01", "What is AI?", ["History to today", "Narrow vs general AI", "Lab: map use cases"]),
            ("02", "ML basics", ["Data, models, prediction", "Common algorithms at a glance", "Lab: interpret a model card"]),
            ("03", "Generative AI", ["LLMs in plain language", "Prompting basics", "Lab: safe prompt patterns"]),
            ("04", "Responsible AI", ["Bias, privacy, governance", "Buying vs building", "Lab: risk checklist"]),
        ],
        labs=[
            ("01", "Use cases", "Industry AI map.", "lt-recon", "Ideas"),
            ("02", "Model card", "Read results carefully.", "lt-defend", "ML"),
            ("03", "Prompts", "Write safer prompts.", "lt-attack", "GenAI"),
            ("04", "Risks", "Governance checklist.", "lt-recon", "Ethics"),
        ],
        quick_wins=[
            ("📚", "Clear vocabulary", "Talk AI with confidence"),
            ("🧭", "Use-case sense", "Spot real vs hype"),
            ("✨", "Prompt basics", "Start using Gen AI well"),
            ("🛡️", "Ethics lens", "Ask the right risk questions"),
        ],
        who_for=[
            ("📈", "Business roles", "Need AI literacy fast."),
            ("🎓", "Students", "First structured AI course."),
            ("🏢", "Managers", "Sponsor AI initiatives."),
            ("💼", "HR & L&D", "Design team upskilling."),
            ("🧪", "Career explorers", "Decide next technical step."),
            ("📊", "Analysts", "Bridge to ML programmes."),
        ],
        prereqs=["No coding required", "Curiosity about AI at work"],
        path_chips=[("AI Fundamentals", "you"), ("Intro ML", "next"), ("AI-900", "next")],
        path_name="AI literacy",
        salary_html='AI-literate analysts and coordinators in KL often earn <strong style="color:#86efac">RM 4,000 – RM 8,000/month</strong> depending on domain.',
        next_steps=[
            ("Before this", "None", "True beginner friendly.", "Start →"),
            ("You are here", "AI Fundamentals", "Literacy track.", "Currently viewing →"),
            ("Recommended next", "Intro to ML or AI-900", "Technical or Azure path.", "Talk to us →"),
        ],
    )
)

BATCH.append(
    _course(
        slug="deep-learning-using-pytorch",
        title="Deep Learning Using PyTorch",
        title_html="Deep Learning<br><em>Using PyTorch</em>",
        watermark="PyTorch",
        subtitle="Tensors, neural networks, training loops and transfer learning with PyTorch — hands-on deep learning for practitioners who already know basic ML.",
        level="Intermediate",
        badge_extra="Deep Learning",
        duration="4 days / 32 hrs",
        intake="26 Oct 2026",
        price="RM 2,800",
        price_orig="RM 3,400",
        price_save="Save 18%",
        overview_head=("PyTorch that", "actually trains."),
        overview_p1="Move from classical ML into neural networks with clean PyTorch patterns: datasets, models, optimisers, checkpoints and evaluation.",
        overview_p2="Includes GPU lab access and a mini image or text classification project.",
        modules=[
            ("01", "PyTorch foundations", ["Tensors", "Autograd", "Lab: tensor workout"]),
            ("02", "Training loops", ["Datasets & DataLoaders", "Loss & optimisers", "Lab: train from scratch"]),
            ("03", "CNNs & transfer learning", ["Pretrained models", "Fine-tuning", "Lab: image classifier"]),
            ("04", "Production mindset", ["Checkpoints", "Overfitting controls", "Lab: package & present"]),
        ],
        labs=[
            ("01", "Tensors", "Autograd drills.", "lt-recon", "Core"),
            ("02", "Train", "End-to-end loop.", "lt-defend", "NN"),
            ("03", "Transfer", "Fine-tune a model.", "lt-attack", "CNN"),
            ("04", "Ship", "Save & evaluate.", "lt-recon", "Project"),
        ],
        quick_wins=[
            ("🔥", "PyTorch fluency", "Write clean training code"),
            ("🖼️", "Transfer learning", "Strong results faster"),
            ("📈", "Debug skills", "Spot overfitting early"),
            ("📦", "Project artefact", "Portfolio-ready notebook"),
        ],
        who_for=[
            ("💻", "ML engineers", "Moving into deep learning."),
            ("📊", "Data scientists", "Need PyTorch practice."),
            ("🎓", "Graduates", "Strengthen DL portfolio."),
            ("🧪", "Researchers", "Modern training patterns."),
            ("🏢", "AI teams", "Shared PyTorch standard."),
            ("📈", "Bootcamp grads", "Next step after scikit-learn."),
        ],
        prereqs=["Python proficiency", "Intro ML or equivalent experience", "16 GB RAM recommended"],
        path_chips=[("Intro ML", "prev"), ("PyTorch DL", "you"), ("AI/ML Bootcamp", "next")],
        path_name="deep learning",
        salary_html='Deep learning practitioners in MY typically target <strong style="color:#86efac">RM 7,000 – RM 14,000/month</strong> with production experience.',
        next_steps=[
            ("Before this", "Intro to ML", "Classical ML foundation.", "Prep →"),
            ("You are here", "Deep Learning PyTorch", "Neural nets track.", "Currently viewing →"),
            ("Recommended next", "Gen AI / DP-100", "LLMs or Azure ML.", "Talk to us →"),
        ],
    )
)

BATCH.append(
    _course(
        slug="generative-ai-applications-python-fundamentals",
        title="Generative AI Applications and Python Fundamentals",
        title_html="Generative AI Apps<br><em>+ Python Fundamentals</em>",
        watermark="GenAI+Py",
        subtitle="Combine essential Python skills with practical generative AI application patterns — prompts, APIs, simple RAG and a working mini-app.",
        level="Beginner+",
        badge_extra="Gen AI",
        duration="4 days / 32 hrs",
        intake="2 Nov 2026",
        price="RM 2,400",
        price_orig="RM 2,900",
        price_save="Save 17%",
        overview_head=("Python + Gen AI", "in one track."),
        overview_p1="Built for professionals who need enough Python to call LLM APIs and enough Gen AI practice to ship a useful assistant or content workflow.",
        overview_p2="A bridge between Python Bootcamp and the full Gen AI practitioner programme.",
        modules=[
            ("01", "Python essentials", ["Functions & data structures", "Files & JSON", "Lab: Python drills"]),
            ("02", "LLM APIs", ["Prompts as code", "Parameters", "Lab: first API app"]),
            ("03", "Applications", ["Chat UX patterns", "Simple RAG", "Lab: knowledge Q&A"]),
            ("04", "Ship", ["Evaluation basics", "Safety checks", "Lab: demo day"]),
        ],
        labs=[
            ("01", "Python", "Core language labs.", "lt-recon", "Py"),
            ("02", "API", "Call an LLM safely.", "lt-defend", "API"),
            ("03", "RAG lite", "Retrieve + answer.", "lt-attack", "GenAI"),
            ("04", "Demo", "Present your app.", "lt-recon", "Ship"),
        ],
        quick_wins=[
            ("🐍", "Python enough to ship", "APIs and scripts"),
            ("✨", "LLM applications", "Useful Gen AI mini-apps"),
            ("🔗", "RAG lite", "Ground answers in docs"),
            ("🛡️", "Safety basics", "PII and prompt injection awareness"),
        ],
        who_for=[
            ("💻", "Developers", "Add Gen AI to existing skills."),
            ("📊", "Analysts", "Automate with LLMs + Python."),
            ("🎓", "Students", "Portfolio Gen AI project."),
            ("🏢", "Teams", "Shared starter programme."),
            ("🧪", "Innovators", "Fast PoC track."),
            ("📈", "PMs", "Hands-on Gen AI literacy."),
        ],
        prereqs=["Basic computer literacy", "No prior Gen AI required"],
        path_chips=[("Python+GenAI", "you"), ("Gen AI", "next"), ("Agentic AI", "next")],
        path_name="generative AI apps",
        salary_html='Gen AI-capable developers in KL often earn <strong style="color:#86efac">RM 6,000 – RM 12,000/month</strong> with shipping experience.',
        next_steps=[
            ("Before this", "Optional Python refresher", "Available on request.", "Prep →"),
            ("You are here", "Gen AI + Python Fundamentals", "App track.", "Currently viewing →"),
            ("Recommended next", "Gen AI Practitioner", "Deeper RAG & evaluation.", "View Gen AI →"),
        ],
    )
)

BATCH.append(
    _course(
        slug="microsoft-copilot",
        title="Microsoft Copilot",
        title_html="Microsoft Copilot<br><em>Productivity Course</em>",
        watermark="Copilot",
        subtitle="Use Microsoft Copilot across M365 work — Word, Excel, PowerPoint, Teams and Outlook — with prompt patterns, governance awareness and measurable productivity habits.",
        level="Beginner",
        badge_extra="M365",
        duration="2 days / 16 hrs",
        intake="9 Oct 2026",
        price="RM 1,400",
        price_orig="RM 1,800",
        price_save="Save 22%",
        overview_head=("Copilot that", "saves hours."),
        overview_p1="Learn practical Copilot workflows for everyday Microsoft 365 work while understanding data boundaries, responsible use and when human review is required.",
        overview_p2="Ideal for business users and teams rolling out Copilot licences.",
        modules=[
            ("01", "Copilot foundations", ["How Copilot works", "Grounding & permissions", "Lab: safe first prompts"]),
            ("02", "Word & Outlook", ["Drafting", "Rewriting", "Lab: email + document pack"]),
            ("03", "Excel & PowerPoint", ["Analysis prompts", "Slide generation", "Lab: insight deck"]),
            ("04", "Teams & governance", ["Meeting recap", "Policies", "Lab: team playbook"]),
        ],
        labs=[
            ("01", "Safe start", "Permission-aware prompts.", "lt-recon", "Basics"),
            ("02", "Docs", "Word + Outlook flow.", "lt-defend", "M365"),
            ("03", "Analysis", "Excel + slides.", "lt-attack", "BI"),
            ("04", "Playbook", "Team usage rules.", "lt-recon", "Gov"),
        ],
        quick_wins=[
            ("✍️", "Faster drafting", "Emails and documents"),
            ("📊", "Excel help", "Analysis shortcuts"),
            ("📑", "Slide speed", "First-draft decks"),
            ("🛡️", "Safe use", "Governance awareness"),
        ],
        who_for=[
            ("💼", "Office professionals", "Daily M365 users."),
            ("📈", "Managers", "Lead Copilot adoption."),
            ("🏢", "Admin teams", "Policy-aware usage."),
            ("🎓", "Students", "Workplace AI skills."),
            ("🧪", "Change agents", "Rollout champions."),
            ("📊", "Analysts", "Faster first drafts."),
        ],
        prereqs=["Microsoft 365 familiarity", "Copilot-enabled tenant helpful for live labs"],
        path_chips=[("Copilot", "you"), ("AI Fundamentals", "next"), ("Prompt Engineering", "next")],
        path_name="workplace AI",
        salary_html='Copilot-fluent business roles gain productivity leverage that supports mid-level MY salaries of <strong style="color:#86efac">RM 4,500 – RM 9,000/month</strong>.',
        next_steps=[
            ("Before this", "M365 basics", "Word/Excel/Outlook comfort.", "Prep →"),
            ("You are here", "Microsoft Copilot", "Workplace AI track.", "Currently viewing →"),
            ("Recommended next", "Prompt Engineering", "Stronger prompt systems.", "View course →"),
        ],
    )
)

BATCH.append(
    _course(
        slug="prompt-engineering-certification",
        title="Prompt Engineering Certification Course with LLM",
        title_html="Prompt Engineering<br><em>Certification with LLMs</em>",
        watermark="Prompt",
        subtitle="Master structured prompting for large language models — system prompts, few-shot patterns, evaluation, and reusable prompt libraries for work.",
        level="Beginner+",
        badge_extra="LLM Skills",
        duration="2 days / 16 hrs",
        intake="16 Oct 2026",
        price="RM 1,500",
        price_orig="RM 1,900",
        price_save="Save 21%",
        overview_head=("Prompts as", "systems."),
        overview_p1="Move beyond one-off chat prompts. Design, test and document prompt systems that produce reliable outputs for writing, analysis, coding assistance and customer workflows.",
        overview_p2="Pairs well with Gen AI, Copilot and chatbot programmes.",
        modules=[
            ("01", "Prompt foundations", ["Roles & constraints", "Output formats", "Lab: rewrite weak prompts"]),
            ("02", "Advanced patterns", ["Few-shot", "Chain-of-thought wisely", "Lab: prompt library"]),
            ("03", "Evaluation", ["Rubrics", "Regression checks", "Lab: A/B prompt tests"]),
            ("04", "Work systems", ["Templates for teams", "Safety notes", "Lab: certification project"]),
        ],
        labs=[
            ("01", "Rewrite", "Fix weak prompts.", "lt-recon", "Basics"),
            ("02", "Library", "Reusable templates.", "lt-defend", "Patterns"),
            ("03", "Eval", "Score outputs.", "lt-attack", "QA"),
            ("04", "Project", "Team prompt pack.", "lt-recon", "Cert"),
        ],
        quick_wins=[
            ("✨", "Better outputs", "Consistent LLM results"),
            ("📚", "Prompt library", "Reusable team assets"),
            ("🧪", "Evaluation", "Know when prompts regress"),
            ("🛡️", "Safer prompts", "Reduce leaky instructions"),
        ],
        who_for=[
            ("💼", "Knowledge workers", "Use LLMs daily."),
            ("💻", "Builders", "Ship LLM features."),
            ("📈", "PMs & analysts", "Design reliable prompts."),
            ("🏢", "Teams", "Standardise prompt practice."),
            ("🎓", "Students", "Certification-style project."),
            ("🧪", "Content leads", "Quality-controlled drafting."),
        ],
        prereqs=["Comfortable using ChatGPT/Claude/Copilot", "No coding required"],
        path_chips=[("Prompt Eng", "you"), ("Gen AI", "next"), ("Chatbot", "next")],
        path_name="prompt engineering",
        salary_html='Strong prompt + LLM skills support AI-enabled roles commonly paying <strong style="color:#86efac">RM 5,000 – RM 11,000/month</strong> in Malaysia.',
        next_steps=[
            ("Before this", "AI Fundamentals", "Helpful but optional.", "Prep →"),
            ("You are here", "Prompt Engineering", "LLM craft track.", "Currently viewing →"),
            ("Recommended next", "Gen AI", "RAG and deployment.", "View Gen AI →"),
        ],
    )
)

BATCH.append(
    _course(
        slug="claude-ai-productivity-90-minutes",
        title="Claude AI in 90 Minutes Productivity Course: Build Your AI Work Assistant",
        title_html="Claude AI in 90 Minutes<br><em>Build Your Work Assistant</em>",
        watermark="Claude",
        subtitle="A focused 90-minute productivity workshop to set up Claude as your personal work assistant — workflows for writing, research, planning and daily ops.",
        level="Beginner",
        badge_extra="Workshop",
        duration="90 minutes",
        intake="Weekly · book ahead",
        price="RM 299",
        price_orig="RM 499",
        price_save="Save 40%",
        overview_head=("Claude,", "configured for work."),
        overview_p1="In one intensive session you configure Claude projects/instructions, build reusable prompts, and leave with a personal AI work assistant playbook.",
        overview_p2="Perfect lunch-and-learn or team kickoff before longer Gen AI programmes.",
        format_label="Live Workshop",
        delivery="Virtual · On-site available",
        modules=[
            ("01", "Claude setup", ["Projects & instructions", "Safety defaults", "Lab: configure your workspace"]),
            ("02", "Work assistant patterns", ["Writing", "Planning", "Research briefs", "Lab: 3 workflow templates"]),
            ("03", "Daily operating system", ["Checklists", "Follow-ups", "Lab: personal assistant playbook"]),
        ],
        labs=[
            ("01", "Setup", "Configure Claude for work.", "lt-recon", "Setup"),
            ("02", "Templates", "Three reusable workflows.", "lt-defend", "Prod"),
            ("03", "Playbook", "Your assistant OS.", "lt-attack", "Ship"),
        ],
        quick_wins=[
            ("⚡", "90-minute impact", "Use Claude the same day"),
            ("🧰", "Templates", "Writing + planning packs"),
            ("🗂️", "Assistant OS", "Repeatable daily workflows"),
            ("🛡️", "Safe defaults", "Work-appropriate settings"),
        ],
        who_for=[
            ("💼", "Busy professionals", "Need AI help fast."),
            ("📈", "Managers", "Team lunch-and-learn."),
            ("🎓", "Students", "Study assistant setup."),
            ("🏢", "Ops teams", "SOP drafting aid."),
            ("🧪", "Creators", "Research & writing boost."),
            ("📊", "Analysts", "Briefing templates."),
        ],
        prereqs=["Claude account access", "No coding required"],
        path_chips=[("Claude 90m", "you"), ("Prompt Eng", "next"), ("Copilot", "next")],
        path_name="AI productivity",
        salary_html='Productivity AI skills compound across roles — most valuable as leverage on top of your current career track.',
        pass_rate=97,
        next_steps=[
            ("Before this", "None", "Beginner friendly.", "Start →"),
            ("You are here", "Claude 90 Minutes", "Productivity workshop.", "Currently viewing →"),
            ("Recommended next", "Prompt Engineering", "Deeper prompt systems.", "View course →"),
        ],
    )
)

BATCH.append(
    _course(
        slug="oracle-plsql-database-programming",
        title="Oracle PL/SQL Database Programming Course",
        title_html="Oracle PL/SQL<br><em>Database Programming</em>",
        watermark="PL/SQL",
        subtitle="Write robust Oracle PL/SQL — anonymous blocks, procedures, functions, packages, cursors, exceptions and performance-minded SQL for real database work.",
        level="Intermediate",
        badge_extra="Database",
        duration="4 days / 32 hrs",
        intake="28 Oct 2026",
        price="RM 2,600",
        price_orig="RM 3,200",
        price_save="Save 19%",
        overview_head=("PL/SQL for", "production databases."),
        overview_p1="Learn Oracle PL/SQL programming patterns used by DB developers and DBAs — from blocks and packages to exception handling and bulk processing.",
        overview_p2="Useful alongside SQL for Data Professionals and Azure/SQL DBA tracks.",
        modules=[
            ("01", "PL/SQL foundations", ["Blocks", "Variables", "Control flow", "Lab: anonymous blocks"]),
            ("02", "Cursors & SQL", ["Explicit cursors", "Bulk collect intro", "Lab: cursor reports"]),
            ("03", "Procedures & functions", ["Parameters", "Functions", "Lab: reusable units"]),
            ("04", "Packages & exceptions", ["Package design", "Error handling", "Lab: mini package project"]),
        ],
        labs=[
            ("01", "Blocks", "First PL/SQL scripts.", "lt-recon", "Core"),
            ("02", "Cursors", "Row processing.", "lt-defend", "SQL"),
            ("03", "Units", "Proc + function.", "lt-attack", "Code"),
            ("04", "Package", "Team-ready module.", "lt-recon", "Project"),
        ],
        quick_wins=[
            ("🗄️", "PL/SQL fluency", "Write maintainable code"),
            ("📦", "Packages", "Organise database logic"),
            ("🛡️", "Exceptions", "Handle failures cleanly"),
            ("⚡", "Practical SQL", "Performance-minded patterns"),
        ],
        who_for=[
            ("💻", "DB developers", "Oracle application logic."),
            ("🗄️", "DBAs", "Automation and scripts."),
            ("📊", "Data engineers", "Oracle source systems."),
            ("🎓", "Students", "Database career track."),
            ("🏢", "Enterprise teams", "Legacy Oracle stacks."),
            ("🧪", "SQL analysts", "Moving into programming."),
        ],
        prereqs=["Solid SQL SELECT/JOIN skills", "Access to an Oracle practice environment (lab provided)"],
        path_chips=[("SQL", "prev"), ("Oracle PL/SQL", "you"), ("DP-300", "next")],
        path_name="database engineering",
        salary_html='Oracle PL/SQL developers in Malaysia commonly earn <strong style="color:#86efac">RM 5,500 – RM 11,000/month</strong> depending on experience.',
        next_steps=[
            ("Before this", "SQL fundamentals", "Our SQL course is ideal prep.", "Prep →"),
            ("You are here", "Oracle PL/SQL", "Database programming track.", "Currently viewing →"),
            ("Recommended next", "DP-300 / SQL advanced", "Cloud DBA or deeper SQL.", "Talk to us →"),
        ],
    )
)


# ── Data Science Field ────────────────────────────────────────────────────────

BATCH.append(
    _course(
        slug="tableau-for-beginners",
        title="Tableau for Beginners",
        title_html="Tableau<br><em>for Beginners</em>",
        watermark="Tableau",
        subtitle="Build your first interactive Tableau dashboards — connect data, craft charts, apply filters and publish insights without prior BI experience.",
        level="Beginner",
        badge_extra="BI",
        duration="2 days / 16 hrs",
        intake="8 Oct 2026",
        price="RM 1,400",
        price_orig="RM 1,800",
        price_save="Save 22%",
        overview_head=("First dashboards,", "fast."),
        overview_p1="A gentle on-ramp to Tableau Desktop for analysts who currently live in Excel and need interactive visuals quickly.",
        overview_p2="Natural next step: Tableau Desktop Specialist exam prep or Advanced Tableau visualisation.",
        modules=[
            ("01", "Tableau orientation", ["Interface", "Data connections", "Lab: connect & explore"]),
            ("02", "Core charts", ["Bars, lines, maps", "Marks card", "Lab: KPI views"]),
            ("03", "Dashboards", ["Filters & actions", "Layout", "Lab: first dashboard"]),
            ("04", "Share", ["Stories", "Export/publish basics", "Lab: present insights"]),
        ],
        labs=[
            ("01", "Connect", "Load sample data.", "lt-recon", "Data"),
            ("02", "Charts", "Build core visuals.", "lt-defend", "Viz"),
            ("03", "Dashboard", "Interactive layout.", "lt-attack", "BI"),
            ("04", "Present", "Tell the story.", "lt-recon", "Story"),
        ],
        quick_wins=[
            ("📊", "First dashboard", "Interactive in two days"),
            ("🔗", "Data connect", "Excel/CSV to Tableau"),
            ("🧭", "Chart sense", "Pick the right visual"),
            ("📤", "Share", "Present to stakeholders"),
        ],
        who_for=[
            ("📊", "Excel analysts", "Moving to Tableau."),
            ("📈", "Business users", "Self-serve visuals."),
            ("🎓", "Students", "BI portfolio start."),
            ("🏢", "Teams", "Shared beginner standard."),
            ("🧪", "Managers", "Read dashboards better."),
            ("💼", "Consultants", "Client-ready visuals."),
        ],
        prereqs=["Comfortable with Excel tables", "No Tableau experience required"],
        path_chips=[("Tableau Beginner", "you"), ("Tableau Specialist", "next"), ("Adv Tableau", "next")],
        path_name="data visualisation",
        salary_html='Junior BI / Tableau analysts in KL often earn <strong style="color:#86efac">RM 4,000 – RM 7,500/month</strong>.',
        next_steps=[
            ("Before this", "Excel basics", "Tables and charts help.", "Prep →"),
            ("You are here", "Tableau for Beginners", "BI entry track.", "Currently viewing →"),
            ("Recommended next", "Tableau Desktop Specialist", "Certification path.", "View cert →"),
        ],
    )
)

BATCH.append(
    _course(
        slug="data-science-foundation",
        title="Data Science Foundation",
        title_html="Data Science<br><em>Foundation</em>",
        watermark="DS Found",
        subtitle="Foundations of the data science lifecycle — problem framing, data wrangling, exploratory analysis, basic modelling and communication of results.",
        level="Beginner+",
        badge_extra="Data Science",
        duration="4 days / 32 hrs",
        intake="21 Oct 2026",
        price="RM 2,200",
        price_orig="RM 2,700",
        price_save="Save 19%",
        overview_head=("Data science,", "from the ground up."),
        overview_p1="Build the end-to-end habit of a data scientist: ask the right question, prepare data, explore, model lightly and communicate findings.",
        overview_p2="Complements Data Science with Python and Introduction to Machine Learning.",
        modules=[
            ("01", "Lifecycle & questions", ["Problem framing", "Success metrics", "Lab: define a brief"]),
            ("02", "Wrangling", ["Cleaning", "Joins mindset", "Lab: tidy a messy set"]),
            ("03", "EDA & visuals", ["Distributions", "Relationships", "Lab: insight notebook"]),
            ("04", "Light modelling & story", ["Baselines", "Communicate results", "Lab: foundation project"]),
        ],
        labs=[
            ("01", "Brief", "Frame the problem.", "lt-recon", "Scope"),
            ("02", "Clean", "Wrangle data.", "lt-defend", "Data"),
            ("03", "EDA", "Find the story.", "lt-attack", "EDA"),
            ("04", "Project", "Present findings.", "lt-recon", "Capstone"),
        ],
        quick_wins=[
            ("🧭", "Lifecycle clarity", "Know the full DS loop"),
            ("🧹", "Wrangling", "Clean real datasets"),
            ("📊", "EDA", "Find patterns faster"),
            ("🗣️", "Storytelling", "Explain to non-technical leads"),
        ],
        who_for=[
            ("📊", "Analysts", "Stepping into data science."),
            ("🎓", "Students", "Foundation before bootcamps."),
            ("💻", "Developers", "Data thinking skills."),
            ("🏢", "Teams", "Shared DS language."),
            ("🧪", "Career switchers", "Structured entry point."),
            ("📈", "Managers", "Sponsor data work better."),
        ],
        prereqs=["Basic Excel or Python helpful", "Comfort with numbers"],
        path_chips=[("DS Foundation", "you"), ("DS with Python", "next"), ("Intro ML", "next")],
        path_name="data science",
        salary_html='Foundation-level data roles in Malaysia often start around <strong style="color:#86efac">RM 4,000 – RM 8,000/month</strong>.',
        next_steps=[
            ("Before this", "Excel / basic Python", "Optional refresher.", "Prep →"),
            ("You are here", "Data Science Foundation", "DS entry track.", "Currently viewing →"),
            ("Recommended next", "Data Science with Python", "Deeper Python path.", "View course →"),
        ],
    )
)

BATCH.append(
    _course(
        slug="advanced-data-visualization-tableau",
        title="Advanced Data Visualization Using Tableau",
        title_html="Advanced Data Visualization<br><em>Using Tableau</em>",
        watermark="Adv Tab",
        subtitle="Level up Tableau with calculated fields, LOD expressions, advanced interactivity, performance tips and executive-ready dashboard design.",
        level="Intermediate",
        badge_extra="Advanced BI",
        duration="3 days / 24 hrs",
        intake="4 Nov 2026",
        price="RM 2,000",
        price_orig="RM 2,500",
        price_save="Save 20%",
        overview_head=("Tableau beyond", "basic charts."),
        overview_p1="For analysts who already build simple dashboards and need advanced calculations, LOD, parameter actions and polished storytelling for leadership reviews.",
        overview_p2="Excellent follow-on after Tableau for Beginners or Tableau Desktop Specialist prep.",
        modules=[
            ("01", "Advanced calcs", ["Table calcs", "LOD intro", "Lab: complex KPIs"]),
            ("02", "Interactivity", ["Parameters", "Set actions", "Lab: guided analytics"]),
            ("03", "Design systems", ["Layout & accessibility", "Mobile considerations", "Lab: executive dashboard"]),
            ("04", "Performance & scale", ["Extracts", "Optimisation", "Lab: speed tune-up"]),
        ],
        labs=[
            ("01", "LOD", "Advanced KPIs.", "lt-recon", "Calcs"),
            ("02", "Actions", "Interactive exploration.", "lt-defend", "UX"),
            ("03", "Exec pack", "Leadership dashboard.", "lt-attack", "Design"),
            ("04", "Perf", "Make it fast.", "lt-recon", "Scale"),
        ],
        quick_wins=[
            ("🧮", "LOD & calcs", "Harder KPIs solved"),
            ("🖱️", "Interactivity", "Guided analytics UX"),
            ("🎨", "Exec polish", "Leadership-ready design"),
            ("⚡", "Performance", "Faster workbooks"),
        ],
        who_for=[
            ("📊", "Tableau users", "Past beginner stage."),
            ("📈", "BI analysts", "Need advanced techniques."),
            ("🏢", "Reporting teams", "Standardise advanced patterns."),
            ("🎓", "Specialist candidates", "Deepen exam skills."),
            ("🧪", "Consultants", "Client dashboard quality."),
            ("💼", "Leads", "Review advanced designs."),
        ],
        prereqs=["Tableau for Beginners or equivalent practice", "Comfort building basic dashboards"],
        path_chips=[("Tableau Beginner", "prev"), ("Adv Tableau", "you"), ("PL-300", "next")],
        path_name="advanced visualisation",
        salary_html='Advanced Tableau / BI specialists in KL often earn <strong style="color:#86efac">RM 6,000 – RM 11,000/month</strong>.',
        next_steps=[
            ("Before this", "Tableau for Beginners", "Or equivalent experience.", "Prep →"),
            ("You are here", "Advanced Tableau Viz", "Advanced BI track.", "Currently viewing →"),
            ("Recommended next", "PL-300 / Specialist cert", "Expand BI stack.", "Talk to us →"),
        ],
    )
)

BATCH.append(
    _course(
        slug="data-visualization-with-seaborn",
        title="Data Visualization with Seaborn Using Python",
        title_html="Data Visualization with Seaborn<br><em>Using Python</em>",
        watermark="Seaborn",
        subtitle="Create statistical visuals with Python Seaborn — distributions, relationships, categorical plots and publication-ready figures for analysis notebooks.",
        level="Beginner+",
        badge_extra="Python Viz",
        duration="2 days / 16 hrs",
        intake="11 Nov 2026",
        price="RM 1,300",
        price_orig="RM 1,700",
        price_save="Save 24%",
        overview_head=("Beautiful stats plots", "in Python."),
        overview_p1="Learn Seaborn patterns that analysts use daily: distribution plots, relational grids, categorical comparisons and styling for reports.",
        overview_p2="Pairs with Netflix Data Analysis Workshop, Data Science Foundation and Python Bootcamp.",
        modules=[
            ("01", "Seaborn setup", ["Figure mindset", "Themes", "Lab: first plots"]),
            ("02", "Distributions", ["hist/kde/box", "Outliers", "Lab: profile a feature"]),
            ("03", "Relationships", ["scatter/line/reg", "Facets", "Lab: multi-variable story"]),
            ("04", "Polish", ["Titles & export", "Notebook narrative", "Lab: insight pack"]),
        ],
        labs=[
            ("01", "Theme", "Style a figure.", "lt-recon", "Setup"),
            ("02", "Dist", "Distribution suite.", "lt-defend", "EDA"),
            ("03", "Relate", "Multi-var views.", "lt-attack", "Viz"),
            ("04", "Pack", "Export for slides.", "lt-recon", "Story"),
        ],
        quick_wins=[
            ("📉", "Stat plots", "Seaborn fluency"),
            ("🎨", "Styling", "Report-ready figures"),
            ("🔍", "EDA speed", "See patterns faster"),
            ("📓", "Notebook craft", "Visual analysis narrative"),
        ],
        who_for=[
            ("📊", "Python analysts", "Need better visuals."),
            ("🎓", "Students", "Notebook portfolio polish."),
            ("💻", "Data scientists", "Faster EDA."),
            ("🏢", "Teams", "Shared plotting standards."),
            ("🧪", "Researchers", "Publication-style figures."),
            ("📈", "Bootcamp grads", "Viz specialisation."),
        ],
        prereqs=["Basic Python and pandas", "Jupyter or VS Code"],
        path_chips=[("Python", "prev"), ("Seaborn Viz", "you"), ("DS Foundation", "next")],
        path_name="Python visualisation",
        salary_html='Python visualisation skills strengthen analyst packages often ranging <strong style="color:#86efac">RM 4,500 – RM 9,000/month</strong> in Malaysia.',
        next_steps=[
            ("Before this", "Python basics", "pandas helpful.", "Prep →"),
            ("You are here", "Seaborn Visualisation", "Python viz track.", "Currently viewing →"),
            ("Recommended next", "Data Science Foundation", "Broader DS path.", "View course →"),
        ],
    )
)
