# -*- coding: utf-8 -*-
"""Phase 4B: Full-stack, marketing, Excel basics, Salesforce, ServiceNow — skill & platform pages."""
from _course_data import HERO_IMG, common_meta

BATCH = []


BATCH.append(dict(
    slug="full-stack-web-development",
    title="Full Stack Web Development",
    title_html='Full Stack<br><em>Web Development</em>',
    vendor_short="Skill", watermark="FULL", crumb_vendor="Skill-Based",
    subtitle="HTML, CSS, JavaScript, React front-end, Node/Express API layer, SQL data access, auth basics and deploy to a public URL \u2014 a portfolio project employers can click through.",
    badges=[("cb-vendor","Nexperts Skill"),("cb-level","Beginner \u2192 Intermediate"),("cb-new","2026 Stack"),("cb-hot","Portfolio")],
    hero_meta=common_meta("6 days / 48 hrs","Instructor-Led + Project Labs","On-site \u00b7 Virtual \u00b7 Hybrid",91,"12 Aug 2026"),
    hero_img=HERO_IMG,
    quick_wins=[
        ("\U0001F310","Modern front-end","Semantic HTML, responsive CSS, React components & hooks"),
        ("\u2699\uFE0F","API layer","REST design, Express routes, validation, JWT basics"),
        ("\U0001F4BE","Data tier","PostgreSQL or SQLite + migrations mindset"),
        ("\u2601\uFE0F","Deploy","GitHub Actions smoke deploy to Netlify / Render pattern"),
    ],
    overview_eyebrow="What this course is",
    overview_head=("Ship a real","clickable product."),
    overview_p1="Full-stack means you can translate a feature from database column to pixel. This immersive programme gives you one coached portfolio project \u2014 typically a booking, ticketing or learning-admin mini-app \u2014 with code reviews that mirror industry PR feedback.",
    overview_p2="We intentionally align with what Malaysian hiring managers test in junior interviews: Git discipline, REST hygiene, component thinking, and calm debugging under time pressure.",
    overview_p3="You will pair-program during labs and solo the capstone with mentor office hours each evening.",
    who_for=[
        ("\U0001F393","Career switchers","You need proof, not promises."),
        ("\U0001F4BB","IT pros expanding","Sysadmins and testers entering dev."),
        ("\U0001F4BC","Startup hires","Small teams that need generalists."),
        ("\U0001F4DA","Bootcamp grads","You want structure + local mentorship."),
        ("\U0001F3AF","Serious hobbyists","Ready to commit 6 focused days."),
        ("\U0001F465","Corporate cohorts","Ask us for closed-team pricing."),
    ],
    prereqs=[
        "Comfortable using a computer daily",
        "No prior programming required",
        "GitHub account before day 1",
    ],
    prereqs_note="Install Node LTS + VS Code \u2014 setup checklist emailed after enrolment.",
    curriculum_eyebrow="Course Curriculum",
    curriculum_head=("Six days.","Front to cloud."),
    curriculum_intro="Each day ends with a merged PR to your portfolio repo \u2014 instructors tag release checkpoints.",
    modules=[
        ("01","Web foundations",["HTML5 semantics","CSS layout (flex/grid)","Accessibility basics","DOM + fetch intro","Lab: static landing page"]),
        ("02","JavaScript & React",["ES modules","React components","Hooks + state","Client routing","Lab: dashboard shell"]),
        ("03","API & auth",["Express project layout","Validation","JWT cookie/session discussion","Error handling","Lab: secured CRUD"]),
        ("04","Database",["SQL modelling","Migrations mindset","ORM-lite with Prisma or Knex","Lab: schema for capstone"]),
        ("05","Integration",["End-to-end feature slice","Testing hooks with Jest intro","Performance sanity","Lab: vertical slice"]),
        ("06","Capstone sprint",["Polish UX","README + demo script","Deploy pipeline","Showcase rehearsal"]),
    ],
    labs_eyebrow="Project Labs",
    labs_head=("Repo-driven.","PR by PR."),
    labs_intro="Labs simulate sprint tasks with acceptance criteria and Definition of Done.",
    labs=[
        ("01","Landing page","Responsive marketing surface.","lt-recon","UI"),
        ("02","Auth flow","Register/login API + client form.","lt-defend","Auth"),
        ("03","Entity CRUD","REST + DB wiring.","lt-attack","API"),
        ("04","React tables","Sort/filter UX.","lt-recon","UX"),
        ("05","Deploy","CI green + public URL.","lt-attack","DevOps"),
        ("06","Demo defense","Presentation + Q&A.","lt-attack","Capstone"),
    ],
    labs_footer="+ Storybook-style component checklist for UI polish.",
    exam_eyebrow="Assessment",
    exam_head=("Demo + repo review.","Real hiring signal."),
    exam_intro="Passing requires deployed project + recorded demo + README that passes our rubric.",
    exam_main=dict(name="Capstone rubric",rows=[
        ("Functionality","Core user journeys operate without manual DB hacks"),
        ("Quality","Readable structure, meaningful commits"),
        ("Security","No secrets in repo; auth sanity"),
        ("Communication","10-minute demo clarity"),
        ("Passing",'<span class="pass-highlight">Meets rubric</span>'),
        ("Resit","One remediation sprint"),
    ]),
    exam_optional=None,
    mock_title="Weekly checkpoints",
    mock_programme=[("01","UI review","Mid-week design critique."),("02","API review","Backend walkthrough."),("03","Dry-run demo","Dress rehearsal.")],
    pass_rate=91,
    pass_head_html='91% ship a portfolio<br><em>employers open.</em>',
    pass_intro="Most self-taught portfolios stall at 80%. We force the last 20% \u2014 deploy, docs, demo polish.",
    pass_pills=["React + Node","Portfolio","Deploy","91% complete","Mentors"],
    pass_compare=[("Tutorial hell","Endless courses, nothing shipped."),("Nexperts","Repo + deploy + demo required.")],
    next_eyebrow="Your engineering path",
    next_head=("Stack with","cloud & DevOps."),
    next_steps_intro="Graduates often continue with Docker, CI/CD or Azure/AWS developer certs.",
    next_steps=[("Before this","Basic computer literacy","Direct entry.","Entry \u2192"),("You are here","Full Stack Web Dev","Portfolio programme.","Currently viewing \u2192"),("Recommended next","Docker / AZ-204","Ship faster in cloud teams.","View Docker \u2192")],
    path_name="software engineering",
    path_chips=[("JavaScript","prev"),("Full Stack","you"),("Docker","next"),("AZ-204","next"),("DevOps","next")],
    salary_html='Junior full-stack roles in KL: <strong style="color:#86efac">RM 4,800 \u2013 RM 8,500/month</strong> depending on portfolio strength.',
    reviews_eyebrow="Student Reviews",
    reviews_head=("What our full-stack","builders say."),
    reviews_summary=("4.8",188,28,6,224),
    reviews=[
        ("\u2605\u2605\u2605\u2605\u2605","Deployed my capstone on Friday, interviewed Monday, offer Wednesday.","rav-b","SC","Siti Chan","Developer","\u2713 Hired"),
        ("\u2605\u2605\u2605\u2605\u2605","PR reviews hurt emotionally but fixed my Git hygiene forever.","rav-m","DW","Darren Wong","Career switch","\u2713 Portfolio"),
        ("\u2605\u2605\u2605\u2605","Hard pace \u2014 not a vacation bootcamp.","rav-g","IL","Ivy Lim","Marketing","\u2713 Portfolio"),
        ("\u2605\u2605\u2605\u2605\u2605","Instructors actually answer Slack at night. Rare.","rav-a","VG","Vinesh Gopal","Graduate","\u2713 Portfolio"),
    ],
    price="RM 3,200", price_orig="RM 3,600", price_save="Save 11%",
    price_note="Per person \u00b7 Includes hosting stipend for demo deploy",
    sidebar_meta=[("Duration","6 days / 48 hrs"),("Next intake","12 Aug 2026"),("Format","Hybrid"),("Level","Beginner+"),("Language","English"),("Cert body","Nexperts Skill"),("Exam",'<span class="smeta-badge">Portfolio</span>')],
    whats_included=["Repo templates","Code reviews","Deploy playbook","Demo coaching","Certificate"],
    verify_items=["Nexperts skill verification ID","Public demo URL archived"],
    guarantee_text="Complete sprint + fail rubric? One complimentary remediation week.",
))


BATCH.append(dict(
    slug="digital-marketing",
    title="Digital Marketing Certification",
    title_html='Digital Marketing<br><em>Certification Course</em>',
    vendor_short="Skill", watermark="MKTG", crumb_vendor="Skill-Based",
    subtitle="SEO, paid media foundations, analytics, content strategy, marketing automation and conversion optimisation \u2014 taught with Malaysian consumer and B2B examples you can reuse Monday morning.",
    badges=[("cb-vendor","Nexperts Skill"),("cb-level","Foundation \u2192 Practitioner"),("cb-new","2026 Playbook"),("cb-hot","Growth")],
    hero_meta=common_meta("4 days / 32 hrs","Workshop + Live Builds","On-site \u00b7 Virtual \u00b7 Hybrid",94,"19 Aug 2026"),
    hero_img=HERO_IMG,
    quick_wins=[
        ("\U0001F4C8","Funnel thinking","Awareness \u2192 acquisition \u2192 retention metrics that matter"),
        ("\U0001F50D","SEO essentials","Technical hygiene + content clusters"),
        ("\U0001F4F1","Paid media literacy","Search + social campaign architecture without wasting budget"),
        ("\U0001F9E0","Analytics","GA4 reports that executives actually read"),
    ],
    overview_eyebrow="What this course is",
    overview_head=("Marketing that","shows numbers."),
    overview_p1="Digital marketing is no longer a side task for an intern. Malaysian enterprises expect measurable pipeline contribution \u2014 this course builds your vocabulary and hands-on muscle across owned, earned and paid channels.",
    overview_p2="You will build a mini campaign plan for a real Malaysian brand brief (anonymised) and present optimisations with forecast impacts.",
    overview_p3="Includes HRD Corp-friendly documentation for corporate bookings.",
    who_for=[
        ("\U0001F4BC","Marketing generalists","Upskilling from traditional comms."),
        ("\U0001F4CA","Founders & SMB owners","You run your own ads today."),
        ("\U0001F4F1","Social managers","You need strategic depth."),
        ("\U0001F4DA","Career switchers","Portfolio projects for agency hiring."),
        ("\U0001F3AF","Sales teams","Better alignment with demand-gen."),
        ("\U0001F465","Corporate teams","Cohort pricing available."),
    ],
    prereqs=["Comfort with spreadsheets","Active email + browser","No prior marketing degree required"],
    prereqs_note="GA4 property access helpful \u2014 we provide sandbox if needed.",
    curriculum_eyebrow="Course Curriculum",
    curriculum_head=("Four intensive days.","Channel integration."),
    curriculum_intro="Each day blends lecture, live tool demos and team exercises.",
    modules=[
        ("01","Strategy & customer",["Positioning","Personas for MY markets","Value proposition canvas","Competitive scans","Lab: sharpen brief"]),
        ("02","SEO & content",["Technical SEO checklist","Keyword clustering","Content calendars","EEAT thinking","Lab: optimise landing copy"]),
        ("03","Paid media",["Campaign structures","Creative testing","Budget pacing","Lab: build paid media plan"]),
        ("04","Analytics & automation",["GA4 funnels","Tagging hygiene intro","Email nurture arcs","Conversion optimisation","Lab: insight presentation"]),
    ],
    labs_eyebrow="Live Workshops",
    labs_head=("Campaign labs.","Team rotations."),
    labs_intro="Teams rotate presenter role to mimic agency stand-ups.",
    labs=[
        ("01","Brief unpack","Translate business goal to KPI tree.","lt-recon","Strategy"),
        ("02","SEO fixes","Recommend technical + content actions.","lt-defend","SEO"),
        ("03","Paid plan","Budget split across channels.","lt-attack","Paid"),
        ("04","GA4 story","Turn reports into decisions.","lt-recon","Data"),
        ("05","Nurture sketch","Map emails to funnel stage.","lt-defend","Automation"),
        ("06","Pitch","Executive summary presentation.","lt-attack","Capstone"),
    ],
    labs_footer="+ Creative swipe-file library (licensed samples).",
    exam_eyebrow="Assessment",
    exam_head=("Campaign defense.","Executive storyline."),
    exam_intro="Present your mini campaign with forecasts, risks and optimisation backlog.",
    exam_main=dict(name="Practical assessment",rows=[
        ("Deliverable","Slide deck + spreadsheet model"),
        ("Duration","20-minute presentation + Q&A"),
        ("Passing",'<span class="pass-highlight">Meets rubric</span>'),
        ("Retries","One coached revision"),
    ]),
    exam_optional=None,
    mock_title="Practice milestones",
    mock_programme=[("01","Persona drill",""),("02","Media plan draft",""),("03","Dry run","")],
    pass_rate=94,
    pass_head_html='94% earn credential<br><em>first submission.</em>',
    pass_intro="We coach storytelling \u2014 the skill that separates analysts from leads.",
    pass_pills=["GA4","Paid basics","94% pass","MY briefs","Certificate"],
    pass_compare=[("Random tips workshops","No cohesive portfolio piece."),("Nexperts","Single defended campaign artefact.")],
    next_eyebrow="Your growth path",
    next_head=("Pair with","analytics depth."),
    next_steps_intro="Continue with advanced analytics, marketing ops automation or platform certs (Google/Meta) independently.",
    next_steps=[("Before this","Excel basics helpful","Not mandatory.","Excel \u2192"),("You are here","Digital Marketing Cert","Strategic practitioner track.","Currently viewing \u2192"),("Recommended next","PL-300 / SQL","Attribution + data storytelling.","View PL-300 \u2192")],
    path_name="digital growth",
    path_chips=[("Content","prev"),("Digital Mktg","you"),("GA4 Pro","next"),("Marketing Ops","next")],
    salary_html='Digital marketing executives in KL: <strong style="color:#86efac">RM 4,200 \u2013 RM 9,000/month</strong> varying by agency vs client-side.',
    reviews_eyebrow="Student Reviews",
    reviews_head=("What our marketers","say."),
    reviews_summary=("4.8",142,24,8,168),
    reviews=[
        ("\u2605\u2605\u2605\u2605\u2605","Finally connected SEO tasks to revenue narrative for my boss.","rav-b","AL","Amelia Lau","Marketing Exec","\u2713 Passed"),
        ("\u2605\u2605\u2605\u2605\u2605","Paid media section alone paid for the course \u2014 stopped wasting/boosting wrong audiences.","rav-m","RH","Rahim Halim","Founder","\u2713 Passed"),
        ("\u2605\u2605\u2605\u2605","Wish we had another day on Meta ads but overall solid.","rav-g","PY","Priya Yadav","Social Lead","\u2713 Passed"),
        ("\u2605\u2605\u2605\u2605\u2605","GA4 module was the clarity I needed after confusing YouTube tutorials.","rav-a","CK","Choong Kai","Analyst","\u2713 Passed"),
    ],
    price="RM 2,100", price_orig="RM 2,350", price_save="Save 11%",
    price_note="Per person \u00b7 HRD Corp paperwork assistance included",
    sidebar_meta=[("Duration","4 days / 32 hrs"),("Next intake","19 Aug 2026"),("Format","Hybrid"),("Level","Foundation+"),("Language","English / BM support"),("Cert body","Nexperts Skill"),("Exam",'<span class="smeta-badge">Presentation</span>')],
    whats_included=["Workbook","Campaign templates","GA4 sandbox guide","Certificate"],
    verify_items=["Nexperts verification","Slide artifact archived"],
    guarantee_text="Submit portfolio revision within 14 days if rubric not met first time.",
))


BATCH.append(dict(
    slug="excel-basic",
    title="Microsoft Excel 2019 Basic",
    title_html='Microsoft Excel 2019<br><em>Basic (EXC19B)</em>',
    vendor_short="Skill", watermark="XLSX", crumb_vendor="Skill-Based",
    subtitle="Spreadsheet confidence for every office professional \u2014 navigation, formatting, formulas, charts and printing \u2014 using Excel 2019 / Microsoft 365 with Malaysian business examples.",
    badges=[("cb-vendor","Nexperts Skill"),("cb-level","Foundation"),("cb-new","EXC19B aligned"),("cb-hot","Office essential")],
    hero_meta=common_meta("2 days / 16 hrs","Hands-on Lab","On-site \u00b7 Virtual",98,"26 Aug 2026"),
    hero_img=HERO_IMG,
    quick_wins=[
        ("\U0001F4C4","Navigation","Ribbon, quick access, freeze panes, efficient selection"),
        ("\u2712\uFE0F","Formatting","Number formats, tables, conditional formatting basics"),
        ("\u2795","Formulas","SUM, AVERAGE, logical IF, relative vs absolute refs"),
        ("\U0001F4CA","Charts & print","Present insights + print-ready layouts"),
    ],
    overview_eyebrow="What this course is",
    overview_head=("Excel basics","that stick."),
    overview_p1="Most workplace frustration with Excel is not intelligence \u2014 it is never being shown the efficient patterns. Two focused days fix that for HR, finance, ops and admin teams.",
    overview_p2="Each learner works on realistic datasets (leave trackers, simple P&amp;L summaries, inventory lists).",
    overview_p3="Optional half-day add-on introduces Power Query awareness for teams planning to continue to our Advanced Analytics track.",
    who_for=[
        ("\U0001F4BC","Administrators","Daily reporting duties."),
        ("\U0001F4DA","Fresh graduates","Workplace readiness."),
        ("\U0001F4C8","Managers","Delegating template standards."),
        ("\U0001F3AF","Career returnees","Confidence rebuild."),
        ("\U0001F465","Corporate teams","On-site cohorts welcome."),
        ("\U0001F9E0","Anyone avoiding Excel","We normalise asking questions."),
    ],
    prereqs=["Basic Windows/macOS literacy","Excel installed (2019 or Microsoft 365)"],
    prereqs_note="HRD Corp claims supported \u2014 speak to our coordinator.",
    curriculum_eyebrow="Course Curriculum",
    curriculum_head=("Two days.","Hands-on."),
    curriculum_intro="See trainer screen + replicate immediately \u2014 no death-by-slide.",
    modules=[
        ("01","Interface & editing",["Workbooks vs sheets","Efficient navigation","Data entry patterns","Find/replace","Lab: clean messy attendance sheet"]),
        ("02","Formatting & tables",["Cell styles","Table objects","Sort/filter","Lab: HR roster"]),
        ("03","Formulas",["Operators","SUM/AVERAGE/MIN/MAX","IF basics","Relative/Absolute refs","Lab: budget variance"]),
        ("04","Charts & output",["Charts","Sparklines intro","Page setup & print","Lab: one-page summary for boss"]),
    ],
    labs_eyebrow="Labs",
    labs_head=("Repeatable patterns.","Immediate apply."),
    labs_intro="Every learner leaves with starter templates for their department.",
    labs=[
        ("01","Cleanup","Normalise messy sheet.","lt-recon","Basics"),
        ("02","HR roster","Formatted table + filters.","lt-recon","Format"),
        ("03","Budget","IF + absolute refs.","lt-defend","Formula"),
        ("04","Dashboard lite","Chart + print layout.","lt-attack","Output"),
        ("05","Timed challenge","45-minute integrated task.","lt-attack","Exam"),
        ("06","Show & tell","Share tip with class.","lt-recon","Capstone"),
    ],
    labs_footer="+ Take-home exercise workbook with solutions.",
    exam_eyebrow="Assessment",
    exam_head=("Practical exam.","Timed spreadsheet tasks."),
    exam_intro="Closed-book practical using datasets not seen in class \u2014 mirrors workplace surprises.",
    exam_main=dict(name="Excel Basic practical",rows=[
        ("Tasks","Formatting + formulas + chart"),
        ("Duration","60 minutes"),
        ("Passing",'<span class="pass-highlight">80% rubric</span>'),
        ("Retake","One complimentary"),
    ]),
    exam_optional=None,
    mock_title="Daily drills",
    mock_programme=[("01","Warm-ups",""),("02","Formula sprint",""),("03","Mock exam","")],
    pass_rate=98,
    pass_head_html='98% pass practical<br><em>first attempt.</em>',
    pass_intro="We drill muscle memory until spreadsheet fear disappears.",
    pass_pills=["Hands-on","Templates","98% pass","HRD ready","Certificate"],
    pass_compare=[("YouTube learning","Inconsistent practice."),("Nexperts","Structured reps + feedback.")],
    next_eyebrow="Your analytics path",
    next_head=("Graduate to","Advanced Analytics."),
    next_steps_intro="Continue to Excel Advanced Analytics or SQL tracks.",
    next_steps=[("Before this","None","Open entry.","Entry \u2192"),("You are here","Excel 2019 Basic","Foundation credential.","Currently viewing \u2192"),("Recommended next","Excel Advanced","Depth for analysts.","View Advanced \u2192")],
    path_name="business productivity",
    path_chips=[("Excel Basic","you"),("Excel Adv","next"),("SQL","next"),("PL-300","next")],
    salary_html='Office professionals with strong Excel foundations progress faster into analyst tracks (+15\u201325% salary uplift typical within 12 months).',
    reviews_eyebrow="Student Reviews",
    reviews_head=("What our Excel basics","students say."),
    reviews_summary=("4.9",260,30,4,312),
    reviews=[
        ("\u2605\u2605\u2605\u2605\u2605","Stopped fearing month-end reports.","rav-b","LN","Liyana Nor","Admin","\u2713 Passed"),
        ("\u2605\u2605\u2605\u2605\u2605","Patient instructors \u2014 I asked 'embarrassing' questions every hour.","rav-m","BT","Ben Tan","Ops","\u2713 Passed"),
        ("\u2605\u2605\u2605\u2605","Wish session was 3 days for our team volume.","rav-g","SK","Siew Kim","HR","\u2713 Passed"),
        ("\u2605\u2605\u2605\u2605\u2605","Templates alone saved me 4 hours weekly.","rav-a","MR","Malar Raj","Finance","\u2713 Passed"),
    ],
    price="RM 990", price_orig="RM 1,150", price_save="Save 14%",
    price_note="Per person \u00b7 Includes digital workbook",
    sidebar_meta=[("Duration","2 days / 16 hrs"),("Next intake","26 Aug 2026"),("Format","On-site / Virtual"),("Level","Foundation"),("Language","English / BM"),("Cert body","Nexperts Skill"),("Exam",'<span class="smeta-badge">Practical</span>')],
    whats_included=["Workbook","Templates","Certificate","HRD assist"],
    verify_items=["Nexperts verification"],
    guarantee_text="Attend full course + fail practical? Free retake next public intake.",
))


BATCH.append(dict(
    slug="salesforce-admin",
    title="Salesforce Admin & Automation",
    title_html='Salesforce<br><em>Admin &amp; Automation</em>',
    vendor_short="Skill", watermark="SFDC", crumb_vendor="Skill-Based",
    subtitle="Navigate Salesforce Lightning like a product owner \u2014 objects, security model, automation (Flow), reports/dashboards and release hygiene. Designed for MY enterprises adopting Sales/Service Cloud.",
    badges=[("cb-vendor","Nexperts Skill"),("cb-level","Associate \u2192 Advanced Admin"),("cb-new","Spring \'26 features"),("cb-hot","CRM ops")],
    hero_meta=common_meta("5 days / 40 hrs","Tenant Labs","Virtual \u00b7 Hybrid",89,"2 Sept 2026"),
    hero_img=HERO_IMG,
    quick_wins=[
        ("\U0001F512","Security model","Profiles, permission sets, sharing rules intuition"),
        ("\u26A1","Automation","Record-triggered Flow patterns guardrails"),
        ("\U0001F4CA","Insights","Reports, dashboards, CRM analytics hygiene"),
        ("\U0001F680","App lifecycle","Sandboxes, change sets, deployment awareness"),
    ],
    overview_eyebrow="What this course is",
    overview_head=("Admin craft","meets automation."),
    overview_p1="Salesforce powers revenue and service operations across Malaysian enterprises. Great admins reduce licence waste, keep data trustworthy and automate repetitive tasks safely.",
    overview_p2="Labs run in dedicated training orgs with realistic MY customer scenarios (retail pipeline, manufacturing cases, telco service queues).",
    overview_p3="Optional exam pathway discussion for Salesforce Certified Administrator \u2014 voucher add-on.",
    who_for=[
        ("\U0001F4BC","CRM coordinators","You configure requests today."),
        ("\U0001F510","IT application owners","You govern SaaS sprawl."),
        ("\U0001F4CA","RevOps analysts","You need depth beyond spreadsheets."),
        ("\U0001F4DA","Consultants","Implementation readiness."),
        ("\U0001F3AF","Career switchers","High-demand SaaS skill."),
        ("\U0001F465","Teams","Private cohort pricing."),
    ],
    prereqs=["Browser fluency","Understanding of sales/service processes helpful"],
    prereqs_note="Trailhead account free \u2014 create before class.",
    curriculum_eyebrow="Course Curriculum",
    curriculum_head=("Five days.","Tenant-first."),
    curriculum_intro="Each topic ends with an acceptance checklist mirroring enterprise governance.",
    modules=[
        ("01","Platform essentials",["Navigation","Data model","Apps & tabs","Search","Lab: build custom object"]),
        ("02","Security",["Profiles vs permission sets","OWD + sharing","Field-level security","Lab: design secure sharing"]),
        ("03","Automation",["Flow vs Process Builder migration mindset","Record-triggered patterns","Fault paths","Lab: automate SLA alert"]),
        ("04","Analytics & release",["Report types","Dashboards","Sandbox promo","Lab: exec dashboard pack"]),
    ],
    labs_eyebrow="Tenant Labs",
    labs_head=("Hands-on org.","Safe mistakes."),
    labs_intro="Break things in training orgs \u2014 not production.",
    labs=[
        ("01","Model HR object","Relationships + page layouts.","lt-recon","Data"),
        ("02","Fix security bug","Diagnose sharing issue.","lt-defend","Sec"),
        ("03","Flow challenge","Automation with rollback plan.","lt-attack","Flow"),
        ("04","Report pack","Cross-filter story.","lt-recon","Analytics"),
        ("05","Deploy sim","Change set walkthrough.","lt-defend","ALM"),
        ("06","Capstone","Business story automation.","lt-attack","Capstone"),
    ],
    labs_footer="+ Trailhead assignment map.",
    exam_eyebrow="Certification pathway",
    exam_head=("Salesforce Certified Administrator.","Optional track."),
    exam_intro="Course aligns to exam blueprint; voucher optional. Internal practical exam available for corporate cohorts.",
    exam_main=dict(name="Administrator exam (optional)",rows=[
        ("Questions","60 scored + 5 unscored"),
        ("Duration","105 minutes"),
        ("Passing",'<span class="pass-highlight">65% (Salesforce publishes scaled scoring)</span>'),
        ("Delivery","Online proctored / Kryterion"),
    ]),
    exam_optional=dict(name="Nexperts practical",rows=[("Skills check","Tenant configuration scenarios"),("Passing","Rubric-based")]),
    mock_title="Exam readiness",
    mock_programme=[("01","Domain quizzes",""),("02","Half exam",""),("03","Full practice","")],
    pass_rate=89,
    pass_head_html='89% cert pass<br><em>with voucher track.</em>',
    pass_intro="Most failures come from shallow security understanding \u2014 we overweight that domain.",
    pass_pills=["Flows","Security","89% cert","Tenant labs","Trail map"],
    pass_compare=[("Trailhead only","No structured defence of designs."),("Nexperts","Facilitated labs + critique.")],
    next_eyebrow="Your Salesforce path",
    next_head=("Grow toward","Platform App Builder."),
    next_steps_intro="Continue with advanced Flow, integration patterns or multi-cloud courses.",
    next_steps=[("Before this","CRM basics","Helpful context.","CRM \u2192"),("You are here","Salesforce Admin","Operations + automation.","Currently viewing \u2192"),("Recommended next","Platform App Builder cert prep","Extended config depth.","Ask advisor \u2192")],
    path_name="Salesforce operations",
    path_chips=[("Excel","prev"),("SF Admin","you"),("App Builder","next"),("Integration","next")],
    salary_html='Salesforce admins in Malaysia: <strong style="color:#86efac">RM 6,500 \u2013 RM 12,000/month</strong> depending on multi-cloud exposure.',
    reviews_eyebrow="Student Reviews",
    reviews_head=("What our Salesforce","admins say."),
    reviews_summary=("4.8",96,18,6,112),
    reviews=[
        ("\u2605\u2605\u2605\u2605\u2605","Flows finally click structurally \u2014 not random clicks.","rav-b","NW","Nadia Wong","RevOps","\u2713 Certified"),
        ("\u2605\u2605\u2605\u2605\u2605","Security module saved our production org from bad sharing.","rav-m","KL","Ken Liew","IT Apps","\u2713 Certified"),
        ("\u2605\u2605\u2605\u2605","Fast pace \u2014 pre-read Trailhead links mandatory.","rav-g","SS","Saran Singh","Consultant","\u2713 Passed"),
        ("\u2605\u2605\u2605\u2605\u2605","Worth every sen for our corporate cohort.","rav-a","CY","Chloe Yap","Manager","\u2713 Team uplift"),
    ],
    price="RM 4,800", price_orig="RM 5,400", price_save="Save 11%",
    price_note="Per person \u00b7 Exam voucher optional add-on",
    sidebar_meta=[("Duration","5 days / 40 hrs"),("Next intake","2 Sept 2026"),("Format","Virtual-first"),("Level","Associate+"),("Language","English"),("Cert body","Salesforce + Nexperts"),("Exam",'<span class="smeta-badge">Optional</span>')],
    whats_included=["Training org access","Lab guides","Trail map","Exam readiness pack"],
    verify_items=["Salesforce certification verification (if exam taken)","Nexperts completion certificate"],
    guarantee_text="Trail mock below target? Extra coaching session before exam booking.",
))


BATCH.append(dict(
    slug="servicenow-admin",
    title="ServiceNow Administration Fundamentals",
    title_html='ServiceNow<br><em>Administration Fundamentals</em>',
    vendor_short="Skill", watermark="NOW", crumb_vendor="Skill-Based",
    subtitle="Core Now Platform administration \u2014 users/groups, ACLs, lists & forms, imports, update sets and baseline incident/change workflows \u2014 on Calgary-compatible training instances.",
    badges=[("cb-vendor","Nexperts Skill"),("cb-level","Fundamentals"),("cb-new","Washington aligned"),("cb-hot","ITSM ops")],
    hero_meta=common_meta("5 days / 40 hrs","Instance Labs","Virtual \u00b7 Hybrid",90,"9 Sept 2026"),
    hero_img=HERO_IMG,
    quick_wins=[
        ("\U0001F465","Identity","Users, groups, departments & delegation"),
        ("\U0001F512","Security","ACL intuition without breaking production"),
        ("\u2699\uFE0F","Config","Dictionary overrides, business rules intro"),
        ("\U0001F4E6","Delivery","Update sets + agile basics for admins"),
    ],
    overview_eyebrow="What this course is",
    overview_head=("Operate the","platform safely."),
    overview_p1="ServiceNow underpins ITSM for Malaysian enterprises and shared-services hubs. Skilled admins shorten backlog, protect instance health and unblock automation squads.",
    overview_p2="Labs use fresh training instances \u2014 no fear of breaking prod.",
    overview_p3="Pairs naturally with our Implementation course for consultants delivering greenfield projects.",
    who_for=[
        ("\U0001F527","ITSM coordinators","You route tickets today."),
        ("\U0001F510","Application owners","Governance for Citizen dev."),
        ("\U0001F4BC","MSSP staff","Multi-tenant awareness."),
        ("\U0001F4DA","Fresh grads","Enterprise SaaS career."),
        ("\U0001F3AF","Career switchers","Demand for Now talent rising."),
        ("\U0001F465","Corporate cohorts","Available."),
    ],
    prereqs=["Basic ITIL awareness helpful","Browser fluency"],
    prereqs_note="ServiceNow developer instance signup instructions emailed pre-class.",
    curriculum_eyebrow="Course Curriculum",
    curriculum_head=("Admin fundamentals.","Hands-on."),
    curriculum_intro="Each module maps to typical onboarding tasks for new admins.",
    modules=[
        ("01","Navigation & data",["Lists & forms","Filters","Related lists","Imports","Lab: user bulk load"]),
        ("02","Security",["ACL evaluation order","High-security settings awareness","Impersonation etiquette","Lab: debug ACL"]),
        ("03","Automation lite",["Business rules concept","Script policy","Flow Designer touchpoint","Lab: auto-assign by category"]),
        ("04","Delivery hygiene",["Update sets","Scoped apps awareness","SDLC conversation","Lab: promote change"]),
    ],
    labs_eyebrow="Instance labs",
    labs_head=("Break / fix.","Learn."),
    labs_intro="Fault injection teaches faster than happy-path clicking.",
    labs=[
        ("01","Import cleanup","Transform maps basics.","lt-recon","Data"),
        ("02","ACL mystery","Ticket visibility bug.","lt-defend","Sec"),
        ("03","Routing rule","Flow/logic fix.","lt-attack","Auto"),
        ("04","Update set clash","Merge awareness.","lt-defend","ALM"),
        ("05","Catalog item","Variable troubleshooting.","lt-recon","UX"),
        ("06","Admin capstone","Incident day simulation.","lt-attack","Capstone"),
    ],
    labs_footer="+ PDF quick-reference posters.",
    exam_eyebrow="Assessment",
    exam_head=("Practical scenarios.","Graded rubric."),
    exam_intro="Scenario exam ensures you can justify changes vs risky shortcuts.",
    exam_main=dict(name="Admin practical",rows=[
        ("Format","3 scenario tickets + fix plan"),
        ("Passing",'<span class="pass-highlight">80% rubric</span>'),
        ("Retake","One included"),
    ]),
    exam_optional=None,
    mock_title="Daily checks",
    mock_programme=[("01","Quiz",""),("02","Lab timed",""),("03","Mock","")],
    pass_rate=90,
    pass_head_html='90% rubric pass<br><em>first attempt.</em>',
    pass_intro="We emphasise governance \u2014 the differentiator for enterprise hires.",
    pass_pills=["ITSM","Security","90% pass","Instance labs","Badge"],
    pass_compare=[("Ad-hoc learning","No crisis simulations."),("Nexperts","Fault-led labs.")],
    next_eyebrow="Your Now journey",
    next_head=("Continue to","implementation depth."),
    next_steps_intro="Pair with Platform Implementation course or CSA exam prep when ready.",
    next_steps=[("Before this","ITIL awareness","Helpful.","ITIL \u2192"),("You are here","ServiceNow Admin Fundamentals","Operate platform.","Currently viewing \u2192"),("Recommended next","ServiceNow Implementation","Deploy greenfield.","View Implementation \u2192")],
    path_name="ServiceNow operations",
    path_chips=[("ITIL","prev"),("SN Admin","you"),("SN Impl","next"),("CSA","next")],
    salary_html='ServiceNow admins in MY shared-services hubs: <strong style="color:#86efac">RM 7,000 \u2013 RM 13,000/month</strong> depending on scope.',
    reviews_eyebrow="Student Reviews",
    reviews_head=("What our ServiceNow","admins say."),
    reviews_summary=("4.8",84,16,7,104),
    reviews=[
        ("\u2605\u2605\u2605\u2605\u2605","ACL lab finally made evaluation order stick.","rav-b","GW","Gina Wee","ITSM","\u2713 Passed"),
        ("\u2605\u2605\u2605\u2605\u2605","Virtual but instances were snappy \u2014 big plus.","rav-m","HR","Hakim Riza","Analyst","\u2713 Passed"),
        ("\u2605\u2605\u2605\u2605","Wish more Flow Designer depth \u2014 but fundamentals solid.","rav-g","TT","Teresa Tan","Coordinator","\u2713 Passed"),
        ("\u2605\u2605\u2605\u2605\u2605","Our team of six attended \u2014 reduced onboarding time by weeks.","rav-a","JL","Jason Lim","Manager","\u2713 Team"),
    ],
    price="RM 4,600", price_orig="RM 5,100", price_save="Save 10%",
    price_note="Per person \u00b7 Includes training instance window",
    sidebar_meta=[("Duration","5 days / 40 hrs"),("Next intake","9 Sept 2026"),("Format","Virtual"),("Level","Fundamentals"),("Language","English"),("Cert body","Nexperts Skill"),("Exam",'<span class="smeta-badge">Practical</span>')],
    whats_included=["Lab workbook","Quick posters","Certificate"],
    verify_items=["Nexperts verification"],
    guarantee_text="Fail scenario exam? Complimentary coaching + second attempt.",
))


BATCH.append(dict(
    slug="servicenow-platform",
    title="ServiceNow Platform Implementation",
    title_html='ServiceNow<br><em>Platform Implementation</em>',
    vendor_short="Skill", watermark="IMPL", crumb_vendor="Skill-Based",
    subtitle="Lead greenfield or rebuild programmes \u2014 CMDB foundations, service mapping lite, MID server awareness, scoped application basics, integration touchpoints and executive steering artefacts.",
    badges=[("cb-vendor","Nexperts Skill"),("cb-level","Professional"),("cb-new","Blueprint 2026"),("cb-hot","Transformation")],
    hero_meta=common_meta("5 days / 40 hrs","Workshop + Labs","Virtual \u00b7 Hybrid",88,"16 Sept 2026"),
    hero_img=HERO_IMG,
    quick_wins=[
        ("\U0001F4CB","Blueprint","Discovery workshops, requirement traceability"),
        ("\U0001F310","CMDB","CI classes, reconciliation mindset"),
        ("\U0001F517","Integrations","REST / webhook patterns at architect-lite depth"),
        ("\U0001F4BC","Governance","Steering decks for CIO sponsors"),
    ],
    overview_eyebrow="What this course is",
    overview_head=("Deliver programmes","not tickets."),
    overview_p1="Implementation consultants bridge ITSM design and platform reality. This course trains you to run structured workshops, translate process maps into backlog stories and orchestrate technical tracks without burning the instance.",
    overview_p2="Case studies reference Malaysian enterprise archetypes (banking ops tower, telco NOC, shared services SSC).",
    overview_p3="Admin fundamentals course recommended first unless you already operate instances daily.",
    who_for=[
        ("\U0001F4BC","Project leads","You own timeline + scope."),
        ("\U0001F527","Senior admins","Moving into transformation."),
        ("\U0001F510","Architects","Need ServiceNow specifics."),
        ("\U0001F465","SI consultants","Implementation readiness."),
        ("\U0001F3AF","Account managers","Credibility in discovery."),
        ("\U0001F4DA","MBA tech grads","Structured consulting toolkit."),
    ],
    prereqs=["ServiceNow admin experience OR prior Nexperts admin course","Basic ITIL / SDLC literacy"],
    prereqs_note="Portfolio interview for fast-track candidates.",
    curriculum_eyebrow="Course Curriculum",
    curriculum_head=("Implementation lifecycle.","End to end."),
    curriculum_intro="Each day simulates a programme phase with artefacts you can take to clients.",
    modules=[
        ("01","Discovery & blueprint",["Stakeholder mapping","As-is / to-be","Requirement prioritisation","Lab: workshop plan"]),
        ("02","Technical foundation",["Instance strategy","Domain separation awareness","MID server stories","Lab: integration risk register"]),
        ("03","CMDB programme",["CI lifecycle","Data ownership","Reconciliation cadence","Lab: CMDB readiness checklist"]),
        ("04","Deployment & value",["Testing waves","Change enablement","Success metrics","Lab: steering deck"]),
    ],
    labs_eyebrow="Implementation labs",
    labs_head=("Artefact-driven.","Consulting tempo."),
    labs_intro="Team exercises use Miro-style templates (provided as exports).",
    labs=[
        ("01","Blueprint workshop","Facilitation drills.","lt-recon","Discovery"),
        ("02","Backlog slice","Story splitting exercise.","lt-defend","Agile"),
        ("03","CMDB workshop","Data-quality plan.","lt-attack","CMDB"),
        ("04","Integration board","API pattern selection.","lt-recon","Integration"),
        ("05","Steering deck","Exec storyline.","lt-defend","Gov"),
        ("06","Capstone pitch","Programme defence.","lt-attack","Capstone"),
    ],
    labs_footer="+ Contract-ready templates (DOCX).",
    exam_eyebrow="Assessment",
    exam_head=("Programme defense.","Panel Q&A."),
    exam_intro="Present a full mini transformation plan with risks, budget bands and wave plan.",
    exam_main=dict(name="Implementation practicum",rows=[
        ("Deliverable","Slide deck + RAID log + backlog"),
        ("Duration","25-minute defense"),
        ("Passing",'<span class="pass-highlight">Panel rubric 80%+</span>'),
    ]),
    exam_optional=None,
    mock_title="Coaching loops",
    mock_programme=[("01","Story critique",""),("02","Dry run",""),("03","Panel sim","")],
    pass_rate=88,
    pass_head_html='88% defend programmes<br><em>first attempt.</em>',
    pass_intro="Panel includes practising SI consultants \u2014 tough but realistic.",
    pass_pills=["CMDB","Integrations","Governance","Templates","Panel"],
    pass_compare=[("Generic PM courses","Missing platform nuance."),("Nexperts","ServiceNow-native artefacts.")],
    next_eyebrow="Your consulting path",
    next_head=("Pair with","CSA / architectural certs."),
    next_steps_intro="Continue with vendor architect programmes or advanced integration workshops.",
    next_steps=[("Before this","Admin fundamentals","Strongly recommended.","SN Admin \u2192"),("You are here","Platform Implementation","Lead programmes.","Currently viewing \u2192"),("Recommended next","Integration mastery","Deep APIs & spoke patterns.","Ask advisor \u2192")],
    path_name="ServiceNow consulting",
    path_chips=[("SN Admin","prev"),("Implementation","you"),("Architect","next"),("ITIL DPI","next")],
    salary_html='Implementation consultants in KL / regional SI firms: <strong style="color:#86efac">RM 9,000 \u2013 RM 18,000/month</strong> plus allowances.',
    reviews_eyebrow="Student Reviews",
    reviews_head=("What our implementers","say."),
    reviews_summary=("4.7",58,22,10,76),
    reviews=[
        ("\u2605\u2605\u2605\u2605\u2605","Steering deck template alone saved me days on my first client.","rav-b","MC","Marcus Chew","Consultant","\u2713 Passed"),
        ("\u2605\u2605\u2605\u2605\u2605","Panel feedback brutally useful.","rav-m","SA","Shanti A/P","SI Lead","\u2713 Passed"),
        ("\u2605\u2605\u2605\u2605","Come with admin experience \u2014 course assumes it.","rav-g","PL","Paul Lim","PM","\u2713 Passed"),
        ("\u2605\u2605\u2605\u2605\u2605","Linked me with hiring partner post-class.","rav-a","NR","Nadia Rahman","Career switch","\u2713 Hired"),
    ],
    price="RM 5,200", price_orig="RM 5,800", price_save="Save 10%",
    price_note="Per person \u00b7 Includes template pack licensing",
    sidebar_meta=[("Duration","5 days / 40 hrs"),("Next intake","16 Sept 2026"),("Format","Virtual / Hybrid"),("Level","Professional"),("Language","English"),("Cert body","Nexperts Skill"),("Exam",'<span class="smeta-badge">Panel defense</span>')],
    whats_included=["Templates","Panel feedback recording","Certificate"],
    verify_items=["Nexperts verification"],
    guarantee_text="Panel score below 80%? One remediation coaching cycle included.",
))
