# -*- coding: utf-8 -*-
"""Fortinet Certified Professional (FCP) Network Security."""

from _course_data import HERO_IMG, common_meta

BATCH = [
    dict(
        slug="fortinet-certified-professional-network-security",
        seo_title="Fortinet Certified Professional Course in Malaysia | Nexperts Academy",
        seo_description="Master FortiGate, VPN, SD-WAN, IPS, and Security Fabric with Fortinet Certified Professional Network Security training in Malaysia.",
        canonical_path="/fortinet-certified-professional-network-security-course-malaysia",
        title="Fortinet FCP Network Security",
        title_html="Fortinet Certified Professional<br><em>Network Security Course in Malaysia</em>",
        vendor_short="Fortinet",
        watermark="FCP",
        crumb_vendor="Fortinet",
        subtitle="Build in-demand network security skills with Fortinet Certified Professional (FCP) training — FortiGate, VPN, SD-WAN, IPS, Security Fabric and hands-on labs aligned to Fortinet certification.",
        badges=[
            ("cb-vendor", "Fortinet Authorised"),
            ("cb-level", "Professional · Network Security"),
            ("cb-new", "FCP Secure Networking"),
            ("cb-hot", "FortiGate & SD-WAN"),
        ],
        hero_meta=common_meta(
            "5 days / 40 hrs",
            "Instructor-Led + FortiGate Labs",
            "On-site · Virtual · Hybrid",
            92,
            "16 Jun 2026",
        ),
        hero_img=HERO_IMG,
        quick_wins=[
            ("🛡️", "FortiGate mastery", "Firewall policies, NAT, routing and Security Fabric administration"),
            ("🔐", "Secure connectivity", "SSL VPN and IPsec VPN for remote and site-to-site access"),
            ("📡", "Threat protection", "IPS, antivirus, web filtering and application control"),
            ("🌐", "Secure SD-WAN", "Link monitoring, traffic steering and WAN optimisation"),
        ],
        overview_eyebrow="Fortinet Certified Professional",
        overview_head=("Network security training", "for enterprise defenders."),
        overview_p1="Build in-demand cybersecurity and network security skills with the Fortinet Certified Professional (FCP) Network Security course in Malaysia. This programme helps IT professionals, network engineers, security administrators and cybersecurity specialists gain hands-on expertise deploying, configuring, managing and securing enterprise networks with Fortinet technologies.",
        overview_p2="The Fortinet Certified Professional (FCP) certification validates your ability to secure networks and applications through deployment, management, monitoring and troubleshooting of Fortinet solutions — including FortiGate firewalls, VPNs, SD-WAN, IPS, web filtering and advanced threat protection.",
        overview_quote="Fortinet powers security for enterprises, MSSPs and governments worldwide. FCP proves you can operate FortiGate and Security Fabric in production — not just pass a theory exam.",
        overview_p3="Whether you are advancing your cybersecurity career, strengthening network security expertise or preparing for official Fortinet certification exams, this course delivers the knowledge and practical experience required to succeed.",
        overview_sections=[
            {
                "eyebrow": "Why Choose Fortinet Certified Professional Network Security Training?",
                "eyebrow_class": "m",
                "intro": "Modern organisations rely on secure and resilient networks to protect critical business assets. As cyber threats evolve, demand for certified Fortinet professionals is growing across Malaysia and globally.",
                "bullets": [
                    "Master FortiGate firewall administration",
                    "Configure advanced network security policies",
                    "Implement VPN and secure remote access solutions",
                    "Manage Security Fabric architecture",
                    "Deploy IPS, Antivirus and Web Filtering",
                    "Configure Secure SD-WAN",
                    "Monitor and troubleshoot security incidents",
                    "Prepare for Fortinet FCP certification exams",
                    "Gain practical experience through hands-on labs",
                ],
            },
            {
                "eyebrow": "Course Overview",
                "intro": "The Fortinet Certified Professional Network Security course provides in-depth training on Fortinet's security ecosystem and focuses on real-world implementation scenarios.",
                "subtitle": "Training highlights",
                "bullets": [
                    "FortiGate Firewall Administration",
                    "Security Policies & NAT Configuration",
                    "User Authentication & Access Control",
                    "SSL VPN & IPsec VPN Deployment",
                    "Network Segmentation",
                    "Intrusion Prevention System (IPS)",
                    "Antivirus & Anti-Malware Protection",
                    "Web Filtering & Application Control",
                    "High Availability (HA)",
                    "Routing & Traffic Management",
                    "Fortinet Security Fabric",
                    "Secure SD-WAN Implementation",
                    "Security Monitoring & Troubleshooting",
                ],
            },
            {
                "eyebrow": "Skills You Will Learn",
                "intro": "Upon completion of this training, participants will be able to:",
                "skill_groups": [
                    (
                        "Network Security Fundamentals",
                        [
                            "Network security architecture",
                            "Threat landscape analysis",
                            "Security best practices",
                            "Zero Trust principles",
                        ],
                    ),
                    (
                        "FortiGate Administration",
                        [
                            "Initial setup and configuration",
                            "Firewall policy management",
                            "Routing and switching",
                            "Network segmentation",
                        ],
                    ),
                    (
                        "Security Services",
                        [
                            "Intrusion Prevention System (IPS)",
                            "Antivirus protection",
                            "Web filtering",
                            "Application control",
                            "Threat intelligence integration",
                        ],
                    ),
                    (
                        "Secure Connectivity",
                        [
                            "SSL VPN configuration",
                            "IPsec VPN deployment",
                            "Remote user access",
                            "Site-to-site connectivity",
                        ],
                    ),
                    (
                        "Advanced Security Features",
                        [
                            "High Availability (HA)",
                            "SD-WAN deployment",
                            "Security Fabric integration",
                            "Traffic analysis and optimization",
                        ],
                    ),
                    (
                        "Monitoring and Troubleshooting",
                        [
                            "Log management",
                            "Event monitoring",
                            "Security auditing",
                            "Performance optimization",
                        ],
                    ),
                ],
                "footer": "These skills align with industry requirements for managing Fortinet-powered security infrastructures.",
            },
            {
                "eyebrow": "Career Opportunities",
                "intro": "After completing the Fortinet Certified Professional Network Security course, learners can pursue roles such as:",
                "bullets": [
                    "Network Security Engineer",
                    "Cybersecurity Analyst",
                    "Firewall Administrator",
                    "Security Consultant",
                    "Security Operations Center (SOC) Analyst",
                    "Infrastructure Security Engineer",
                    "IT Security Specialist",
                    "Network Administrator",
                    "Security Architect",
                    "Security Operations Engineer",
                ],
                "footer": "With organisations increasingly adopting Fortinet technologies, certified professionals remain highly sought after across banking, healthcare, government, telecommunications, cloud services and enterprise IT sectors.",
            },
            {
                "eyebrow": "Why Learn with Nexperts Academy?",
                "intro": "At Nexperts Academy, our training programmes are designed to provide practical, industry-focused cybersecurity education.",
                "subtitle": "Benefits of training with us",
                "bullets": [
                    "Expert-led instructor training",
                    "Real-world lab environments",
                    "Hands-on FortiGate configuration exercises",
                    "Certification-focused curriculum",
                    "Flexible learning options",
                    "Industry-relevant case studies",
                    "Career guidance and support",
                    "Certification exam preparation assistance",
                ],
            },
            {
                "eyebrow": "Online Fortinet Certification Training in Malaysia",
                "eyebrow_class": "m",
                "intro": "Nexperts Academy offers flexible online Fortinet certification training for students and working professionals across Malaysia.",
                "subtitle": "Training options include",
                "bullets": [
                    "Live online classes",
                    "Instructor-led virtual training",
                    "Weekend batches",
                    "Corporate cybersecurity training",
                    "Hybrid classroom learning",
                ],
            },
        ],
        who_for=[
            ("🌐", "Network Engineers", "Building FortiGate and enterprise network security skills."),
            ("🛡️", "Security Engineers", "Owning firewall, VPN and Security Fabric operations."),
            ("🔥", "Firewall Administrators", "Formalising FortiGate administration with certification."),
            ("📡", "SOC Analysts", "Adding network-tier context to alert triage and response."),
            ("👨‍💻", "System Administrators", "Extending admin work with NGFW and SD-WAN depth."),
            ("💼", "IT Infrastructure Engineers", "Securing hybrid and multi-site enterprise networks."),
        ],
        prereqs=[
            "Basic networking knowledge (TCP/IP, routing, VLANs recommended)",
            "Familiarity with firewalls or security appliances helpful",
            "Comfortable with CLI and GUI administration",
            "CompTIA Network+ or CCNA recommended but not mandatory",
        ],
        prereqs_note="New to networking? Ask about our Network+ → Fortinet FCP bundled learning path.",
        curriculum_eyebrow="Course Curriculum",
        curriculum_head=("Ten modules.", "FortiGate to certification."),
        curriculum_intro="The curriculum follows the Fortinet Certified Professional Secure Networking path — from Security Fabric fundamentals through FortiGate administration, threat protection, SD-WAN and exam readiness.",
        modules=[
            (
                "01",
                "Introduction to Cybersecurity & Fortinet Security Fabric",
                [
                    "Cybersecurity fundamentals",
                    "Security challenges in modern networks",
                    "Fortinet ecosystem overview",
                    "Security Fabric architecture",
                ],
            ),
            (
                "02",
                "FortiGate Deployment & Administration",
                [
                    "Initial device configuration",
                    "Interface setup",
                    "Administrative access",
                    "Configuration backup and restore",
                ],
            ),
            (
                "03",
                "Firewall Policies and NAT",
                [
                    "Security policy creation",
                    "Traffic inspection",
                    "Network Address Translation (NAT)",
                    "Policy optimization",
                ],
            ),
            (
                "04",
                "User Authentication & Access Control",
                [
                    "Local users and groups",
                    "LDAP integration",
                    "Multi-factor authentication",
                    "Role-based access control",
                ],
            ),
            (
                "05",
                "VPN Technologies",
                [
                    "SSL VPN deployment",
                    "IPsec VPN configuration",
                    "Remote access solutions",
                    "Site-to-site VPN implementation",
                ],
            ),
            (
                "06",
                "Threat Protection",
                [
                    "IPS configuration",
                    "Antivirus deployment",
                    "Web filtering policies",
                    "Application control management",
                ],
            ),
            (
                "07",
                "Secure SD-WAN",
                [
                    "SD-WAN concepts",
                    "Link performance monitoring",
                    "Traffic steering",
                    "WAN optimization",
                ],
            ),
            (
                "08",
                "Security Fabric Integration",
                [
                    "Fabric connectors",
                    "Centralized visibility",
                    "Threat response automation",
                    "Security orchestration",
                ],
            ),
            (
                "09",
                "Monitoring and Reporting",
                [
                    "Logging and analytics",
                    "Event monitoring",
                    "Compliance reporting",
                    "Troubleshooting techniques",
                ],
            ),
            (
                "10",
                "Certification Exam Preparation",
                [
                    "Exam objectives",
                    "Practice assessments",
                    "Scenario-based exercises",
                    "Certification readiness review",
                ],
            ),
        ],
        labs_eyebrow="Hands-On Lab Stack",
        labs_head=("10 FortiGate labs.", "Real appliances & VMs."),
        labs_intro="Every learner works on FortiGate VMs and physical lab units. Labs mirror production change windows — policy builds, VPN cutovers, SD-WAN steering and incident triage under time pressure.",
        labs=[
            ("01", "FortiGate Baseline", "Initial setup, interfaces, admin hardening and backup discipline.", "lt-defend", "Admin"),
            ("02", "Policy & NAT Build", "Segmented security policies with NAT for a fintech-style topology.", "lt-defend", "Policy"),
            ("03", "LDAP + MFA VPN", "Authenticate remote users with LDAP and multi-factor access.", "lt-recon", "Identity"),
            ("04", "Site-to-Site IPsec", "Branch-to-HQ VPN with routing and failover testing.", "lt-defend", "VPN"),
            ("05", "IPS Tuning Workshop", "Reduce false positives while keeping coverage on critical threats.", "lt-attack", "IPS"),
            ("06", "Web Filter & App Control", "Block risky categories without breaking business apps.", "lt-defend", "Filtering"),
            ("07", "HA Pair Deployment", "Active-passive HA with stateful failover validation.", "lt-defend", "HA"),
            ("08", "SD-WAN Steering", "Multi-link SD-WAN with SLA-based path selection.", "lt-recon", "SD-WAN"),
            ("09", "Fabric Visibility", "Centralised logging, dashboards and alert response.", "lt-forensic", "Fabric"),
            ("10", "Capstone IR Scenario", "Detect, contain and document a simulated breach end-to-end.", "lt-attack", "Capstone"),
        ],
        labs_footer="+ FortiOS CLI quick-reference and post-course lab access for 30 days.",
        exam_eyebrow="Certification Preparation",
        exam_head=("Fortinet FCP", "Secure Networking path."),
        exam_intro="This course is aligned with the Fortinet Certified Professional (FCP) Secure Networking certification path. Training includes exam objective mapping, practice assessments and scenario drills. Exam vouchers can be arranged through Fortinet's official channels — ask our team for current bundle options.",
        exam_main=dict(
            name="Fortinet Certified Professional (FCP)",
            rows=[
                ("Certification path", "FCP — Secure Networking"),
                ("Focus", "FortiGate, VPN, SD-WAN, Security Fabric"),
                ("Validation", "Deploy, manage, monitor Fortinet network security"),
                ("Lab requirement", "Hands-on FortiGate exercises included"),
                ("Exam prep", "Practice assessments + scenario review"),
                ("Delivery", "Fortinet authorised exam channels"),
                ("Nexperts pass rate", '<span class="pass-highlight">92% first attempt (prep cohort)</span>'),
            ],
        ),
        exam_optional=None,
        mock_title="Our 3-Mock Programme",
        mock_programme=[
            ("01", "Diagnostic", "End of day 2. Policy and routing baseline. Average score: 58%."),
            ("02", "Domain Drill", "Mid-course. VPN, IPS and SD-WAN scenarios. Average score: 74%."),
            ("03", "Clearance Mock", "Full timed simulation before exam booking. 80%+ target. Average: 86%."),
        ],
        pass_rate=92,
        pass_head_html="92% of our Fortinet FCP<br>candidates pass <em>on first attempt.</em>",
        pass_intro="Fortinet exams reward hands-on FortiGate experience. We spend 65% of class time in labs, gate exam booking on a clearance mock, and drill the policy-and-VPN scenarios that trip up most first-time candidates.",
        pass_pills=[
            "FortiGate lab stack",
            "Security Fabric depth",
            "92% first attempt",
            "Exam prep included",
            "SD-WAN + VPN labs",
        ],
        pass_compare=[
            (
                "Industry average: ~68%",
                "Many candidates study theory without enough time on live FortiGate policy builds, VPN cutovers and SD-WAN tuning.",
            ),
            (
                "Nexperts: 92%",
                "You configure FortiGate from day one. You earn your exam slot only after clearing our timed scenario mock.",
            ),
        ],
        next_eyebrow="Your Network Security Path",
        next_head=("FCP unlocks", "NSE and advanced roles."),
        next_steps_intro="Fortinet FCP is the professional tier. From here, many learners progress to NSE 7 specialisations, pair with CSA or CND for blue-team depth, or move into security architecture roles.",
        next_steps=[
            ("Before this", "Network+ or CCNA", "Solid networking foundation before FortiGate specialisation.", "View Network+ →"),
            ("You are here", "Fortinet FCP", "Professional FortiGate and Security Fabric operations.", "Currently viewing →"),
            ("Recommended next", "NSE 7 or CSA", "Advanced Fortinet specialisation or SOC operations depth.", "View CSA →"),
        ],
        path_name="Fortinet / network security",
        path_chips=[
            ("Network+", "prev"),
            ("Security+", "prev"),
            ("FCP", "you"),
            ("NSE 7", "next"),
            ("CSA", "next"),
        ],
        salary_html='Expected salary range after FCP + experience: <strong style="color:#86efac">RM 7,000 – RM 13,500/month</strong> for network security and firewall roles in Malaysia.',
        reviews_eyebrow="Student Reviews",
        reviews_head=("What our Fortinet", "graduates say."),
        reviews_summary=(4.8, 96, 11, 2, 118),
        reviews=[
            (
                "★★★★★",
                "Best FortiGate course I've attended in MY. The SD-WAN and VPN labs matched what we run at our MSSP. Cleared FCP on first attempt.",
                "rav-b",
                "AR",
                "Ahmad Rizal",
                "Network Security Engineer · Fave Asia",
                "✓ Passed first attempt",
            ),
            (
                "★★★★★",
                "Came from CCNA. The Security Fabric module finally connected how FortiGate, logging and automation fit together. Highly practical.",
                "rav-m",
                "LS",
                "Lee Suet May",
                "Firewall Admin · Maxis",
                "✓ Passed first attempt",
            ),
            (
                "★★★★",
                "IPS tuning lab alone was worth the fee. I cut false positives at work by half the week after class ended.",
                "rav-g",
                "VK",
                "Vikneswaran Kumar",
                "Security Engineer · TM",
                "✓ Passed first attempt",
            ),
            (
                "★★★★★",
                "Corporate batch for our team — consistent FortiGate baseline across three sites. Trainer knew enterprise change windows, not just slides.",
                "rav-a",
                "NF",
                "Nurul Farah",
                "IT Security Lead · Bank Islam",
                "✓ Team certification",
            ),
        ],
        price="RM 4,200",
        price_orig="RM 4,650",
        price_save="Save 10%",
        price_note="Per person · Includes FortiGate lab access, courseware and exam prep materials",
        sidebar_meta=[
            ("Duration", "5 days / 40 hrs"),
            ("Next intake", "16 Jun 2026"),
            ("Format", "On-site · Hybrid · Virtual"),
            ("Level", "Professional"),
            ("Language", "English"),
            ("Cert body", "Fortinet"),
            ("Exam", '<span class="smeta-badge">Prep included</span>'),
        ],
        whats_included=[
            "Fortinet-aligned courseware and lab guides",
            "FortiGate VM + physical lab access",
            "10 hands-on FortiGate lab scenarios",
            "3 timed mock assessments",
            "Security Fabric integration exercises",
            "SD-WAN and VPN deployment labs",
            "Post-course instructor access (30 days)",
            "Exam objective mapping workbook",
            "Certificate of completion — Nexperts Academy",
        ],
        verify_items=[
            "Fortinet certification via official Fortinet channels",
            "Nexperts course completion certificate",
            "LinkedIn-ready skills badge from Nexperts",
            "Verifiable training transcript on request",
        ],
        guarantee_text="Follow our programme and don't pass your Fortinet exam? We include one structured retake prep cycle. Ask for terms at enrolment.",
        faqs=[
            (
                "What is the Fortinet Certified Professional (FCP) Network Security certification?",
                "The FCP certification validates your ability to deploy, manage, monitor and secure enterprise networks using Fortinet security technologies.",
            ),
            (
                "Who should take this course?",
                "Network engineers, cybersecurity professionals, firewall administrators, SOC analysts and IT professionals looking to specialise in network security.",
            ),
            (
                "Do I need prior experience?",
                "Basic networking knowledge is recommended, but beginners with IT backgrounds can also benefit from the course.",
            ),
            (
                "What technologies are covered?",
                "The course covers FortiGate, FortiOS, VPNs, Security Fabric, IPS, Antivirus, Web Filtering, Application Control, SD-WAN and firewall management.",
            ),
            (
                "Is the training hands-on?",
                "Yes. The program includes practical labs and real-world implementation exercises.",
            ),
            (
                "Will this course help me pass the FCP certification exam?",
                "Yes. The curriculum is designed to align with the Fortinet Certified Professional Secure Networking certification requirements.",
            ),
            (
                "What job roles can I apply for after certification?",
                "You can pursue roles such as Network Security Engineer, Security Analyst, Firewall Administrator, Security Consultant and Cybersecurity Specialist.",
            ),
            (
                "Is the certification recognized globally?",
                "Yes. Fortinet certifications are recognized worldwide by employers and cybersecurity organizations.",
            ),
        ],
        hidden_course_title="Fortinet Certified Professional (FCP) Network Security",
        faq_head=("Fortinet FCP Network Security", "FAQs."),
    ),
]
