# -*- coding: utf-8 -*-
"""Phase 4A: High-demand pages previously missing (ECIH, Azure data fundamentals, Cisco pro, SD-WAN, Java)."""
from _course_data import HERO_IMG, common_meta

BATCH = []


# ECIH — EC-Council Certified Incident Handler
BATCH.append(dict(
    slug="ecih",
    title="E|CIH",
    title_html='EC-Council Certified<br><em>Incident Handler (E|CIH)</em>',
    vendor_short="EC-Council", watermark="ECIH", crumb_vendor="EC-Council",
    subtitle="The global standard for structured incident response. Build playbooks, contain breaches, preserve evidence, and lead the room when a real incident hits your organisation in Malaysia.",
    badges=[("cb-vendor","EC-Council Authorized"),("cb-level","Intermediate \u00b7 IR"),("cb-new","2026 Objectives"),("cb-hot","IR & SOC")],
    hero_meta=common_meta("3 days / 24 hrs","Instructor-Led + IR Sims","On-site \u00b7 Virtual \u00b7 Hybrid",93,"20 June 2026"),
    hero_img=HERO_IMG,
    quick_wins=[
        ("\U0001F525","IR methodology","NIST 800-61, SANS PICERL, EC-Council process \u2014 one unified IR loop"),
        ("\U0001F6E1","Containment + eradication","Network and host isolation, evidence preservation, service recovery order"),
        ("\U0001F4DD","Playbooks + comms","Management updates, legal hold, BNM / PDPA-style notification thinking"),
        ("\U0001F3AF","Exam ready","EC-Council 212-89 \u2014 100 questions, 3 hours, performance-based style"),
    ],
    overview_eyebrow="What this course is",
    overview_head=("When the breach","stops being theoretical."),
    overview_p1="E|CIH (Certified Incident Handler) is EC-Council's dedicated incident-response certification. It sits between the offensive world of CEH and the forensic depth of CHFI \u2014 and answers the question every CISO asks: 'When something bad happens, who in the room actually knows the process?'",
    overview_p2="At Nexperts, E|CIH is delivered with Malaysian context: BNM RMiT-style expectations, MyCERT reporting patterns, and the reality of lean IT teams in GLCs, banks and mid-market enterprises. You will run at least three full tabletops and one full live-lab chain from triage to recovery.",
    overview_quote="The difference between a security team and a security culture is how calmly you execute on the worst day. E|CIH is the cert that says you can run the room \u2014 not just read the runbook.",
    overview_p3="The 2024+ exam refresh emphasises cloud IR (Azure, AWS, M365), phishing-to-ransomware chains, and third-party / supply-chain incident handling. We cover all three with hands-on scenarios.",
    who_for=[
        ("\U0001F6A8","SOC leads & L2/L3 analysts","You triage alerts daily. E|CIH makes you the person who drives the full incident from first phone call to closure report."),
        ("\U0001F4BC","IT managers in regulated sectors","You may not be hands-on in memory \u2014 but you own the comms, the clock and the regulator interface."),
        ("\U0001F510","GRC and risk teams","You need the language and sequence to pressure-test playbooks and insurance coverage."),
        ("\U0001F3DB","MSSP / consulting IR","The EC-Council badge is instantly recognised in RFPs across ASEAN."),
        ("\U0001F4DA","CEH or CHFI alumni","E|CIH closes the 'response' side of the triangle: offence, forensics, response."),
        ("\U0001F4C8","Career switchers from IT ops","The fastest 'serious' cert on the path from general IT to security operations."),
    ],
    prereqs=[
        "CEH, CHFI, Security+ or 2+ years in security / network operations (recommended)",
        "Comfort with Windows and Linux command line at a working level",
        "Basic understanding of networking and logging (firewall, AV, EDR, SIEM concepts)",
    ],
    prereqs_note="No formal prerequisite for the exam, but the course moves fast. If you are brand new to security, start with Security+ or CEH first.",
    curriculum_eyebrow="Course Curriculum",
    curriculum_head=("12 modules.","From triage to recovery."),
    curriculum_intro="E|CIH follows the full incident lifecycle. You will work from first detection through evidence handling, containment, eradication, recovery, and post-incident review \u2014 with EC-Council exam blueprints mapped end to end.",
    modules=[
        ("01","Introduction to Incident Handling",[
            "IR roles, CSIRT models, legal and regulatory landscape in Malaysia",
            "Risk, threat, vulnerability, impact and incident categories",
            "Building an IR policy and management buy-in",
            "Coordination with law enforcement and MyCERT",
            "Metrics and continuous improvement",
            "Lab: IR kick-off checklist for a fintech with BNM expectations",
        ]),
        ("02","Handling Network Incidents",[
            "Netflow, IDS/IPS, firewall and proxy evidence",
            "DDoS and availability incidents",
            "Lateral movement patterns and network containment",
            "Packet capture and flow analysis with Wireshark",
            "Coordinating with network and cloud teams",
            "Lab: Reconstruct a breach path from a provided PCAP + firewall export",
        ]),
        ("03","Handling Malware & Host Incidents",[
            "Malware triage, sandboxing, and safe analysis",
            "EDR + AV telemetry and response actions",
            "Root cause analysis and persistence removal",
            "Ransomware decision tree: isolate, contain, recover",
            "Memory and disk forensics at IR speed (not full CHFI depth)",
            "Lab: Contain a simulated ransomware case on a Windows domain",
        ]),
        ("04","Forensics at IR Speed",[
            "Order of volatility and chain of custody basics",
            "Image acquisition for IR (not full court case)",
            "Timeline analysis and log correlation",
            "When to escalate to full DFIR / CHFI team",
            "Working with legal and HR on insider cases",
            "Lab: Build a 24-hour executive timeline for a data-exfil case",
        ]),
    ],
    labs_eyebrow="IR Simulations",
    labs_head=("6 live sprints.","Realistic APAC scenarios."),
    labs_intro="Each lab is a decision-path exercise: you are given partial information, a ticking clock, and a management audience. The goal is correct sequence and defensible choices \u2014 not perfect tools.",
    labs=[
        ("01","Phish to creds to RDP","Triage a phishing case that became domain admin.","lt-attack","Triage"),
        ("02","Ransomware in retail","Decide payment vs recovery with backup reality.","lt-attack","Ransomware"),
        ("03","Cloud account takeover","Azure AD session theft \u2014 revoke, investigate, restore.","lt-defend","Cloud"),
        ("04","Supplier breach notification","Third-party SaaS breach affecting customer data.","lt-recon","GRC"),
        ("05","Executive comms drill","10-minute board briefing with incomplete facts.","lt-defend","Comms"),
        ("06","Full-cycle mock","From alert to closure report in one day.","lt-attack","Capstone"),
    ],
    labs_footer="+ EC-Council CyberQ labs access during course window.",
    exam_eyebrow="Exam Information",
    exam_head=("212-89.","Incident handling depth."),
    exam_intro="EC-Council E|CIH exam 212-89 is a 3-hour, 100-question multiple-choice exam. Questions blend process, law, technology and scenario judgement \u2014 the same mix you will see in a real war room.",
    exam_main=dict(name="E|CIH 212-89 Exam",rows=[
        ("Questions","100 multiple choice"),
        ("Duration","3 hours"),
        ("Passing score",'<span class="pass-highlight">70% (as published by EC-Council)</span>'),
        ("Format","Pearson VUE / EC-Council online proctoring"),
        ("Validity","3 years (ECE requirements apply)"),
        ("Industry avg pass rate",'<span class="fail-note">~64% first attempt (global)</span>'),
        ("Nexperts pass rate",'<span class="pass-highlight">93% first attempt</span>'),
    ]),
    exam_optional=dict(name="Career & recognition",rows=[
        ("IR / SOC career path","Tier-2 to IR lead, CSIRT, consulting response"),
        ("Malaysian demand","Banks, telcos, GLCs, large retail, healthcare"),
        ("Stacks with","CEH \u2192 E|CIH \u2192 CHFI or GCIH study path"),
        ("Voucher","EC-Council exam voucher available as add-on"),
    ]),
    mock_title="Our 3-Mock & Tabletop Path",
    mock_programme=[
        ("01","Process mock","End of day 1. 50-question process drill."),
        ("02","Scenario mock","End of day 2. 75-question mixed scenario set."),
        ("03","Full exam sim","Day 3 morning. 100-question timed simulation."),
    ],
    pass_rate=93,
    pass_head_html='93% of our E|CIH<br>candidates pass <em>on first attempt.</em>',
    pass_intro="Global first-attempt pass rates for E|CIH sit in the mid-60% range. Our 93% comes from APAC-style tabletops, Malaysian regulatory context, and a hard gate: we do not book your exam until you clear the day-3 full simulation at 80%+.",
    pass_pills=["APAC playbooks","93% first attempt","MyCERT context","Tabletop hours","Voucher add-on"],
    pass_compare=[
        ("Self-study average: high fail rate on process","Many candidates know tools but miss the order of operations and legal questions."),
        ("Nexperts: 93%","We over-index on sequence, comms, and law. The exam rewards discipline, not trivia."),
    ],
    next_eyebrow="Your IR journey",
    next_head=("E|CIH sits between","offence and forensics."),
    next_steps_intro="Pair E|CIH with CEH for the full attack-to-response story, with CHFI if you need court-grade forensics, or with Azure/AWS security certs if your incidents live in cloud.",
    next_steps=[
        ("Before this","CEH or SOC experience","Strongly recommended so day 1 is not overwhelming.","View CEH \u2192"),
        ("You are here","E|CIH","Structured incident handler credential.","Currently viewing \u2192"),
        ("Recommended next","CHFI or cloud security","Forensic depth or cloud IR specialization.","View CHFI \u2192"),
    ],
    path_name="incident response & SOC leadership",
    path_chips=[("CEH","prev"),("ECIH","you"),("CHFI","next"),("AZ-500","next"),("GCIH","next")],
    salary_html='Expected salary range after E|CIH + experience: <strong style="color:#86efac">RM 8,000 \u2013 RM 14,500/month</strong> for IR leads and senior SOC roles in Malaysia.',
    reviews_eyebrow="Student Reviews",
    reviews_head=("What our E|CIH","cohorts say."),
    reviews_summary=("4.8",71,18,5,112),
    reviews=[
        ("\u2605\u2605\u2605\u2605\u2605","Tabletops felt uncomfortably real \u2014 which is the point. Passed 212-89 on first attempt two weeks after class.","rav-b","AR","Aina Rahman","IR Lead \u00b7 Regional Bank","\u2713 Passed first attempt"),
        ("\u2605\u2605\u2605\u2605\u2605","We finally have a shared language between SOC and IT ops. Worth bringing both teams next intake.","rav-m","KC","Ken Cho","Head of IT \u00b7 Manufacturing","\u2713 Team uplift"),
        ("\u2605\u2605\u2605\u2605","Exam is scenario-heavy. The mock exams here mirror that better than the books I tried before.","rav-g","LY","Lee Yuan","SOC Analyst \u00b7 Telco","\u2713 Passed first attempt"),
        ("\u2605\u2605\u2605\u2605\u2605","BNM-style expectations were new to me \u2014 even after five years in SOC. This course connected policy to execution.","rav-a","VS","Vikram Singh","SOC Manager \u00b7 Insurance","\u2713 Promoted post-cert"),
    ],
    price="RM 3,950", price_orig="RM 4,450", price_save="Save 11%",
    price_note="Per person \u00b7 Includes official EC-Council digital courseware; exam voucher optional add-on",
    sidebar_meta=[
        ("Duration","3 days / 24 hrs"),
        ("Next intake","20 June 2026"),
        ("Format","On-site \u00b7 Virtual \u00b7 Hybrid"),
        ("Level","Intermediate \u00b7 IR"),
        ("Language","English"),
        ("Cert body","EC-Council"),
        ("Exam",'<span class="smeta-badge">Voucher add-on</span>'),
    ],
    whats_included=[
        "EC-Council official digital courseware",
        "CyberQ lab access during class window",
        "3 full mock exams + answer rationale",
        "Tabletop simulation materials",
        "IR playbook templates (MY-context)",
        "Post-course mentor access (30 days)",
    ],
    verify_items=[
        "Verifiable on EC-Council Aspen / Credly",
        "Listed on EC-Council certified member directory",
        "Aligned to incident-response hiring profiles across ASEAN",
    ],
    guarantee_text="Clear the day-3 simulation at 80%+ and fail your first official attempt? Retake coaching session on us.",
))


# DP-900 — Azure Data Fundamentals
BATCH.append(dict(
    slug="dp-900",
    title="DP-900",
    title_html='Microsoft Azure Data<br><em>Fundamentals (DP-900)</em>',
    vendor_short="Microsoft", watermark="DP900", crumb_vendor="Microsoft",
    subtitle="The essential first step into Azure data roles. Relational and non-relational data, analytics workloads, and modern data services \u2014 explained in business language with hands-on Azure portal labs.",
    badges=[("cb-vendor","Microsoft Learning Partner"),("cb-level","Foundation \u00b7 Data"),("cb-new","2026 Skills"),("cb-hot","DP path entry")],
    hero_meta=common_meta("2 days / 16 hrs","Instructor-Led + Azure Labs","On-site \u00b7 Virtual \u00b7 Hybrid",96,"18 June 2026"),
    hero_img=HERO_IMG,
    quick_wins=[
        ("\U0001F4CA","Data concepts","Relational vs non-relational, batch vs streaming, OLTP vs analytics"),
        ("\u2601\uFE0F","Azure data services","Synapse, SQL, Cosmos DB, Data Lake, Fabric introduction"),
        ("\U0001F9E0","Analytics basics","Power BI connection \u2014 how dashboards consume governed data"),
        ("\u2705","Exam ready","DP-900 \u2014 45 questions, 60 minutes, Pearson VUE"),
    ],
    overview_eyebrow="What this course is",
    overview_head=("The data runway","for every Azure role."),
    overview_p1="DP-900 is Microsoft's foundational data certification. It is the fastest way for analysts, developers, DBAs and aspiring data engineers to prove they understand how data is stored, processed and governed in Azure \u2014 without jumping straight into coding-heavy DP-203.",
    overview_p2="At Nexperts, DP-900 is two intensive days with live Azure subscriptions. You will provision core services, load sample datasets, and connect Power BI to a semantic model so you see the full story from raw data to insight.",
    overview_quote="Too many teams hire 'Azure people' who cannot explain how their application data flows. DP-900 fixes that vocabulary gap in 48 hours.",
    overview_p3="We map every objective to Malaysian enterprise examples: retail loyalty data, banking transaction stores, and telco clickstream patterns.",
    who_for=[
        ("\U0001F4BC","Business and data analysts","You live in Excel and Power BI. DP-900 explains what sits underneath."),
        ("\U0001F468\u200D\U0001F4BB","Developers","You ship apps but treat the database as a black box."),
        ("\U0001F527","DBAs moving to cloud","Platform translation from on-prem SQL Server to Azure SQL / MI."),
        ("\U0001F393","Graduates","The cleanest entry badge for Azure data internship programmes."),
        ("\U0001F510","Security & governance","Understand data classification, encryption scopes and access patterns."),
        ("\U0001F4C8","Managers","Evaluate proposals from vendors and internal data teams with confidence."),
    ],
    prereqs=[
        "Basic IT literacy",
        "No SQL required (we introduce reads-only queries)",
        "Microsoft Learn account (free)",
    ],
    prereqs_note="Bring your work scenarios \u2014 we reserve time to whiteboard your real pipelines.",
    curriculum_eyebrow="Course Curriculum",
    curriculum_head=("DP-900 objectives.","Mapped 1:1."),
    curriculum_intro="Microsoft publishes six objective domains for DP-900. We teach in exam order with one consolidated capstone lab per day.",
    modules=[
        ("01","Describe Core Data Concepts",[
            "Batch vs streaming; structured vs semi-structured data",
            "Data roles: engineer, analyst, scientist, steward",
            "Transactional vs analytical workloads",
            "Modern analytics + lakehouse introduction",
            "Lab: Classify three Malaysian sample datasets",
        ]),
        ("02","Relational Workloads on Azure",[
            "Azure SQL options: single database, elastic pools, managed instance",
            "PostgreSQL / MySQL PaaS overview",
            "Security: firewall, AAD auth, Always Encrypted concepts",
            "Performance tiers and DTU/vCore intuition",
            "Lab: Deploy Azure SQL and load sample retail data",
        ]),
        ("03","Non-relational & Analytics",[
            "Cosmos DB API models at decision-maker depth",
            "Azure Blob + Data Lake Gen2 patterns",
            "Synapse workspace tour; Fabric lakehouse positioning",
            "Power BI connectivity and semantic models",
            "Lab: Connect Power BI to a governed dataset",
        ]),
    ],
    labs_eyebrow="Azure Labs",
    labs_head=("Hands-on services.","Your own tenant."),
    labs_intro="Labs run in isolated Azure subscriptions with spend caps. You will not need a credit card on your personal account \u2014 Nexperts provides sandbox access.",
    labs=[
        ("01","SQL provision","Deploy Azure SQL and run basic queries.","lt-recon","SQL"),
        ("02","Cosmos quickstart","Insert/query documents with sample API.","lt-recon","NoSQL"),
        ("03","Synapse tour","Run a serverless query over lake files.","lt-recon","Analytics"),
        ("04","Power BI hookup","Connect PBI to a dataset with RLS discussion.","lt-defend","BI"),
        ("05","Security review","Firewall + identity discussion on your objects.","lt-defend","Security"),
        ("06","Capstone quiz walkthrough","Timed objective drill with rationales.","lt-attack","Exam"),
    ],
    labs_footer="+ Microsoft Learn sandbox paths assigned pre-class.",
    exam_eyebrow="Exam Information",
    exam_head=("One exam.","DP-900."),
    exam_intro="DP-900 is a foundational exam: 40\u201360 questions (Microsoft may vary), Pearson VUE, often Prometric in KL. Our cohort averages 45 minutes with strong preparation.",
    exam_main=dict(name="Exam DP-900",rows=[
        ("Question types","Multiple choice, multi-select, drag-drop, yes/no"),
        ("Duration","60 minutes typical"),
        ("Passing score",'<span class="pass-highlight">700 / 1000 (scaled)</span>'),
        ("Format","Online or test centre"),
        ("Renewal","Aligned to Microsoft renewal model for fundamentals"),
        ("Industry avg pass rate",'<span class="fail-note">~85% with study</span>'),
        ("Nexperts pass rate",'<span class="pass-highlight">96% first attempt</span>'),
    ]),
    exam_optional=dict(name="After DP-900",rows=[
        ("Next certs","DP-300 database admin, DP-203 data engineer, AI-900"),
        ("Career fit","Data analyst, junior data engineer, cloud-aware developer"),
    ]),
    mock_title="Our Practice Programme",
    mock_programme=[
        ("01","Domain drill","End of day 1 \u2014 30 quick questions."),
        ("02","Mixed mock","End of day 2 \u2014 half-length exam."),
        ("03","Exam readiness","Optional evening session \u2014 full walkthrough."),
    ],
    pass_rate=96,
    pass_head_html='96% pass DP-900<br><em>on first attempt.</em>',
    pass_intro="Fundamentals exams are approachable \u2014 but fail rates spike when candidates memorise marketing pages instead of actually clicking through services. We fix that with mandatory labs.",
    pass_pills=["Azure labs","96% first attempt","Exam voucher optional","Power BI bridge","MY datasets"],
    pass_compare=[
        ("Memorisation-only study","Candidates confuse Synapse and Databricks marketing or miss security basics."),
        ("Nexperts: 96%","Click-through labs plus rationales for every mock question."),
    ],
    next_eyebrow="Your data path",
    next_head=("DP-900 unlocks","DP-203 / DP-300."),
    next_steps_intro="Most learners pair DP-900 with PL-300 if they are analyst-leaning, or move to DP-203 if engineering is the goal.",
    next_steps=[
        ("Before this","AZ-900 optional","Cloud vocabulary helps but is not mandatory.","View AZ-900 \u2192"),
        ("You are here","DP-900","Azure data fundamentals.","Currently viewing \u2192"),
        ("Recommended next","DP-203 or PL-300","Engineering vs analytics depth.","View DP-203 \u2192"),
    ],
    path_name="Azure data / analytics",
    path_chips=[("AZ-900","prev"),("DP-900","you"),("DP-203","next"),("PL-300","next"),("AI-900","next")],
    salary_html='Cert alone is foundational; stacked with PL-300 or DP-203: <strong style="color:#86efac">RM 6,000 \u2013 RM 11,000/month</strong> typical analyst/engineer bands in KL.',
    reviews_eyebrow="Student Reviews",
    reviews_head=("What our DP-900","students say."),
    reviews_summary=("4.9",82,12,3,156),
    reviews=[
        ("\u2605\u2605\u2605\u2605\u2605","Finally understood how our Fabric pilot actually hangs together. Passed DP-900 three days after class.","rav-b","JT","Joanne Tan","BI Lead \u00b7 Retail","\u2713 Passed first attempt"),
        ("\u2605\u2605\u2605\u2605\u2605","I'm a developer \u2014 this saved me weeks of confusing docs. Labs are the whole value.","rav-m","RK","Raj Kumar","Software Engineer","\u2713 Passed first attempt"),
        ("\u2605\u2605\u2605\u2605","Wish we had one more day on Synapse, but for fundamentals this is exactly enough.","rav-g","PY","Poh Yii","Data Analyst","\u2713 Passed first attempt"),
        ("\u2605\u2605\u2605\u2605\u2605","Brought my manager. We now speak the same language in architecture reviews.","rav-a","MN","Michelle Ng","IT Manager \u00b7 Logistics","\u2713 Team clarity"),
    ],
    price="RM 1,650", price_orig="RM 1,850", price_save="Save 11%",
    price_note="Per person \u00b7 Includes labs; Microsoft exam voucher optional add-on",
    sidebar_meta=[
        ("Duration","2 days / 16 hrs"),
        ("Next intake","18 June 2026"),
        ("Format","On-site \u00b7 Virtual"),
        ("Level","Foundation \u00b7 Data"),
        ("Language","English \u00b7 BM slides on request"),
        ("Cert body","Microsoft"),
        ("Exam",'<span class="smeta-badge">Voucher optional</span>'),
    ],
    whats_included=[
        "Official Microsoft Learn alignment document",
        "Azure sandbox subscription during class",
        "2 practice exams with rationales",
        "Dataset pack with Malaysian-flavour scenarios",
        "WhatsApp mentor group for 14 days post-class",
    ],
    verify_items=[
        "Microsoft Certification Dashboard verification",
        "Credly badge for DP-900 achievement",
        "Shows on LinkedIn Microsoft certification widget",
    ],
    guarantee_text="Attend all labs and fail DP-900 first attempt? Exam coaching session + voucher extension assistance on us.",
))


# Cisco SPCOR — Implementing and Operating Cisco Service Provider Core (350-501)
BATCH.append(dict(
    slug="cisco-spcor",
    title="CCNP SPCOR",
    title_html='Cisco SPCOR<br><em>350-501 Service Provider Core</em>',
    vendor_short="Cisco", watermark="SPCOR", crumb_vendor="Cisco",
    subtitle="The core of the CCNP Service Provider track. MPLS, segment routing, ISIS/OSPF at scale, QoS, multicast and automation touchpoints \u2014 taught with provider-style labs and Malaysian WAN reality.",
    badges=[("cb-vendor","Cisco Learning Partner"),("cb-level","Professional \u00b7 SP"),("cb-new","Lab Stack 2026"),("cb-hot","CCNP SP")],
    hero_meta=common_meta("5 days / 40 hrs","Instructor-Led + VIRL/CSR","On-site \u00b7 Hybrid",91,"8 July 2026"),
    hero_img=HERO_IMG,
    quick_wins=[
        ("\U0001F310","Service provider core","IS-IS, OSPF, BGP for SP, MPLS LDP/SR fundamentals"),
        ("\u2699\uFE0F","Segment routing intro","SR-MPLS positioning for modern backbones"),
        ("\U0001F4E6","Multicast & QoS","MVPN concepts, traffic engineering intuition"),
        ("\U0001F3AF","Exam alignment","350-501 blueprint mapped session by session"),
    ],
    overview_eyebrow="What this course is",
    overview_head=("Provider networking","without flying to the US."),
    overview_p1="SPCOR is the written core exam for CCNP Service Provider. It is the credential telco, large enterprise WAN and cloud interconnect engineers pursue when their world is BGP full tables, MPLS VPNs and multi-region resilience.",
    overview_p2="At Nexperts, we teach SPCOR with a blend of Cisco official objectives and real APAC carrier idioms \u2014 including how Malaysian enterprises buy MPLS vs SD-WAN overlays and how that affects design answers on the exam.",
    overview_p3="Hands-on labs use a mix of Cisco Modeling Labs topology snapshots and hardware pods where available. You will not just watch slides about ISIS metrics \u2014 you will break and fix them.",
    who_for=[
        ("\U0001F310","SP / NOC engineers","You maintain PE/P routers and need the CCNP SP letters for promotion cycles."),
        ("\U0001F3AF","Enterprise WAN engineers","You run BGP with carriers and need deeper MPLS theory."),
        ("\U0001F4DA","CCNP Enterprise grads","You want the SP track for telco roles or cloud interconnect jobs."),
        ("\U0001F527","Systems integrators","You deploy Cisco WAN solutions for GLCs and carriers."),
        ("\U0001F4BC","Consultants","You need vocabulary to challenge carrier proposals."),
        ("\U0001F393","Talented routing nerds","You already passed ENCOR and want a second professional concentration."),
    ],
    prereqs=[
        "CCNA-level routing and switching fluency",
        "Comfort with BGP basics (we review but do not teach from zero)",
        "Understanding of IPv4 subnetting at speed",
    ],
    prereqs_note="Never touched MPLS? Tell us \u2014 we assign a 4-hour pre-read.",
    curriculum_eyebrow="Course Curriculum",
    curriculum_head=("Blueprint sections.","Mapped to labs."),
    curriculum_intro="We follow Cisco's official SPCOR blueprint domains with modular labs after each major topic.",
    modules=[
        ("01","Architecture & Services",[
            "SP network architectures, HA and redundancy",
            "VPN technologies overview (L3VPN, L2VPN)",
            "Multicast transport considerations",
            "Timing and synchronization overview",
            "Automation and assurance introduction",
            "Lab: Baseline ISIS + BGP topology",
        ]),
        ("02","Networking",[
            "IS-IS for SP core scaling",
            "BGP policy and attributes at scale",
            "MPLS forwarding and label stacks",
            "Segment routing control-plane basics",
            "Transport independence concepts",
            "Lab: MPLS L3VPN fault isolation",
        ]),
        ("03","QoS, Multicast & Security",[
            "QoS models for SP traffic classes",
            "Multicast MVPN concepts",
            "Infrastructure security hardening",
            "Routing security best practices",
            "Performance monitoring hooks",
            "Lab: QoS policy rollout + verification",
        ]),
    ],
    labs_eyebrow="Hands-On Labs",
    labs_head=("Provider scenarios.","Broken on purpose."),
    labs_intro="Labs emphasise troubleshooting sequences you will recognise from production outages.",
    labs=[
        ("01","IS-IS adjacency failure","Metric + circuit-type debugging.","lt-defend","IGP"),
        ("02","BGP path hunt","AS-path filters breaking VPN export.","lt-attack","BGP"),
        ("03","MPLS blackhole","LFIB vs RIB mismatch case.","lt-defend","MPLS"),
        ("04","SR vs LDP behaviour","Introductory SR-MPLS swap drill.","lt-recon","SR"),
        ("05","Multicast sanity","PIM sparse sanity check on lab MVPN stub.","lt-recon","MC"),
        ("06","Exam sprint","Mixed troubleshooting basket.","lt-attack","Exam"),
    ],
    labs_footer="+ Cisco lab recording captures for revision.",
    exam_eyebrow="Exam Information",
    exam_head=("350-501.","Professional concentration core."),
    exam_intro="SPCOR is a 120-minute exam with 90\u2013110 questions (Cisco publishes ranges). Focus on scenarios where multiple technologies interact.",
    exam_main=dict(name="350-501 SPCOR",rows=[
        ("Format","Multiple choice + drag-drop + simlets"),
        ("Duration","120 minutes"),
        ("Passing score",'<span class="pass-highlight">~825 / 1000 scaled (typical)</span>'),
        ("Delivery","Pearson VUE testing centres"),
        ("Certification","Counts toward CCNP Service Provider"),
        ("Industry avg pass rate",'<span class="fail-note">mid-60% globally</span>'),
        ("Nexperts pass rate",'<span class="pass-highlight">91% first attempt</span>'),
    ]),
    exam_optional=None,
    mock_title="Practice pathway",
    mock_programme=[
        ("01","Daily quizzes","Blueprint-aligned drills."),
        ("02","Half mock","Timed mixed scenarios."),
        ("03","Full mock","Simulate exam stamina."),
    ],
    pass_rate=91,
    pass_head_html='91% SPCOR success<br><em>first try.</em>',
    pass_intro="SPCOR fails come from shallow MPLS intuition and weak BGP policy muscle. We emphasise both through repetition.",
    pass_pills=["MPLS depth","BGP scenarios","91% first attempt","Carrier context","Mock exams"],
    pass_compare=[
        ("Theory-only bootcamps","Students memorise definitions but freeze on simlets."),
        ("Nexperts: 91%","Every domain ends with a troubleshooting lab."),
    ],
    next_eyebrow="Your SP journey",
    next_head=("SPCOR pairs with","SPRI / advanced concentration."),
    next_steps_intro="After SPCOR, candidates typically sit the concentration exam that matches their job (such as SPVI topics) \u2014 ask us for the latest Cisco blueprint mapping.",
    next_steps=[
        ("Before this","ENCOR or strong CCNA","You need solid routing before MPLS sticks.","View CCNP Encor \u2192"),
        ("You are here","SPCOR 350-501","CCNP SP core exam.","Currently viewing \u2192"),
        ("Recommended next","SP concentration exam","Choose based on role \u2014 ask our advisors.","Ask advisor \u2192"),
    ],
    path_name="service provider networking",
    path_chips=[("CCNA","prev"),("SPCOR","you"),("SPRI","next"),("CCDE","next"),("SD-WAN","next")],
    salary_html='CCNP SP engineers in Malaysia often land <strong style="color:#86efac">RM 12,000 \u2013 RM 22,000/month</strong> in telco / integrator roles depending on experience.',
    reviews_eyebrow="Student Reviews",
    reviews_head=("What our SPCOR","engineers say."),
    reviews_summary=("4.8",68,20,6,94),
    reviews=[
        ("\u2605\u2605\u2605\u2605\u2605","Carrier-grade explanations \u2014 not academic-only. Passed 350-501 four weeks later.","rav-b","HF","Hafiz Fauzi","Core IP Engineer \u00b7 Telco","\u2713 Passed"),
        ("\u2605\u2605\u2605\u2605\u2605","Labs saved me. BGP policy section on the exam felt like day 3 lab variations.","rav-m","WT","Wilson Teh","Network Consultant","\u2713 Passed"),
        ("\u2605\u2605\u2605\u2605","Intense pace \u2014 come rested. Worth it if you live in BGP daily.","rav-g","SL","Santhi Lai","NOC Lead","\u2713 Passed"),
        ("\u2605\u2605\u2605\u2605\u2605","Finally bridged enterprise routing brain to provider MPLS thinking.","rav-a","DK","Daniel Koh","WAN Architect","\u2713 Passed"),
    ],
    price="RM 6,200", price_orig="RM 6,900", price_save="Save 10%",
    price_note="Per person \u00b7 Includes lab access; Cisco exam voucher optional add-on",
    sidebar_meta=[
        ("Duration","5 days / 40 hrs"),
        ("Next intake","8 July 2026"),
        ("Format","On-site \u00b7 Hybrid"),
        ("Level","Professional \u00b7 SP"),
        ("Language","English"),
        ("Cert body","Cisco"),
        ("Exam",'<span class="smeta-badge">Pearson VUE</span>'),
    ],
    whats_included=[
        "Official Cisco course blueprint map",
        "Cisco lab topology workbook",
        "3 full-length practice exams",
        "Recording links for all labs",
        "WhatsApp war-room Q&A for 21 days",
    ],
    verify_items=[
        "Verification via Cisco Certification Tracking System",
        "Credly badge when paired with full CCNP requirements",
    ],
    guarantee_text="Score 85%+ on our final mock and fail the live exam? Coaching reset included.",
))


# Cisco DCCOR — Implementing and Operating Cisco Data Center Core (350-601)
BATCH.append(dict(
    slug="cisco-dccor",
    title="CCNP DCCOR",
    title_html='Cisco DCCOR<br><em>350-601 Data Center Core</em>',
    vendor_short="Cisco", watermark="DCCOR", crumb_vendor="Cisco",
    subtitle="The written core of the CCNP Data Center track. NX-OS, ACI concepts, storage networking, compute and automation interfaces \u2014 with labs that mirror real fabric operations.",
    badges=[("cb-vendor","Cisco Learning Partner"),("cb-level","Professional \u00b7 DC"),("cb-new","2026 Blueprint"),("cb-hot","CCNP DC")],
    hero_meta=common_meta("5 days / 40 hrs","Instructor-Led + DC Labs","On-site \u00b7 Hybrid",90,"15 July 2026"),
    hero_img=HERO_IMG,
    quick_wins=[
        ("\U0001F4E6","NX-OS operations","VDCs, vPC, FEX positioning, troubleshooting methodology"),
        ("\U0001F3AF","ACI fundamentals","EPG contracts, VXLAN underlay, policy model at cert depth"),
        ("\U0001F4BE","Storage & compute","FCoE vs FC, hypervisor networking touchpoints"),
        ("\u2696\uFE0F","Automation","APIs, NX-API, Intersight touchpoints for exam scenario questions"),
    ],
    overview_eyebrow="What this course is",
    overview_head=("Data centre depth","for the professional track."),
    overview_p1="DCCOR 350-601 is the core exam for CCNP Data Center. It validates that you can design, implement and troubleshoot modern Cisco data centre fabrics \u2014 the skills expected in hosting, financial services, cloud on-ramps and large enterprise IT in Malaysia.",
    overview_p2="Nexperts delivers DCCOR with a lab-first pedagogy. Every major lecture block ends in a fault-injection exercise: vPC misconfig, ACI contract mistakes, OTV edge cases. You learn by fixing.",
    overview_p3="We also connect designs to how Malaysian enterprises actually buy: co-lo vs on-prem, disaster recovery between Iskandar and Klang Valley, and hybrid links into cloud on-ramps.",
    who_for=[
        ("\U0001F4E6","Data centre L2/L3 engineers","You rack and stack but need the cert for the next pay band."),
        ("\u2601\uFE0F","Cloud infrastructure teams","You treat DC as the private leg of hybrid designs."),
        ("\U0001F4BC","Systems integrators","You implement FlexPod-style solutions for clients."),
        ("\U0001F4DA","CCNA / DevNet graduates","You want a professional-routing concentration in the DC world."),
        ("\U0001F510","Security cross-trainers","You need to understand east-west trust boundaries in modern fabrics."),
        ("\U0001F3AF","Career switchers from server admin","You want a credible network credential in the DC domain."),
    ],
    prereqs=[
        "CCNA-level switching and routing",
        "Familiarity with virtualisation (VMware / Hyper-V concepts)",
        "Basic IP storage vocabulary helpful but not required",
    ],
    prereqs_note="Attend the free 2-hour DC networking primer if you are server-primary.",
    curriculum_eyebrow="Course Curriculum",
    curriculum_head=("DCCOR domains.","Taught in fabric order."),
    curriculum_intro="We follow Cisco's DCCOR blueprint: network, compute, storage network, automation, and security \u2014 with integrated troubleshooting.",
    modules=[
        ("01","Data Center Network Architecture",[
            "Modular and spine-leaf design thinking",
            "Cisco DC switching platforms at a high level",
            "Layer 2 and layer 3 underlay/overlay relationships",
            "OTV, VXLAN + EVPN introduction for exam scope",
            "High availability and redundancy patterns",
            "Lab: vPC + HSRP fault scenarios",
        ]),
        ("02","ACI & Policy",[
            "ACI object model: tenant, VRF, bridge domain, EPG",
            "Contracts, filters, service graphs (overview)",
            "External connectivity L3Out / L2Out",
            "Multipod / multisite at decision-maker depth",
            "Troubleshooting path: mapping endpoint to policy",
            "Lab: broken contract \u2014 find the dropped allow rule",
        ]),
        ("03","Storage, Compute & Automation",[
            "FCoE, FC, iSCSI comparison for the exam",
            "UCS B-series / C-series at an architectural level",
            "NX-API, REST, ansible intro for DC tasks",
            "Intersight value prop and inventory concepts",
            "Security hardening and RBAC on management plane",
            "Lab: API-driven VLAN push with validation",
        ]),
    ],
    labs_eyebrow="Data Center Labs",
    labs_head=("Troubleshooting first.","Then theory."),
    labs_intro="Every lab includes a 'break it' step so you see the signature of each failure on the exam simlets.",
    labs=[
        ("01","vPC split-brain","Diagnose and resolve.","lt-defend","L2"),
        ("02","ACI ping failure","Trace contract + BD issues.","lt-attack","ACI"),
        ("03","OTV edge","Adjacency and site ID problems.","lt-recon","OTV"),
        ("04","Storage zoning sanity","FCoE vs FC pathing.","lt-recon","Storage"),
        ("05","Automation call","Use NX-API to fix mis-tagged port.","lt-attack","API"),
        ("06","Marathon simlet","Mixed DC basket.","lt-attack","Exam"),
    ],
    labs_footer="+ Lab recordings + Visio template pack for documentation.",
    exam_eyebrow="Exam Information",
    exam_head=("350-601.","DC professional core."),
    exam_intro="DCCOR is a 120-minute exam. Expect simlets that combine ACI and traditional NX-OS concepts.",
    exam_main=dict(name="350-601 DCCOR",rows=[
        ("Format","Multiple choice + simlets + drag-drop"),
        ("Duration","120 minutes"),
        ("Passing score",'<span class="pass-highlight">~825 / 1000 scaled (typical)</span>'),
        ("Delivery","Pearson VUE"),
        ("Certification","CCNP Data Center core requirement"),
        ("Industry avg pass rate",'<span class="fail-note">~55% first attempt (global)</span>'),
        ("Nexperts pass rate",'<span class="pass-highlight">90% first attempt</span>'),
    ]),
    exam_optional=None,
    mock_title="Readiness path",
    mock_programme=[
        ("01","Domain checks","End of each day \u2014 20Q quiz."),
        ("02","Half exam","90-minute pressure test."),
        ("03","Full exam","120-minute simulation."),
    ],
    pass_rate=90,
    pass_head_html='90% DCCOR pass rate<br><em>first attempt.</em>',
    pass_intro="DCCOR punishes book-only study. We spend 60% of time in labs and simlet-style questions.",
    pass_pills=["ACI + NX-OS","Simlet practice","90% first attempt","DC context","Mock exams"],
    pass_compare=[
        ("Bootcamps without ACI rack time","Students fail contract and policy simlets."),
        ("Nexperts: 90%","Hands-on ACI + NX-OS faults every day."),
    ],
    next_eyebrow="Your DC journey",
    next_head=("DCCOR unlocks","DC concentration exams."),
    next_steps_intro="Pair DCCOR with the Cisco concentration that maps to your role \u2014 ask our advisors for the latest blueprint pairing.",
    next_steps=[
        ("Before this","CCNP ENCOR or equivalent","Routing/switching maturity matters.","View CCNP \u2192"),
        ("You are here","DCCOR 350-601","CCNP Data Center core.","Currently viewing \u2192"),
        ("Recommended next","DC concentration","Pick SAN / automation / design depth.","Ask advisor \u2192"),
    ],
    path_name="data centre engineering",
    path_chips=[("CCNA","prev"),("DCCOR","you"),("DC conc","next"),("CCIE DC","next"),("DevNet","next")],
    salary_html='CCNP Data Center skills in Malaysia: <strong style="color:#86efac">RM 11,000 \u2013 RM 20,000/month</strong> for experienced DC engineers in KL / co-lo operators.',
    reviews_eyebrow="Student Reviews",
    reviews_head=("What our DCCOR","engineers say."),
    reviews_summary=("4.7",64,22,8,88),
    reviews=[
        ("\u2605\u2605\u2605\u2605\u2605","ACI labs were the differentiator. Finally passed 350-601 after failing self-study twice.","rav-b","AL","Arif Liew","DC Engineer \u00b7 Co-lo","\u2713 Passed"),
        ("\u2605\u2605\u2605\u2605\u2605","Simlet practice on day 4 matched the real exam feel.","rav-m","CT","Chloe Tang","Network Consultant","\u2713 Passed"),
        ("\u2605\u2605\u2605\u2605","Heavy course \u2014 pre-read is mandatory. Instructor depth is excellent.","rav-g","BP","Bala Prakash","Sysadmin","\u2713 Passed"),
        ("\u2605\u2605\u2605\u2605\u2605","Connected UCS + ACI stories to how my employer actually runs pods.","rav-a","SR","Shawn Rao","Cloud Infra Lead","\u2713 Passed"),
    ],
    price="RM 6,400", price_orig="RM 7,100", price_save="Save 10%",
    price_note="Per person \u00b7 Labs included; exam voucher optional",
    sidebar_meta=[
        ("Duration","5 days / 40 hrs"),
        ("Next intake","15 July 2026"),
        ("Format","On-site \u00b7 Hybrid"),
        ("Level","Professional \u00b7 DC"),
        ("Language","English"),
        ("Cert body","Cisco"),
        ("Exam",'<span class="smeta-badge">Pearson VUE</span>'),
    ],
    whats_included=[
        "Blueprint-aligned workbook",
        "ACI + NX-OS lab exercises",
        "3 practice exams",
        "Recording links",
        "21-day mentor channel",
    ],
    verify_items=[
        "Cisco Certification Tracking System verification",
        "Credly badge when CCNP requirements satisfied",
    ],
    guarantee_text="Clear final mock at 85%+ and fail live exam? Remediation plan + partial retake credit.",
))


# Cisco SD-WAN — Implementing Cisco SD-WAN Solutions (ENSDWI) v2.0
BATCH.append(dict(
    slug="sdwan",
    title="Cisco SD-WAN ENSDWI",
    title_html='Implementing Cisco SD-WAN<br><em>ENSDWI v2.0</em>',
    vendor_short="Cisco", watermark="SDWAN", crumb_vendor="Cisco",
    subtitle="Design, deploy and operate Cisco SD-WAN (Viptela architecture) across enterprise and provider-managed WANs \u2014 including overlays on MPLS, Internet and LTE with policy-driven steering.",
    badges=[("cb-vendor","Cisco Learning Partner"),("cb-level","Professional"),("cb-new","v2.0 Skills"),("cb-hot","WAN Transformation")],
    hero_meta=common_meta("5 days / 40 hrs","Instructor-Led + SD-WAN Lab","On-site \u00b7 Hybrid",92,"22 July 2026"),
    hero_img=HERO_IMG,
    quick_wins=[
        ("\U0001F310","Fabric operations","vManage, vSmart, vBond roles and certificate posture"),
        ("\U0001F500","Policies","Control policies, data policies, QoS and application-aware routing"),
        ("\U0001F6E1","Security services","Firewall zones, IPS/Snort integration concepts at ENSDWI depth"),
        ("\U0001F3AF","Exam alignment","300-415 ENSDWI blueprint mapped"),
    ],
    overview_eyebrow="What this course is",
    overview_head=("WAN transformation","you can actually run."),
    overview_p1="ENSDWI is Cisco's professional-level SD-WAN implementation course and exam path. It is the credential networking engineers pursue when enterprises retire legacy MPLS-only WANs and adopt intelligent overlays with central policy.",
    overview_p2="At Nexperts, labs use Cisco SD-WAN on-prem components with scenario overlays mimicking Malaysian enterprise realities: HQ in KL, factories in Penang and Johor, cloud SaaS breakout and LTE backup.",
    overview_p3="You will touch design (routing protocols on WAN transports), deployment (templates, device onboarding), operations (monitoring, alarms, QoS) and troubleshooting (control vs data plane paths).",
    who_for=[
        ("\U0001F310","WAN engineers","You manage MPLS today and must implement SD-WAN tomorrow."),
        ("\U0001F3AF","Presales consultants","You need defensible designs for CIO decks."),
        ("\U0001F527","Systems integrators","You deploy Cisco-powered WAN refresh programmes."),
        ("\U0001F4BC","Network architects","You decide hybrid WAN vs full internet overlays."),
        ("\U0001F4DA","CCNP Enterprise alumni","You want practical SD-WAN depth beyond ENCOR survey chapters."),
        ("\U0001F393","Talented routing engineers","BGP +/MPLS background accelerates learning."),
    ],
    prereqs=[
        "Routing fundamentals (BGP, OSPF) at CCNP level recommended",
        "Understanding of IPsec basics",
        "Awareness of MPLS VPN services helpful",
    ],
    prereqs_note="Bring your WAN topology (sanitised) \u2014 instructors whiteboard migration paths.",
    curriculum_eyebrow="Course Curriculum",
    curriculum_head=("Architecture to ops.","Five intensive days."),
    curriculum_intro="We teach ENSDWI in lifecycle order: plan, deploy template, bring sites online, implement policies, secure and troubleshoot.",
    modules=[
        ("01","SD-WAN Architecture",[
            "Components and certificates",
            "Underlay vs overlay routing",
            "OMP fundamentals",
            "Zero-touch provisioning concepts",
            "High availability and redundancy",
            "Lab: Bring up controller trio",
        ]),
        ("02","Routing & Policies",[
            "BGP / OMP interplay",
            "TLOC routes and colour concepts",
            "Control policy vs data policy",
            "Application-aware routing",
            "QoS framework on SD-WAN",
            "Lab: Break and fix colour preference",
        ]),
        ("03","Security & Services",[
            "Firewall policy insertion",
            "IPS / AMP placement overview",
            "Direct Internet Access patterns",
            "Cloud on-ramp considerations",
            "Monitoring and assurance tools",
            "Lab: Security policy troubleshooting basket",
        ]),
    ],
    labs_eyebrow="SD-WAN Labs",
    labs_head=("Real overlays.","Designed to fail."),
    labs_intro="Each lab ends with a rollback story \u2014 how you safely back out a bad change during production migration.",
    labs=[
        ("01","Onboarding fail","Certificate or vbond misconfig.","lt-defend","Deploy"),
        ("02","OMP stuck routes","Control plane debugging.","lt-attack","Routing"),
        ("03","Policy mismatch","Application route shifts unexpectedly.","lt-attack","Policy"),
        ("04","QoS verification","Queue counters and SLA classes.","lt-recon","QoS"),
        ("05","Security chain","IPS drop affecting SaaS.","lt-defend","Security"),
        ("06","Exam combo","Timed multi-site scenario.","lt-attack","Exam"),
    ],
    labs_footer="+ WAN migration checklist template (Excel).",
    exam_eyebrow="Exam Information",
    exam_head=("300-415 ENSDWI.","Professional concentration."),
    exam_intro="ENSDWI focuses on implementation depth. Expect scenarios asking what to configure on vManage for a stated outcome.",
    exam_main=dict(name="300-415 ENSDWI",rows=[
        ("Format","Multiple choice + drag-drop + exhibits"),
        ("Duration","90 minutes typical"),
        ("Passing score",'<span class="pass-highlight">~825 / 1000 scaled (typical)</span>'),
        ("Delivery","Pearson VUE"),
        ("Certification","CCNP concentration / specialist path"),
        ("Industry avg pass rate",'<span class="fail-note">~68% first attempt</span>'),
        ("Nexperts pass rate",'<span class="pass-highlight">92% first attempt</span>'),
    ]),
    exam_optional=None,
    mock_title="Practice pathway",
    mock_programme=[
        ("01","Daily drills","Short quizzes."),
        ("02","Policy workshop","Hands-on policy marathon."),
        ("03","Full mock","Exam-length simulation."),
    ],
    pass_rate=92,
    pass_head_html='92% ENSDWI<br><em>first attempt.</em>',
    pass_intro="ENSDWI fails often come from weak OMP/TLOC intuition. We hammer overlays until it is reflex.",
    pass_pills=["Live controllers","Policy labs","92% first attempt","WAN context","Mocks"],
    pass_compare=[
        ("Video-only training","No muscle memory for vManage workflows."),
        ("Nexperts: 92%","Controller-touch hours every day."),
    ],
    next_eyebrow="Your WAN path",
    next_head=("SD-WAN pairs with","routing security."),
    next_steps_intro="Combine ENSDWI with CCNP Security or DevNet skills depending on whether you lean infrastructure or automation.",
    next_steps=[
        ("Before this","ENCOR-level routing","BGP confidence required.","View CCNP \u2192"),
        ("You are here","ENSDWI v2.0","Cisco SD-WAN implementation.","Currently viewing \u2192"),
        ("Recommended next","300-420 / security track","Align to employer stack.","Ask advisor \u2192"),
    ],
    path_name="WAN engineering",
    path_chips=[("CCNP","prev"),("ENSDWI","you"),("DevNet","next"),("CCNP Sec","next"),("AWS Net","next")],
    salary_html='Senior WAN / SD-WAN roles in Malaysia: <strong style="color:#86efac">RM 10,000 \u2013 RM 18,000/month</strong> depending on carrier vs enterprise employer.',
    reviews_eyebrow="Student Reviews",
    reviews_head=("What our ENSDWI","engineers say."),
    reviews_summary=("4.8",70,18,7,96),
    reviews=[
        ("\u2605\u2605\u2605\u2605\u2605","Finally moved from slide decks to real templates. Passed 300-415 on first try.","rav-b","GS","Gary Sim","WAN Lead","\u2713 Passed"),
        ("\u2605\u2605\u2605\u2605\u2605","Policy labs are intense \u2014 exactly what the exam expects.","rav-m","LC","Lydia Chong","Consultant","\u2713 Passed"),
        ("\u2605\u2605\u2605\u2605","Bring your laptop with decent RAM \u2014 labs are heavy. Worth it.","rav-g","MN","Marcus Ng","Network Engineer","\u2713 Passed"),
        ("\u2605\u2605\u2605\u2605\u2605","Best explanation of OMP/TLOC I've heard in 12 years doing WAN.","rav-a","FH","Farah Halim","Architect","\u2713 Passed"),
    ],
    price="RM 5,900", price_orig="RM 6,600", price_save="Save 11%",
    price_note="Per person \u00b7 Includes lab tokens; exam voucher optional",
    sidebar_meta=[
        ("Duration","5 days / 40 hrs"),
        ("Next intake","22 July 2026"),
        ("Format","On-site \u00b7 Hybrid"),
        ("Level","Professional \u00b7 WAN"),
        ("Language","English"),
        ("Cert body","Cisco"),
        ("Exam",'<span class="smeta-badge">Pearson VUE</span>'),
    ],
    whats_included=[
        "SD-WAN lab topology guides",
        "Template pack for migrations",
        "3 practice exams",
        "Recording links",
        "21-day Q&A channel",
    ],
    verify_items=[
        "Cisco certification verification portal",
        "Digital badge when passed",
    ],
    guarantee_text="Pass final mock and fail official exam? One complimentary remediation day.",
))


# Certified Java Programming — Java SE + app foundations (skills track)
BATCH.append(dict(
    slug="java-programming",
    title="Certified Java Programming",
    title_html='Certified<br><em>Java Programming</em>',
    vendor_short="Skill", watermark="JAVA", crumb_vendor="Skill-Based",
    subtitle="Java from syntax to solid small applications \u2014 OOP, collections, exceptions, JDBC basics and a Spring Boot taste for backend-readiness. Built for developers entering enterprise IT teams in Malaysia.",
    badges=[("cb-vendor","Nexperts Skill"),("cb-level","Beginner \u2192 Intermediate"),("cb-new","2026 Syllabus"),("cb-hot","Hiring skill")],
    hero_meta=common_meta("5 days / 40 hrs","Instructor-Led + IDE Labs","On-site \u00b7 Virtual \u00b7 Hybrid",93,"5 Aug 2026"),
    hero_img=HERO_IMG,
    quick_wins=[
        ("\u2615","Java foundations","Classes, interfaces, generics, collections \u2014 production idioms"),
        ("\U0001F525","Build habits","JUnit basics, Maven projects, Git workflow"),
        ("\U0001F310","Data access","JDBC patterns + intro to Spring JDBC template"),
        ("\U0001F4E6","Mini Spring Boot","REST endpoint that persists to H2 / MySQL"),
    ],
    overview_eyebrow="What this course is",
    overview_head=("Java as a","professional language."),
    overview_p1="Java remains the backbone of enterprise backends across Malaysian banks, telcos and government digital services. This programme is not a hobby introduction \u2014 it is a five-day sprint to professional-grade foundations with a portfolio artefact you can show hiring managers.",
    overview_p2="You will work in IntelliJ / VS Code with Git from day one. Every module ships code reviews with instructors \u2014 the same feedback loop you will see in real teams.",
    overview_p3="Capstone options include a ticket-webhook microservice, a batch payroll calculator with tests, or a Spring Boot CRUD API \u2014 pick what matches your target role.",
    who_for=[
        ("\U0001F468\u200D\U0001F4BB","IT graduates","You need a credential employers recognise faster than 'I did online courses'."),
        ("\U0001F4CA","Ops engineers moving to dev","You script already \u2014 Java unlocks enterprise software teams."),
        ("\U0001F510","Test automation engineers","You will appreciate strong typing and tooling."),
        ("\U0001F4BC","Career returnees","Structured classroom beats inconsistent self-study."),
        ("\U0001F393","Intern pipeline candidates","Portfolio piece for bank tech graduate programmes."),
        ("\u2699\uFE0F","PHP / Node devs","You want JVM ecosystem fluency for new roles."),
    ],
    prereqs=[
        "Logical thinking and patience with compiler errors",
        "No Java prerequisite",
        "Laptop with 16 GB RAM recommended",
    ],
    prereqs_note="Install OpenJDK 21 + IntelliJ Community before day 1 \u2014 pre-class setup guide sent on enrolment.",
    curriculum_eyebrow="Course Curriculum",
    curriculum_head=("Five days.","Syntax to service."),
    curriculum_intro="We alternate short lectures with paired programming exercises. Homework is optional but encouraged \u2014 office hours each evening.",
    modules=[
        ("01","Language fundamentals",[
            "JDK, classpath, packages",
            "Types, operators, control flow",
            "Methods, parameters, overloading",
            "Arrays and strings",
            "Lab: CLI expense tracker",
        ]),
        ("02","OOP & APIs",[
            "Classes, inheritance, polymorphism",
            "Interfaces and abstract classes",
            "Enums and records (where applicable)",
            "Exceptions and try-with-resources",
            "Lab: extend domain model for HR scenario",
        ]),
        ("03","Collections & IO",[
            "Lists, maps, sets and iteration idioms",
            "Streams introduction",
            "File I/O and JSON with Jackson",
            "Lab: ingest CSV, emit summary report",
        ]),
        ("04","JDBC + Intro Spring",[
            "Connection pools and prepared statements",
            "Transaction basics",
            "Spring Boot project layout",
            "REST controller + repository stub",
            "Lab: CRUD API backed by H2",
        ]),
    ],
    labs_eyebrow="Hands-On Labs",
    labs_head=("Pair programming.","Real IDE workflow."),
    labs_intro="Labs are timed just enough to pressure you without chaos \u2014 mirroring sprint tasks.",
    labs=[
        ("01","Expense CLI","Parse commands + persist JSON.","lt-recon","Java I"),
        ("02","Payroll OOP","Polymorphic employee types.","lt-recon","OOP"),
        ("03","Streams","ETL mini pipeline.","lt-defend","Collections"),
        ("04","JDBC","Load customers from DB.","lt-recon","Data"),
        ("05","Spring REST","Expose CRUD endpoints.","lt-attack","Spring"),
        ("06","Capstone","Choose track + defend.","lt-attack","Capstone"),
    ],
    labs_footer="+ Git template repo with CI smoke test.",
    exam_eyebrow="Assessment",
    exam_head=("Portfolio defence.","Not a multiple-choice trivia quiz."),
    exam_intro="You will be assessed on a capstone project (built in class) with a 20-minute structured walkthrough covering design trade-offs and tests.",
    exam_main=dict(name="Practical assessment",rows=[
        ("Deliverable","Spring Boot or pure Java project per track"),
        ("Evaluation","Code quality, tests, README, demo"),
        ("Passing",'<span class="pass-highlight">Meets rubric + working demo</span>'),
        ("Academic integrity","Pair-friendly labs; capstone is individual"),
        ("Resit","One complimentary resit window within 90 days"),
        ("Cohort success",'<span class="pass-highlight">93% pass capstone first attempt</span>'),
    ]),
    exam_optional=None,
    mock_title="Weekly checkpoints",
    mock_programme=[
        ("01","Syntax check","Day 2 quiz."),
        ("02","OOP challenge","Day 3 timed exercise."),
        ("03","Integration lab","Day 4 joint code review."),
    ],
    pass_rate=93,
    pass_head_html='93% capstone pass<br><em>first attempt.</em>',
    pass_intro="We optimise for employability: readable Java, tests, and articulate explanations \u2014 the hiring bar for junior engineers in KL.",
    pass_pills=["Spring taste","Portfolio","93% pass","Git habits","Mentor hours"],
    pass_compare=[
        ("Video-only Java courses","No accountability on code quality."),
        ("Nexperts: 93%","Live reviews + capstone rubric aligned to hiring screens."),
    ],
    next_eyebrow="Your developer path",
    next_head=("Java pairs with","SQL and DevOps literacy."),
    next_steps_intro="Graduates often continue with our SQL + Docker workshops or pursue Oracle Java certification independently.",
    next_steps=[
        ("Before this","No coding OK","We start from zero syntax.","View basics \u2192"),
        ("You are here","Certified Java Programming","Professional Java foundations + Spring taste.","Currently viewing \u2192"),
        ("Recommended next","SQL or AZ-204","Data access depth or cloud-native Java on Azure.","View SQL \u2192"),
    ],
    path_name="software development",
    path_chips=[("Python","prev"),("Java","you"),("SQL","next"),("Docker","next"),("AZ-204","next")],
    salary_html='Junior Java developer offers in KL often start <strong style="color:#86efac">RM 4,500 \u2013 RM 7,500/month</strong> with strong portfolio and communication skills.',
    reviews_eyebrow="Student Reviews",
    reviews_head=("What our Java","cohorts say."),
    reviews_summary=("4.9",210,32,5,268),
    reviews=[
        ("\u2605\u2605\u2605\u2605\u2605","Capstone project landed me my first dev interview \u2014 they cloned my Git repo on the call.","rav-b","YM","Yasmin Mokhtar","Junior Developer","\u2713 Hired"),
        ("\u2605\u2605\u2605\u2605\u2605","Instructors actually read your code line by line. Brutal but fair.","rav-m","JT","Jason Teh","Career switcher","\u2713 Capstone pass"),
        ("\u2605\u2605\u2605\u2605","Wish we had another week on Spring \u2014 but foundations are solid.","rav-g","KL","Kim Lim","IT Analyst","\u2713 Capstone pass"),
        ("\u2605\u2605\u2605\u2605\u2605","Best classroom energy of any course I've taken in KL.","rav-a","DP","Deepak Prasad","Graduate","\u2713 Capstone pass"),
    ],
    price="RM 2,450", price_orig="RM 2,750", price_save="Save 11%",
    price_note="Per person \u00b7 Includes repo templates + mentor channel",
    sidebar_meta=[
        ("Duration","5 days / 40 hrs"),
        ("Next intake","5 Aug 2026"),
        ("Format","On-site \u00b7 Virtual"),
        ("Level","Beginner \u2192 Intermediate"),
        ("Language","English"),
        ("Cert body","Nexperts Skill Certificate"),
        ("Exam",'<span class="smeta-badge">Capstone</span>'),
    ],
    whats_included=[
        "Java + Maven starter repo",
        "Spring Boot baseline template",
        "Code review sessions",
        "Capstone rubric + sample solutions",
        "LinkedIn endorsement guidance",
    ],
    verify_items=[
        "Nexperts skill certificate with verification ID",
        "Portfolio Git repository artefact",
    ],
    guarantee_text="Finish attendance + exercises and do not pass capstone? Remediation slot within 90 days.",
))
