# -*- coding: utf-8 -*-
"""Microsoft course data (AZ-900, AZ-104, AZ-305, SC-200, PL-300, DP-203)."""
from _course_data import HERO_IMG, common_meta

BATCH = []

# 1. AZ-900 Azure Fundamentals
BATCH.append(dict(
    slug="az-900",
    title="AZ-900: Azure Fundamentals",
    title_html='AZ-900: Azure<br><em>Fundamentals</em>',
    vendor_short="Microsoft", watermark="AZ-900", crumb_vendor="Microsoft",
    subtitle="The Azure literacy credential. Cloud concepts, Azure services, governance, security, privacy and pricing \u2014 the right first step for anyone entering the Microsoft cloud ecosystem.",
    badges=[("cb-vendor","Microsoft Authorized"),("cb-level","Foundation"),("cb-new","2026 Updated"),("cb-hot","Government Cloud Essential")],
    hero_meta=common_meta("3 days / 24 hrs","Instructor-Led + Azure Sandbox","On-site \u00b7 Virtual \u00b7 Hybrid",98,"21 July 2026"),
    hero_img=HERO_IMG,
    quick_wins=[
        ("\u2601\uFE0F","Azure literacy in 3 days","Speak Azure with developers, architects and finance teams"),
        ("\U0001F4B0","Cost & subscription model","Azure billing, reservations and cost management essentials"),
        ("\U0001F510","Compliance for MY context","Azure regulatory alignment with PDPA, BNM RMiT, MyDigital"),
        ("\U0001F30F","M365 \u00d7 Azure crossover","See how Azure intersects with the M365 stack you already use"),
    ],
    overview_eyebrow="What this course is",
    overview_head=("AZ-900 is","Azure literacy."),
    overview_p1="The Microsoft AZ-900 (Azure Fundamentals) certification validates that you understand cloud concepts, core Azure services, security, governance, privacy and pricing. It is the most widely held cloud foundational credential in the Microsoft ecosystem, especially in MY government and GLC environments.",
    overview_p2="At Nexperts, AZ-900 is taught against a live Azure sandbox subscription that every learner has full access to during and after the course. You launch real resources \u2014 not slides.",
    overview_quote="AZ-900 is not a developer cert. It is a cross-functional cloud literacy cert that finance, project, governance and IT staff all benefit from equally.",
    overview_p3="The 2026 update of AZ-900 incorporates Microsoft Copilot for Azure, modernised pricing options, and updated Well-Architected Framework alignment. We teach with current Malaysian banking, GLC and government Azure deployments as case context.",
    who_for=[
        ("\U0001F468\u200D\U0001F4BC","Project & program managers","Lead Azure migration projects credibly without being lost in the technical conversation."),
        ("\U0001F4CA","Finance & procurement","Understand Azure billing and reservations \u2014 essential for cloud cost governance."),
        ("\U0001F3DB\uFE0F","Government & GLC staff","MY government cloud-first policy makes Azure literacy increasingly required."),
        ("\U0001F4BB","M365 administrators","Already familiar with the Microsoft cloud \u2014 AZ-900 extends your range."),
        ("\U0001F393","Career switchers","The fastest path into the Microsoft cloud ecosystem."),
        ("\U0001F4DA","Pre-AZ-104 / AZ-204","AZ-900 is the foundational step before specialised Azure roles."),
    ],
    prereqs=[
        "Basic IT literacy",
        "No Azure experience required",
        "Familiarity with Office or M365 helpful",
        "Curiosity about cloud and Microsoft platforms",
    ],
    prereqs_note="No IT background? AZ-900 is still accessible. Ask us about our pre-AZ-900 primer.",
    curriculum_eyebrow="Course Curriculum",
    curriculum_head=("Three domains.","Azure end-to-end."),
    curriculum_intro="AZ-900 is structured into Cloud Concepts, Azure Architecture and Services, and Azure Management and Governance. We deliver each with hands-on sandbox labs.",
    modules=[
        ("01","Cloud Concepts",[
            "Cloud computing benefits and trade-offs",
            "IaaS, PaaS, SaaS \u2014 with Azure-specific examples",
            "Public, private, hybrid \u2014 mapped to MY context",
            "Capex vs opex models",
            "Cloud responsibility model in Microsoft cloud",
            "Lab: Map your existing on-prem to Azure equivalents",
        ]),
        ("02","Azure Architecture & Services",[
            "Azure regions, availability zones, region pairs",
            "Compute \u2014 VMs, App Service, AKS, Functions",
            "Storage \u2014 Blob, Files, Queue, Table, Disks",
            "Networking \u2014 VNet, Load Balancer, Front Door, ExpressRoute",
            "Databases \u2014 SQL DB, Cosmos DB, MySQL, PostgreSQL",
            "Lab: Deploy a 3-tier web app on Azure",
        ]),
        ("03","Management & Governance",[
            "Azure pricing models and billing",
            "Service-level agreements (SLAs) and composite SLAs",
            "Cost Management + Cost Anomaly Detection",
            "Azure Policy, Blueprints, RBAC",
            "Microsoft Defender for Cloud and Azure Sentinel essentials",
            "Lab: Apply a policy and audit Azure resources",
        ]),
    ],
    labs_eyebrow="Hands-On Azure Sandbox",
    labs_head=("24 lab tasks.","Live Azure tenant."),
    labs_intro="Every learner gets full Azure sandbox access for 30 days. You'll launch real resources, configure real RBAC, set up real budgets \u2014 against your own dedicated Azure subscription.",
    labs=[
        ("01","Provision an Azure VM","Deploy a Windows Server 2025 VM. Connect via RDP. Capture an image.","lt-recon","Compute"),
        ("02","Blob Storage Static Website","Host a static website from blob storage. Configure CDN.","lt-recon","Storage"),
        ("03","VNet Architecture","Build a VNet with two subnets, NSGs, and Bastion access.","lt-recon","Networking"),
        ("04","Azure SQL Provision","Provision Azure SQL DB. Connect from VM. Apply firewall rules.","lt-recon","Database"),
        ("05","Function App + Logic App","Build a serverless workflow combining Function and Logic apps.","lt-attack","Serverless"),
        ("06","RBAC Lockdown","Create custom roles. Apply at resource group scope. Test failures.","lt-defend","Identity"),
        ("07","Cost Budget & Anomaly","Configure budgets and Cost Anomaly Detection.","lt-defend","Finance"),
        ("08","Defender for Cloud","Enable secure score. Address top 3 recommendations.","lt-defend","Security"),
        ("09","Copilot for Azure","Use Copilot to deploy infrastructure conversationally.","lt-recon","Copilot"),
    ],
    labs_footer="+ 15 additional sandbox tasks. Sandbox access for 30 days post-course.",
    exam_eyebrow="Exam Information",
    exam_head=("One exam.","Concept-focused, broad."),
    exam_intro="AZ-900 is the foundational Azure exam \u2014 broad coverage, scenario-based questions, no deep technical traps. Pattern recognition and clear conceptual understanding pass it.",
    exam_main=dict(name="AZ-900 Exam",rows=[
        ("Questions","40\u201360 multiple choice"),
        ("Duration","60 minutes (85 with accommodations)"),
        ("Passing score",'<span class="pass-highlight">700 / 1000</span>'),
        ("Format","Pearson VUE / Online proctor"),
        ("Validity","No expiration (Microsoft fundamentals)"),
        ("Industry avg pass rate",'<span class="fail-note">~78% first attempt</span>'),
        ("Nexperts pass rate",'<span class="pass-highlight">98% first attempt</span>'),
    ]),
    exam_optional=dict(name="Microsoft Azure Path",rows=[
        ("Stacks with","AZ-900 \u2192 AZ-104 \u2192 AZ-305"),
        ("Cross-track","Pairs with AI-900, DP-900, SC-900"),
        ("Voucher","Bundled \u2014 Microsoft exam voucher included"),
        ("Career fit","Cloud-aware PM, BA, finance, generalist"),
        ("Renewal","No expiration \u2014 lifetime credential"),
        ("Pre-bridge","Required understanding for AZ-104"),
        ("MY recognition","Required by MyDigital cloud-first policy"),
    ]),
    mock_title="Our AZ-900 3-Mock Programme",
    mock_programme=[
        ("01","Diagnostic Mock","Day 1 evening. Maps weak service knowledge. Average score: 71%."),
        ("02","Scenario Mock","Day 2. 60-question scenario simulation. Average score: 84%."),
        ("03","Final Clearance","Day 3. Timed full simulation. 87%+ before booking. Average score: 91%."),
    ],
    pass_rate=98,
    pass_head_html='98% of our AZ-900 candidates<br>pass <em>on first attempt.</em>',
    pass_intro="The global AZ-900 first-attempt rate is around 78%. Our 98% comes from 30 days of Azure sandbox access, three timed mocks, and an instructor who has run two MY government cloud migrations across the past 4 years.",
    pass_pills=["30-day Azure sandbox","3 timed mocks","98% first attempt","MY context throughout","Free retake voucher"],
    pass_compare=[
        ("Industry average: ~78%","Most candidates underestimate the breadth of services. They study compute deeply and miss governance, billing and SLAs entirely."),
        ("Nexperts: 98%","We force every service to memory through the sandbox. We hard-gate on a clearance mock at 87%."),
    ],
    next_eyebrow="Your Certification Journey",
    next_head=("AZ-900 unlocks","every Azure path."),
    next_steps_intro="From AZ-900 you specialise \u2014 administration with AZ-104, development with AZ-204, security with SC-200, or AI with AI-900 / AI-102.",
    next_steps=[
        ("Before this","No prerequisite","AZ-900 is the Microsoft cloud entry. It assumes only general IT literacy.","View entry path \u2192"),
        ("You are here","AZ-900: Azure Fundamentals","Cloud-fluent across Azure services, governance, billing and security.","Currently viewing \u2192"),
        ("Recommended next","AZ-104 or AI-900","AZ-104 is the most-hired Azure credential. AI-900 specialises into the AI track.","View AZ-104 \u2192"),
    ],
    path_name="Microsoft Azure career",
    path_chips=[("None","prev"),("AZ-900","you"),("AZ-104 / AI-900","next"),("AZ-305 / SC-200","prev"),("AZ-400 / AI-102","prev")],
    salary_html='Expected salary range after AZ-900: <strong style="color:#86efac">RM 4,500 \u2013 RM 7,500/month</strong> for cloud-aware IT and project roles in Malaysian enterprises.',
    reviews_eyebrow="Student Reviews",
    reviews_head=("What our AZ-900","graduates say."),
    reviews_summary=("4.9",95,4,1,289),
    reviews=[
        ("\u2605\u2605\u2605\u2605\u2605","I'm a procurement officer at a federal agency. AZ-900 gave me the language to evaluate Azure tender responses credibly. It was the cert I didn't know I needed.","rav-b","NS","Norazlinda Saari","Procurement Officer \u00b7 MAMPU","\u2713 Passed first attempt \u00b7 851 / 700"),
        ("\u2605\u2605\u2605\u2605\u2605","The Copilot for Azure module made me feel like I'd skipped a year of training. Conversational deployment is the future and we got to play with it on day one.","rav-m","CS","Chong Sheng Ming","M365 Admin \u00b7 Hong Leong Bank","\u2713 Passed first attempt \u00b7 832 / 700"),
        ("\u2605\u2605\u2605\u2605\u2605","Came in cold from a banking background. Sandbox access made all the difference. By day three I was deploying SQL DBs and feeling capable.","rav-g","KK","Kavitha Krishnan","BA \u00b7 OCBC Malaysia","\u2713 Passed first attempt \u00b7 798 / 700"),
        ("\u2605\u2605\u2605\u2605\u2605","Cost management module saved my GLC RM 78k/month in over-provisioned dev environments. The cert was free in retrospect.","rav-a","FA","Faizal Ariffin","Senior Manager \u00b7 PETRONAS","\u2713 Passed first attempt \u00b7 871 / 700"),
    ],
    price="RM 2,400", price_orig="RM 3,000", price_save="Save 20%",
    price_note="Per person \u00b7 Includes Microsoft voucher, 30-day sandbox, courseware",
    sidebar_meta=[
        ("Duration","3 days / 24 hrs"),
        ("Next intake","21 July 2026"),
        ("Format","On-site \u00b7 Virtual \u00b7 Hybrid"),
        ("Level","Foundation"),
        ("Language","English \u00b7 BM available"),
        ("Cert body","Microsoft"),
        ("Exam",'<span class="smeta-badge">Included</span>'),
    ],
    whats_included=[
        "Microsoft official courseware",
        "Microsoft exam voucher (AZ-900)",
        "30-day full Azure sandbox subscription",
        "3 full timed mock exams",
        "Azure service flashcard pack",
        "Cost-management spreadsheet templates",
        "Post-course instructor access (30 days)",
        "Free retake voucher (conditions apply)",
        "Digital badge via Microsoft Learn",
    ],
    verify_items=[
        "Verifiable on Microsoft Learn",
        "Digital badge via Credly",
        "Required by MyDigital cloud-first policy",
        "Stacks with all Azure role-based credentials",
    ],
    guarantee_text="Hit the 87% mock threshold and don't pass first attempt? Microsoft retake voucher on us.",
))


# ===== Helper for shorter Microsoft entries below =====
def _ms_course(slug, title, title_html, watermark, subtitle, badges_extra, duration, intake, pass_rate, **rest):
    """Compact factory used to keep Microsoft batch readable."""
    base = dict(
        slug=slug, title=title, title_html=title_html,
        vendor_short="Microsoft", watermark=watermark, crumb_vendor="Microsoft",
        subtitle=subtitle,
        badges=[("cb-vendor","Microsoft Authorized")] + badges_extra,
        hero_meta=common_meta(duration,"Instructor-Led + Azure Sandbox","On-site \u00b7 Virtual \u00b7 Hybrid",pass_rate,intake),
        hero_img=HERO_IMG,
        pass_rate=pass_rate,
    )
    base.update(rest)
    return base


# 2. AZ-104 Azure Administrator
BATCH.append(_ms_course(
    slug="az-104",
    title="AZ-104: Azure Administrator",
    title_html='AZ-104: Azure<br><em>Administrator Associate</em>',
    watermark="AZ-104",
    subtitle="The most-hired Azure credential in MY enterprises. Manage identities, networking, storage, virtual machines, governance and monitoring \u2014 the day-to-day Azure admin role.",
    badges_extra=[("cb-level","Associate"),("cb-new","AZ-104 \u00b7 2026"),("cb-hot","#1 Azure Hire in MY")],
    duration="5 days / 40 hrs",
    intake="28 July 2026",
    pass_rate=96,
    quick_wins=[
        ("\U0001F510","Identity & RBAC mastery","Entra ID, custom roles, PIM, conditional access"),
        ("\U0001F310","Azure networking depth","VNets, peering, ExpressRoute, Front Door, Application Gateway"),
        ("\U0001F4BE","Storage & VM operations","Tiers, redundancy, backups, monitoring, recovery"),
        ("\U0001F4CA","Governance & monitoring","Policy, Defender for Cloud, Log Analytics, alerts"),
    ],
    overview_eyebrow="What this course is",
    overview_head=("AZ-104 is","day-to-day Azure ops."),
    overview_p1="AZ-104 is the most-hired Azure credential in Malaysian enterprises. It validates that you can implement, manage and monitor identity, governance, storage, compute and virtual networks in Azure.",
    overview_p2="At Nexperts, AZ-104 is delivered against a multi-subscription Azure tenant with Entra ID, hybrid VPN to a simulated on-prem and full RBAC. You administer real resources, not slide diagrams.",
    overview_quote="AZ-104 does not test what you know about Azure. It tests how quickly you can find, fix and document Azure operations under pressure.",
    overview_p3="The 2026 update brings deeper coverage of Microsoft Entra ID (formerly Azure AD), Azure Arc-managed resources, and Defender for Cloud. We teach all three with current MY enterprise Azure deployments as context.",
    who_for=[
        ("\U0001F4BB","Sysadmins moving to cloud","On-prem AD admins moving to Entra ID and Azure-managed infra."),
        ("\U0001F310","Network engineers","Take your network skills into Azure VNets, peering, ExpressRoute and Front Door."),
        ("\u2601\uFE0F","AZ-900 graduates","The natural specialisation step into the most-hired Azure role."),
        ("\U0001F4CA","M365 administrators","Extend your Microsoft cloud range from M365 into Azure infrastructure."),
        ("\U0001F50D","Pre-AZ-305 candidates","AZ-104 is the operational base before AZ-305 architecture."),
        ("\U0001F4DA","DevOps practitioners","Operations fluency for the Azure-side of CI/CD and IaC pipelines."),
    ],
    prereqs=[
        "AZ-900 or equivalent Azure foundational knowledge",
        "6+ months of general Azure or sysadmin experience",
        "Comfort with PowerShell and Azure CLI",
        "Familiarity with Active Directory concepts",
    ],
    prereqs_note="Don't have AZ-900? Ask us about our 7-day combined AZ-900 \u2192 AZ-104 track.",
    curriculum_eyebrow="Course Curriculum",
    curriculum_head=("Five domains.","Operations end-to-end."),
    curriculum_intro="AZ-104 is structured into Identity, Governance, Storage, Compute, and Virtual Networking + Monitoring. We sequence as a real ops engineer's day.",
    modules=[
        ("01","Identity & Governance",[
            "Entra ID users, groups, devices",
            "Custom RBAC roles and PIM",
            "Conditional access and MFA",
            "Azure Policy and Blueprints",
            "Tag governance and resource locks",
            "Lab: Build an Entra ID hybrid join from on-prem AD",
        ]),
        ("02","Storage Implementation",[
            "Storage accounts, redundancy options",
            "Blob containers, lifecycle, immutability",
            "Azure Files, sync and File Sync",
            "Storage encryption and keys",
            "Backup and restore strategies",
            "Lab: Configure RA-GZRS blob with lifecycle automation",
        ]),
        ("03","Compute Resources",[
            "VM creation, sizing and Spot pricing",
            "VM scale sets and availability options",
            "App Service plans and deployment slots",
            "Container Apps and AKS basics",
            "Azure Functions for ops automation",
            "Lab: Build a VMSS with auto-scaling and load balancing",
        ]),
        ("04","Virtual Networking",[
            "VNet design, subnets, NSGs, ASGs",
            "VNet peering and hub-spoke topologies",
            "Site-to-Site VPN and ExpressRoute",
            "Azure Firewall, App Gateway, Front Door",
            "Private Endpoints and DNS",
            "Lab: Hub-spoke topology with Azure Firewall in transit",
        ]),
        ("05","Monitoring & Backup",[
            "Azure Monitor, Log Analytics, Workbooks",
            "Alerts, action groups and runbooks",
            "Azure Backup and Site Recovery",
            "Defender for Cloud secure score",
            "Cost Management + budgets",
            "Lab: Build a unified monitoring dashboard for 3 subscriptions",
        ]),
    ],
    labs_eyebrow="Hands-On Multi-Subscription Sandbox",
    labs_head=("40 admin tasks.","Live Azure tenant."),
    labs_intro="The Nexperts AZ-104 sandbox is a 3-subscription Azure tenant with Entra ID, hybrid VPN to a simulated on-prem AD and pre-staged workloads.",
    labs=[
        ("01","Entra ID Hybrid Join","Join a simulated on-prem AD to Entra ID. Test conditional access.","lt-defend","Identity"),
        ("02","Custom RBAC at Scale","Create 5 custom RBAC roles aligned to job functions.","lt-defend","Governance"),
        ("03","Hub-Spoke Network","Build a hub-spoke with Azure Firewall in transit.","lt-recon","Networking"),
        ("04","ExpressRoute Simulation","Configure ExpressRoute peering (sim). Test routing.","lt-recon","Connectivity"),
        ("05","VMSS Auto-Scale","Deploy a VMSS with metric-driven auto-scaling.","lt-recon","Compute"),
        ("06","Azure Files SMB Share","Create a SMB share. Sync from a simulated on-prem.","lt-recon","Storage"),
        ("07","Azure Backup + ASR","Protect VMs with Backup and Site Recovery. Test failover.","lt-defend","DR"),
        ("08","Log Analytics Workspace","Centralise logs from 3 subscriptions. Build alerts.","lt-defend","Monitoring"),
        ("09","Defender for Cloud Hardening","Improve secure score from 35 to 75 in 60 minutes.","lt-defend","Security"),
    ],
    labs_footer="+ 31 additional admin tasks. Sandbox access for 60 days post-course.",
    exam_eyebrow="Exam Information",
    exam_head=("One exam.","Lab-style PBQs."),
    exam_intro="AZ-104 includes case-study-style questions and a small live lab section. The exam tests whether you can navigate the Azure Portal and CLI under time pressure.",
    exam_main=dict(name="AZ-104 Exam",rows=[
        ("Questions","40\u201360 incl. case study and lab"),
        ("Duration","100 minutes"),
        ("Passing score",'<span class="pass-highlight">700 / 1000</span>'),
        ("Format","Pearson VUE / Online proctor"),
        ("Validity","1 year (renewal via free assessment)"),
        ("Industry avg pass rate",'<span class="fail-note">~68% first attempt</span>'),
        ("Nexperts pass rate",'<span class="pass-highlight">96% first attempt</span>'),
    ]),
    exam_optional=dict(name="Azure Career Trajectory",rows=[
        ("Stacks with","AZ-900 \u2192 AZ-104 \u2192 AZ-305"),
        ("Renewal","Free \u2014 yearly Microsoft Learn assessment"),
        ("MY salary uplift","Average +RM 1,500/mo post-cert"),
        ("Voucher","Bundled \u2014 Microsoft exam voucher"),
        ("Lab section","Yes \u2014 dedicated coaching included"),
        ("Pre-bridge","Required for AZ-305 architecture path"),
        ("Career fit","Cloud admin, M365 \u00d7 Azure ops, junior architect"),
    ]),
    mock_title="Our AZ-104 3-Mock Programme",
    mock_programme=[
        ("01","Diagnostic Mock","Day 2. Maps weak admin areas. Average score: 64%."),
        ("02","Lab-Section Mock","Day 4. Live portal task simulation. Average score: 75%."),
        ("03","Final Clearance","Day 5. Full timed simulation. 84%+ before booking. Average score: 88%."),
    ],
    pass_head_html='96% of our AZ-104 admins<br>pass <em>on first attempt.</em>',
    pass_intro="The global AZ-104 first-attempt rate is around 68%. Our 96% comes from a multi-subscription tenant, dedicated portal-task coaching, and an instructor who manages 600+ Azure VMs across 4 MY banks.",
    pass_pills=["Multi-subscription tenant","Live lab coaching","96% first attempt","Hybrid AD setup","Free retake voucher"],
    pass_compare=[
        ("Industry average: ~68%","Most candidates fail on the lab section because they're slow in the Portal under time pressure. They know the answer; they just can't click it fast enough."),
        ("Nexperts: 96%","We drill Portal speed. We make you do timed clicking exercises. We treat the lab section like a sport \u2014 because it is."),
    ],
    next_eyebrow="Your Certification Journey",
    next_head=("AZ-104 builds the","Azure ops foundation."),
    next_steps_intro="From AZ-104 you choose architecture (AZ-305), development (AZ-204), security (SC-200) or specialise into Networks/Identity Specialty paths.",
    next_steps=[
        ("Before this","AZ-900","Azure foundational literacy is the prerequisite. AZ-104 builds operations on top.","View AZ-900 \u2192"),
        ("You are here","AZ-104: Azure Administrator","Most-hired Azure credential. Run identity, networking, storage, compute and monitoring.","Currently viewing \u2192"),
        ("Recommended next","AZ-305 or SC-200","AZ-305 takes you to architecture. SC-200 pivots into security operations.","View AZ-305 \u2192"),
    ],
    path_name="Azure administrator",
    path_chips=[("AZ-900","prev"),("AZ-104","you"),("AZ-305 / SC-200","next"),("AZ-400 / DP-203","prev"),("Azure Hero","prev")],
    salary_html='Expected salary range after AZ-104: <strong style="color:#86efac">RM 6,500 \u2013 RM 11,000/month</strong> for cloud admin and Azure ops roles in Malaysian enterprises.',
    reviews_eyebrow="Student Reviews",
    reviews_head=("What our AZ-104","graduates say."),
    reviews_summary=("4.8",88,10,2,221),
    reviews=[
        ("\u2605\u2605\u2605\u2605\u2605","Hub-spoke architecture made networking finally click. We rebuilt our company's Azure topology three weeks after the course \u2014 cleaner, cheaper, more secure.","rav-b","SR","Sayoga Ravi","Cloud Administrator \u00b7 Boost Bank","\u2713 Passed first attempt \u00b7 832 / 700"),
        ("\u2605\u2605\u2605\u2605\u2605","Portal-speed drills were unique. I'd written off the lab section as luck of the draw. Nexperts proved otherwise. Finished the lab with 4 minutes to spare.","rav-m","TY","Tan Yi Wei","Azure Engineer \u00b7 RHB Bank","\u2713 Passed first attempt \u00b7 798 / 700"),
        ("\u2605\u2605\u2605\u2605\u2605","Hybrid AD join was the module I most needed. Three weeks later, we joined our finance domain to Entra ID using exactly the playbook from class.","rav-g","HK","Hassan Kassim","Senior IT Officer \u00b7 Malaysia Airlines","\u2713 Passed first attempt \u00b7 821 / 700"),
        ("\u2605\u2605\u2605\u2605\u2605","Defender for Cloud secure-score sprint was eye-opening. Our company score moved from 32 to 78 in three weeks of post-course work.","rav-a","NL","Nicholas Lee","Cloud Engineer \u00b7 Standard Chartered","\u2713 Passed first attempt \u00b7 871 / 700"),
    ],
    price="RM 3,400", price_orig="RM 4,100", price_save="Save 17%",
    price_note="Per person \u00b7 Includes Microsoft voucher, multi-subscription sandbox, courseware",
    sidebar_meta=[
        ("Duration","5 days / 40 hrs"),
        ("Next intake","28 July 2026"),
        ("Format","On-site \u00b7 Hybrid"),
        ("Level","Associate"),
        ("Language","English"),
        ("Cert body","Microsoft"),
        ("Exam",'<span class="smeta-badge">Included</span>'),
    ],
    whats_included=[
        "Microsoft official AZ-104 courseware",
        "Microsoft exam voucher (AZ-104)",
        "60-day multi-subscription Azure sandbox",
        "3 full timed mock exams",
        "Live lab section coaching workshop",
        "Hub-spoke networking playbook",
        "Post-course instructor access (45 days)",
        "Free retake voucher (conditions apply)",
        "Digital badge via Microsoft Learn",
    ],
    verify_items=[
        "Verifiable on Microsoft Learn",
        "Digital badge via Credly",
        "Renewable yearly via Microsoft assessment",
        "Stacks toward AZ-305 / SC-200 / AZ-400",
    ],
    guarantee_text="Hit the 84% mock threshold and don't pass first attempt? Microsoft retake voucher on us.",
))


# 3. AZ-305 Solutions Architect Expert
BATCH.append(_ms_course(
    slug="az-305",
    title="AZ-305: Solutions Architect",
    title_html='AZ-305: Solutions<br><em>Architect Expert</em>',
    watermark="AZ-305",
    subtitle="Microsoft's most-respected architecture credential. Design for identity, governance, data platforms, business continuity and infrastructure across enterprise Azure environments.",
    badges_extra=[("cb-level","Expert"),("cb-new","2026 Updated"),("cb-hot","Architecture Apex")],
    duration="6 days / 48 hrs",
    intake="4 August 2026",
    pass_rate=93,
    quick_wins=[
        ("\U0001F3DB\uFE0F","Enterprise architect mindset","Trade-off thinking across cost, security, performance"),
        ("\U0001F510","Identity & governance mastery","Hybrid AD, Entra ID, B2B/B2C, governance hierarchy"),
        ("\U0001F4BE","Data platform design","Cosmos DB, Synapse, Purview \u2014 design for analytics scale"),
        ("\U0001F31F","BCDR by design","Multi-region, geo-DR, backup tiering, recovery models"),
    ],
    overview_eyebrow="What this course is",
    overview_head=("AZ-305 is","architecture mastery."),
    overview_p1="The Microsoft Certified: Azure Solutions Architect Expert (AZ-305) is the highest Microsoft architecture credential. It tests scenario design across identity, governance, business continuity, infrastructure and data \u2014 the cross-domain choices that real enterprise architects make.",
    overview_p2="Nexperts AZ-305 is delivered as a 6-day deep-dive against a multi-tenant Azure environment. You architect across two regulated MY case studies \u2014 a fictional bank and a fictional healthcare provider \u2014 covering all six AZ-305 design domains.",
    overview_quote="AZ-305 will not test whether you know a service. It will test whether you can choose between two services with overlapping capabilities and defend the choice.",
    overview_p3="The 2026 refresh strengthens governance, hybrid identity and Microsoft Fabric data platform alignment. We teach with current MY context \u2014 BNM RMiT, PDPA, healthcare data sovereignty and government cloud-first policy.",
    who_for=[
        ("\U0001F3DB\uFE0F","AZ-104 administrators","The natural progression. AZ-104 proved you can run Azure. AZ-305 proves you can design it."),
        ("\U0001F4BC","Enterprise consultants","Big-4 and tier-1 consultancies require AZ-305 for senior Azure advisory roles."),
        ("\U0001F4CA","Pre-sales architects","Vendor pre-sales architects designing customer-facing Azure proposals."),
        ("\U0001F3DC\uFE0F","Banking & telco architects","BNM RMiT cloud guidelines align with AZ-305 design patterns."),
        ("\U0001F50D","CCoE leaders","Cloud Centre of Excellence leaders need AZ-305-grade design fluency."),
        ("\U0001F4DA","Hybrid architects","Mapping on-prem skills onto modern Azure with hybrid governance."),
    ],
    prereqs=[
        "AZ-104 Azure Administrator Associate",
        "2+ years of hands-on Azure architecture experience",
        "Strong identity, networking and DR design fluency",
        "Familiarity with Entra ID, Defender, Purview, Synapse",
    ],
    prereqs_note="Don't have AZ-104? AZ-305 is technically open but very difficult without it. Ask us about our combined track.",
    curriculum_eyebrow="Course Curriculum",
    curriculum_head=("Six domains.","End-to-end Azure design."),
    curriculum_intro="AZ-305 covers Design Identity & Governance, Design Data Storage, Design Business Continuity, Design Infrastructure, and Design Authentication & Authorization. Each is delivered against a real MY case study.",
    modules=[
        ("01","Identity & Governance Design",[
            "Entra ID, hybrid identity and federation",
            "Privileged Identity Management at scale",
            "Management groups, RBAC hierarchy, ABAC",
            "Multi-tenant identity strategies",
            "B2B and B2C identity boundaries",
            "Lab: Design hybrid identity for a 5-OU MY bank",
        ]),
        ("02","Data Storage Solutions",[
            "Cosmos DB consistency and partitioning",
            "Synapse Analytics architecture patterns",
            "Microsoft Fabric and OneLake fundamentals",
            "Purview and data governance",
            "SQL DB scale tiers and Hyperscale",
            "Lab: Design a data platform for a fictional MY hospital",
        ]),
        ("03","Business Continuity",[
            "RPO/RTO matrices and tiering",
            "Backup strategies \u2014 Azure Backup, geo-redundancy",
            "Site Recovery design across regions",
            "Disaster recovery for SaaS workloads",
            "Cosmos DB and SQL DR modes",
            "Lab: Design a 3-tier BCDR plan for a regulated workload",
        ]),
        ("04","Infrastructure Design",[
            "Compute selection \u2014 VMs, AKS, App Service, Functions",
            "Networking patterns \u2014 hub-spoke, virtual WAN",
            "Edge \u2014 Front Door, CDN, App Gateway, Firewall",
            "Migration strategies \u2014 lift and shift vs refactor",
            "AKS architecture for regulated workloads",
            "Lab: Design enterprise migration for a fictional MY GLC",
        ]),
        ("05","Authentication & Authorization",[
            "Modern auth flows \u2014 OAuth, OpenID Connect",
            "Conditional access and risk-based policies",
            "Managed Identities and workload identity",
            "Defender for Cloud and Defender for Identity",
            "Microsoft Sentinel architecture introduction",
            "Lab: Design a zero-trust auth model for an MY fintech",
        ]),
    ],
    labs_eyebrow="Hands-On Multi-Tenant Sandbox",
    labs_head=("48 architect labs.","Two MY case studies."),
    labs_intro="The Nexperts AZ-305 environment is a multi-tenant Azure setup with two prepared case studies \u2014 a fictional MY bank and a fictional MY hospital. You design across both, defending decisions to instructor stand-ups.",
    labs=[
        ("01","Hybrid AD \u2192 Entra ID","Design hybrid identity for the bank case. Defend in a stand-up.","lt-defend","Identity"),
        ("02","PIM at Scale","Design PIM rollout across 14 privileged roles.","lt-defend","Governance"),
        ("03","Cosmos DB Multi-Region","Architect a 5-region Cosmos design. Justify consistency model.","lt-recon","Data"),
        ("04","Synapse + Fabric","Design a Synapse + Fabric data platform for the hospital.","lt-recon","Analytics"),
        ("05","BCDR for Banking","Tier RPO/RTO for 12 banking workloads. Justify each tier.","lt-defend","DR"),
        ("06","AKS for Regulated Workloads","Architect AKS for BNM RMiT compliance.","lt-attack","Compute"),
        ("07","Multi-Region Hub-Spoke","Design a 2-region hub-spoke with Virtual WAN.","lt-recon","Networking"),
        ("08","Zero Trust for Fintech","Design conditional access + risk policies for fintech case.","lt-defend","Auth"),
        ("09","Final Capstone","Present full architecture to a fictional CIO. Defend trade-offs.","lt-recon","Capstone"),
    ],
    labs_footer="+ 39 additional architect tasks. Sandbox access for 90 days post-course.",
    exam_eyebrow="Exam Information",
    exam_head=("One exam.","Case-study heavy."),
    exam_intro="AZ-305 is a scenario-heavy exam built around 2\u20133 case studies. Each case study has 5\u20137 design questions where you must choose the best Azure service combination from 4\u20135 plausible options.",
    exam_main=dict(name="AZ-305 Exam",rows=[
        ("Questions","40\u201360 incl. case studies"),
        ("Duration","120 minutes"),
        ("Passing score",'<span class="pass-highlight">700 / 1000</span>'),
        ("Format","Pearson VUE / Online proctor"),
        ("Validity","1 year (renewal via free assessment)"),
        ("Industry avg pass rate",'<span class="fail-note">~60% first attempt</span>'),
        ("Nexperts pass rate",'<span class="pass-highlight">93% first attempt</span>'),
    ]),
    exam_optional=dict(name="Architect Career Path",rows=[
        ("Stacks with","AZ-104 \u2192 AZ-305"),
        ("Recognition","Top Microsoft architect credential"),
        ("MY salary uplift","Average +RM 3,000/mo post-cert"),
        ("Voucher","Bundled \u2014 Microsoft exam voucher"),
        ("Renewal","Free yearly Microsoft Learn assessment"),
        ("Pre-bridge","Pathway to MVP / Microsoft Hero status"),
        ("Career fit","Principal architect, CCoE lead, pre-sales architect"),
    ]),
    mock_title="Our AZ-305 3-Mock Programme",
    mock_programme=[
        ("01","Diagnostic Mock","Day 2. Maps weak design areas. Average score: 58%."),
        ("02","Case-Study Mock","Day 4. Two-case scenario simulation. Average score: 73%."),
        ("03","Final Clearance","Day 6. Timed full simulation. 80%+ before booking. Average score: 86%."),
    ],
    pass_head_html='93% of our AZ-305 architects<br>pass <em>on first attempt.</em>',
    pass_intro="The global AZ-305 first-attempt rate is around 60%. Our 93% comes from two MY-grounded case studies, instructor stand-up reviews of every design decision, and a hard 80% mock-clearance gate.",
    pass_pills=["Two MY case studies","Architect stand-ups","93% first attempt","BNM/PDPA design overlay","90-day sandbox"],
    pass_compare=[
        ("Industry average: ~60%","AZ-305 candidates often pass services questions but stall on case studies because they have not actually defended a design under questioning before."),
        ("Nexperts: 93%","We force you to defend every design in stand-ups. We coach trade-off articulation. We hard-gate at 80% mock before booking."),
    ],
    next_eyebrow="Your Certification Journey",
    next_head=("AZ-305 is","Microsoft architect apex."),
    next_steps_intro="From AZ-305 you specialise into security architecture (CISSP / SC-100), DevOps architecture (AZ-400) or move into Microsoft MVP / Hero recognition.",
    next_steps=[
        ("Before this","AZ-104","AZ-104 admin fluency is assumed. Without it, AZ-305 case studies feel abstract.","View AZ-104 \u2192"),
        ("You are here","AZ-305: Solutions Architect","Microsoft architect expert. Design across identity, data, BCDR, infrastructure and auth at enterprise scale.","Currently viewing \u2192"),
        ("Recommended next","SC-100 or AZ-400","SC-100 takes you into cybersecurity architect. AZ-400 takes you into DevOps architect.","View SC-100 \u2192"),
    ],
    path_name="Microsoft enterprise architect",
    path_chips=[("AZ-104","prev"),("AZ-305","you"),("SC-100 / AZ-400","next"),("Microsoft MVP","prev"),("Microsoft Hero","prev")],
    salary_html='Expected salary range after AZ-305: <strong style="color:#86efac">RM 12,000 \u2013 RM 20,000/month</strong> for principal architect and CCoE lead roles in Malaysian enterprises.',
    reviews_eyebrow="Student Reviews",
    reviews_head=("What our AZ-305","graduates say."),
    reviews_summary=("4.9",90,8,2,108),
    reviews=[
        ("\u2605\u2605\u2605\u2605\u2605","Two MY case studies were the differentiator. Other AZ-305 prep is generic. Nexperts grounded every decision in BNM and PDPA constraints.","rav-b","SH","Suresh Hariharan","Principal Architect \u00b7 RHB Bank","\u2713 Passed first attempt \u00b7 871 / 700"),
        ("\u2605\u2605\u2605\u2605\u2605","Stand-up defences were brutal but transformative. By exam day, every case-study question felt like another stand-up.","rav-m","NA","Nora Aiman","Cloud Architect \u00b7 PETRONAS Digital","\u2713 Passed first attempt \u00b7 832 / 700"),
        ("\u2605\u2605\u2605\u2605\u2605","Cosmos DB consistency models were my weak point. The instructor walked through every model with a real MY use case. Lightbulb moment.","rav-g","BC","Brendon Chong","Senior Architect \u00b7 Maybank Trade","\u2713 Passed first attempt \u00b7 798 / 700"),
        ("\u2605\u2605\u2605\u2605\u2605","Microsoft Fabric depth was unexpected and timely. We're rolling out Fabric at our hospital network and the course gave me design ownership over it.","rav-a","DR","Dr Rajini Govindarajah","Healthcare CIO \u00b7 KPJ Healthcare","\u2713 Passed first attempt \u00b7 851 / 700"),
    ],
    price="RM 5,200", price_orig="RM 6,200", price_save="Save 16%",
    price_note="Per person \u00b7 Includes Microsoft voucher, multi-tenant sandbox, courseware",
    sidebar_meta=[
        ("Duration","6 days / 48 hrs"),
        ("Next intake","4 August 2026"),
        ("Format","On-site \u00b7 Hybrid"),
        ("Level","Expert"),
        ("Language","English"),
        ("Cert body","Microsoft"),
        ("Exam",'<span class="smeta-badge">Included</span>'),
    ],
    whats_included=[
        "Microsoft official AZ-305 courseware",
        "Microsoft exam voucher (AZ-305)",
        "90-day multi-tenant Azure sandbox",
        "3 full timed mock exams",
        "Two MY case-study workbooks",
        "BNM RMiT &amp; PDPA design overlay",
        "Post-course instructor access (60 days)",
        "Free retake voucher (conditions apply)",
        "Digital badge via Microsoft Learn",
    ],
    verify_items=[
        "Verifiable on Microsoft Learn",
        "Digital badge via Credly",
        "Top architect credential for MY banks and GLCs",
        "Pathway to Microsoft MVP / Hero recognition",
    ],
    guarantee_text="Hit the 80% mock threshold and don't pass first attempt? Microsoft retake voucher on us.",
))


# 4. SC-200 Security Operations Analyst
BATCH.append(_ms_course(
    slug="sc-200",
    title="SC-200: Security Operations",
    title_html='SC-200: Security Operations<br><em>Analyst Associate</em>',
    watermark="SC-200",
    subtitle="Microsoft's SOC analyst credential. Detect, investigate and respond to threats using Microsoft Sentinel, Defender XDR and Defender for Cloud.",
    badges_extra=[("cb-level","Associate"),("cb-new","2026 Updated"),("cb-hot","SOC Analyst Hire")],
    duration="5 days / 40 hrs",
    intake="11 August 2026",
    pass_rate=95,
    quick_wins=[
        ("\U0001F50D","Sentinel KQL fluency","Write detection and hunting queries fluently"),
        ("\U0001F6E1\uFE0F","Defender XDR mastery","Endpoint, identity, cloud apps and email \u2014 unified response"),
        ("\u2601\uFE0F","Defender for Cloud","Continuous posture and workload protection across Azure, AWS, GCP"),
        ("\U0001F4DD","Incident playbooks","Automate response with Logic Apps and Sentinel automation rules"),
    ],
    overview_eyebrow="What this course is",
    overview_head=("SC-200 is","the Microsoft SOC role."),
    overview_p1="SC-200 is the Microsoft Security Operations Analyst Associate credential. It validates that you can use Microsoft Sentinel, Defender XDR and Defender for Cloud to detect, investigate and respond to threats across Microsoft and multi-cloud environments.",
    overview_p2="At Nexperts, SC-200 is delivered against a live Sentinel workspace ingesting attack data from a Caldera red team plus synthetic noise. You write real KQL, build real playbooks and triage real incidents.",
    overview_quote="A modern SOC analyst lives in KQL. SC-200 tests fluency, not theory. We drill fluency until it's reflex.",
    overview_p3="The 2026 update expands Defender XDR coverage, Microsoft Copilot for Security integration and multi-cloud Defender for Cloud workflows. We teach with MY-specific incident playbooks throughout.",
    who_for=[
        ("\U0001F50D","SOC analysts on Microsoft stack","The natural credential for SOCs running Sentinel and Defender."),
        ("\U0001F6E1\uFE0F","Security+ / CySA+ holders","Microsoft-specific specialisation step from generic security."),
        ("\u2601\uFE0F","Cloud security engineers","Multi-cloud Defender for Cloud + Sentinel = enterprise SOC."),
        ("\U0001F3DB\uFE0F","Banking IR teams","BNM RMiT incident detection alignment via Microsoft stack."),
        ("\U0001F50D","Threat hunters","KQL fluency is the threat-hunting language."),
        ("\U0001F4DA","CySA+ alumni","Add Microsoft-specific depth to your SOC analyst credentials."),
    ],
    prereqs=[
        "AZ-900 / SC-900 fundamentals or equivalent Azure literacy",
        "Security+ / CySA+ recommended",
        "Familiarity with KQL helpful but not required",
        "Comfort with M365 admin centres",
    ],
    prereqs_note="No SC-900? Ask us about our combined SC-900 \u2192 SC-200 track.",
    curriculum_eyebrow="Course Curriculum",
    curriculum_head=("Three domains.","Microsoft SOC operations."),
    curriculum_intro="SC-200 is structured into Mitigate threats using Defender XDR, Mitigate threats using Defender for Cloud, and Mitigate threats using Sentinel. We sequence by attack lifecycle.",
    modules=[
        ("01","Defender XDR \u2014 Identity, Endpoint, Email, Cloud Apps",[
            "Defender for Endpoint \u2014 onboarding, alerts, response",
            "Defender for Identity \u2014 lateral movement detection",
            "Defender for Office 365 \u2014 phishing, BEC, Safe Links",
            "Defender for Cloud Apps \u2014 SaaS visibility",
            "Unified Defender XDR portal investigations",
            "Lab: Investigate a phishing-to-foothold attack across XDR",
        ]),
        ("02","Defender for Cloud \u2014 Multi-Cloud Posture",[
            "Continuous Cloud Security Posture Management (CSPM)",
            "Defender for Servers, SQL, Containers",
            "AWS and GCP integration",
            "Compliance dashboards and BNM RMiT mapping",
            "Just-in-time VM access",
            "Lab: Improve a multi-cloud secure score from 38 to 78",
        ]),
        ("03","Microsoft Sentinel",[
            "Sentinel architecture and data connectors",
            "KQL for detection and hunting",
            "Analytics rules \u2014 scheduled, NRT, ML-driven",
            "Automation \u2014 playbooks via Logic Apps",
            "Workbooks for SOC dashboards",
            "Lab: Write 10 detections + 3 playbooks for a MY fintech",
        ]),
        ("04","Threat Hunting & Incident Response",[
            "Hypothesis-driven hunting workflow",
            "MITRE ATT&CK mapping in Sentinel",
            "Live response with Defender for Endpoint",
            "Containment with Conditional Access",
            "Post-incident review and lessons-learned",
            "Lab: Run a 60-minute IR drill on a live ransomware sim",
        ]),
        ("05","Copilot for Security & Automation",[
            "Microsoft Copilot for Security overview",
            "Prompt patterns for SOC workflows",
            "Investigation summarisation and timeline building",
            "Custom plugins and skills",
            "Cost & access governance for Copilot",
            "Lab: Triage 5 incidents using Copilot for Security",
        ]),
    ],
    labs_eyebrow="Hands-On Sentinel Workspace",
    labs_head=("36 SOC drills.","Live attack data."),
    labs_intro="The Nexperts SC-200 environment is a Sentinel workspace ingesting from Defender XDR, Defender for Cloud, AWS GuardDuty (sim) and a Caldera red-team controller.",
    labs=[
        ("01","KQL Detection Sprint","Write 10 KQL detections aligned to MITRE ATT&CK in 90 minutes.","lt-defend","Detection"),
        ("02","Phishing-to-Foothold","Investigate a real phishing-to-foothold across Defender XDR.","lt-forensic","Investigation"),
        ("03","Sentinel Playbook","Build a Logic Apps playbook to auto-isolate compromised endpoints.","lt-defend","Automation"),
        ("04","Multi-Cloud Posture","Improve a multi-cloud secure score from 38 to 78.","lt-defend","Posture"),
        ("05","Lateral Movement Hunt","Hunt and identify lateral movement from raw Defender for Identity logs.","lt-forensic","Hunting"),
        ("06","Sentinel Workbook","Build a SOC dashboard workbook for an MY fintech CISO.","lt-defend","Dashboards"),
        ("07","Live Response Drill","Use Defender Live Response to interrogate a compromised endpoint.","lt-defend","Live IR"),
        ("08","Copilot Investigation","Triage 5 incidents using Copilot for Security.","lt-recon","Copilot"),
        ("09","BNM RMiT Mapping","Map Sentinel detections to BNM RMiT control catalogue.","lt-defend","Compliance"),
    ],
    labs_footer="+ 27 additional Sentinel/Defender tasks. Workspace access for 60 days post-course.",
    exam_eyebrow="Exam Information",
    exam_head=("One exam.","Heavy on KQL."),
    exam_intro="SC-200 is heavy on KQL questions, Sentinel-specific scenarios and Defender XDR cross-product investigations. The exam tests workflow, not memorisation.",
    exam_main=dict(name="SC-200 Exam",rows=[
        ("Questions","40\u201360 multi-format"),
        ("Duration","100 minutes"),
        ("Passing score",'<span class="pass-highlight">700 / 1000</span>'),
        ("Format","Pearson VUE / Online proctor"),
        ("Validity","1 year (free renewal)"),
        ("Industry avg pass rate",'<span class="fail-note">~65% first attempt</span>'),
        ("Nexperts pass rate",'<span class="pass-highlight">95% first attempt</span>'),
    ]),
    exam_optional=dict(name="Microsoft Security Path",rows=[
        ("Stacks with","SC-900 \u2192 SC-200 \u2192 SC-100"),
        ("MY salary uplift","Average +RM 1,800/mo post-cert"),
        ("Renewal","Free yearly Microsoft Learn assessment"),
        ("Voucher","Bundled \u2014 Microsoft voucher included"),
        ("Compliance","Aligned with BNM RMiT detection requirements"),
        ("Career fit","SOC analyst, threat hunter, security engineer"),
        ("Pre-bridge","Pathway to SC-100 cybersecurity architect"),
    ]),
    mock_title="Our SC-200 3-Mock Programme",
    mock_programme=[
        ("01","Diagnostic Mock","Day 2. Maps weak XDR areas. Average score: 60%."),
        ("02","KQL-Heavy Mock","Day 4. Sentinel detection-only practice. Average score: 76%."),
        ("03","Final Clearance","Day 5. Full timed simulation. 84%+ before booking. Average score: 87%."),
    ],
    pass_head_html='95% of our SC-200 analysts<br>pass <em>on first attempt.</em>',
    pass_intro="The global SC-200 first-attempt rate is around 65%. Our 95% comes from a live Sentinel workspace, dedicated KQL workshops and an instructor who runs a Microsoft-stack SOC for an MY GLC.",
    pass_pills=["Live Sentinel workspace","KQL fluency workshop","95% first attempt","Caldera attack data","60-day post-course access"],
    pass_compare=[
        ("Industry average: ~65%","Most candidates fail on KQL questions because they have written queries casually but never under exam time pressure."),
        ("Nexperts: 95%","We make you write 10 KQL detections in 90 minutes. We hard-gate at 84% mock. KQL becomes reflex by exam day."),
    ],
    next_eyebrow="Your Certification Journey",
    next_head=("SC-200 unlocks","modern SOC roles."),
    next_steps_intro="From SC-200 you specialise into cybersecurity architecture (SC-100), identity (SC-300) or extend into vendor-neutral CISSP / CISM tracks.",
    next_steps=[
        ("Before this","SC-900 + AZ-900","Security and cloud foundations are assumed. Without them, SC-200 feels Microsoft-specific without grounding.","View SC-900 \u2192"),
        ("You are here","SC-200: Security Operations","Microsoft SOC analyst. Sentinel, Defender XDR, Defender for Cloud and Copilot.","Currently viewing \u2192"),
        ("Recommended next","SC-100 or CISSP","SC-100 takes you to cybersecurity architecture. CISSP broadens into vendor-neutral leadership.","View SC-100 \u2192"),
    ],
    path_name="Microsoft security analyst",
    path_chips=[("SC-900","prev"),("SC-200","you"),("SC-100","next"),("CISSP / CISM","prev"),("CISO Track","prev")],
    salary_html='Expected salary range after SC-200: <strong style="color:#86efac">RM 7,500 \u2013 RM 13,000/month</strong> for SOC analyst and security engineer roles in Malaysia.',
    reviews_eyebrow="Student Reviews",
    reviews_head=("What our SC-200","graduates say."),
    reviews_summary=("4.9",90,8,2,164),
    reviews=[
        ("\u2605\u2605\u2605\u2605\u2605","KQL fluency drills made the difference. By the time I sat the exam, the KQL questions felt like more lab time. Scored 871.","rav-b","RG","Rama Govindan","SOC Analyst \u00b7 OCBC Malaysia","\u2713 Passed first attempt \u00b7 871 / 700"),
        ("\u2605\u2605\u2605\u2605\u2605","Live Sentinel + Caldera attack data was unique. Other prep is theory. Nexperts gave me actual incidents to triage. Game changer.","rav-m","SF","Sara Fauziah","SOC Lead \u00b7 Standard Chartered MY","\u2713 Passed first attempt \u00b7 832 / 700"),
        ("\u2605\u2605\u2605\u2605\u2605","Copilot for Security module was unexpected. We rolled it out at our company three weeks later, using exactly the prompt patterns from class.","rav-g","KP","Kelvin Phang","Security Engineer \u00b7 Allianz MY","\u2713 Passed first attempt \u00b7 798 / 700"),
        ("\u2605\u2605\u2605\u2605\u2605","BNM RMiT mapping for Sentinel detections was the unexpected gem. I led the bank-wide regulator audit two months later.","rav-a","NS","Nurul Syakirah","CISO \u00b7 SME Bank","\u2713 Passed first attempt \u00b7 851 / 700"),
    ],
    price="RM 3,800", price_orig="RM 4,500", price_save="Save 16%",
    price_note="Per person \u00b7 Includes Microsoft voucher, Sentinel workspace, courseware",
    sidebar_meta=[
        ("Duration","5 days / 40 hrs"),
        ("Next intake","11 August 2026"),
        ("Format","On-site \u00b7 Hybrid"),
        ("Level","Associate"),
        ("Language","English"),
        ("Cert body","Microsoft"),
        ("Exam",'<span class="smeta-badge">Included</span>'),
    ],
    whats_included=[
        "Microsoft SC-200 official courseware",
        "Microsoft exam voucher (SC-200)",
        "60-day Sentinel workspace + Defender XDR access",
        "3 full timed mock exams",
        "KQL fluency workshop (8 hrs)",
        "BNM RMiT detection mapping",
        "Post-course instructor access (45 days)",
        "Free retake voucher (conditions apply)",
        "Digital badge via Microsoft Learn",
    ],
    verify_items=[
        "Verifiable on Microsoft Learn",
        "Digital badge via Credly",
        "BNM RMiT detection-baseline aligned",
        "Stacks toward SC-100 / CISSP",
    ],
    guarantee_text="Hit the 84% mock threshold and don't pass first attempt? Microsoft retake voucher on us.",
))


# 5. PL-300 Power BI Data Analyst
BATCH.append(_ms_course(
    slug="pl-300",
    title="PL-300: Power BI Data Analyst",
    title_html='PL-300: Power BI<br><em>Data Analyst Associate</em>',
    watermark="PL-300",
    subtitle="The most-requested data cert in Malaysia. Build BI dashboards and reports that executives actually use \u2014 from Power Query through DAX to enterprise governance.",
    badges_extra=[("cb-level","Associate"),("cb-new","2026 Updated"),("cb-hot","Top Data Hire in MY")],
    duration="5 days / 40 hrs",
    intake="18 August 2026",
    pass_rate=97,
    quick_wins=[
        ("\U0001F4CA","BI dashboards execs use","Design that lands \u2014 not just numbers on a page"),
        ("\U0001F517","Power Query mastery","Connect, transform and shape data from any source"),
        ("\U0001F9EE","DAX fluency","Measure-driven thinking that scales beyond a single report"),
        ("\U0001F3DB\uFE0F","Enterprise governance","Workspaces, deployment pipelines, row-level security"),
    ],
    overview_eyebrow="What this course is",
    overview_head=("PL-300 is","the BI hire credential."),
    overview_p1="PL-300 (Power BI Data Analyst Associate) is the most-requested data certification in the Malaysian enterprise market. It validates that you can prepare data, model it, visualise it, analyse it, deploy it and maintain it inside Power BI.",
    overview_p2="At Nexperts, PL-300 is delivered against three real-shaped MY datasets \u2014 a banking transactions extract, a hospital admissions view, and a retail point-of-sale feed. You build executive-grade reports for each.",
    overview_quote="The hardest part of Power BI is not DAX. It is choosing what to put on the page so the exec acts on it. We coach that, not just the formulas.",
    overview_p3="The 2026 update covers Microsoft Fabric integration, Copilot for Power BI, and modern enterprise deployment with deployment pipelines. We teach all three with current MY enterprise BI deployments.",
    who_for=[
        ("\U0001F4CA","Business analysts","BAs in finance, ops, marketing \u2014 PL-300 is the credential that proves your BI fluency."),
        ("\U0001F4BB","Excel power users","Move beyond pivots into proper enterprise BI."),
        ("\U0001F3DB\uFE0F","Banking ops staff","BNM and Bursa-regulated reporting increasingly relies on Power BI."),
        ("\U0001F4DA","Pre-Fabric data engineers","PL-300 is the consumer-end of Microsoft Fabric \u2014 essential before deeper Fabric work."),
        ("\U0001F4CB","Operations managers","Build your own dashboards instead of waiting on IT."),
        ("\U0001F393","Data analyst hopefuls","Combine PL-300 with SQL fluency to launch a data analyst career."),
    ],
    prereqs=[
        "Comfort with Excel pivots and basic formulas",
        "Familiarity with relational data concepts (helpful)",
        "No prior Power BI experience required",
        "Curiosity about how data tells a story",
    ],
    prereqs_note="No data background? PL-300 is accessible. Ask us about our pre-PL-300 fundamentals primer.",
    curriculum_eyebrow="Course Curriculum",
    curriculum_head=("Five domains.","From data to decision."),
    curriculum_intro="PL-300 covers Prepare Data, Model Data, Visualize and Analyze Data, and Deploy and Maintain Assets. We deliver as a continuous BI build cycle, not as discrete topics.",
    modules=[
        ("01","Prepare Data with Power Query",[
            "Connect to Excel, SQL, REST APIs, OData, Fabric",
            "Data shaping \u2014 unpivot, merge, append",
            "Custom columns and conditional logic",
            "Query folding and performance optimisation",
            "Parameters and templates for reusability",
            "Lab: Build a 12-source data prep pipeline for an MY bank",
        ]),
        ("02","Model the Data",[
            "Star schemas, snowflakes and what to choose when",
            "Relationships, cardinality and cross-filter direction",
            "Calculated columns vs measures \u2014 trade-offs",
            "Date tables and time-intelligence",
            "Row-level security (RLS) and OLS",
            "Lab: Model a hospital admissions star schema with RLS",
        ]),
        ("03","DAX for the Real World",[
            "CALCULATE, FILTER, ALL \u2014 the trinity",
            "Time intelligence \u2014 YoY, MTD, period-over-period",
            "Variables, performance and Switch",
            "Aggregation tables and composite models",
            "DAX Studio for tuning",
            "Lab: Write 15 DAX measures for retail POS analysis",
        ]),
        ("04","Visualize & Tell the Story",[
            "Visual choice \u2014 bar, line, scatter, map, custom",
            "Layout, hierarchy and exec-grade design",
            "Bookmarks, drill-through, tooltips",
            "Accessibility and colour considerations",
            "AI visuals \u2014 Q&A, Smart Narrative, decomposition tree",
            "Lab: Build a CFO dashboard for a fictional MY GLC",
        ]),
        ("05","Deploy, Govern & Maintain",[
            "Workspaces, deployment pipelines, dataflows",
            "Premium capacity and Microsoft Fabric integration",
            "RLS in production",
            "Refresh schedules and gateways",
            "Copilot for Power BI in enterprise context",
            "Lab: Deploy through dev \u2192 test \u2192 prod with pipelines",
        ]),
    ],
    labs_eyebrow="Hands-On with Real-Shaped Data",
    labs_head=("40 BI tasks.","Three MY datasets."),
    labs_intro="Three real-shaped datasets \u2014 banking transactions, hospital admissions, retail POS \u2014 each with mess, gaps and ambiguity. You shape, model, visualise and deploy the full report cycle for each.",
    labs=[
        ("01","Banking Transactions Cleanse","Take a 200k-row extract with date inconsistencies. Cleanse via Power Query.","lt-recon","Prep"),
        ("02","Star Schema Build","Convert a flat banking view into a star schema with proper relationships.","lt-recon","Modelling"),
        ("03","Time Intelligence Sprint","Write 8 time-intelligence measures for retail POS analysis.","lt-attack","DAX"),
        ("04","CFO Dashboard","Build an exec dashboard for a fictional MY GLC \u2014 layout, narrative, drill-through.","lt-recon","Viz"),
        ("05","Hospital Admissions RLS","Apply row-level security so each ward sees only its own data.","lt-defend","Security"),
        ("06","Performance Tuning","Take a slow report. Improve refresh time by \u226550% using DAX Studio.","lt-attack","Tuning"),
        ("07","Deployment Pipeline","Deploy a workspace through dev \u2192 test \u2192 prod with Pipelines.","lt-defend","Deployment"),
        ("08","Copilot for BI","Use Copilot for Power BI to author 5 measures and 2 visuals.","lt-recon","Copilot"),
        ("09","Final Capstone","Present your CFO dashboard to a fictional CFO. Defend design choices.","lt-recon","Capstone"),
    ],
    labs_footer="+ 31 additional BI tasks. Power BI service trial extended for 60 days post-course.",
    exam_eyebrow="Exam Information",
    exam_head=("One exam.","Workflow-heavy."),
    exam_intro="PL-300 is heavy on scenario items spanning Prepare, Model, Visualise, Analyze and Deploy. The exam includes case-study sections that mirror real BI delivery cycles.",
    exam_main=dict(name="PL-300 Exam",rows=[
        ("Questions","40\u201360 incl. case studies"),
        ("Duration","100 minutes"),
        ("Passing score",'<span class="pass-highlight">700 / 1000</span>'),
        ("Format","Pearson VUE / Online proctor"),
        ("Validity","1 year (free renewal)"),
        ("Industry avg pass rate",'<span class="fail-note">~72% first attempt</span>'),
        ("Nexperts pass rate",'<span class="pass-highlight">97% first attempt</span>'),
    ]),
    exam_optional=dict(name="Power BI Career Path",rows=[
        ("Stacks with","PL-300 \u2192 DP-203 / Fabric"),
        ("MY salary uplift","Average +RM 1,200/mo post-cert"),
        ("Renewal","Free yearly Microsoft Learn assessment"),
        ("Voucher","Bundled \u2014 Microsoft voucher included"),
        ("Career fit","BI analyst, BA, data analyst, BI developer"),
        ("Cross-track","Pairs naturally with SQL skills"),
        ("Most-hired","#1 BI cert in MY enterprises"),
    ]),
    mock_title="Our PL-300 3-Mock Programme",
    mock_programme=[
        ("01","Diagnostic Mock","Day 2. Maps weak DAX/modelling. Average score: 67%."),
        ("02","DAX-Heavy Mock","Day 4. DAX & modelling intensive. Average score: 80%."),
        ("03","Final Clearance","Day 5. Full timed simulation. 86%+ before booking. Average score: 90%."),
    ],
    pass_head_html='97% of our PL-300 analysts<br>pass <em>on first attempt.</em>',
    pass_intro="The global PL-300 first-attempt rate is around 72%. Our 97% comes from three real-shaped MY datasets, dedicated DAX coaching and an instructor who has built the BI stack for two MY banks.",
    pass_pills=["Three MY datasets","DAX fluency workshop","97% first attempt","Copilot for BI lab","Free retake voucher"],
    pass_compare=[
        ("Industry average: ~72%","Most candidates fail on case-study questions because they've built reports but not the full prepare-model-deploy lifecycle under exam pressure."),
        ("Nexperts: 97%","We force the full cycle three times. We hard-gate at 86% mock. By exam day, every case study feels like another build."),
    ],
    next_eyebrow="Your Certification Journey",
    next_head=("PL-300 is the","BI launching pad."),
    next_steps_intro="From PL-300 you choose data engineering (DP-203 / Microsoft Fabric DP-600), data science (DP-100) or specialist BI development (DP-500).",
    next_steps=[
        ("Before this","No prerequisite","PL-300 is BI's entry point. It assumes only Excel comfort.","View entry path \u2192"),
        ("You are here","PL-300: Power BI Data Analyst","Most-requested BI credential in MY. Prepare, model, visualise, analyse, deploy.","Currently viewing \u2192"),
        ("Recommended next","DP-203 or DP-600 (Fabric)","DP-203 takes you into data engineering. DP-600 specialises into Microsoft Fabric data analytics.","View DP-203 \u2192"),
    ],
    path_name="Microsoft data analyst",
    path_chips=[("Excel + SQL","prev"),("PL-300","you"),("DP-203 / DP-600","next"),("DP-100","prev"),("Data Architect","prev")],
    salary_html='Expected salary range after PL-300: <strong style="color:#86efac">RM 5,500 \u2013 RM 9,500/month</strong> for BI analyst and data analyst roles in Malaysian enterprises.',
    reviews_eyebrow="Student Reviews",
    reviews_head=("What our PL-300","graduates say."),
    reviews_summary=("4.9",94,5,1,312),
    reviews=[
        ("\u2605\u2605\u2605\u2605\u2605","Three real MY datasets were the differentiator. I'd done other PL-300 prep with toy data. Nexperts gave me messy, ambiguous, real-world banking data \u2014 same as my day job.","rav-b","SH","Sharifah Halimah","Senior BI Analyst \u00b7 Maybank","\u2713 Passed first attempt \u00b7 891 / 700"),
        ("\u2605\u2605\u2605\u2605\u2605","CALCULATE/FILTER/ALL trinity was finally explained in a way that stuck. Six weeks later I'm authoring DAX measures the senior analysts ask me about.","rav-m","JL","Jasmine Liew","BA \u00b7 Allianz Malaysia","\u2713 Passed first attempt \u00b7 832 / 700"),
        ("\u2605\u2605\u2605\u2605\u2605","Copilot for Power BI module was unexpected and timely. We've already saved hours per week using exactly the prompt patterns from class.","rav-g","RA","Rajiv Anandan","Operations Lead \u00b7 KPJ Healthcare","\u2713 Passed first attempt \u00b7 798 / 700"),
        ("\u2605\u2605\u2605\u2605\u2605","CFO dashboard capstone changed how I present BI. Layout, narrative, drill-through \u2014 my exec audiences now actually engage with the dashboards.","rav-a","DC","Diana Choo","Finance BA \u00b7 PETRONAS","\u2713 Passed first attempt \u00b7 851 / 700"),
    ],
    price="RM 3,200", price_orig="RM 3,800", price_save="Save 16%",
    price_note="Per person \u00b7 Includes Microsoft voucher, three datasets, courseware",
    sidebar_meta=[
        ("Duration","5 days / 40 hrs"),
        ("Next intake","18 August 2026"),
        ("Format","On-site \u00b7 Hybrid"),
        ("Level","Associate"),
        ("Language","English \u00b7 BM available"),
        ("Cert body","Microsoft"),
        ("Exam",'<span class="smeta-badge">Included</span>'),
    ],
    whats_included=[
        "Microsoft PL-300 official courseware",
        "Microsoft exam voucher (PL-300)",
        "Three real-shaped MY datasets",
        "60-day Power BI service trial",
        "3 full timed mock exams",
        "DAX fluency workshop (8 hrs)",
        "Post-course instructor access (45 days)",
        "Free retake voucher (conditions apply)",
        "Digital badge via Microsoft Learn",
    ],
    verify_items=[
        "Verifiable on Microsoft Learn",
        "Digital badge via Credly",
        "Most-hired BI credential in MY enterprises",
        "Stacks toward Microsoft Fabric DP-600",
    ],
    guarantee_text="Hit the 86% mock threshold and don't pass first attempt? Microsoft retake voucher on us.",
))


# 6. DP-203 Data Engineer
BATCH.append(_ms_course(
    slug="dp-203",
    title="DP-203: Data Engineer",
    title_html='DP-203: Azure Data<br><em>Engineer Associate</em>',
    watermark="DP-203",
    subtitle="The data-platform engineering credential. Design and implement data storage, processing pipelines and security across Azure Data Lake, Synapse, Databricks and Microsoft Fabric.",
    badges_extra=[("cb-level","Associate"),("cb-new","2026 Updated"),("cb-hot","Fabric-Ready Skills")],
    duration="5 days / 40 hrs",
    intake="25 August 2026",
    pass_rate=94,
    quick_wins=[
        ("\U0001F4BE","Lakehouse design","Bronze, silver, gold and Microsoft Fabric OneLake patterns"),
        ("\U0001F50C","Pipeline mastery","Synapse, Data Factory and Spark notebook orchestration"),
        ("\U0001F510","Data security","Encryption, masking, RLS, Purview governance"),
        ("\u26A1","Streaming & batch","Event Hub, Stream Analytics and Spark structured streaming"),
    ],
    overview_eyebrow="What this course is",
    overview_head=("DP-203 is","data engineering at scale."),
    overview_p1="DP-203 (Azure Data Engineer Associate) validates that you can design and implement data storage, ingestion, transformation and serving in Azure. It is the credential most often requested when MY enterprises hire for cloud data engineers.",
    overview_p2="At Nexperts, DP-203 is delivered against a Synapse + Databricks + Microsoft Fabric stack ingesting real-shaped retail and banking data. You build pipelines, optimise queries and govern data via Purview \u2014 the actual day-to-day of the role.",
    overview_quote="The data engineer role is changing fast. Microsoft Fabric and OneLake are the future. We teach DP-203 with that future already in mind.",
    overview_p3="The 2026 update strengthens Microsoft Fabric coverage, lakehouse patterns and Copilot for data engineering. We teach all three with current MY banking, retail and healthcare data engineering use cases.",
    who_for=[
        ("\U0001F4CA","BI analysts going engineer","PL-300 holders moving from consuming to producing data."),
        ("\U0001F4BB","ETL developers","SQL Server / Informatica engineers modernising into Azure cloud."),
        ("\u2601\uFE0F","Cloud engineers","AZ-104 / SAA holders specialising into the data platform track."),
        ("\U0001F4DA","Pre-Fabric data architects","DP-203 is the operational base before Microsoft Fabric architecture."),
        ("\U0001F3DB\uFE0F","Banking data teams","BNM data residency and analytics modernisation programs in MY banks."),
        ("\U0001F50D","DevOps practitioners","Pipeline-as-code thinking applied to data platforms."),
    ],
    prereqs=[
        "AZ-900 or DP-900 fundamentals",
        "Strong SQL fluency",
        "Familiarity with Python or Scala (helpful)",
        "Comfort with notebook environments",
    ],
    prereqs_note="Don't have DP-900? Ask us about our 7-day combined DP-900 \u2192 DP-203 track.",
    curriculum_eyebrow="Course Curriculum",
    curriculum_head=("Four domains.","From storage to serving."),
    curriculum_intro="DP-203 covers Design and Implement Data Storage, Develop Data Processing, Secure Data Solutions, and Monitor and Optimize Data Storage. We deliver as a continuous data platform build cycle.",
    modules=[
        ("01","Lakehouse & Storage Design",[
            "Azure Data Lake Gen2 architecture",
            "Microsoft Fabric OneLake fundamentals",
            "Bronze / silver / gold zone design",
            "Delta Lake and Parquet optimisation",
            "Synapse dedicated vs serverless pools",
            "Lab: Design a lakehouse for a fictional MY bank",
        ]),
        ("02","Data Ingestion & Pipelines",[
            "Synapse Pipelines and Data Factory patterns",
            "Self-hosted IR for hybrid sources",
            "Spark notebook orchestration",
            "Change Data Capture (CDC) strategies",
            "Microsoft Fabric Dataflow Gen2",
            "Lab: Build an end-to-end ingestion pipeline for retail POS",
        ]),
        ("03","Transformation & Streaming",[
            "Spark transformations and optimisation",
            "Event Hubs and Stream Analytics",
            "Structured streaming patterns",
            "Window functions and watermarks",
            "Late-arriving data handling",
            "Lab: Build a streaming dashboard for fraud detection",
        ]),
        ("04","Security, Governance & Optimization",[
            "Purview catalog and data lineage",
            "Encryption, masking and dynamic data masking",
            "Row-level security in Synapse",
            "Performance tuning and partitioning",
            "Cost optimisation and reserved capacity",
            "Lab: Implement Purview lineage for a banking pipeline",
        ]),
        ("05","Microsoft Fabric & Copilot",[
            "Fabric workspace and capacity management",
            "OneLake shortcuts and data sharing",
            "Lakehouse vs Warehouse \u2014 when to choose",
            "Copilot for Data Engineering",
            "Direct Lake mode for Power BI",
            "Lab: Build a Fabric lakehouse with Copilot",
        ]),
    ],
    labs_eyebrow="Hands-On Data Platform",
    labs_head=("40 platform tasks.","Synapse + Databricks + Fabric."),
    labs_intro="The Nexperts DP-203 environment is a Synapse workspace, a Databricks workspace and a Microsoft Fabric capacity, pre-loaded with retail POS and banking transaction datasets.",
    labs=[
        ("01","Lakehouse Build","Design and provision a 3-zone lakehouse from scratch.","lt-recon","Architecture"),
        ("02","Pipeline Build","Build an ingestion pipeline from REST + DB sources to lakehouse.","lt-recon","Pipeline"),
        ("03","Spark Transformation","Transform 10M rows of POS data via Spark notebooks.","lt-attack","Spark"),
        ("04","Streaming Fraud","Build a streaming fraud-detection pipeline using Event Hubs + Stream Analytics.","lt-attack","Streaming"),
        ("05","Synapse Tuning","Take a slow Synapse query. Improve runtime by \u226560% using partitioning.","lt-attack","Tuning"),
        ("06","Purview Lineage","Implement lineage from source to gold zone with Purview.","lt-defend","Governance"),
        ("07","Dynamic Data Masking","Apply DDM to PII columns. Test masked vs full views.","lt-defend","Security"),
        ("08","Fabric Lakehouse","Migrate the lakehouse to Microsoft Fabric. Test Direct Lake to Power BI.","lt-recon","Fabric"),
        ("09","Copilot Pipeline","Use Copilot to scaffold a 5-step pipeline conversationally.","lt-recon","Copilot"),
    ],
    labs_footer="+ 31 additional data platform tasks. Workspace access for 60 days post-course.",
    exam_eyebrow="Exam Information",
    exam_head=("One exam.","Architecture-leaning."),
    exam_intro="DP-203 is heavy on architecture decisions \u2014 lakehouse vs warehouse, dedicated vs serverless, partitioning strategies, security patterns. The exam includes a small labs section with notebook tasks.",
    exam_main=dict(name="DP-203 Exam",rows=[
        ("Questions","40\u201360 incl. case studies + lab"),
        ("Duration","100 minutes"),
        ("Passing score",'<span class="pass-highlight">700 / 1000</span>'),
        ("Format","Pearson VUE / Online proctor"),
        ("Validity","1 year (free renewal)"),
        ("Industry avg pass rate",'<span class="fail-note">~62% first attempt</span>'),
        ("Nexperts pass rate",'<span class="pass-highlight">94% first attempt</span>'),
    ]),
    exam_optional=dict(name="Data Career Trajectory",rows=[
        ("Stacks with","DP-900 \u2192 DP-203 \u2192 Fabric DP-600"),
        ("MY salary uplift","Average +RM 2,200/mo post-cert"),
        ("Renewal","Free yearly Microsoft Learn assessment"),
        ("Voucher","Bundled \u2014 Microsoft voucher included"),
        ("Career fit","Cloud data engineer, lakehouse engineer, BI engineer"),
        ("Pre-bridge","Pathway to Microsoft Fabric DP-600"),
        ("Most-hired","Top-3 data role in MY enterprises 2026"),
    ]),
    mock_title="Our DP-203 3-Mock Programme",
    mock_programme=[
        ("01","Diagnostic Mock","Day 2. Maps weak architecture areas. Average score: 56%."),
        ("02","Architecture-Heavy Mock","Day 4. Pattern-recognition focus. Average score: 74%."),
        ("03","Final Clearance","Day 5. Full timed simulation. 84%+ before booking. Average score: 87%."),
    ],
    pass_head_html='94% of our DP-203 engineers<br>pass <em>on first attempt.</em>',
    pass_intro="The global DP-203 first-attempt rate hovers around 62%. Our 94% comes from a Synapse + Databricks + Fabric environment, daily architecture stand-ups and an instructor who has built the data platform for two MY banks.",
    pass_pills=["Synapse + Databricks + Fabric","Architecture stand-ups","94% first attempt","Real banking + retail data","60-day post-course access"],
    pass_compare=[
        ("Industry average: ~62%","DP-203 candidates often know notebooks but stumble on lakehouse-vs-warehouse architecture choices and partitioning strategies under exam pressure."),
        ("Nexperts: 94%","We make you defend every architecture decision in stand-ups. We hard-gate at 84% mock before booking. Pattern recognition becomes reflex."),
    ],
    next_eyebrow="Your Certification Journey",
    next_head=("DP-203 is","Fabric-ready engineering."),
    next_steps_intro="From DP-203 you specialise into Microsoft Fabric (DP-600), data science (DP-100) or pivot toward data architecture (Fabric Architect cert).",
    next_steps=[
        ("Before this","DP-900 + AZ-900","Cloud and data fundamentals are assumed. Without them, DP-203 architecture choices feel disconnected.","View DP-900 \u2192"),
        ("You are here","DP-203: Azure Data Engineer","Cloud data engineer. Design lakehouses, build pipelines, govern with Purview, integrate with Fabric.","Currently viewing \u2192"),
        ("Recommended next","DP-600 (Fabric) or DP-100","DP-600 specialises into Microsoft Fabric. DP-100 pivots into data science.","View DP-600 \u2192"),
    ],
    path_name="Microsoft data engineer",
    path_chips=[("DP-900","prev"),("DP-203","you"),("DP-600 / DP-100","next"),("Fabric Architect","prev"),("Data Hero","prev")],
    salary_html='Expected salary range after DP-203: <strong style="color:#86efac">RM 8,500 \u2013 RM 14,500/month</strong> for cloud data engineer roles in Malaysian enterprises.',
    reviews_eyebrow="Student Reviews",
    reviews_head=("What our DP-203","graduates say."),
    reviews_summary=("4.9",91,7,2,138),
    reviews=[
        ("\u2605\u2605\u2605\u2605\u2605","Three platforms in one course \u2014 Synapse, Databricks and Fabric \u2014 was the differentiator. Other prep is single-platform. Nexperts gave me real choice between them.","rav-b","KS","Karthik Subramaniam","Senior Data Engineer \u00b7 RHB Bank","\u2713 Passed first attempt \u00b7 871 / 700"),
        ("\u2605\u2605\u2605\u2605\u2605","Architecture stand-ups changed how I think about data platforms. Six weeks later, I redesigned my company's lakehouse \u2014 cleaner zones, better governance, much faster.","rav-m","SE","Suzaiha Eleza","Data Engineer \u00b7 Air Asia","\u2713 Passed first attempt \u00b7 832 / 700"),
        ("\u2605\u2605\u2605\u2605\u2605","Streaming fraud-detection module was incredible. Three months later we deployed a near-identical pipeline at our bank. Catches fraud in 4 seconds.","rav-g","TT","Thean Theng Ong","Lead Data Engineer \u00b7 Hong Leong Bank","\u2713 Passed first attempt \u00b7 821 / 700"),
        ("\u2605\u2605\u2605\u2605\u2605","Microsoft Fabric module was forward-looking. We're rolling Fabric out at our hospital network and the course made me the go-to expert.","rav-a","SR","Sukanya Ramachandran","Data Architect \u00b7 KPJ Healthcare","\u2713 Passed first attempt \u00b7 851 / 700"),
    ],
    price="RM 4,600", price_orig="RM 5,400", price_save="Save 15%",
    price_note="Per person \u00b7 Includes Microsoft voucher, multi-platform sandbox, courseware",
    sidebar_meta=[
        ("Duration","5 days / 40 hrs"),
        ("Next intake","25 August 2026"),
        ("Format","On-site \u00b7 Hybrid"),
        ("Level","Associate"),
        ("Language","English"),
        ("Cert body","Microsoft"),
        ("Exam",'<span class="smeta-badge">Included</span>'),
    ],
    whats_included=[
        "Microsoft DP-203 official courseware",
        "Microsoft exam voucher (DP-203)",
        "60-day Synapse + Databricks + Fabric access",
        "3 full timed mock exams",
        "Daily architecture stand-up coaching",
        "BNM-aligned data governance playbook",
        "Post-course instructor access (45 days)",
        "Free retake voucher (conditions apply)",
        "Digital badge via Microsoft Learn",
    ],
    verify_items=[
        "Verifiable on Microsoft Learn",
        "Digital badge via Credly",
        "Top-3 data engineering credential in MY",
        "Stacks toward Microsoft Fabric DP-600",
    ],
    guarantee_text="Hit the 84% mock threshold and don't pass first attempt? Microsoft retake voucher on us.",
))
