# -*- coding: utf-8 -*-
"""CompTIA course data (5 courses: A+, Network+, Security+, CySA+, PenTest+)."""
from _course_data import HERO_IMG, common_meta

BATCH = []

# 1. CompTIA A+
BATCH.append(dict(
    slug="comptia-a-plus",
    title="CompTIA A+",
    title_html='CompTIA A+<br><em>Core 1 &amp; Core 2</em>',
    vendor_short="CompTIA", watermark="A+", crumb_vendor="CompTIA",
    subtitle="The most trusted entry credential into IT. Hardware, operating systems, networking, virtualisation, mobile and security \u2014 the foundation every IT career builds on.",
    badges=[("cb-vendor","CompTIA Authorized"),("cb-level","Foundation \u00b7 Entry"),("cb-new","2026 Objectives"),("cb-hot","Most Hired Entry Cert")],
    hero_meta=common_meta("6 days / 48 hrs","Instructor-Led + Lab Kits","On-site \u00b7 Virtual \u00b7 Hybrid",96,"5 May 2026"),
    hero_img=HERO_IMG,
    quick_wins=[
        ("\U0001F527","Hardware mastery","Build, repair and diagnose desktops, laptops and mobile devices"),
        ("\U0001F4BB","Multi-OS proficiency","Windows 11, macOS, Linux, iOS and Android \u2014 installs and support"),
        ("\U0001F310","Networking & cloud basics","TCP/IP, wireless, virtualisation and SaaS troubleshooting"),
        ("\U0001F6E1\uFE0F","Security fundamentals","Endpoint protection, identity, malware response and best practices"),
    ],
    overview_eyebrow="What this course is",
    overview_head=("Every IT career","starts with A+."),
    overview_p1="CompTIA A+ is the world's most recognised starting credential for technology support roles. It validates that you can install, configure, troubleshoot and support hardware, software, mobile devices and networks across Windows, macOS and Linux.",
    overview_p2="At Nexperts Academy, A+ isn't a slide-led grind. We run real teardowns of desktops and laptops, real network troubleshooting on a live lab, and walk you through the same support tickets we see graduates solve in their first month at MNCs in Cyberjaya and KL.",
    overview_quote="A+ is not just a cert. It is the only one that proves you can sit in front of a broken machine and fix it before lunch.",
    overview_p3="The 2026 update of A+ (Core 1 220-1101 and Core 2 220-1102) adds modern troubleshooting for cloud-managed endpoints, zero-trust identity flows, and the Windows 11 administrative model. You finish able to walk into any L1 or L2 support role and be productive on day one.",
    who_for=[
        ("\U0001F468\u200D\U0001F4BB","School & college leavers","Looking for a structured first step into IT \u2014 A+ is what hiring managers screen for."),
        ("\U0001F504","Career switchers","Coming from non-IT backgrounds. A+ gives you the language, the hardware fluency and the credibility."),
        ("\U0001F6E0\uFE0F","Helpdesk staff","Already doing the work without certification \u2014 A+ formalises and grows the salary band."),
        ("\U0001F3E2","Corporate IT teams","Standardise baseline knowledge across distributed support staff."),
        ("\U0001F393","Diploma students","TVET, polytechnic and ICT students wanting an industry-recognised credential."),
        ("\U0001F30F","Aspiring expat IT staff","A+ is recognised across the Gulf, ANZ, UK and the wider commonwealth."),
    ],
    prereqs=[
        "Basic computer literacy \u2014 using Windows or macOS daily",
        "Comfort installing software and using a browser",
        "Willingness to handle physical hardware in lab sessions",
        "Curiosity \u2014 that's the only real prerequisite",
    ],
    prereqs_note="No prior IT certification required. This is the start of the path.",
    curriculum_eyebrow="Course Curriculum",
    curriculum_head=("Two exams.","One foundation."),
    curriculum_intro="A+ is delivered as Core 1 (Hardware, Networking, Mobile, Cloud, Troubleshooting) and Core 2 (OS, Security, Software, Operational Procedures). We teach them as one continuous story.",
    modules=[
        ("01","Mobile Devices, Hardware & Networking",[
            "Laptops, mobile and wearable hardware components",
            "Networking fundamentals \u2014 TCP/IP, ports and protocols",
            "Wireless standards \u2014 802.11, Bluetooth, NFC",
            "SOHO router configuration and security",
            "Cable types, connectors and RJ45 termination",
            "Lab: Build and configure a small office network",
        ]),
        ("02","Hardware Components & Storage",[
            "RAM types, motherboards and CPUs",
            "Power supplies and PSU troubleshooting",
            "SATA, NVMe and storage technologies",
            "GPU, sound and expansion cards",
            "Printer technologies and shared printing",
            "Lab: Full desktop teardown and rebuild",
        ]),
        ("03","Virtualisation & Cloud Computing",[
            "Cloud concepts \u2014 IaaS, PaaS, SaaS",
            "Public, private, hybrid and community clouds",
            "Virtual desktop infrastructure (VDI)",
            "Hypervisors \u2014 Hyper-V, VirtualBox, ESXi",
            "Cloud-managed endpoints \u2014 Intune fundamentals",
            "Lab: Deploy a VM and a containerised app",
        ]),
        ("04","Operating Systems \u2014 Windows \u00b7 macOS \u00b7 Linux",[
            "Windows 10/11 install, configuration and tuning",
            "Active Directory and Group Policy basics",
            "PowerShell and CMD essential commands",
            "macOS administration and Time Machine",
            "Linux command-line fundamentals",
            "Lab: Multi-OS troubleshooting under time pressure",
        ]),
        ("05","Security, Software Troubleshooting & Operations",[
            "Malware detection, removal and prevention",
            "Authentication, MFA and password policy",
            "Social engineering recognition and response",
            "Software troubleshooting workflow",
            "Documentation, change management and backups",
            "Lab: End-to-end ransomware response simulation",
        ]),
    ],
    labs_eyebrow="Hands-On Lab Kits",
    labs_head=("48 lab tasks.","Real hardware. Real OS."),
    labs_intro="Every learner gets a Nexperts lab kit \u2014 a real motherboard, RAM modules, NVMe drive, and a 4-port switch. You don't simulate hardware support. You do hardware support.",
    labs=[
        ("01","Build a PC from Components","Receive a parts kit. Assemble, install Windows 11 and bring it onto a working network \u2014 graded on time and stability.","lt-recon","Hardware"),
        ("02","Diagnose & Replace a Failing PSU","Walk through a failure scenario. Identify the bad component using only a multimeter, system logs and process of elimination.","lt-defend","Diagnostics"),
        ("03","Wireless SOHO Network Configuration","Configure a small office wireless network with VLANs, guest access and WPA3 encryption.","lt-recon","Networking"),
        ("04","Multi-Boot Workstation Build","Install Windows 11, Ubuntu Linux and recover a macOS image \u2014 manage three OSes on one workstation.","lt-attack","OS Install"),
        ("05","Endpoint Hardening Sprint","Take a fresh Windows install. Within 60 minutes, apply CIS-aligned hardening using Group Policy and PowerShell.","lt-defend","Security"),
        ("06","Active Directory Joiner-Mover-Leaver","Run the full identity lifecycle for a fictional user \u2014 onboard, transfer, decommission. Document every step.","lt-attack","Identity"),
        ("07","Cloud Endpoint Enrolment","Enrol a Windows endpoint into Microsoft Intune. Push policy. Wipe remotely. Re-enrol.","lt-recon","Cloud Mgmt"),
        ("08","Malware Triage Drill","A user reports their machine is slow. Identify the malware family, contain, remediate and write the user-friendly summary.","lt-defend","Defence"),
        ("09","Live Helpdesk Tickets","20 real tickets. 90 minutes. Triage, resolve and close them. Graded on resolution rate and ticket hygiene.","lt-forensic","Support Ops"),
    ],
    labs_footer="+ 39 additional micro-tasks across hardware, networking, security and operations. Lab kits are yours to keep.",
    exam_eyebrow="Exam Information",
    exam_head=("Two exams.","Both required."),
    exam_intro="A+ requires passing both Core 1 (220-1101) and Core 2 (220-1102). Most candidates take them within 30 days of each other. Nexperts bundles both vouchers and runs separate mock cycles for each Core.",
    exam_main=dict(name="Core 1 (220-1101) Exam",rows=[
        ("Questions","Up to 90 (MC + performance based)"),
        ("Duration","90 minutes"),
        ("Passing score",'<span class="pass-highlight">675 / 900</span>'),
        ("Format","Pearson VUE / Online"),
        ("Validity","3 years (CE renewal)"),
        ("Industry avg pass rate",'<span class="fail-note">~71% first attempt</span>'),
        ("Nexperts pass rate",'<span class="pass-highlight">96% first attempt</span>'),
    ]),
    exam_optional=dict(name="Core 2 (220-1102) Exam",rows=[
        ("Questions","Up to 90 (MC + performance based)"),
        ("Duration","90 minutes"),
        ("Passing score",'<span class="pass-highlight">700 / 900</span>'),
        ("Both required","Yes \u2014 A+ awarded only on passing both"),
        ("Best practice","Take Core 1, then Core 2 within 30 days"),
        ("Voucher pack","Bundled \u2014 both exams included"),
        ("Renewal","CompTIA CE \u2014 20 CEUs in 3 years"),
    ]),
    mock_title="Our Dual-Mock Programme",
    mock_programme=[
        ("01","Diagnostic \u2014 Core 1","Taken end of week 1. Highlights weak areas across hardware and networking. Average score: 64%."),
        ("02","Targeted Mock \u2014 Core 2","Focus on OS and security. Each wrong answer reviewed in a 90-minute walkthrough. Average score: 79%."),
        ("03","Final Clearance","Two full exams back to back under timed conditions. 80%+ before we book. Average score: 87%."),
    ],
    pass_rate=96,
    pass_head_html='96% of our A+ students<br>pass <em>both exams.</em>',
    pass_intro="The combined first-attempt rate for A+ Core 1 + Core 2 sits around 71% globally. We deliver 96% \u2014 driven by hands-on lab kits, dual-mock exams for both Cores, and an instructor who has supported MNC desktops in Cyberjaya for over 12 years.",
    pass_pills=["Lab kit included","Dual mock exams","96% combined pass","Voucher bundle saves 12%","Free retake on either Core"],
    pass_compare=[
        ("Industry average: ~71%","Most candidates pass Core 1 but stumble on Core 2 because they treat it as 'just OS'. They underestimate Operational Procedures and security."),
        ("Nexperts: 96%","We schedule both exams within 30 days. We hard-gate on a clearance mock. And we cover OPs, security and documentation as if they were technical domains \u2014 because they are."),
    ],
    next_eyebrow="Your Certification Journey",
    next_head=("A+ is the entry.","Choose your direction."),
    next_steps_intro="A+ is the foundation. From here you specialise \u2014 networking with Network+, security with Security+, or jump straight into a vendor track like Microsoft AZ-900 or AWS Cloud Practitioner.",
    next_steps=[
        ("Before this","No prerequisite","A+ is the starting credential. If you can use a computer, you can take A+. We provide the rest.","View entry path \u2192"),
        ("You are here","CompTIA A+","Foundational hands-on IT support credential. You can install, troubleshoot and secure devices across Windows, macOS, Linux, iOS and Android.","Currently viewing \u2192"),
        ("Recommended next","Network+ or Security+","Networking specialisation or security foundation. Both build directly on A+ and unlock specialised IT roles.","View Network+ \u2192"),
    ],
    path_name="IT support \u2192 infrastructure",
    path_chips=[("ICT Diploma","prev"),("CompTIA A+","you"),("Network+","next"),("Security+","prev"),("AZ-104 / AWS SAA","prev")],
    salary_html='Expected salary range after A+: <strong style="color:#86efac">RM 2,800 \u2013 RM 4,500/month</strong> for L1/L2 IT support roles in the Klang Valley.',
    reviews_eyebrow="Student Reviews",
    reviews_head=("What our A+","graduates say."),
    reviews_summary=("4.8",86,12,2,198),
    reviews=[
        ("\u2605\u2605\u2605\u2605\u2605","Walked into the course with zero IT background. Six weeks later, I'd passed both Cores and accepted a helpdesk offer at Maxis. The lab kit drills made the performance-based questions feel routine.","rav-b","AS","Aisyah Sulaiman","Service Desk Analyst \u00b7 Maxis","\u2713 Passed both Cores \u00b7 762 / 720"),
        ("\u2605\u2605\u2605\u2605\u2605","I'd been doing helpdesk informally at my company for three years without certification. A+ formalised everything I'd been doing and I got a 22% salary bump within two months of certification.","rav-m","JT","Jeevan Thanggavelu","IT Support Lead \u00b7 Sime Darby","\u2713 Passed first attempt"),
        ("\u2605\u2605\u2605\u2605","The lab kit alone is worth the course fee. I built and rebuilt that PC about a dozen times. By the time I sat the performance-based items, nothing was unfamiliar.","rav-g","MN","Marsha Ng","Junior IT Officer \u00b7 KPMG Malaysia","\u2713 Passed both Cores \u00b7 840 / 768"),
        ("\u2605\u2605\u2605\u2605\u2605","The instructor explained Active Directory in 20 minutes better than two semesters of college had. The way he linked theory to a real ticket I'd see on Monday morning made every concept stick.","rav-a","RH","Ridhwan Hakim","Desktop Support \u00b7 Petronas ICT","\u2713 Passed first attempt \u00b7 815 / 745"),
    ],
    price="RM 2,800", price_orig="RM 3,400", price_save="Save 18%",
    price_note="Per person \u00b7 Includes both exam vouchers, lab kit, courseware",
    sidebar_meta=[
        ("Duration","6 days / 48 hrs"),
        ("Next intake","5 May 2026"),
        ("Format","On-site \u00b7 Hybrid"),
        ("Level","Foundation"),
        ("Language","English \u00b7 BM available"),
        ("Cert body","CompTIA"),
        ("Exam",'<span class="smeta-badge">Bundled x2</span>'),
    ],
    whats_included=[
        "CompTIA official courseware (digital + PDF)",
        "Pearson VUE vouchers \u2014 both Core 1 &amp; Core 2",
        "Nexperts hardware lab kit (yours to keep)",
        "2 full timed mock exams per Core",
        "Mock review sessions with instructor",
        "Performance-based question coaching",
        "Post-course instructor access (30 days)",
        "Free single retake on either Core",
        "Digital badge via CompTIA Marketplace",
    ],
    verify_items=[
        "Verifiable on CompTIA Marketplace",
        "Digital badge via Credly",
        "ANSI / ISO 17024 accredited",
        "LinkedIn certificate integration",
    ],
    guarantee_text="Follow our programme and don't pass either Core? We cover one retake voucher. No fine print.",
))

# 2. CompTIA Network+
BATCH.append(dict(
    slug="comptia-network-plus",
    title="CompTIA Network+",
    title_html='CompTIA Network+<br><em>N10-009</em>',
    vendor_short="CompTIA", watermark="N+", crumb_vendor="CompTIA",
    subtitle="The vendor-neutral networking credential. OSI, IP, routing, switching, wireless, virtualisation and network security \u2014 the language of every enterprise IT environment.",
    badges=[("cb-vendor","CompTIA Authorized"),("cb-level","Foundation \u00b7 Intermediate"),("cb-new","N10-009 \u00b7 2026"),("cb-hot","Pre-CCNA Favourite")],
    hero_meta=common_meta("5 days / 40 hrs","Instructor-Led + Cisco Sims","On-site \u00b7 Virtual \u00b7 Hybrid",96,"19 May 2026"),
    hero_img=HERO_IMG,
    quick_wins=[
        ("\U0001F310","Master OSI & TCP/IP","Apply the seven-layer model to real troubleshooting workflows"),
        ("\U0001F4E1","Wireless & SD-WAN","Modern wireless, MIMO, beamforming and SD-WAN essentials"),
        ("\U0001F512","Network security baked in","Zero trust, NAC, IDS/IPS, secure VPN \u2014 the 2026 N10-009 priority"),
        ("\U0001F6E0\uFE0F","Vendor-agnostic skills","Skills carry across Cisco, HPE, Aruba, MikroTik, Juniper environments"),
    ],
    overview_eyebrow="What this course is",
    overview_head=("Networking is","the nervous system of IT."),
    overview_p1="Network+ proves you can design, configure and troubleshoot wired and wireless networks regardless of vendor. It's the credential most often paired with A+ to step into real network and infrastructure roles.",
    overview_p2="At Nexperts, Network+ is taught in front of an actual rack \u2014 Cisco switches, Aruba access points, a pfSense firewall and a Juniper edge router. You learn the protocol fundamentals on the whiteboard, then walk over to the rack and prove them.",
    overview_quote="You cannot troubleshoot networks from a slide deck. You troubleshoot them from a console, a packet capture and a clear head.",
    overview_p3="The N10-009 update doubles down on cloud-edge networking, SD-WAN, IPv6 and zero-trust segmentation \u2014 the things you'll actually configure in your first network role.",
    who_for=[
        ("\U0001F4E1","A+ holders","The natural next step. A+ taught you the device. Network+ teaches you how devices talk."),
        ("\U0001F6E1\uFE0F","Aspiring SOC analysts","Almost every SOC alert traces back to a network event. Network+ gives you the literacy to read them."),
        ("\u2601\uFE0F","Junior cloud engineers","VPCs, subnets, route tables \u2014 cloud networking is networking. Get the foundations right first."),
        ("\U0001F527","NOC / desktop staff","Move out of L1 by demonstrating you understand the wire, not just the device."),
        ("\U0001F4DA","Pre-CCNA learners","Network+ is the gentlest lead-in to CCNA. Vendor-neutral first, Cisco-specific later."),
        ("\U0001F3E2","Corporate IT generalists","Sysadmins, helpdesk leads \u2014 Network+ broadens your toolkit and makes you a better escalation."),
    ],
    prereqs=[
        "CompTIA A+ or equivalent foundational IT knowledge",
        "Comfortable with Windows command line basics",
        "Understanding of IP addressing at a conceptual level",
        "9\u201312 months of general IT experience recommended",
    ],
    prereqs_note="Don't have A+? Ask us about our A+ \u2192 Network+ pathway bundle.",
    curriculum_eyebrow="Course Curriculum",
    curriculum_head=("Five domains.","Every layer of the stack."),
    curriculum_intro="N10-009 is organised into five domains \u2014 Networking Fundamentals, Implementations, Operations, Security and Troubleshooting. We deliver them in the order you'll actually use them on the job.",
    modules=[
        ("01","Networking Fundamentals",[
            "OSI and TCP/IP models \u2014 practical mapping",
            "IPv4 and IPv6 addressing and subnetting",
            "Ports, protocols and common services",
            "Network topologies and architectures",
            "Cable standards \u2014 Cat6A, fibre, MPO/MTP",
            "Lab: Subnet a /16 into 256 useable /24s",
        ]),
        ("02","Network Implementations",[
            "Switch configuration \u2014 VLANs, trunks, STP",
            "Router configuration \u2014 static and dynamic routing",
            "OSPF, EIGRP and BGP fundamentals",
            "Wireless \u2014 802.11ax, controller-based deployment",
            "Network access control (NAC) and 802.1X",
            "Lab: Build a multi-VLAN office on a real switch stack",
        ]),
        ("03","Network Operations",[
            "Documentation \u2014 diagrams, IP plans, runbooks",
            "Change management and maintenance windows",
            "SNMP, syslog and centralised monitoring",
            "Performance metrics \u2014 latency, jitter, packet loss",
            "QoS markings \u2014 DSCP, CoS, queueing",
            "Lab: Build a monitoring stack with Zabbix",
        ]),
        ("04","Network Security",[
            "Common attacks \u2014 DDoS, ARP spoofing, VLAN hopping",
            "Firewalls \u2014 stateful, NGFW, IPS/IDS",
            "VPN technologies \u2014 IPsec, SSL, WireGuard",
            "Zero trust networking principles",
            "Network segmentation and microsegmentation",
            "Lab: Implement a zero-trust segment with NGFW + 802.1X",
        ]),
        ("05","Network Troubleshooting",[
            "Structured troubleshooting methodology",
            "Layer-by-layer fault isolation",
            "Tools \u2014 ping, traceroute, tcpdump, Wireshark",
            "Cable certification and continuity testing",
            "Common scenarios \u2014 slow apps, intermittent loss",
            "Lab: 60-minute fault isolation under timed pressure",
        ]),
    ],
    labs_eyebrow="Hands-On Lab Stack",
    labs_head=("40+ labs.","On a real rack."),
    labs_intro="The Nexperts Network+ rack is two Cisco Catalyst switches, a pair of Cisco ISR routers, an Aruba controller with three APs, a pfSense firewall and a Linux jumphost.",
    labs=[
        ("01","Subnet Design Sprint","Receive a network spec. Design IP, VLAN and routing in 45 minutes.","lt-recon","Design"),
        ("02","Multi-VLAN Switching","Configure 4 VLANs across two switches with trunking and inter-VLAN routing.","lt-attack","Switching"),
        ("03","OSPF Multi-Area Lab","Build a 3-area OSPF topology. Tune metrics. Force convergence under failure.","lt-attack","Routing"),
        ("04","Wireless Site Deployment","Survey a controlled space. Place 3 APs. Configure controller. Validate with a heatmap.","lt-recon","Wireless"),
        ("05","Wireshark Detective","Receive a 50MB pcap. Within 30 minutes \u2014 identify the attacker and impacted host.","lt-forensic","Forensics"),
        ("06","Zero-Trust Segment","Build a microsegmented design with NGFW + 802.1X. Validate denied flows.","lt-defend","Security"),
        ("07","VPN Site-to-Site","Configure IPsec between two pfSense edges. Bring up dynamic routing across the tunnel.","lt-defend","VPN"),
        ("08","QoS Under Load","Saturate a link. Apply DSCP-based QoS for voice. Verify protected latency under congestion.","lt-attack","QoS"),
        ("09","Outage Simulation","An entire floor is offline. You have 45 minutes, console access and one cable tester. Restore.","lt-defend","Ops"),
    ],
    labs_footer="+ 31 additional bench tasks. Pre-built capture libraries to take home.",
    exam_eyebrow="Exam Information",
    exam_head=("One exam.","Heavy on PBQs."),
    exam_intro="Network+ N10-009 is a single 90-minute exam, but it's loaded with performance-based questions \u2014 drag-drop, simulator, configuration. Most candidates fail not on theory, but on PBQ time pressure.",
    exam_main=dict(name="Network+ N10-009 Exam",rows=[
        ("Questions","Max 90 (MC + performance-based)"),
        ("Duration","90 minutes"),
        ("Passing score",'<span class="pass-highlight">720 / 900</span>'),
        ("Format","Pearson VUE / Online"),
        ("Validity","3 years (CE renewal)"),
        ("Industry avg pass rate",'<span class="fail-note">~70% first attempt</span>'),
        ("Nexperts pass rate",'<span class="pass-highlight">96% first attempt</span>'),
    ]),
    exam_optional=dict(name="Performance-Based Question Coaching",rows=[
        ("Item count","5\u20136 PBQs per exam"),
        ("Item type","Drag-drop, simulator, fill-in"),
        ("Score weighting","PBQs are heavily weighted"),
        ("Coaching","Dedicated 4-hour PBQ workshop"),
        ("Strategy","Time-box PBQs to 5 minutes each"),
        ("Outcome","PBQ score uplift averages +18%"),
        ("Walkthrough","Past PBQ archive \u2014 anonymised"),
    ]),
    mock_title="Our 3-Mock Programme",
    mock_programme=[
        ("01","Diagnostic Mock","End of week 1. Pure-MCQ to map weak domains. Average score: 61%."),
        ("02","PBQ-Heavy Mock","Mid-course. PBQ-only practice \u2014 drag-drop, simulator, configuration. Average score: 73%."),
        ("03","Final Clearance","Full N10-009 timed simulation. 82%+ before we book. Average score: 86%."),
    ],
    pass_rate=96,
    pass_head_html='96% of our Network+ candidates<br>pass <em>on first attempt.</em>',
    pass_intro="The global N10-009 first-attempt rate hovers around 70%. Our 96% comes from a real lab rack, dedicated PBQ coaching, and an instructor who has run network operations for two regional banks for the past 14 years.",
    pass_pills=["Real rack labs","PBQ coaching workshop","96% first attempt","Wireshark capture library","Free retake voucher"],
    pass_compare=[
        ("Industry average: ~70%","Most candidates fail Network+ at the PBQs. They studied the theory, but they've never actually sub-netted a /22 under five minutes of pressure."),
        ("Nexperts: 96%","We dedicate four hours just to PBQs. We force speed. We force accuracy. We don't book the exam until you can demolish a PBQ in under five minutes."),
    ],
    next_eyebrow="Your Certification Journey",
    next_head=("Network+ unlocks","two big paths."),
    next_steps_intro="Network+ opens networking, security and cloud paths simultaneously. Most learners use it as a stepping stone into either Cisco CCNA or directly into Security+.",
    next_steps=[
        ("Before this","CompTIA A+","If you don't already work in IT, A+ provides the device and OS fluency Network+ assumes you have.","View A+ \u2192"),
        ("You are here","Network+ N10-009","Vendor-neutral networking expert. You can design, build and troubleshoot enterprise networks on Cisco, Aruba, Juniper or any modern vendor.","Currently viewing \u2192"),
        ("Recommended next","CCNA or Security+","CCNA goes deeper into Cisco. Security+ pivots into cybersecurity. Both are excellent moves from Network+.","View CCNA \u2192"),
    ],
    path_name="networking \u2192 infrastructure",
    path_chips=[("CompTIA A+","prev"),("Network+","you"),("Security+ / CCNA","next"),("CySA+ / CCNP","prev"),("CISSP","prev")],
    salary_html='Expected salary range after Network+: <strong style="color:#86efac">RM 3,500 \u2013 RM 6,500/month</strong> for junior network and infrastructure roles in Malaysian enterprises.',
    reviews_eyebrow="Student Reviews",
    reviews_head=("What our Network+","graduates say."),
    reviews_summary=("4.8",84,13,3,156),
    reviews=[
        ("\u2605\u2605\u2605\u2605\u2605","The 50MB pcap forensics lab broke me on day three and rebuilt me by day five. By the time I sat the exam, every PBQ felt like a familiar lab task. Scored 832.","rav-b","PV","Pavithra Vairavan","Network Engineer \u00b7 CelcomDigi","\u2713 Passed first attempt \u00b7 832 / 720"),
        ("\u2605\u2605\u2605\u2605\u2605","I had been pushed up from helpdesk into network ops without certification. Network+ formalised the gaps and now I'm leading change windows. Salary rose 18% within four months.","rav-m","ZF","Zafrul Faiz","Network Operations \u00b7 CIMB Group","\u2713 Passed first attempt \u00b7 768 / 720"),
        ("\u2605\u2605\u2605\u2605\u2605","OSPF was my Achilles heel. The instructor sat me down with a console and a hand-drawn topology and refused to leave until I could build it from memory.","rav-g","DK","Dineshkumar Krishnan","Junior Engineer \u00b7 TM Wholesale","\u2713 Passed first attempt \u00b7 805 / 720"),
        ("\u2605\u2605\u2605\u2605","The Wireshark module was the highlight. I now use packet captures in my actual job at least twice a week. The course paid for itself in the first month.","rav-a","JN","Jia Ning Lim","IT Support Lead \u00b7 Hong Leong","\u2713 Passed first attempt \u00b7 781 / 720"),
    ],
    price="RM 2,900", price_orig="RM 3,500", price_save="Save 17%",
    price_note="Per person \u00b7 Includes Pearson VUE voucher, rack-time, courseware",
    sidebar_meta=[
        ("Duration","5 days / 40 hrs"),
        ("Next intake","19 May 2026"),
        ("Format","On-site (rack lab)"),
        ("Level","Foundation\u2013Intermediate"),
        ("Language","English \u00b7 BM available"),
        ("Cert body","CompTIA"),
        ("Exam",'<span class="smeta-badge">Included</span>'),
    ],
    whats_included=[
        "CompTIA official courseware (digital + PDF)",
        "Pearson VUE voucher (N10-009)",
        "Rack-time access on real Cisco / Aruba / pfSense gear",
        "3 full timed mock exams",
        "Dedicated 4-hour PBQ workshop",
        "Wireshark capture library (40 captures)",
        "Post-course instructor access (30 days)",
        "Free single retake voucher",
        "Digital badge via CompTIA Marketplace",
    ],
    verify_items=[
        "Verifiable on CompTIA Marketplace",
        "Digital badge via Credly",
        "ANSI / ISO 17024 accredited",
        "LinkedIn certificate integration",
    ],
    guarantee_text="Hit the 82% mock threshold and don't pass on first attempt? We cover the retake voucher.",
))

# 3. CompTIA Security+
BATCH.append(dict(
    slug="comptia-security-plus",
    title="CompTIA Security+",
    title_html='CompTIA Security+<br><em>SY0-701</em>',
    vendor_short="CompTIA", watermark="S+", crumb_vendor="CompTIA",
    subtitle="The most-requested cybersecurity credential by Malaysian employers. Threats, attacks, vulnerabilities, architecture, identity, governance and operations \u2014 the cybersecurity baseline.",
    badges=[("cb-vendor","CompTIA Authorized"),("cb-level","Intermediate"),("cb-new","SY0-701 \u00b7 2026"),("cb-hot","DoD 8570 / 8140")],
    hero_meta=common_meta("5 days / 40 hrs","Instructor-Led + Range Labs","On-site \u00b7 Virtual \u00b7 Hybrid",97,"26 May 2026"),
    hero_img=HERO_IMG,
    quick_wins=[
        ("\U0001F6E1\uFE0F","Speak the language of security","5 domains, 25 objectives \u2014 fluency every security role expects"),
        ("\u2694\uFE0F","Threat / attack / vulnerability","Walk in cold to a SOC alert and know exactly what is happening"),
        ("\U0001F3DB\uFE0F","Governance, risk & compliance","PDPA, ISO 27001, NIST CSF \u2014 applied to the Malaysian context"),
        ("\U0001F916","Zero-trust & cloud-native","Modern architecture, IAM, SASE and edge \u2014 the SY0-701 priority"),
    ],
    overview_eyebrow="What this course is",
    overview_head=("Security+ is","the cybersecurity baseline."),
    overview_p1="CompTIA Security+ (SY0-701) is the credential employers screen for when hiring for a junior security role. Bank Negara, Petronas, Maxis and most local banks list it as a baseline expectation.",
    overview_p2="At Nexperts Academy, we teach Security+ from the perspective of someone who actually responds to incidents \u2014 not someone who has only read about them. Our instructor has led IR engagements across Malaysian financial institutions for over a decade.",
    overview_quote="You don't pass Security+ by memorising terms. You pass it by recognising the patterns of an attack the second the alert fires.",
    overview_p3="SY0-701 modernises the older SY0-601 \u2014 the new domains emphasise cloud security, zero trust, automation, and modern threat actors. We teach with current Malaysian incidents \u2014 what really happened, how it was detected, how it was contained.",
    who_for=[
        ("\U0001F6E1\uFE0F","Aspiring SOC analysts","Security+ is the fastest path into a SOC role in a Malaysian bank or MNC."),
        ("\U0001F310","Network+ holders","Pivot directly from networking into security with a credential that proves the transition."),
        ("\u2601\uFE0F","Cloud engineers","Modern cloud roles increasingly require security baseline. Security+ delivers it."),
        ("\U0001F3DB\uFE0F","GRC and audit professionals","Need to understand technical controls behind the policies you write."),
        ("\U0001F393","ICT students","Final-year and fresh graduates \u2014 Security+ pairs with your degree for a strong first cybersecurity job."),
        ("\U0001F504","Career switchers","Coming from non-security IT roles. Security+ is the bridge into the cybersecurity profession."),
    ],
    prereqs=[
        "Network+ or equivalent networking knowledge (TCP/IP fluency)",
        "2 years of general IT experience recommended",
        "Comfortable with Windows and Linux command lines",
        "Understanding of basic system administration",
    ],
    prereqs_note="No Network+? Ask us about our combined Network+ \u2192 Security+ track.",
    curriculum_eyebrow="Course Curriculum",
    curriculum_head=("Five domains.","The full security stack."),
    curriculum_intro="SY0-701 is structured into General Security Concepts, Threats and Vulnerabilities, Security Architecture, Security Operations, and Security Program Management.",
    modules=[
        ("01","General Security Concepts",[
            "Confidentiality, Integrity, Availability \u2014 applied",
            "Security control types \u2014 preventive, detective, corrective",
            "Zero trust architecture and assumptions",
            "Cryptography \u2014 symmetric, asymmetric, hashing",
            "Identity and access management essentials",
            "Lab: Build a CA and issue certificates",
        ]),
        ("02","Threats, Vulnerabilities & Mitigations",[
            "Threat actor types and motivations",
            "Common attack vectors \u2014 phishing, supply chain, IoT",
            "Malware families and indicators",
            "Application attacks \u2014 XSS, SQLi, request forgery",
            "Vulnerability scanning and patch management",
            "Lab: Run a Nessus scan, prioritise via CVSS",
        ]),
        ("03","Security Architecture",[
            "Network architecture \u2014 segmentation, DMZ, VLANs",
            "Cloud architecture \u2014 IaaS / PaaS / SaaS security",
            "Resilience and recovery \u2014 RPO, RTO, BCP/DR",
            "Data protection \u2014 DLP, tokenisation, masking",
            "Encryption at rest and in transit",
            "Lab: Design a zero-trust network for a 200-user firm",
        ]),
        ("04","Security Operations",[
            "Security monitoring and SIEM concepts",
            "Incident response phases \u2014 NIST 800-61 model",
            "Digital forensics \u2014 chain of custody",
            "Threat hunting and intelligence integration",
            "Endpoint detection and response (EDR)",
            "Lab: Triage a simulated phishing-to-ransomware incident",
        ]),
        ("05","Security Program Management & Oversight",[
            "Governance, Risk and Compliance (GRC)",
            "Frameworks \u2014 ISO 27001, NIST CSF, PCI-DSS",
            "Malaysian context \u2014 PDPA, BNM RMiT, MyDigital",
            "Risk management \u2014 qualitative and quantitative",
            "Third-party risk and supply chain",
            "Lab: Build a Security+ aligned policy pack",
        ]),
    ],
    labs_eyebrow="Hands-On Range",
    labs_head=("40 range exercises.","Live attack and defence."),
    labs_intro="The Nexperts Security+ range is hosted on a dedicated Proxmox cluster \u2014 vulnerable Windows AD, a Linux web stack with deliberate flaws, a Splunk-fed SIEM and a Caldera red-team controller.",
    labs=[
        ("01","PKI Build & CA Hierarchy","Build a two-tier CA. Issue user, server and code-signing certificates.","lt-defend","Crypto"),
        ("02","Phishing-to-Foothold Trace","Receive a phishing email + memory dump. Identify the dropper, the C2 and the foothold.","lt-forensic","Detection"),
        ("03","Vulnerability Triage Sprint","Receive 240 raw findings. Prioritise via CVSS + business context in 30 minutes.","lt-recon","Vuln Mgmt"),
        ("04","Zero-Trust Design Workshop","Take a flat 200-user network. Re-architect to zero trust on a whiteboard.","lt-defend","Architecture"),
        ("05","Splunk Detection Engineering","Write 5 detection rules for common attacks. Tune them to <5% false-positive on the live feed.","lt-defend","SOC"),
        ("06","Ransomware IR Drill","60 minutes. A live encryption event. Identify entry, contain spread, preserve forensic evidence.","lt-forensic","IR"),
        ("07","Web App Attack Recognition","Replay 30 attack signatures against a vulnerable app. Recognise OWASP Top 10 from logs.","lt-attack","AppSec"),
        ("08","ISO 27001 Gap Assessment","Take a fictional Malaysian SME. Run a 5-control gap assessment. Write the executive summary.","lt-recon","GRC"),
        ("09","BNM RMiT Mapping","Map Security+ controls to BNM Risk Management in Tech. Identify the 3 you'd prioritise.","lt-defend","Compliance"),
    ],
    labs_footer="+ 31 additional range tasks. Range access for 60 days post-course.",
    exam_eyebrow="Exam Information",
    exam_head=("One exam.","Modern, performance-based."),
    exam_intro="Security+ SY0-701 is heavy on scenario items and PBQs that simulate SIEM dashboards, partial configs and incident timelines. Theory alone won't pass it. Pattern recognition will.",
    exam_main=dict(name="Security+ SY0-701 Exam",rows=[
        ("Questions","Max 90 (MC + performance-based)"),
        ("Duration","90 minutes"),
        ("Passing score",'<span class="pass-highlight">750 / 900</span>'),
        ("Format","Pearson VUE / Online"),
        ("Validity","3 years (CE renewal)"),
        ("Industry avg pass rate",'<span class="fail-note">~70% first attempt</span>'),
        ("Nexperts pass rate",'<span class="pass-highlight">97% first attempt</span>'),
    ]),
    exam_optional=dict(name="DoD 8570 / 8140 Recognition",rows=[
        ("Approved baseline","IAT Level 2, IAM Level 1"),
        ("MNC alignment","Used by US-affiliated MNCs in MY"),
        ("Banking","Listed in Bank Negara security baselines"),
        ("Government","Recognised by MAMPU and CyberSecurity Malaysia"),
        ("Voucher","Bundled \u2014 Pearson VUE voucher included"),
        ("Renewal","CompTIA CE programme \u2014 50 CEUs in 3 years"),
        ("Stacks with","CySA+, CASP, PenTest+, CISSP"),
    ]),
    mock_title="Our 3-Mock Programme",
    mock_programme=[
        ("01","Diagnostic Mock","End of day 2. Pinpoints weak domains. Average score: 64%."),
        ("02","PBQ-Focus Mock","Mid-course. Performance-based items only. Average score: 76%."),
        ("03","Final Clearance","Full SY0-701 timed simulation. 85%+ before booking. Average score: 89%."),
    ],
    pass_rate=97,
    pass_head_html='97% of our Security+ students<br>pass <em>on their first attempt.</em>',
    pass_intro="Global Security+ first-attempt rates hover near 70%. We deliver 97% \u2014 through 40 live-range exercises, three timed mocks with PBQ coaching, and instructors who have run real IR engagements for Malaysian banks, telecoms and energy companies.",
    pass_pills=["Live range labs","PBQ workshop","97% first attempt","Free retake voucher","85% mock gate"],
    pass_compare=[
        ("Industry average: ~70%","Most Security+ candidates pass the multi-choice items but stall on PBQs that require interpreting a SIEM dashboard or a partial config under time pressure."),
        ("Nexperts: 97%","We dedicate a full day to PBQ patterns. We hard-gate on a clearance mock at 85%. And we run live attack-defence scenarios so the patterns are familiar long before exam day."),
    ],
    next_eyebrow="Your Certification Journey",
    next_head=("Security+ is","the cybersecurity entry."),
    next_steps_intro="Security+ is the cybersecurity entry point. From here you specialise \u2014 into SOC operations with CySA+, into offensive security with CEH/PenTest+, or into management with CISM/CISSP.",
    next_steps=[
        ("Before this","Network+ or A+","Network fluency is the prerequisite. Without it, Security+ feels abstract.","View Network+ \u2192"),
        ("You are here","Security+ SY0-701","Cybersecurity baseline. Globally recognised. DoD 8570/8140 approved. Most-requested by Malaysian employers.","Currently viewing \u2192"),
        ("Recommended next","CySA+ or CEH","CySA+ goes deeper into SOC and detection. CEH goes offensive. Both are excellent next-step certifications.","View CySA+ \u2192"),
    ],
    path_name="cybersecurity",
    path_chips=[("CompTIA A+ / Network+","prev"),("Security+","you"),("CySA+ / CEH","next"),("CISSP / CASP+","prev"),("CISO Track","prev")],
    salary_html='Expected salary range after Security+: <strong style="color:#86efac">RM 4,500 \u2013 RM 8,500/month</strong> for junior security analyst and security engineer roles in Malaysia.',
    reviews_eyebrow="Student Reviews",
    reviews_head=("What our Security+","graduates say."),
    reviews_summary=("4.9",90,8,2,263),
    reviews=[
        ("\u2605\u2605\u2605\u2605\u2605","I sat Security+ four months after switching from network operations into a security role. The PDPA and BNM mapping content alone made me look like the most prepared person in the team's first audit drill.","rav-b","ME","Mohd Ehsan","SOC Analyst \u00b7 RHB Bank","\u2713 Passed first attempt \u00b7 832 / 750"),
        ("\u2605\u2605\u2605\u2605\u2605","The phishing-to-foothold trace lab is exactly the kind of incident I deal with in real life. By the time I sat the exam, the pattern recognition was automatic.","rav-m","AR","Anita Raman","Security Engineer \u00b7 YTL Communications","\u2713 Passed first attempt \u00b7 798 / 750"),
        ("\u2605\u2605\u2605\u2605\u2605","Took three Security+ attempts elsewhere. Came to Nexperts. Passed at 821. The PBQ workshop and live range made the difference. Worth every ringgit.","rav-g","VC","Vincent Cheong","IT Risk Officer \u00b7 KPMG Malaysia","\u2713 Passed first attempt at Nexperts \u00b7 821 / 750"),
        ("\u2605\u2605\u2605\u2605\u2605","BNM RMiT mapping was new to me even after 6 years in banking IT. The Malaysian context throughout the course made it immediately useful in my day job.","rav-a","FH","Fariza Hassan","Information Security Officer \u00b7 Bank Islam","\u2713 Passed first attempt \u00b7 812 / 750"),
    ],
    price="RM 3,200", price_orig="RM 3,800", price_save="Save 16%",
    price_note="Per person \u00b7 Includes Pearson VUE voucher, range access, courseware",
    sidebar_meta=[
        ("Duration","5 days / 40 hrs"),
        ("Next intake","26 May 2026"),
        ("Format","On-site \u00b7 Hybrid"),
        ("Level","Intermediate"),
        ("Language","English \u00b7 BM available"),
        ("Cert body","CompTIA"),
        ("Exam",'<span class="smeta-badge">Included</span>'),
    ],
    whats_included=[
        "CompTIA official courseware (digital + PDF)",
        "Pearson VUE voucher (SY0-701)",
        "60-day Nexperts range access",
        "3 full timed mock exams",
        "Dedicated 8-hour PBQ workshop",
        "BNM RMiT &amp; PDPA mapping playbook",
        "Post-course instructor access (45 days)",
        "Free single retake voucher",
        "Digital badge via CompTIA Marketplace",
    ],
    verify_items=[
        "Verifiable on CompTIA Marketplace",
        "Digital badge via Credly",
        "DoD 8570 / 8140 approved",
        "ANSI / ISO 17024 accredited",
    ],
    guarantee_text="Hit the 85% mock threshold and don't pass first attempt? We cover the retake voucher.",
))

# 4. CompTIA CySA+
BATCH.append(dict(
    slug="comptia-cysa-plus",
    title="CompTIA CySA+",
    title_html='CompTIA CySA+<br><em>CS0-003</em>',
    vendor_short="CompTIA", watermark="CySA", crumb_vendor="CompTIA",
    subtitle="The cybersecurity analyst credential for SOC roles. Behavioural analytics, threat intelligence, vulnerability management, incident response and forensic foundations.",
    badges=[("cb-vendor","CompTIA Authorized"),("cb-level","Intermediate"),("cb-new","CS0-003 \u00b7 2026"),("cb-hot","SOC Analyst Track")],
    hero_meta=common_meta("5 days / 40 hrs","Instructor-Led + Live SOC","On-site \u00b7 Virtual \u00b7 Hybrid",96,"2 June 2026"),
    hero_img=HERO_IMG,
    quick_wins=[
        ("\U0001F4E1","Detect, don't just defend","Move from prevention thinking to active behavioural detection"),
        ("\U0001F50D","Threat intelligence applied","TTPs, IOCs, MITRE ATT&CK and threat feed analysis"),
        ("\U0001F6E0\uFE0F","Hands-on SIEM coaching","Splunk and Sentinel queries, dashboards, alert tuning"),
        ("\U0001F4DD","Reporting that lands","Write IR reports an executive will read and act on"),
    ],
    overview_eyebrow="What this course is",
    overview_head=("CySA+ is the","SOC analyst credential."),
    overview_p1="CySA+ (CS0-003) sits between Security+ (foundation) and CASP / CISSP (architecture). It validates that you can sit in a SOC, run live detection, triage incidents and manage vulnerabilities \u2014 the day-to-day work of a Tier 2 analyst.",
    overview_p2="At Nexperts, CySA+ is delivered against a live cloud-hosted SOC stack \u2014 Splunk Enterprise Security, Microsoft Sentinel, Crowdstrike Falcon and Cortex XSOAR. You don't memorise vendors. You drive them.",
    overview_quote="A SOC analyst is judged by mean time to detect and mean time to contain. Both are measured in minutes \u2014 and minutes are what we drill.",
    overview_p3="The CS0-003 update emphasises automation, threat hunting and the analyst's role in vulnerability prioritisation. We teach all three in real workflows you'll execute on Monday morning at your job.",
    who_for=[
        ("\U0001F6E1\uFE0F","Security+ holders","The most logical next step. CySA+ specialises Security+ into the SOC analyst role."),
        ("\U0001F50D","SOC L1 analysts","Already triaging tickets \u2014 formalise your skills and step up to L2 / threat hunting."),
        ("\U0001F4CA","Vulnerability managers","Going beyond raw scan output into business-aware prioritisation."),
        ("\U0001F310","Network engineers pivoting","Network fluency + CySA+ = a strong route into security."),
        ("\U0001F3DB\uFE0F","Banking IT staff","BNM RMiT requires demonstrable detection capabilities. CySA+ aligns directly."),
        ("\U0001F4DA","Pre-CISSP learners","CySA+ adds the operational depth CISSP candidates often lack."),
    ],
    prereqs=[
        "CompTIA Security+ or equivalent foundation",
        "4 years IT experience (3 in security recommended)",
        "Comfort with Windows event logs and Linux syslog",
        "Basic SIEM or log-search experience an advantage",
    ],
    prereqs_note="No Security+? Ask us about our combined Security+ \u2192 CySA+ pathway.",
    curriculum_eyebrow="Course Curriculum",
    curriculum_head=("Five domains.","SOC operations end to end."),
    curriculum_intro="CS0-003 covers Security Operations, Vulnerability Management, Incident Response and Management, and Reporting and Communication. We deliver them as a connected SOC workflow.",
    modules=[
        ("01","Security Operations Foundations",[
            "Network and host operating concepts for analysts",
            "Cloud and hybrid log sources \u2014 what to collect, why",
            "Process behaviours \u2014 parent/child anomalies",
            "Memory artefacts \u2014 process trees, handles",
            "Detection engineering basics",
            "Lab: Build a live alert from raw Sysmon logs",
        ]),
        ("02","Threat Hunting & Intelligence",[
            "MITRE ATT&CK matrix \u2014 applied",
            "TTPs, IOCs, indicators of behaviour",
            "Open-source and commercial threat feeds",
            "Hypothesis-driven hunting workflow",
            "Diamond model and Cyber Kill Chain",
            "Lab: Hypothesis-driven hunt for living-off-the-land",
        ]),
        ("03","Vulnerability Management",[
            "Scanning \u2014 authenticated, unauthenticated, agent",
            "CVSS scoring and contextual prioritisation",
            "Patch management lifecycle and exceptions",
            "Threat-informed prioritisation \u2014 EPSS and KEV",
            "Risk acceptance and remediation reporting",
            "Lab: Run Nessus + correlate against EPSS / KEV",
        ]),
        ("04","Incident Response & Management",[
            "NIST 800-61 IR phases \u2014 operationalised",
            "Containment strategies \u2014 network, host, cloud",
            "Evidence preservation and chain of custody",
            "Forensic acquisitions \u2014 disk, memory, network",
            "Tabletop exercises and runbook design",
            "Lab: Full IR exercise from alert to executive briefing",
        ]),
        ("05","Reporting & Communication",[
            "Writing for executives vs technical peers",
            "Building incident timelines stakeholders trust",
            "Risk language \u2014 qualitative and quantitative",
            "Metrics that matter \u2014 MTTD, MTTC, dwell time",
            "Stakeholder management during active incidents",
            "Lab: Write an IR report with the business in mind",
        ]),
    ],
    labs_eyebrow="Hands-On SOC",
    labs_head=("36 SOC drills.","Live alerts. Live data."),
    labs_intro="Our CySA+ environment ingests live attack data from a Caldera red team, plus synthetic noise from a 200-endpoint simulation. You'll run real Splunk and Sentinel queries against real activity.",
    labs=[
        ("01","Sysmon to SIEM Pipeline","Build the full pipeline \u2014 Sysmon \u2192 Universal Forwarder \u2192 Splunk index \u2192 dashboards.","lt-defend","Pipeline"),
        ("02","Living-off-the-Land Hunt","Hypothesise. Hunt. Find the persistence mechanism the red team planted last week.","lt-forensic","Hunting"),
        ("03","KQL Detection Sprint","Write 10 Sentinel KQL detections aligned to MITRE ATT&CK in 90 minutes.","lt-defend","Detection"),
        ("04","CVSS + EPSS Triage","Receive 500 raw findings. Prioritise via EPSS, KEV and business context. Defend top-25.","lt-recon","Vuln Mgmt"),
        ("05","Memory Forensics","Run Volatility against a captured memory image. Identify the malware family.","lt-forensic","Forensics"),
        ("06","Cloud IR \u2014 Azure","An attacker compromised a service principal. Trace, contain and rotate credentials.","lt-defend","Cloud IR"),
        ("07","DNS Beacon Detection","Spot the DNS C2 channel hidden in 2 million queries. Ten minutes.","lt-attack","Hunting"),
        ("08","Tabletop \u2014 Ransomware","Run a full 90-minute tabletop with C-suite, legal and PR. Document decisions.","lt-defend","TTX"),
        ("09","Executive IR Briefing","Take a complex incident. Prepare a 5-minute executive briefing. Defend questions.","lt-recon","Comms"),
    ],
    labs_footer="+ 27 additional SOC tasks. Splunk and Sentinel access for 60 days post-course.",
    exam_eyebrow="Exam Information",
    exam_head=("One exam.","Heavy on PBQs."),
    exam_intro="CS0-003 is dominated by performance-based questions simulating SIEM dashboards, alert triage decisions and IR workflows. Pure-theory study fails this exam.",
    exam_main=dict(name="CySA+ CS0-003 Exam",rows=[
        ("Questions","Max 85 (MC + performance-based)"),
        ("Duration","165 minutes"),
        ("Passing score",'<span class="pass-highlight">Pass / Fail (no scaled score)</span>'),
        ("Format","Pearson VUE / Online"),
        ("Validity","3 years (CE renewal)"),
        ("Industry avg pass rate",'<span class="fail-note">~66% first attempt</span>'),
        ("Nexperts pass rate",'<span class="pass-highlight">96% first attempt</span>'),
    ]),
    exam_optional=dict(name="DoD 8570 / 8140 Recognition",rows=[
        ("Approved roles","CSSP Analyst, IAT Level 2"),
        ("Banking","Recognised across BNM-regulated entities"),
        ("Voucher","Bundled \u2014 Pearson VUE included"),
        ("Renewal","CompTIA CE \u2014 60 CEUs in 3 years"),
        ("Stacks with","Security+ \u2192 CySA+ \u2192 CASP+"),
        ("Prereq waiver","Counts toward CISSP experience"),
        ("Career fit","Tier 2 / Tier 3 SOC analyst, threat hunter"),
    ]),
    mock_title="Our CySA+ 3-Mock Programme",
    mock_programme=[
        ("01","Diagnostic Mock","Day 2. Pinpoints weak detection patterns. Average score: 58%."),
        ("02","SIEM-Heavy Mock","Mid-course. PBQ-only \u2014 Splunk and Sentinel scenarios. Average score: 74%."),
        ("03","Final Clearance","Full timed simulation. 84%+ before booking. Average score: 88%."),
    ],
    pass_rate=96,
    pass_head_html='96% of our CySA+ analysts<br>pass <em>on first attempt.</em>',
    pass_intro="Industry-wide CS0-003 first-attempt rate is around 66%. Our 96% comes from a live SOC environment, dedicated KQL/SPL workshops, and an instructor who runs Tier-3 escalations for two regional SOCs every month.",
    pass_pills=["Live SOC environment","SPL + KQL workshops","96% first attempt","MITRE ATT&CK drills","Free retake voucher"],
    pass_compare=[
        ("Industry average: ~66%","Most candidates fail on PBQs because they've never actually queried a SIEM under time pressure. They know the theory, not the workflow."),
        ("Nexperts: 96%","We give you 60 days of live SIEM access, force you through 90-minute SOC drills, and don't book the exam until your detection writing is fluent."),
    ],
    next_eyebrow="Your Certification Journey",
    next_head=("CySA+ unlocks the","Tier 2 / 3 SOC track."),
    next_steps_intro="From CySA+ you choose architecture (CASP+), management (CISSP) or specialisation (Threat Hunting / IR / Forensics).",
    next_steps=[
        ("Before this","Security+ SY0-701","Security fundamentals are the prerequisite. Without them, CySA+ feels conceptual.","View Security+ \u2192"),
        ("You are here","CySA+ CS0-003","Operational SOC analyst credential. You can detect, hunt, triage, respond and report.","Currently viewing \u2192"),
        ("Recommended next","CASP+ or CISSP","CASP+ goes architecture. CISSP goes management. Both are strong from CySA+.","View CASP+ \u2192"),
    ],
    path_name="SOC analyst",
    path_chips=[("Security+","prev"),("CySA+","you"),("CASP+ / CHFI","next"),("CISSP","prev"),("CISO Track","prev")],
    salary_html='Expected salary range after CySA+: <strong style="color:#86efac">RM 6,500 \u2013 RM 11,000/month</strong> for Tier 2 SOC and threat-hunting roles in Malaysia.',
    reviews_eyebrow="Student Reviews",
    reviews_head=("What our CySA+","graduates say."),
    reviews_summary=("4.8",87,11,2,142),
    reviews=[
        ("\u2605\u2605\u2605\u2605\u2605","I'd been doing SOC L1 for two years and could not pass CASP-style PBQs. CySA+ at Nexperts forced me to actually write Splunk searches under time pressure. Pattern recognition kicked in around day 3.","rav-b","RY","Reza Yazid","SOC L2 \u00b7 Maybank","\u2713 Passed first attempt"),
        ("\u2605\u2605\u2605\u2605\u2605","The MITRE ATT&CK module is what tipped me. We mapped real threat actor TTPs to our own SIEM coverage and found three blind spots in our detection stack.","rav-m","SS","Shobana Sivakumar","Threat Hunter \u00b7 Standard Chartered","\u2713 Passed first attempt"),
        ("\u2605\u2605\u2605\u2605","Memory forensics with Volatility was new to me. I expected slides. Got six hours of hands-on memory-image investigation. Worth it.","rav-g","DK","Daniel Khor","Junior IR Analyst \u00b7 KPMG MY","\u2713 Passed first attempt"),
        ("\u2605\u2605\u2605\u2605\u2605","The executive briefing simulation was brutal \u2014 and exactly what I needed. Two months later I delivered my first real ransomware briefing to my CIO and it landed cleanly.","rav-a","HW","Halimah Wahab","Senior SOC Analyst \u00b7 CIMB","\u2713 Passed first attempt"),
    ],
    price="RM 4,200", price_orig="RM 4,900", price_save="Save 14%",
    price_note="Per person \u00b7 Includes CompTIA voucher, SOC access, courseware",
    sidebar_meta=[
        ("Duration","5 days / 40 hrs"),
        ("Next intake","2 June 2026"),
        ("Format","On-site \u00b7 Hybrid"),
        ("Level","Intermediate"),
        ("Language","English"),
        ("Cert body","CompTIA"),
        ("Exam",'<span class="smeta-badge">Included</span>'),
    ],
    whats_included=[
        "CompTIA CySA+ official courseware",
        "Pearson VUE voucher (CS0-003)",
        "60-day Splunk &amp; Sentinel SOC access",
        "3 full timed mock exams",
        "MITRE ATT&amp;CK detection workshop",
        "SPL and KQL query playbook",
        "Post-course instructor access (45 days)",
        "Free single retake voucher",
        "Digital badge via CompTIA Marketplace",
    ],
    verify_items=[
        "Verifiable on CompTIA Marketplace",
        "Digital badge via Credly",
        "DoD 8570 / 8140 approved (CSSP Analyst)",
        "Stacks toward CASP+ / CISSP",
    ],
    guarantee_text="Hit the 84% mock threshold and don't pass first attempt? Retake voucher on us.",
))

# 5. CompTIA PenTest+
BATCH.append(dict(
    slug="comptia-pentest-plus",
    title="CompTIA PenTest+",
    title_html='CompTIA PenTest+<br><em>PT0-003</em>',
    vendor_short="CompTIA", watermark="PT+", crumb_vendor="CompTIA",
    subtitle="Penetration testing with reporting and compliance built in. Planning, scoping, recon, exploitation, post-exploitation, web app testing and clean executive deliverables.",
    badges=[("cb-vendor","CompTIA Authorized"),("cb-level","Intermediate \u00b7 Advanced"),("cb-new","PT0-003 \u00b7 2026"),("cb-hot","Pre-OSCP Builder")],
    hero_meta=common_meta("5 days / 40 hrs","Instructor-Led + Cyber Range","On-site \u00b7 Virtual \u00b7 Hybrid",95,"9 June 2026"),
    hero_img=HERO_IMG,
    quick_wins=[
        ("\u2694\uFE0F","End-to-end engagement","Plan, scope, exec, report \u2014 the full pentest lifecycle"),
        ("\U0001F4DC","Compliance-aware testing","PCI-DSS, BNM RMiT, PDPA \u2014 what scope clauses really mean"),
        ("\U0001F310","Web, network, cloud and AI","All four core surfaces, with 2026's AI-attack additions"),
        ("\U0001F4DD","Reports clients pay for","Executive summary, technical detail, remediation that lands"),
    ],
    overview_eyebrow="What this course is",
    overview_head=("PenTest+ is","offensive done right."),
    overview_p1="PenTest+ (PT0-003) is the practical penetration testing certification with reporting and compliance built into the syllabus. It's the credential that gets you hired into an offensive security team.",
    overview_p2="At Nexperts, PenTest+ is delivered against the same Caldera-driven cyber range our CEH learners use. The difference: we focus you on engagement workflow \u2014 SOW, statement of engagement, evidence and reporting, not just the exploits.",
    overview_quote="A pentest report that an exec will not read is a pentest report that gets ignored. Half this course is teaching you to write the report.",
    overview_p3="PT0-003 modernises the older PT0-002 with cloud, IaC and AI-attack content. The exam is heavy on PBQs simulating Burp, Metasploit, AD enumeration and report-writing scenarios.",
    who_for=[
        ("\U0001F3AF","Aspiring junior pentesters","PenTest+ is the most-used pre-OSCP credential in MY consultancies."),
        ("\U0001F6E1\uFE0F","Security+ / CySA+ holders","The natural offensive specialisation step."),
        ("\U0001F310","Web developers pivoting","Web-app pentesting is half this exam \u2014 perfect pivot from dev."),
        ("\U0001F3DB\uFE0F","GRC professionals","Understand exactly what scope-of-work clauses mean technically."),
        ("\U0001F4CA","Risk auditors","Read pentest reports critically \u2014 and write better ones."),
        ("\U0001F393","CEH alumni","PenTest+ adds the engagement and reporting depth CEH skips."),
    ],
    prereqs=[
        "Security+ or 3+ years of security experience",
        "Strong networking and Windows / Linux fluency",
        "Comfort with command line and scripting",
        "Network+ recommended",
    ],
    prereqs_note="No Security+? Ask us about our Security+ \u2192 PenTest+ accelerated track.",
    curriculum_eyebrow="Course Curriculum",
    curriculum_head=("Five domains.","Engagement-first sequencing."),
    curriculum_intro="PT0-003 covers Planning and Scoping, Information Gathering, Attacks and Exploits, Reporting and Communication, and Tools and Code Analysis. We sequence them as you'd run a real engagement.",
    modules=[
        ("01","Planning, Scoping & Engagement",[
            "Scope of Work and Statement of Engagement",
            "Rules of engagement and authorisation",
            "PCI-DSS, BNM RMiT, PDPA scoping clauses",
            "Confidentiality, NDA and data handling",
            "Engagement timelines and deliverables",
            "Lab: Draft a real SOW for a Malaysian client",
        ]),
        ("02","Information Gathering & Recon",[
            "OSINT \u2014 passive and active reconnaissance",
            "DNS, WHOIS, certificate transparency",
            "Cloud asset enumeration \u2014 S3, Azure blobs",
            "Active recon \u2014 port scans, service identification",
            "AI-assisted recon \u2014 2026 additions",
            "Lab: Full recon profile of a test target",
        ]),
        ("03","Attacks, Exploits & Post-Exploitation",[
            "Network attacks \u2014 relay, spoofing, downgrade",
            "Application attacks \u2014 OWASP Top 10",
            "Cloud and IaC attacks",
            "Privilege escalation \u2014 Windows / Linux",
            "Lateral movement and persistence",
            "Lab: Full attack chain on the cyber range",
        ]),
        ("04","Reporting & Communication",[
            "Executive summary writing",
            "Technical findings \u2014 severity, evidence, repro",
            "Risk language for non-technical audiences",
            "Remediation prioritisation and roadmap",
            "Stakeholder readouts and Q&amp;A",
            "Lab: Write a full pentest report on a real engagement",
        ]),
        ("05","Tools & Code Analysis",[
            "Burp Suite, Metasploit, Nmap, BloodHound",
            "Command-line tooling \u2014 gobuster, ffuf, hashcat",
            "Source code reading \u2014 Python, Bash, PowerShell",
            "Common vulnerability patterns in code",
            "AI-attack tooling \u2014 2026 additions",
            "Lab: Write a small recon tool in Python",
        ]),
    ],
    labs_eyebrow="Hands-On Range",
    labs_head=("36 attack labs.","Real range. Real exploits."),
    labs_intro="Same Caldera-driven cyber range our CEH learners use. The difference for PenTest+ is the addition of full-engagement workflows \u2014 you'll deliver a real SOW and a real report alongside the exploitation.",
    labs=[
        ("01","SOW & Scope Drafting","Take a fictional client brief. Draft a complete SOW including legal limitations.","lt-recon","Engagement"),
        ("02","Full External Recon","Build a complete external attack surface map of a test target.","lt-recon","Recon"),
        ("03","AD Lateral Movement","From a foothold on one workstation, walk to Domain Admin in 2 hours.","lt-attack","AD Attack"),
        ("04","Web App Pentest","Burp Suite + manual review of a deliberately vulnerable web app.","lt-attack","Web"),
        ("05","Cloud IAM Privilege Escalation","Pivot through a misconfigured AWS IAM role chain.","lt-attack","Cloud"),
        ("06","Wireless Capture & Crack","Capture WPA2 handshakes, set up an evil twin, intercept clients.","lt-attack","Wireless"),
        ("07","Custom Recon Tool in Python","Write a 50-line subdomain enumerator with parallelism.","lt-recon","Tooling"),
        ("08","Pentest Report Writing","6-hour report-writing block. Executive summary + technical detail.","lt-defend","Reporting"),
        ("09","Client Readout Simulation","Present findings to a fictional CIO. Defend recommendations.","lt-defend","Comms"),
    ],
    labs_footer="+ 27 additional range tasks. Range access for 60 days post-course.",
    exam_eyebrow="Exam Information",
    exam_head=("One exam.","Workflow-heavy."),
    exam_intro="PT0-003 is heavy on PBQs simulating Burp Suite, Metasploit, AD enumeration and report-writing scenarios. Theory alone will not pass.",
    exam_main=dict(name="PenTest+ PT0-003 Exam",rows=[
        ("Questions","Max 85 (MC + performance-based)"),
        ("Duration","165 minutes"),
        ("Passing score",'<span class="pass-highlight">750 / 900</span>'),
        ("Format","Pearson VUE / Online"),
        ("Validity","3 years (CE renewal)"),
        ("Industry avg pass rate",'<span class="fail-note">~62% first attempt</span>'),
        ("Nexperts pass rate",'<span class="pass-highlight">95% first attempt</span>'),
    ]),
    exam_optional=dict(name="OSCP Pre-Bridging",rows=[
        ("Pre-bridge value","Builds 70% of OSCP foundation"),
        ("Tooling overlap","Burp, Metasploit, Nmap, AD attacks"),
        ("Scoping & reporting","Adds what OSCP doesn't teach"),
        ("Stacks with","CEH \u2192 PenTest+ \u2192 OSCP \u2192 CPENT"),
        ("Voucher","Bundled \u2014 Pearson VUE included"),
        ("Renewal","CompTIA CE \u2014 60 CEUs in 3 years"),
        ("Career fit","Junior pentester, red team intern"),
    ]),
    mock_title="Our PenTest+ 3-Mock Programme",
    mock_programme=[
        ("01","Diagnostic Mock","Day 2. Maps weak attack categories. Average score: 56%."),
        ("02","Workflow PBQ Mock","Mid-course. PBQ-only \u2014 Burp, Metasploit, AD scenarios. Average score: 71%."),
        ("03","Final Clearance","Full simulation incl. report-writing. 82%+ before booking. Average score: 87%."),
    ],
    pass_rate=95,
    pass_head_html='95% of our PenTest+ candidates<br>pass <em>on first attempt.</em>',
    pass_intro="Industry-average PT0-003 first-attempt sits around 62%. Our 95% is built on a real cyber range, full-engagement workflow drills, and an instructor who has delivered 80+ pentests for Malaysian banks and telcos.",
    pass_pills=["Cyber range labs","Engagement-workflow drills","95% first attempt","Burp + Metasploit fluency","Report-writing coaching"],
    pass_compare=[
        ("Industry average: ~62%","PenTest+ candidates often pass exploitation but struggle with the report-writing PBQs and the scoping nuance \u2014 the things you can't memorise."),
        ("Nexperts: 95%","We dedicate two days to engagement workflow and reporting. We force you to write a full report. We don't book until your scoping logic is bulletproof."),
    ],
    next_eyebrow="Your Certification Journey",
    next_head=("PenTest+ is","the OSCP runway."),
    next_steps_intro="PenTest+ is the most-used pre-OSCP cert in Malaysian consultancies. From here you go OSCP, then CPENT or specialise into red team / AppSec.",
    next_steps=[
        ("Before this","Security+ or CEH","Foundation security and offensive baselines. Without them, PenTest+ feels too tooling-heavy.","View CEH \u2192"),
        ("You are here","PenTest+ PT0-003","Practical pentester with engagement and reporting fluency.","Currently viewing \u2192"),
        ("Recommended next","OSCP or CPENT AI","OSCP is the gold-standard practical exam. CPENT AI adds advanced range and AI attack content.","View CPENT AI \u2192"),
    ],
    path_name="offensive security",
    path_chips=[("Security+","prev"),("CEH / PenTest+","you"),("OSCP","next"),("CPENT AI","prev"),("Red Team Lead","prev")],
    salary_html='Expected salary range after PenTest+: <strong style="color:#86efac">RM 6,000 \u2013 RM 11,500/month</strong> for junior pentester roles in Malaysian consultancies.',
    reviews_eyebrow="Student Reviews",
    reviews_head=("What our PenTest+","candidates say."),
    reviews_summary=("4.8",85,12,3,118),
    reviews=[
        ("\u2605\u2605\u2605\u2605\u2605","The two-hour 'workstation to Domain Admin' lab is exactly the kind of pressure you face on real engagements. By the time I sat the exam, AD privesc PBQs were second nature.","rav-b","HK","Hafidz Karim","Junior Pentester \u00b7 BAE Systems MY","\u2713 Passed first attempt"),
        ("\u2605\u2605\u2605\u2605\u2605","I'd done CEH and felt confident going into PenTest+. Then they made me write a real report. Six hours of writing. Painful \u2014 but the most useful skill I left with.","rav-m","SR","Sheryl Raj","Pentest Consultant \u00b7 EY Malaysia","\u2713 Passed first attempt"),
        ("\u2605\u2605\u2605\u2605","Burp Suite went from a tool I half-knew to one I drive fluently. The web-app pentest lab alone justified the course fee.","rav-g","JM","Jacky Mok","AppSec Engineer \u00b7 iflix","\u2713 Passed first attempt"),
        ("\u2605\u2605\u2605\u2605\u2605","Scoping and PCI-DSS mapping was the real value for me. I now lead my own pentest engagements and the SOWs my consultancy uses are based on the templates from this course.","rav-a","NA","Nadia Anwar","Senior Pentester \u00b7 GHL Systems","\u2713 Passed first attempt"),
    ],
    price="RM 4,500", price_orig="RM 5,200", price_save="Save 13%",
    price_note="Per person \u00b7 Includes voucher, range access, courseware, report templates",
    sidebar_meta=[
        ("Duration","5 days / 40 hrs"),
        ("Next intake","9 June 2026"),
        ("Format","On-site \u00b7 Hybrid"),
        ("Level","Intermediate\u2013Advanced"),
        ("Language","English"),
        ("Cert body","CompTIA"),
        ("Exam",'<span class="smeta-badge">Included</span>'),
    ],
    whats_included=[
        "CompTIA PenTest+ official courseware",
        "Pearson VUE voucher (PT0-003)",
        "60-day cyber range access",
        "3 full timed mock exams",
        "Burp Suite + Metasploit workshops",
        "SOW &amp; pentest report templates",
        "Post-course instructor access (45 days)",
        "Free single retake voucher",
        "Digital badge via CompTIA Marketplace",
    ],
    verify_items=[
        "Verifiable on CompTIA Marketplace",
        "Digital badge via Credly",
        "DoD 8570 / 8140 approved",
        "Stacks toward OSCP / CPENT",
    ],
    guarantee_text="Hit the 82% mock threshold and don't pass on first attempt? Retake voucher on us.",
))
