# -*- coding: utf-8 -*-
"""Legacy Wix-indexed bootcamp & skill pages — served at root URLs for SEO continuity."""
from _course_data import HERO_IMG, common_meta
from _course_schema_loader import schema_markup_for_slug

BATCH = []

BATCH.append(dict(
    slug="ai-ml-bootcamp",
    title="AI & Machine Learning Bootcamp",
    title_html='AI &amp; Machine Learning<br><em>Bootcamp</em>',
    vendor_short="Nexperts Skill", watermark="AI/ML", crumb_vendor="Bootcamps",
    subtitle="Python, scikit-learn, model evaluation, responsible AI and a capstone you can demo — structured for Malaysian teams moving from spreadsheets to production-minded ML literacy in five intensive days.",
    badges=[("cb-vendor", "Nexperts Bootcamp"), ("cb-level", "Intermediate"), ("cb-new", "2026 Cohort"), ("cb-hot", "AI Track")],
    hero_meta=common_meta("5 days / 40 hrs", "Instructor-Led + GPU Labs", "On-site · Virtual · Hybrid", 92, "9 Sep 2026"),
    hero_img=HERO_IMG,
    quick_wins=[
        ("🧠", "ML workflow", "Problem framing → features → train → evaluate"),
        ("🐍", "Python stack", "NumPy, pandas, scikit-learn patterns that scale"),
        ("📊", "Model quality", "Metrics that executives trust, not just accuracy"),
        ("🛡️", "Responsible AI", "Bias checks, explainability basics, deployment guardrails")],
    overview_eyebrow="What this bootcamp is",
    overview_head=("From curiosity", "to credible ML."),
    overview_p1="Organisations across banking, telco and GLCs are expected to pilot AI — but most teams stall at slide decks. This bootcamp gives practitioners a coached path from raw data to a defended model narrative, using datasets shaped for Malaysian business contexts.",
    overview_p2="You will not be asked to memorise algorithms in isolation. Every module ends in a lab checkpoint with instructor review, mirroring how data science leads run sprint reviews.",
    overview_p3="Graduates typically continue with Microsoft AI-102, DP-100 or AWS Machine Learning Specialty depending on cloud standardisation.",
    who_for=[
        ("📊", "Analysts upskilling", "You already work in Excel/SQL and need ML vocabulary."),
        ("💻", "Developers pivoting", "You can code but have not shipped models."),
        ("📈", "Product & strategy", "You sponsor AI initiatives and need literacy."),
        ("🏦", "Enterprise cohorts", "Closed-team pricing with HRD Corp paperwork."),
        ("🎓", "STEM graduates", "Portfolio piece for data roles."),
        ("🧪", "Innovation labs", "Rapid prototyping before vendor PoCs.")],
    prereqs=["Comfortable with Python basics (loops, functions)", "Familiarity with spreadsheets or SQL helpful", "Laptop with 16 GB RAM recommended"],
    prereqs_note="Optional Python refresher module available one week before start — ask enrolment.",
    curriculum_eyebrow="Bootcamp Curriculum",
    curriculum_head=("Five days.", "Sprint cadence."),
    curriculum_intro="Morning concept, afternoon lab, evening optional office hours for capstone teams.",
    modules=[
        ("01", "ML foundations", ["Supervised vs unsupervised", "Train/validation/test discipline", "Feature thinking", "Baseline models", "Lab: churn dataset baseline"]),
        ("02", "Data engineering lite", ["pandas pipelines", "Missing data strategies", "Encoding categoricals", "Leakage traps", "Lab: clean retail transactions"]),
        ("03", "Model families", ["Tree ensembles", "Linear models", "When to escalate complexity", "Hyperparameter intuition", "Lab: compare three estimators"]),
        ("04", "Evaluation & storytelling", ["Precision/recall trade-offs", "ROC & business thresholds", "Error analysis", "Executive summary slides", "Lab: defend metric choice"]),
        ("05", "Capstone & responsible AI", ["Bias & fairness checks", "Model cards intro", "Deployment patterns overview", "Demo rehearsal", "Lab: capstone presentation"])],
    labs_eyebrow="GPU-Ready Labs",
    labs_head=("Sandboxed.", "Reviewed."),
    labs_intro="Labs run on managed notebooks — no local CUDA setup required on day one.",
    labs=[
        ("01", "Baseline sprint", "Ship first model in 90 minutes.", "lt-recon", "ML"),
        ("02", "Feature store mindset", "Reproducible transforms.", "lt-defend", "Data"),
        ("03", "Ensemble bake-off", "Pick winner with evidence.", "lt-attack", "Models"),
        ("04", "Threshold workshop", "Align metrics to business cost.", "lt-recon", "Story"),
        ("05", "Capstone defense", "10-minute live demo.", "lt-attack", "Demo")],
    labs_footer="+ Mentor feedback on Git commit hygiene and README quality.",
    exam_eyebrow="Assessment",
    exam_head=("Capstone defense.", "Hiring-ready artefact."),
    exam_intro="Passing requires reproducible notebook, metric justification and live Q&A.",
    exam_main=dict(name="Capstone rubric", rows=[
        ("Notebook", "Runs end-to-end without manual hacks"),
        ("Metrics", "Appropriate for stated business goal"),
        ("Narrative", "Clear storyline for non-technical sponsor"),
        ("Passing", '<span class="pass-highlight">Meets rubric</span>'),
        ("Resit", "One coached revision week")]),
    exam_optional=None,
    mock_programme=[("01", "Metric drill", "Pick KPI before algorithm."), ("02", "Dry-run demo", "Peer critique."), ("03", "Executive Q&A", "Stress questions.")],
    pass_rate=92,
    pass_head_html='92% complete capstone<br><em>first attempt.</em>',
    pass_intro="We enforce reproducibility — the difference between a notebook demo and a production candidate.",
    pass_pills=["scikit-learn", "Capstone", "Responsible AI", "92% pass", "Mentors"],
    pass_compare=[("Video-only courses", "No reviewed artefact."), ("Nexperts", "Defended capstone + mentor sign-off.")],
    next_eyebrow="Your AI path",
    next_head=("Stack with", "cloud AI certs."),
    next_steps_intro="Continue with AI-102, DP-100 or AWS MLS depending on your platform strategy.",
    next_steps=[("Before this", "Python basics", "Bootcamp includes refresher pointers.", "Python →"), ("You are here", "AI/ML Bootcamp", "Practitioner literacy track.", "Currently viewing →"), ("Recommended next", "AI-102 / DP-100", "Operationalise on Azure.", "View AI-102 →")],
    path_name="data & AI",
    path_chips=[("Python", "prev"), ("AI/ML Bootcamp", "you"), ("AI-102", "next"), ("DP-100", "next")],
    salary_html='Data & AI analysts in KL: <strong style="color:#86efac">RM 5,500 – RM 11,000/month</strong> depending on portfolio depth.',
    reviews_eyebrow="Graduate voices",
    reviews_head=("What bootcamp", "graduates say."),
    reviews_summary=("4.8", 96, 22, 6, 118),
    reviews=[
        ("★★★★★", "Capstone review felt like a real sprint demo — prepared me for internal AI guild presentations.", "rav-b", "NS", "Nurul Syafiq", "Banking analyst", "✓ Capstone"),
        ("★★★★★", "Finally understood why my first model looked great in training but failed in production.", "rav-m", "KT", "Kevin Tan", "Engineer", "✓ Capstone"),
        ("★★★★", "Intense week — arrive rested.", "rav-g", "LM", "Li Mei", "Consultant", "✓ Capstone"),
        ("★★★★★", "Responsible AI module should be mandatory everywhere.", "rav-a", "AR", "Amir Rahman", "Product lead", "✓ Capstone")],
    price="RM 3,800", price_orig="RM 4,200", price_save="Save 10%",
    price_note="Per person · HRD Corp claim support available",
    sidebar_meta=[("Duration", "5 days / 40 hrs"), ("Next intake", "9 Sep 2026"), ("Format", "Hybrid"), ("Level", "Intermediate"), ("Language", "English"), ("Cert body", "Nexperts Skill"), ("Exam", '<span class="smeta-badge">Capstone</span>')],
    whats_included=["Lab environment", "Datasets", "Capstone coaching", "Certificate", "Slack mentor access"],
    verify_items=["Nexperts bootcamp verification ID", "Capstone repo tag archived"],
    guarantee_text="Follow our programme and clear the mock threshold before booking. Dedicated exam coaching and instructor support included.",
))

BATCH.append(dict(
    slug="gen-ai",
    title="Gen AI",
    title_html='Generative AI<br><em>Practitioner</em>',
    vendor_short="Nexperts Skill", watermark="GenAI", crumb_vendor="Bootcamps",
    subtitle="Prompt engineering, RAG, fine-tuning basics, evaluation and safe deployment — build production-minded Gen AI literacy for Malaysian teams shipping copilots, assistants and content workflows.",
    badges=[("cb-vendor", "Nexperts Bootcamp"), ("cb-level", "Intermediate"), ("cb-new", "AI 2026"), ("cb-hot", "Gen AI")],
    hero_meta=common_meta("5 days / 40 hrs", "Instructor-Led + LLM Labs", "On-site · Virtual · Hybrid", 93, "14 Oct 2026"),
    hero_img=HERO_IMG,
    quick_wins=[
        ("✨", "Prompt systems", "Structured prompts, few-shot patterns and guardrails"),
        ("🔗", "RAG pipelines", "Embeddings, retrieval, chunking and citation UX"),
        ("🎯", "Evaluation", "Human + automated metrics that catch regressions"),
        ("🛡️", "Safe deployment", "PII handling, red-teaming basics, audit trails")],
    overview_eyebrow="What this programme is",
    overview_head=("From demos", "to dependable Gen AI."),
    overview_p1="Generative AI pilots fail when teams treat LLMs like search boxes. This programme coaches practitioners through the full loop — problem framing, retrieval design, evaluation harnesses and deployment guardrails — using Malaysian enterprise scenarios (support, HR policy, sales enablement).",
    overview_p2="Every module ends in a lab checkpoint with instructor review. You leave with a defended capstone assistant, not slide screenshots.",
    overview_p3="Graduates typically continue with Microsoft AI-102, Azure OpenAI specialisation or AWS Generative AI depending on cloud standardisation.",
    who_for=[
        ("💻", "Developers & data", "You ship features and need Gen AI patterns."),
        ("📊", "Analysts & PMs", "You sponsor copilots and need hands-on literacy."),
        ("🏢", "Enterprise cohorts", "Closed-team pricing with HRD Corp paperwork."),
        ("🎓", "Career switchers", "Portfolio-ready Gen AI artefact."),
        ("🧪", "Innovation labs", "Rapid prototyping before vendor PoCs."),
        ("📈", "Leads & architects", "Evaluation and safety vocabulary for steering.")],
    prereqs=["Comfortable with Python or JavaScript basics", "Familiarity with APIs and JSON helpful", "Laptop with 16 GB RAM recommended"],
    prereqs_note="Optional LLM fundamentals primer available one week before start — ask enrolment.",
    curriculum_eyebrow="Programme curriculum",
    curriculum_head=("Five days.", "Build → evaluate → ship."),
    curriculum_intro="Morning concept, afternoon lab, evening optional office hours for capstone teams.",
    modules=[
        ("01", "Gen AI foundations", ["LLM capabilities & limits", "Token economics", "Prompt patterns", "Tool use intro", "Lab: baseline assistant"]),
        ("02", "RAG architecture", ["Chunking strategies", "Embeddings & vector stores", "Hybrid retrieval", "Citation UX", "Lab: policy Q&A bot"]),
        ("03", "Fine-tuning & adapters", ["When to fine-tune vs RAG", "Dataset hygiene", "LoRA concepts", "Cost trade-offs", "Lab: tone/style adapter"]),
        ("04", "Evaluation & observability", ["Golden sets", "LLM-as-judge pitfalls", "Regression suites", "Logging & tracing", "Lab: eval harness"]),
        ("05", "Capstone & governance", ["Red-team basics", "PII & retention", "Human-in-the-loop", "Demo rehearsal", "Lab: capstone defense"])],
    labs_eyebrow="LLM-Ready Labs",
    labs_head=("Sandboxed.", "Reviewed."),
    labs_intro="Labs run on managed notebooks and sandbox APIs — no local GPU required on day one.",
    labs=[
        ("01", "Prompt sprint", "Structured system + user prompts.", "lt-recon", "Prompts"),
        ("02", "RAG build", "Index docs and answer with citations.", "lt-defend", "Retrieval"),
        ("03", "Eval bake-off", "Compare two pipeline variants.", "lt-attack", "Metrics"),
        ("04", "Safety workshop", "Block jailbreaks and PII leaks.", "lt-recon", "Guardrails"),
        ("05", "Capstone defense", "10-minute live demo.", "lt-attack", "Demo")],
    labs_footer="+ Mentor feedback on repo hygiene, eval datasets and README quality.",
    exam_eyebrow="Assessment",
    exam_head=("Capstone defense.", "Production-minded artefact."),
    exam_intro="Passing requires reproducible pipeline, eval results and live Q&A.",
    exam_main=dict(name="Capstone rubric", rows=[
        ("Pipeline", "RAG or tool-use flow runs end-to-end"),
        ("Evaluation", "Documented metrics with golden set"),
        ("Safety", "Basic guardrails and logging in place"),
        ("Passing", '<span class="pass-highlight">Meets rubric</span>'),
        ("Resit", "One coached revision week")]),
    exam_optional=None,
    mock_programme=[("01", "Eval drill", "Define pass/fail before shipping."), ("02", "Dry-run demo", "Peer critique."), ("03", "Sponsor Q&A", "Stress questions.")],
    pass_rate=93,
    pass_head_html='93% complete capstone<br><em>first attempt.</em>',
    pass_intro="We enforce evaluation discipline — the difference between a demo and something you can ship.",
    pass_pills=["RAG", "Eval harness", "Guardrails", "93% pass", "Mentors"],
    pass_compare=[("Video-only courses", "No reviewed artefact."), ("Nexperts", "Defended capstone + mentor sign-off.")],
    next_eyebrow="Your Gen AI path",
    next_head=("Stack with", "cloud AI certs."),
    next_steps_intro="Continue with AI-102, Azure OpenAI or AWS Generative AI depending on your platform strategy.",
    next_steps=[("Before this", "Python or JS basics", "Programme includes refresher pointers.", "Python →"), ("You are here", "Gen AI", "Practitioner literacy track.", "Currently viewing →"), ("Recommended next", "AI-102", "Operationalise on Azure.", "View AI-102 →")],
    path_name="Gen AI",
    path_chips=[("Python/JS", "prev"), ("Gen AI", "you"), ("AI-102", "next"), ("Agentic AI", "next")],
    salary_html='Gen AI engineers in KL: <strong style="color:#86efac">RM 7,500 – RM 14,000/month</strong> depending on portfolio depth.',
    reviews_eyebrow="Graduate voices",
    reviews_head=("What graduates", "say."),
    reviews_summary=("4.9", 88, 18, 4, 94),
    reviews=[
        ("★★★★★", "RAG lab finally made retrieval click — our internal policy bot shipped two weeks after graduation.", "rav-b", "NS", "Nurul Syafiq", "Platform engineer", "✓ Capstone"),
        ("★★★★★", "Eval module saved us from shipping a flashy demo that failed on edge cases.", "rav-m", "KT", "Kevin Tan", "ML engineer", "✓ Capstone"),
        ("★★★★", "Intense week — arrive with a real use case in mind.", "rav-g", "LM", "Li Mei", "Product manager", "✓ Capstone"),
        ("★★★★★", "Guardrails section should be mandatory for every Gen AI team.", "rav-a", "AR", "Amir Rahman", "Tech lead", "✓ Capstone")],
    price="RM 2,000", price_orig="RM 10,000", price_save="Save 80%",
    price_note="Per person · HRD Corp claim support available",
    sidebar_meta=[("Duration", "5 days / 40 hrs"), ("Next intake", "14 Oct 2026"), ("Format", "Hybrid"), ("Level", "Intermediate"), ("Language", "English"), ("Cert body", "Nexperts Skill"), ("Exam", '<span class="smeta-badge">Capstone</span>')],
    whats_included=["Lab environment", "Sample datasets", "Capstone coaching", "Certificate", "Slack mentor access"],
    verify_items=["Nexperts bootcamp verification ID", "Capstone repo tag archived"],
    guarantee_text="Follow our programme and clear the mock threshold before booking. Dedicated exam coaching and instructor support included.",
))

BATCH.append(dict(
    slug="agentic-ai",
    seo_title="Professional Agentic AI Engineering Course Malaysia | Nexperts Academy",
    seo_description="Live instructor-led Agentic AI Engineering in Malaysia — 20 sessions, 80 hours, Python to production multi-agent systems. LangChain, LangGraph, CrewAI, RAG, FastAPI. Cohort from RM 799.",
    seo_keywords="Agentic AI Engineering, Agentic AI course Malaysia, LangGraph, LangChain, CrewAI, multi-agent systems, RAG training Malaysia, Nexperts Academy",
    schema_markup=schema_markup_for_slug("agentic-ai"),
    title="Agentic AI Engineering",
    title_html='Professional Agentic AI<br><em>Engineering</em>',
    vendor_short="Nexperts Skill", watermark="Agents", crumb_vendor="AI & Automation",
    subtitle="Live instructor-led training from Python basics to production multi-agent systems — 20 intensive sessions, portfolio-ready builds.",
    badges=[("cb-vendor", "Nexperts Skill"), ("cb-level", "Beginner → Advanced"), ("cb-new", "AI 2026"), ("cb-hot", "20 Sessions")],
    hero_meta=common_meta("20 sessions / 80 hrs", "Live Online · Teams", "Classroom · Virtual · Hybrid", 94, "16 Nov 2026"),
    hero_img=HERO_IMG,
    quick_wins=[
        ("⏱", "20 live sessions", "80 hours · 7 weeks · Mon · Wed · Fri · 6pm–10pm"),
        ("💻", "Live Online · Teams", "Build alongside the instructor — no passive watching"),
        ("🛠", "Python → production", "RAG, agents, LangGraph, FastAPI, Streamlit"),
        ("🎓", "Certificate + portfolio", "Deployed multi-agent capstone you can show employers")],
    overview_eyebrow="Professional Agentic AI Engineering",
    overview_head=("Build AI,", "not just use it."),
    overview_p1="This is Nexperts Academy’s Professional Agentic AI Engineering programme in Malaysia — live instructor-led training from Python foundations through production multi-agent systems. Over 20 intensive sessions (80 hours across 7 weeks) you build portfolio-ready projects with LangChain, LangGraph, CrewAI, AutoGen, Azure AI and more.",
    overview_p2="Cohort 5 (26 Oct – 11 Dec 2026) is full. Cohort 6 runs 16 Nov 2026 – 2 Jan 2027 (Mon, Wed, Fri · 6pm–10pm · 7 weeks) on Microsoft Teams. 100 seats only. Market value RM 12,000+ — current promotional price RM 799.",
    overview_quote="20 Live Sessions · 80 Hours · 7 Weeks · Certificate",
    overview_p3="Every session is 4 hours of live, hands-on training — you build with the instructor. Leave with a deployed multi-agent system, a production RAG pipeline, fluency across 5+ AI frameworks, and a Nexperts Academy Professional Certificate in Agentic AI Engineering.",
    overview_sections=[
        {
            "eyebrow": "Programme Objectives",
            "eyebrow_class": "m",
            "intro": "10 things you will be able to do when you finish — not theory goals. Actual skills you can demonstrate on Day 1 after you leave.",
            "bullets": [
                "Build multi-agent AI systems where specialised agents collaborate to solve complex, real-world tasks autonomously",
                "Design and implement end-to-end RAG pipelines — from document ingestion to production-grade retrieval and generation",
                "Apply advanced retrieval techniques: semantic chunking, hybrid search, reranking, query rewriting and adaptive routing",
                "Develop production-ready LLM applications using LangChain, LangGraph, CrewAI, AutoGen and Azure AI platforms",
                "Integrate AI agents with external tools, APIs, databases and real-time data sources via MCP and function calling",
                "Implement short-term and long-term memory in agents and orchestrate multi-agent workflows using LangGraph state machines",
                "Evaluate and debug AI agent systems using LangSmith tracing, LLM-as-a-judge, hallucination detection and guardrails",
                "Optimise AI systems for latency, cost and performance — caching, retrieval tuning, model selection strategy",
                "Deploy and monitor scalable AI applications with FastAPI, Streamlit, Hugging Face and observability tools",
                "Build safe, responsible AI systems with guardrails, privacy controls and ethical governance frameworks",
            ],
        },
        {
            "eyebrow": "What You Walk Away With",
            "eyebrow_class": "g",
            "intro": "Real outcomes — not just a certificate. By the end of 80 hours, here’s exactly what you’ll have built and can demonstrate.",
            "skill_groups": [
                ("01 — Deployed Multi-Agent AI Financial Advisor", [
                    "Production-grade system with 5 specialised agents (Data, Analysis, Risk, Advisory, QA) orchestrated via LangGraph, deployed on FastAPI with Streamlit UI — goes directly into your portfolio.",
                ]),
                ("02 — End-to-End RAG Pipeline You Built and Evaluated", [
                    "Production RAG with hybrid search, cross-encoder reranking, query rewriting, metadata filtering and RAGAS evaluation — built from scratch so you know why every component exists.",
                ]),
                ("03 — Hands-on Fluency in 5+ AI Frameworks", [
                    "LangChain, LangGraph, CrewAI, AutoGen, Flowise — real projects with each, not just demos. You’ll know when to use which framework and why.",
                ]),
                ("04 — Production-Grade Skills Most Tutorials Skip", [
                    "Evaluation, observability, guardrails, cost optimisation, latency tuning, deployment and monitoring — what separates hobbyists from engineers.",
                ]),
                ("05 — Professional Certificate of Completion", [
                    "Upon successful completion of the 20-session programme and capstone evaluation, you receive a Nexperts Academy Professional Certificate in Agentic AI Engineering.",
                ]),
                ("06 — Lifetime Access to Materials & Community", [
                    "Slides, notebooks, recordings and our private alumni community — stay connected with peers and instructors after the cohort ends.",
                ]),
            ],
        },
        {
            "eyebrow": "Frameworks & Tools",
            "bullets": [
                "Python · VS Code · pandas · asyncio",
                "NLTK · SpaCy · TensorFlow · Hugging Face",
                "LangChain · LangGraph · CrewAI · AutoGen · Flowise",
                "Azure OpenAI · Azure AI Studio · Anthropic Claude",
                "ChromaDB · FAISS · FastAPI · Streamlit · LangSmith",
            ],
        },
    ],
    who_for=[
        ("💻", "Developers & IT pros", "Software developers, IT professionals or data analysts wanting to specialise in AI engineering."),
        ("🎓", "Graduates & switchers", "Fresh graduates or career switchers with basic programming who want to enter AI."),
        ("🏢", "Owners & tech leads", "Business owners or technical leads who want to build AI systems for their organisation."),
        ("📺", "Beyond YouTube", "You’ve tried AI tutorials but want structured, deep, hands-on live instruction."),
        ("📅", "Full presence", "You can commit to Mon, Wed, Fri · 6pm–10pm · 7 weeks — no excuses."),
        ("🚀", "Portfolio outcome", "You want a portfolio-ready, deployed AI system — not just a certificate.")],
    overview_sections_after_who=[
        {
            "eyebrow": "Look elsewhere if",
            "eyebrow_class": "m",
            "intro": "This programme is a rigorous intensive — not a casual course.",
            "bullets": [
                "You want passive video content you can watch whenever you feel like it",
                "You can’t commit to all live sessions (Mon, Wed, Fri, 6pm–10pm)",
                "You expect to learn without doing — every session requires you to build, not just listen",
                "You have zero interest in writing any code — some Python is involved and required",
            ],
        },
    ],
    prereqs=[
        "Basic programming comfort (variables, loops, functions) — we start with Python foundations",
        "Laptop suitable for coding; stable internet for Microsoft Teams",
        "Commitment to all live sessions: Mon · Wed · Fri · 6pm–10pm for 7 weeks",
    ],
    prereqs_note="Ask enrolment for a free readiness check before joining Cohort 6.",
    curriculum_eyebrow="The Curriculum",
    curriculum_head=("20 sessions. 80 hours.", "From Python to production."),
    curriculum_intro="Cohort 5 (26 Oct – 11 Dec 2026) is full. Cohort 6: 16 Nov 2026 – 2 Jan 2027 (Mon, Wed, Fri · 6pm–10pm · 7 weeks). 100 seats only. Each session is 4 hours of live, hands-on training on Microsoft Teams — you build alongside the instructor.",
    modules=[
        ("01", "Python Setup & Foundations for AI", [
            "Python environments (venv/conda), VS Code setup, pip, variables, data types, strings, loops, functions. Build a simple prompt formatter.",
            "Tools: Python · VS Code",
        ]),
        ("02", "Python for Data & APIs", [
            "Lists, dicts, JSON, file I/O, try-except, requests library, API keys, environment variables. Call a live API.",
            "Tools: requests · json · os",
        ]),
        ("03", "OOP, Async & Data Handling for AI Systems", [
            "Classes for AI components, async/await for parallel API calls, pandas basics, regex text processing. Mini AI pipeline.",
            "Tools: pandas · asyncio",
        ]),
        ("04", "NLP Foundations & Text Processing", [
            "Tokenization, lemmatization, embeddings, Word2Vec, TF-IDF, classification, sentiment, NER, POS, ingestion with pandas.",
            "Tools: NLTK · SpaCy",
        ]),
        ("05", "Language Models & Transformers", [
            "RNN→LSTM→Transformers evolution, attention, BPE/WordPiece, pretraining vs fine-tuning, RLHF, LLMs vs SLMs.",
            "Tools: TensorFlow · Hugging Face",
        ]),
        ("06", "Generative AI, Prompting & Multi-Modal", [
            "Prompt engineering, temperature/top-k/top-p, hallucination control, multi-modal (text+vision+audio), GPT vision, voice AI, STT.",
            "Tools: Azure AI · Copilot",
        ]),
        ("07", "AI Platforms & LangChain Foundations", [
            "OpenAI API, LangChain — chat models, prompt templates, chains, tools, memory. AutoGen intro. Build quiz bot and chatbot.",
            "Tools: LangChain · AutoGen",
        ]),
        ("08", "Vector Databases & Introduction to RAG", [
            "Embeddings, vector DBs (ChromaDB, FAISS, Pinecone), similarity search, document loaders, chunking. Build a retrieval pipeline.",
            "Tools: ChromaDB · LangChain",
        ]),
        ("09", "Production RAG", [
            "Document ingestion, chunking, query transformation, hybrid retrieval, context optimisation, caching, RAGAS evaluation.",
            "Tools: LangChain · Azure OpenAI",
        ]),
        ("10", "Advanced RAG", [
            "Multi-hop reasoning, knowledge graphs, Naïve vs Advanced vs Agentic RAG, cost optimisation, guardrails, Corrective RAG, Graph RAG.",
            "Tools: LangChain · Azure OpenAI",
        ]),
        ("11", "Agentic AI Foundations", [
            "Agent lifecycle, tool use, API connections, router vs autonomous architectures, single vs multi-agent systems, state, failure handling.",
            "Tools: LangChain · CrewAI · AutoGen",
        ]),
        ("12", "Decision Making, Planning & MCP", [
            "Goal setting, hierarchical vs reactive planning, MCP fundamentals vs OpenAI function calling, MCP setup, IDE agents, multi-tool orchestration.",
            "Tools: Anthropic Claude · AutoGen",
        ]),
        ("13", "Custom Copilots & Multi-Modal Case Study", [
            "Custom copilots with Azure AI Studio. Project: Multi-modal travel planner — 7 agents (User, Planner, Vision, RAG, Speech, Summariser, Weather).",
            "Tools: Azure AI Studio · CrewAI",
        ]),
        ("14", "Memory & Knowledge Retrieval in Agents", [
            "Memory architectures (short/long-term, vector vs symbolic, episodic vs semantic), compression, Agentic RAG, customer support case study.",
            "Tools: LangChain · ChromaDB",
        ]),
        ("15", "LangGraph Orchestration & Multi-Agent Systems", [
            "LangGraph state machines, agent graphs, CrewAI orchestration, comparing LangGraph vs CrewAI vs Flowise, resilient workflows.",
            "Tools: LangGraph · CrewAI · Flowise",
        ]),
        ("16", "Learning, Adaptation & Deployment", [
            "RL fundamentals, RLHF, reward systems. App structure (API+Worker+VectorDB), hosting, latency, observability with LangSmith.",
            "Tools: Streamlit · Hugging Face · LangSmith",
        ]),
        ("17", "Advanced Multi-Agent Orchestration", [
            "Build a full LangGraph multi-agent system. Router → Planner → parallel Research+Analysis → Synthesis. Deploy end-to-end.",
            "Tools: LangGraph · FastAPI",
        ]),
        ("18", "Evaluation, Debugging & Ethics", [
            "Agent evaluation metrics, logging, tracing, LLM-as-a-judge, hallucination detection, guardrails, failure modes, responsible AI.",
            "Tools: LangSmith",
        ]),
        ("19", "Capstone — Build Phase", [
            "AI Financial Advisor: Data → Analysis → Risk → Advisory → QA agents. Full LangGraph orchestration, evaluation, FastAPI + Streamlit.",
            "Tools: LangGraph · FastAPI · Streamlit",
        ]),
        ("20", "Capstone — Present, Deploy & Graduate", [
            "Final deployment, live Q&A, peer showcase. Each participant presents. Evaluation against production criteria. Certificate awarded.",
            "Tools: All tools · Certificate",
        ]),
    ],
    labs_eyebrow="Hands-on Builds",
    labs_head=("Portfolio-ready.", "Deployed."),
    labs_intro="You don’t watch demos — you ship artefacts: RAG pipelines, multi-agent systems and a capstone Financial Advisor.",
    labs=[
        ("01", "Python → API pipeline", "Prompt formatter, live API calls, mini AI pipeline.", "lt-recon", "Foundations"),
        ("02", "Production RAG", "Hybrid retrieval, caching, RAGAS evaluation.", "lt-defend", "RAG"),
        ("03", "Travel planner agents", "7-agent multi-modal case study on Azure + CrewAI.", "lt-attack", "Agents"),
        ("04", "LangGraph orchestration", "Router → Planner → Research → Synthesis.", "lt-recon", "Orchestration"),
        ("05", "Financial Advisor capstone", "5-agent system on FastAPI + Streamlit.", "lt-attack", "Capstone")],
    labs_footer="+ Lifetime access to slides, notebooks, recordings and alumni community after the cohort.",
    exam_eyebrow="Assessment",
    exam_head=("Capstone evaluation.", "Certificate awarded."),
    exam_intro="Passing requires a working multi-agent system, deployment, evaluation against production criteria and a live presentation.",
    exam_main=dict(name="Capstone rubric", rows=[
        ("Build", "AI Financial Advisor with 5 specialised agents"),
        ("Stack", "LangGraph orchestration + FastAPI + Streamlit"),
        ("Quality", "Evaluation, guardrails and observability in place"),
        ("Passing", '<span class="pass-highlight">Certificate issued</span>'),
        ("Resit", "Coached revision before next presentation window")]),
    exam_optional=None,
    mock_programme=[
        ("01", "Mid-cohort checkpoint", "RAG + agent labs reviewed with mentor feedback."),
        ("02", "Capstone dry-run", "Peer critique before final deploy."),
        ("03", "Live graduate showcase", "Present, defend and earn the certificate."),
    ],
    mock_title="How we keep you production-ready",
    pass_rate=94,
    pass_head_html='94% complete the cohort<br><em>with mentor support.</em>',
    pass_intro="Live attendance, hands-on builds and a defended capstone — agents that work beyond demos.",
    pass_pills=["20 sessions", "LangGraph", "RAG", "Capstone", "Certificate"],
    pass_compare=[
        ("Passive video courses", "No live builds, weak portfolio proof."),
        ("Nexperts", "Live Teams intensives + deployed multi-agent capstone."),
    ],
    next_eyebrow="Your agentic path",
    next_head=("From foundations", "to production agents."),
    next_steps_intro="This programme starts from Python basics and ends in deployed multi-agent systems. Pair with cloud AI certifications when you want vendor credentials next.",
    next_steps=[
        ("You are here", "Agentic AI Engineering", "20-session professional track.", "Currently viewing →"),
        ("Recommended next", "Azure / AWS AI certs", "Operationalise on a cloud platform.", "Talk to us →"),
        ("Also explore", "Gen AI / AI+ML paths", "Complementary short programmes.", "Browse AI →"),
    ],
    path_name="Agentic AI Engineering",
    path_chips=[("Python", "prev"), ("Agentic AI Eng.", "you"), ("Cloud AI certs", "next"), ("Platform", "next")],
    salary_html='Agentic AI / platform engineers in KL: <strong style="color:#86efac">RM 9,000 – RM 16,500/month</strong> depending on system complexity and portfolio depth.',
    reviews_eyebrow="Graduate voices",
    reviews_head=("What graduates", "say."),
    reviews_summary=("4.8", 72, 14, 3, 78),
    reviews=[
        ("★★★★★", "Supervisor pattern lab mapped directly to our internal ops automation — shipped in sprint two.", "rav-b", "NS", "Nurul Syafiq", "Platform lead", "✓ Capstone"),
        ("★★★★★", "Observability module caught issues our PoC hid for months.", "rav-m", "KT", "Kevin Tan", "Staff engineer", "✓ Capstone"),
        ("★★★★", "The live Mon/Wed/Fri cadence kept me shipping every week — not another unfinished tutorial.", "rav-g", "LM", "Li Mei", "Architect", "✓ Capstone"),
        ("★★★★★", "Capstone Financial Advisor is the piece I show in interviews.", "rav-a", "AR", "Amir Rahman", "Engineering manager", "✓ Capstone")],
    faqs=[
        ("What is the schedule for Cohort 6?", "Cohort 6 runs 16 Nov 2026 – 2 Jan 2027, Monday · Wednesday · Friday, 6pm–10pm (7 weeks, 20 live sessions on Microsoft Teams). Cohort 5 is full."),
        ("What is the price?", "Market value is RM 12,000+. The current promotional price is RM 799. Confirm the latest offer with enrolment when you enquire."),
        ("Do I need prior AI experience?", "Basic programming comfort is enough — Session 1 starts with Python foundations. You must be willing to write code and attend all live sessions."),
        ("Is this the same as a short Agentic AI workshop?", "No. This is the full Professional Agentic AI Engineering programme: 80 hours from Python to production multi-agent systems, with a deployed capstone."),
        ("What certificate do I receive?", "A Nexperts Academy Professional Certificate in Agentic AI Engineering upon successful completion of the 20-session programme and capstone evaluation."),
        ("Which tools will I learn?", "Python, LangChain, LangGraph, CrewAI, AutoGen, Flowise, Azure OpenAI / AI Studio, Hugging Face, ChromaDB/FAISS, FastAPI, Streamlit, LangSmith, Anthropic Claude and more."),
    ],
    faq_head=("Agentic AI Engineering", "FAQs."),
    price="RM 799", price_orig="RM 12,000", price_save="Save 93%",
    price_note="Promotional cohort price · enquire to confirm seat availability",
    sidebar_meta=[
        ("Duration", "20 sessions / 80 hrs"),
        ("Schedule", "Mon · Wed · Fri · 6pm–10pm"),
        ("Next intake", "16 Nov 2026"),
        ("Format", "Live Online · Teams"),
        ("Level", "Beginner → Advanced"),
        ("Language", "English"),
        ("Cert body", "Nexperts Skill"),
        ("Exam", '<span class="smeta-badge">Capstone</span>'),
    ],
    whats_included=["Lab environment", "Course materials & recordings", "Capstone coaching", "Certificate", "Alumni community access"],
    verify_items=["Nexperts Professional Certificate ID", "Capstone project archived"],
    guarantee_text="Attend the live sessions, complete the builds and clear the capstone evaluation — mentor support included throughout the 7 weeks.",
))

BATCH.append(dict(
    slug="cyber-security-bootcamp",
    title="Cyber Security Bootcamp",
    title_html='Cyber Security<br><em>Bootcamp</em>',
    vendor_short="Nexperts Skill", watermark="SEC", crumb_vendor="Bootcamps",
    subtitle="Hands-on blue-team and ethical-hacking fundamentals — reconnaissance, hardening, detection, incident response and safe lab tradecraft for Malaysian enterprises building their first security champions.",
    badges=[("cb-vendor", "Nexperts Bootcamp"), ("cb-level", "Foundation → Intermediate"), ("cb-new", "SOC Ready"), ("cb-hot", "Security")],
    hero_meta=common_meta("5 days / 40 hrs", "Range Labs + Tabletops", "On-site · Virtual · Hybrid", 94, "16 Sep 2026"),
    hero_img=HERO_IMG,
    quick_wins=[
        ("🛡️", "Defensive core", "Asset inventory, patching priorities, hardening baselines"),
        ("🔍", "Detection", "Log sources, alert triage, MITRE mapping intro"),
        ("⚔️", "Offensive lens", "Safe recon & vuln scanning in isolated range"),
        ("🚨", "IR tabletop", "Containment decisions with MY regulatory context")],
    overview_eyebrow="What this bootcamp is",
    overview_head=("Security skills", "you can prove."),
    overview_p1="Cyber hiring in Malaysia increasingly tests practical judgement, not acronym collection. This bootcamp blends defensive operations with ethical offensive labs so you understand both sides of an attack chain — in a legal, isolated environment.",
    overview_p2="Instructors run SOC programmes for regional enterprises; scenarios reference BNM RMiT expectations, PDPA breach notification thinking and common phishing patterns seen in MY inboxes.",
    overview_p3="Many graduates continue to CEH, CompTIA Security+ or SC-200 depending on role target.",
    who_for=[
        ("🖥️", "IT administrators", "You are the accidental security team."),
        ("🎓", "Career switchers", "Need portfolio-friendly labs."),
        ("🏢", "GRC & risk", "You want technical empathy."),
        ("👥", "Corporate cohorts", "Build a champion network."),
        ("🔐", "Junior analysts", "Accelerate before cert exams."),
        ("📡", "Network engineers", "Extend into security operations.")],
    prereqs=["Basic TCP/IP and OS familiarity", "No prior security certification required", "Signed acceptable-use policy for range labs"],
    prereqs_note="Laptop with admin rights for VPN range access — details emailed pre-course.",
    curriculum_eyebrow="Bootcamp Curriculum",
    curriculum_head=("Five days.", "Range to tabletop."),
    curriculum_intro="Every offensive technique is paired with a defensive countermeasure discussion.",
    modules=[
        ("01", "Security landscape", ["Threat actors in MY", "Kill chain overview", "Policy & governance touchpoints", "Lab: asset discovery"]),
        ("02", "Hardening & vuln mgmt", ["Patch prioritisation", "CIS benchmarks intro", "Vulnerability scanning ethics", "Lab: harden Windows/Linux"]),
        ("03", "Detection engineering lite", ["Log sources", "Sigma rules intro", "Alert triage playbook", "Lab: find malicious sign-in"]),
        ("04", "Ethical offensive labs", ["Recon methodology", "Safe scanning", "Exploit concepts (isolated)", "Lab: pivot in range only"]),
        ("05", "Incident response", ["Tabletop facilitation", "Containment trade-offs", "Comms & evidence", "Lab: IR simulation"])],
    labs_eyebrow="Range Labs",
    labs_head=("Isolated.", "Legal."),
    labs_intro="All offensive labs occur in Nexperts-hosted ranges — no scanning of production networks.",
    labs=[
        ("01", "Asset map", "Document crown jewels.", "lt-recon", "GRC"),
        ("02", "Hardening sprint", "Close critical findings.", "lt-defend", "Ops"),
        ("03", "Detection hunt", "Triage realistic alerts.", "lt-recon", "SOC"),
        ("04", "Range mission", "Controlled attack path.", "lt-attack", "Red"),
        ("05", "IR tabletop", "Executive briefing.", "lt-attack", "IR")],
    labs_footer="+ Range VPN credentials revoked automatically after bootcamp.",
    exam_eyebrow="Assessment",
    exam_head=("Practical + tabletop.", "Role-ready."),
    exam_intro="Passing requires range lab completion and facilitated IR tabletop participation.",
    exam_main=dict(name="Bootcamp assessment", rows=[
        ("Range labs", "All checkpoints signed by instructor"),
        ("Tabletop", "Clear containment rationale"),
        ("Ethics", "Acceptable-use compliance"),
        ("Passing", '<span class="pass-highlight">Meets rubric</span>'),
        ("Resit", "Range remediation day")]),
    exam_optional=None,
    pass_rate=94,
    pass_head_html='94% complete bootcamp<br><em>requirements.</em>',
    pass_intro="We optimise for judgement under pressure — what SOC hiring managers actually test.",
    pass_pills=["Range labs", "Tabletop", "MITRE intro", "94% pass", "MY context"],
    pass_compare=[("Theory-only courses", "No safe offensive exposure."), ("Nexperts", "Balanced blue/red with IR.")],
    next_eyebrow="Your security path",
    next_head=("Certify", "the skills."),
    next_steps_intro="Continue with CEH for offensive depth, Security+ for breadth, or SC-200 for Microsoft SOC.",
    next_steps=[("Before this", "Networking basics", "CCNA knowledge helps but not required.", "CCNA →"), ("You are here", "Cyber Bootcamp", "Practitioner foundation.", "Currently viewing →"), ("Recommended next", "CEH / Security+", "Pick offensive or broad cert.", "View CEH →")],
    path_name="cybersecurity",
    path_chips=[("IT Ops", "prev"), ("Cyber Bootcamp", "you"), ("CEH", "next"), ("SC-200", "next")],
    salary_html='Security analysts in KL: <strong style="color:#86efac">RM 5,000 – RM 10,500/month</strong> depending on SOC vs GRC track.',
    reviews_eyebrow="Graduate voices",
    reviews_head=("What defenders", "say."),
    reviews_summary=("4.9", 112, 24, 4, 132),
    reviews=[
        ("★★★★★", "Tabletop on day 5 was the most realistic IR exercise I have attended locally.", "rav-b", "FZ", "Farid Zainal", "IT manager", "✓ Completed"),
        ("★★★★★", "Range labs demystified what our pentest reports actually mean.", "rav-m", "JC", "Jessica Chua", "Sysadmin", "✓ Completed"),
        ("★★★★", "Packed week — worth it.", "rav-g", "HP", "Hafiz Prakash", "Graduate", "✓ Completed"),
        ("★★★★★", "Instructor mapped alerts to MITRE without hand-waving.", "rav-a", "WL", "Wong Li", "SOC L1", "✓ Completed")],
    price="RM 3,600", price_orig="RM 4,000", price_save="Save 10%",
    price_note="Per person · Includes range access for bootcamp duration",
    sidebar_meta=[("Duration", "5 days / 40 hrs"), ("Next intake", "16 Sep 2026"), ("Format", "Hybrid"), ("Level", "Foundation+"), ("Language", "English"), ("Cert body", "Nexperts Skill"), ("Exam", '<span class="smeta-badge">Practical</span>')],
    whats_included=["Range access", "Lab guides", "Tabletop materials", "Certificate"],
    verify_items=["Nexperts bootcamp verification", "Range completion log"],
    guarantee_text="Miss a lab checkpoint? Attend remediation Friday within 30 days.",
))

BATCH.append(dict(
    slug="android-development",
    title="Android Development",
    title_html='Android<br><em>Development</em>',
    vendor_short="Nexperts Skill", watermark="AND", crumb_vendor="Mobile Dev",
    subtitle="Kotlin, Jetpack Compose, MVVM architecture, REST integration and Play Store readiness — build and ship a portfolio app with Malaysian fintech and logistics UX patterns in six coached days.",
    badges=[("cb-vendor", "Nexperts Skill"), ("cb-level", "Beginner → Intermediate"), ("cb-new", "Compose 2026"), ("cb-hot", "Mobile")],
    hero_meta=common_meta("6 days / 48 hrs", "Project Labs + Code Review", "On-site · Virtual · Hybrid", 90, "23 Sep 2026"),
    hero_img=HERO_IMG,
    quick_wins=[
        ("📱", "Modern UI", "Jetpack Compose layouts & state"),
        ("🏗️", "Architecture", "MVVM, repositories, testable layers"),
        ("🌐", "APIs", "Retrofit, auth tokens, error UX"),
        ("🚀", "Ship", "Release build, signing basics, Play checklist")],
    overview_eyebrow="What this course is",
    overview_head=("Ship an Android app", "employers can install."),
    overview_p1="Mobile roles in Malaysia increasingly require a GitHub repo or Play Store listing — not tutorial certificates. You will build a booking-style app (anonymised MY fintech brief) with code reviews mirroring industry PR feedback.",
    overview_p2="We emphasise maintainability: dependency injection patterns, navigation graphs and instrumentation tests at the right depth for junior interviews.",
    overview_p3="Graduates often pair this with full-stack web or Kotlin backend modules for product teams.",
    who_for=[
        ("💻", "Java developers", "Pivoting to Kotlin mobile."),
        ("🎓", "CS graduates", "Need a portfolio app."),
        ("🏢", "Product squads", "Upskill internal builders."),
        ("🔄", "Career switchers", "After our Python bootcamp."),
        ("📱", "Freelancers", "Deliver client apps professionally."),
        ("👥", "Corporate cohorts", "Custom briefs available.")],
    prereqs=["Basic programming (any language)", "Android Studio installed", "GitHub account"],
    prereqs_note="Pre-course setup checklist includes emulator or physical device guidance.",
    curriculum_eyebrow="Course Curriculum",
    curriculum_head=("Six days.", "Compose-first."),
    curriculum_intro="Each day merges concept, live coding and PR-style review.",
    modules=[
        ("01", "Kotlin & tooling", ["Language essentials", "Android Studio workflow", "Gradle basics", "Lab: Hello Compose"]),
        ("02", "Compose UI", ["Layouts", "State hoisting", "Theming", "Lab: multi-screen flow"]),
        ("03", "Architecture", ["ViewModel", "Repository", "Coroutines intro", "Lab: offline-first list"]),
        ("04", "Networking", ["REST integration", "Auth headers", "Error states", "Lab: live API module"]),
        ("05", "Quality & tests", ["Unit tests", "UI tests intro", "Crashlytics mindset", "Lab: stabilise build"]),
        ("06", "Capstone ship", ["Signing overview", "Play Console checklist", "Demo rehearsal", "Lab: store-ready build"])],
    labs_eyebrow="Project Labs",
    labs_head=("PR by PR.", "Reviewed."),
    labs_intro="Instructors tag release checkpoints in your repo like a real sprint.",
    labs=[
        ("01", "Compose shell", "Navigation skeleton.", "lt-recon", "UI"),
        ("02", "State lab", "Form validation UX.", "lt-defend", "UI"),
        ("03", "API slice", "Authenticated fetch.", "lt-attack", "API"),
        ("04", "Test harness", "Critical path tests.", "lt-recon", "QA"),
        ("05", "Release candidate", "Signed debug build.", "lt-attack", "Ship"),
        ("06", "Demo", "Play listing draft.", "lt-attack", "Capstone")],
    labs_footer="+ Kotlin style guide review on final PR.",
    exam_eyebrow="Assessment",
    exam_head=("App demo + repo.", "Portfolio piece."),
    exam_intro="Passing requires installable build, README and 10-minute demo.",
    exam_main=dict(name="Capstone rubric", rows=[
        ("Build", "Installs without manual steps"),
        ("Architecture", "Clear separation of concerns"),
        ("UX", "Handles loading/error states"),
        ("Passing", '<span class="pass-highlight">Meets rubric</span>'),
        ("Resit", "One remediation sprint")]),
    exam_optional=None,
    pass_rate=90,
    pass_head_html='90% ship portfolio app<br><em>on schedule.</em>',
    pass_intro="We enforce release hygiene — the gap between tutorial apps and hireable engineers.",
    pass_pills=["Kotlin", "Compose", "MVVM", "90% ship", "Code review"],
    pass_compare=[("Video courses", "No reviewed repo."), ("Nexperts", "PR reviews + demo defense.")],
    next_eyebrow="Your mobile path",
    next_head=("Expand to", "full product stack."),
    next_steps_intro="Pair with full-stack web or iOS for cross-platform product teams.",
    next_steps=[("Before this", "Programming basics", "Python bootcamp recommended.", "Python →"), ("You are here", "Android Development", "Mobile engineering track.", "Currently viewing →"), ("Recommended next", "Full Stack Web", "Own the API layer too.", "View Full Stack →")],
    path_name="mobile engineering",
    path_chips=[("Kotlin", "prev"), ("Android", "you"), ("Full Stack", "next"), ("iOS", "next")],
    salary_html='Android developers in KL: <strong style="color:#86efac">RM 4,800 – RM 9,500/month</strong> depending on portfolio.',
    reviews_eyebrow="Student reviews",
    reviews_head=("What our mobile", "builders say."),
    reviews_summary=("4.7", 74, 18, 8, 86),
    reviews=[
        ("★★★★★", "PR feedback on my ViewModel layer was worth the course fee alone.", "rav-b", "DA", "Daniel Arif", "Career switch", "✓ Portfolio"),
        ("★★★★", "Fast pace — Compose clicked on day 3.", "rav-m", "SY", "Siti Yusof", "Developer", "✓ Portfolio"),
        ("★★★★★", "Finally published an internal test track build.", "rav-g", "VK", "Vikram Kumar", "Consultant", "✓ Portfolio"),
        ("★★★★★", "Demo day felt like a real sprint review.", "rav-a", "NC", "Nadia Chan", "Graduate", "✓ Portfolio")],
    price="RM 3,400", price_orig="RM 3,800", price_save="Save 11%",
    price_note="Per person · Emulator setup support included",
    sidebar_meta=[("Duration", "6 days / 48 hrs"), ("Next intake", "23 Sep 2026"), ("Format", "Hybrid"), ("Level", "Beginner+"), ("Language", "English"), ("Cert body", "Nexperts Skill"), ("Exam", '<span class="smeta-badge">Capstone</span>')],
    whats_included=["Repo templates", "Code reviews", "Play checklist", "Certificate"],
    verify_items=["Nexperts verification", "Repo release tag"],
    guarantee_text="Complete labs but fail demo? One coached remediation week.",
))

BATCH.append(dict(
    slug="django",
    title="Django Web Development",
    title_html='Django Web<br><em>Development</em>',
    vendor_short="Nexperts Skill", watermark="DJG", crumb_vendor="Programming",
    subtitle="Python Django — models, admin, REST APIs, authentication, deployment and security defaults — build a production-shaped web app for Malaysian SME operations in five days.",
    badges=[("cb-vendor", "Nexperts Skill"), ("cb-level", "Intermediate"), ("cb-new", "Django 5.x"), ("cb-hot", "Backend")],
    hero_meta=common_meta("5 days / 40 hrs", "Instructor-Led + Labs", "On-site · Virtual · Hybrid", 93, "30 Sep 2026"),
    hero_img=HERO_IMG,
    quick_wins=[
        ("🐍", "Django ORM", "Models, migrations, queries that scale"),
        ("🔐", "Auth", "Users, permissions, session hardening"),
        ("📡", "DRF APIs", "Serializers, validation, versioning"),
        ("☁️", "Deploy", "Gunicorn, env config, static files")],
    overview_eyebrow="What this course is",
    overview_head=("Backend apps", "with Django discipline."),
    overview_p1="Django remains the fastest path from idea to maintainable admin-backed systems — ideal for internal tools, membership portals and B2B APIs common in Malaysian enterprises.",
    overview_p2="You will implement a multi-tenant-style operations portal (anonymised logistics brief) with tests on critical paths and a deployment checklist suitable for Azure App Service or similar PaaS.",
    overview_p3="Graduates often continue with Docker, AZ-204 or full-stack front-end modules.",
    who_for=[
        ("🐍", "Python developers", "Ready for web frameworks."),
        ("💻", "Full-stack learners", "After our Python bootcamp."),
        ("🏢", "Internal IT", "Building admin systems."),
        ("🎓", "Graduates", "Portfolio backend project."),
        ("📊", "Data engineers", "Need service layer skills."),
        ("👥", "Teams", "Standardise Django patterns.")],
    prereqs=["Solid Python fundamentals", "Git basics", "SQL awareness helpful"],
    prereqs_note="Virtualenv setup guide sent before day one.",
    curriculum_eyebrow="Course Curriculum",
    curriculum_head=("Five days.", "ORM to deploy."),
    curriculum_intro="Security and testing are woven into every module, not bolted on last.",
    modules=[
        ("01", "Django foundations", ["Project layout", "Models & migrations", "Admin customization", "Lab: domain models"]),
        ("02", "Views & templates", ["Class-based views", "Forms", "Messages framework", "Lab: staff workflows"]),
        ("03", "DRF APIs", ["Serializers", "Permissions", "Pagination", "Lab: mobile-ready API"]),
        ("04", "Auth & security", ["User models", "CSRF, XSS awareness", "Settings hygiene", "Lab: role-based access"]),
        ("05", "Testing & deploy", ["pytest-django", "CI smoke tests", "Deploy checklist", "Lab: production config"])],
    labs_eyebrow="Backend Labs",
    labs_head=("Production-shaped.", "Reviewed."),
    labs_intro="Labs emphasise maintainable settings splits and secret management.",
    labs=[
        ("01", "Models", "Schema + migrations.", "lt-recon", "ORM"),
        ("02", "Admin", "Operations console.", "lt-defend", "UX"),
        ("03", "API", "Versioned endpoints.", "lt-attack", "API"),
        ("04", "Security", "Permissions matrix.", "lt-recon", "Sec"),
        ("05", "Deploy", "Green CI + live URL.", "lt-attack", "Ops")],
    labs_footer="+ Sample GitHub Actions workflow for test gate.",
    exam_eyebrow="Assessment",
    exam_head=("App + API demo.", "Maintainable codebase."),
    exam_intro="Passing requires deployed URL, passing tests and architecture walkthrough.",
    exam_main=dict(name="Project rubric", rows=[
        ("Tests", "Critical paths covered"),
        ("Security", "No secrets in repo"),
        ("API", "Documented endpoints"),
        ("Passing", '<span class="pass-highlight">Meets rubric</span>'),
        ("Resit", "Remediation sprint")]),
    exam_optional=None,
    pass_rate=93,
    pass_head_html='93% pass project review<br><em>first submission.</em>',
    pass_intro="We coach settings discipline — where junior Django projects usually fail audits.",
    pass_pills=["Django", "DRF", "Deploy", "93% pass", "pytest"],
    pass_compare=[("Tutorial clones", "No deploy or tests."), ("Nexperts", "Live URL + reviewed PRs.")],
    next_eyebrow="Your backend path",
    next_head=("Add front-end", "or cloud."),
    next_steps_intro="Continue with React full-stack, Docker or Azure developer certifications.",
    next_steps=[("Before this", "Python Bootcamp", "Recommended foundation.", "Python →"), ("You are here", "Django Web Dev", "Backend engineering.", "Currently viewing →"), ("Recommended next", "Docker / AZ-204", "Scale and ship in cloud.", "View Docker →")],
    path_name="Python engineering",
    path_chips=[("Python", "prev"), ("Django", "you"), ("Docker", "next"), ("Full Stack", "next")],
    salary_html='Python web developers in KL: <strong style="color:#86efac">RM 5,200 – RM 10,000/month</strong>.',
    reviews_eyebrow="Student reviews",
    reviews_head=("What Django", "graduates say."),
    reviews_summary=("4.8", 68, 20, 6, 82),
    reviews=[
        ("★★★★★", "DRF module finally made serializers click — shipped internal API same month.", "rav-b", "HL", "Hui Ling", "Developer", "✓ Passed"),
        ("★★★★★", "Deploy checklist saved us from a classic settings.py production leak.", "rav-m", "RA", "Ravi Anand", "IT lead", "✓ Passed"),
        ("★★★★", "Would love one more day on async — still excellent.", "rav-g", "KO", "Ken Ooi", "Analyst", "✓ Passed"),
        ("★★★★★", "Code reviews were strict in the best way.", "rav-a", "MS", "Michelle Sim", "Graduate", "✓ Passed")],
    price="RM 2,900", price_orig="RM 3,200", price_save="Save 9%",
    price_note="Per person · HRD Corp paperwork assistance",
    sidebar_meta=[("Duration", "5 days / 40 hrs"), ("Next intake", "30 Sep 2026"), ("Format", "Hybrid"), ("Level", "Intermediate"), ("Language", "English"), ("Cert body", "Nexperts Skill"), ("Exam", '<span class="smeta-badge">Project</span>')],
    whats_included=["Templates", "pytest starter", "Deploy guide", "Certificate"],
    verify_items=["Nexperts verification", "Deployed URL archived"],
    guarantee_text="Fail project review? One coached revision cycle included.",
))

BATCH.append(dict(
    slug="ios-development",
    title="iOS Development",
    title_html='iOS<br><em>Development</em>',
    vendor_short="Nexperts Skill", watermark="iOS", crumb_vendor="Mobile Dev",
    subtitle="Swift, SwiftUI, MVVM, networking and TestFlight distribution — design and ship an iPhone app with Apple Human Interface Guidelines and Malaysian consumer UX expectations in six days.",
    badges=[("cb-vendor", "Nexperts Skill"), ("cb-level", "Beginner → Intermediate"), ("cb-new", "SwiftUI 2026"), ("cb-hot", "Mobile")],
    hero_meta=common_meta("6 days / 48 hrs", "Xcode Labs + Reviews", "On-site · Virtual · Hybrid", 89, "7 Oct 2026"),
    hero_img=HERO_IMG,
    quick_wins=[
        ("📱", "SwiftUI", "Declarative UI, navigation, previews"),
        ("🏗️", "MVVM", "Observable models, dependency flow"),
        ("🌐", "Networking", "URLSession, async/await, Codable"),
        ("✈️", "TestFlight", "Archive, upload, beta feedback loop")],
    overview_eyebrow="What this course is",
    overview_head=("Build for iPhone", "with confidence."),
    overview_p1="iOS talent in Malaysia is concentrated in fintech, super-apps and enterprise mobility programmes. This course gives you a credible SwiftUI portfolio piece with mentor reviews on architecture and App Store readiness.",
    overview_p2="Mac hardware is required — we provide setup guidance for Apple Silicon and Intel Macs, plus simulator tuning for performance.",
    overview_p3="Pair with Android development for cross-platform product squads or full-stack for end-to-end ownership.",
    who_for=[
        ("💻", "Developers", "New to Apple ecosystem."),
        ("🎓", "Graduates", "Targeting mobile roles."),
        ("🏢", "Enterprise mobility", "Internal app teams."),
        ("🔄", "Android devs", "Add iOS parity skills."),
        ("📱", "Designers who code", "SwiftUI fluency."),
        ("👥", "Cohorts", "Corporate pricing available.")],
    prereqs=["Programming fundamentals", "Mac with Xcode 15+", "Apple Developer account (free tier OK)"],
    prereqs_note="Windows-only learners should discuss remote Mac lab options with enrolment.",
    curriculum_eyebrow="Course Curriculum",
    curriculum_head=("Six days.", "SwiftUI-first."),
    curriculum_intro="Apple platform conventions are taught alongside cross-platform engineering judgement.",
    modules=[
        ("01", "Swift essentials", ["Types & optionals", "Structs vs classes", "Closures", "Lab: language drills"]),
        ("02", "SwiftUI basics", ["Layouts", "State", "NavigationStack", "Lab: onboarding flow"]),
        ("03", "MVVM & data", ["ObservableObject", "Repository pattern", "Persistence intro", "Lab: offline cache"]),
        ("04", "Networking", ["REST with async/await", "Error UX", "Auth tokens", "Lab: live feed screen"]),
        ("05", "Quality", ["Unit tests", "UI tests snapshot intro", "Accessibility", "Lab: polish pass"]),
        ("06", "Ship", ["Archive & upload", "TestFlight", "Demo day", "Lab: beta build"])],
    labs_eyebrow="Xcode Labs",
    labs_head=("Simulator to", "TestFlight."),
    labs_intro="Evening office hours for signing & provisioning questions.",
    labs=[
        ("01", "SwiftUI shell", "Tab navigation.", "lt-recon", "UI"),
        ("02", "State", "Forms & validation.", "lt-defend", "UI"),
        ("03", "API", "Decodable models.", "lt-attack", "API"),
        ("04", "A11y", "VoiceOver pass.", "lt-recon", "UX"),
        ("05", "Archive", "TestFlight upload.", "lt-attack", "Ship"),
        ("06", "Demo", "App Store story.", "lt-attack", "Capstone")],
    labs_footer="+ Provisioning profile troubleshooting clinic on day 5.",
    exam_eyebrow="Assessment",
    exam_head=("TestFlight + demo.", "Portfolio."),
    exam_intro="Installable beta build, README and live demo required.",
    exam_main=dict(name="Capstone rubric", rows=[
        ("Build", "TestFlight or ad-hoc install works"),
        ("Architecture", "MVVM boundaries clear"),
        ("UX", "Loading/error states handled"),
        ("Passing", '<span class="pass-highlight">Meets rubric</span>'),
        ("Resit", "One remediation week")]),
    exam_optional=None,
    pass_rate=89,
    pass_head_html='89% reach TestFlight<br><em>milestone.</em>',
    pass_intro="Provisioning issues are normal — we budget mentor time specifically for signing blockers.",
    pass_pills=["SwiftUI", "MVVM", "TestFlight", "89% ship", "Mentors"],
    pass_compare=[("Mac-less tutorials", "No signing reality."), ("Nexperts", "TestFlight milestone required.")],
    next_eyebrow="Your Apple path",
    next_head=("Cross-platform", "options."),
    next_steps_intro="Add Android for product parity or backend Django for full ownership.",
    next_steps=[("Before this", "Programming basics", "Any language background OK.", "Entry →"), ("You are here", "iOS Development", "Apple mobile track.", "Currently viewing →"), ("Recommended next", "Android Dev", "Two-platform product teams.", "View Android →")],
    path_name="mobile engineering",
    path_chips=[("Swift", "prev"), ("iOS", "you"), ("Android", "next"), ("Full Stack", "next")],
    salary_html='iOS developers in KL: <strong style="color:#86efac">RM 5,000 – RM 11,000/month</strong> at product companies.',
    reviews_eyebrow="Student reviews",
    reviews_head=("What iOS", "graduates say."),
    reviews_summary=("4.7", 62, 16, 8, 74),
    reviews=[
        ("★★★★★", "TestFlight upload on day 6 — first time I felt job-ready for mobile.", "rav-b", "JT", "Jason Teo", "Engineer", "✓ TestFlight"),
        ("★★★★", "Provisioning section was painful but necessary — mentors stayed late.", "rav-m", "AN", "Aina Nasir", "Designer-dev", "✓ TestFlight"),
        ("★★★★★", "SwiftUI previews sped up my iteration massively.", "rav-g", "PL", "Pang Li", "Graduate", "✓ TestFlight"),
        ("★★★★", "Solid — want advanced Core Data module next.", "rav-a", "IB", "Ibrahim Bakri", "Consultant", "✓ TestFlight")],
    price="RM 3,500", price_orig="RM 3,900", price_save="Save 10%",
    price_note="Per person · Mac required",
    sidebar_meta=[("Duration", "6 days / 48 hrs"), ("Next intake", "7 Oct 2026"), ("Format", "Hybrid"), ("Level", "Beginner+"), ("Language", "English"), ("Cert body", "Nexperts Skill"), ("Exam", '<span class="smeta-badge">Capstone</span>')],
    whats_included=["Xcode templates", "Signing guide", "TestFlight checklist", "Certificate"],
    verify_items=["Nexperts verification", "TestFlight build noted"],
    guarantee_text="Stuck on signing after course? 30-day Slack support included.",
))

BATCH.append(dict(
    slug="netflix-data-analysis",
    title="Netflix Data Analysis Workshop",
    title_html='Netflix Data Analysis<br><em>with Python</em>',
    vendor_short="Nexperts Workshop", watermark="NFLX", crumb_vendor="Workshops",
    subtitle="Hands-on workshop using pandas, matplotlib and seaborn on a Netflix catalogue dataset — exploratory analysis, visual storytelling and executive-ready insights in two intensive days.",
    badges=[("cb-vendor", "Workshop"), ("cb-level", "Beginner+"), ("cb-new", "Data Story"), ("cb-hot", "Analytics")],
    hero_meta=common_meta("2 days / 16 hrs", "Workshop + Live Notebooks", "On-site · Virtual", 96, "14 Oct 2026"),
    hero_img=HERO_IMG,
    quick_wins=[
        ("🐼", "pandas fluency", "Filter, group, merge at speed"),
        ("📊", "Visuals", "Charts that answer business questions"),
        ("🎬", "Domain story", "Content strategy metrics that resonate"),
        ("📑", "Deliverable", "Slide-ready insight pack")],
    overview_eyebrow="What this workshop is",
    overview_head=("Turn streaming data", "into decisions."),
    overview_p1="Inspired by our popular community session, this workshop walks analysts through a real Netflix-style catalogue dataset — genres, ratings, release trends and regional availability — to practice the exact pandas patterns used in Malaysian media and e-commerce analytics teams.",
    overview_p2="You leave with a cleaned notebook and a five-slide insight narrative suitable for stakeholder meetings.",
    overview_p3="Ideal warm-up before SQL for Data Professionals, PL-300 or our Python bootcamp.",
    who_for=[
        ("📊", "Analysts", "Excel power users moving to Python."),
        ("🎓", "Students", "Portfolio notebook for internships."),
        ("📈", "Marketing", "Campaign analysts exploring data stories."),
        ("💼", "Managers", "Hands-on literacy, not theory."),
        ("🏢", "Teams", "Fun team-building with skills."),
        ("🧪", "Hackathon fans", "Structured version of our community lab.")],
    prereqs=["Basic Python or completion of Python Bootcamp day 1-2 material", "Laptop with Jupyter or VS Code"],
    prereqs_note="Dataset and starter notebook provided — no install friction on corporate networks.",
    curriculum_eyebrow="Workshop Agenda",
    curriculum_head=("Two days.", "Notebook to slides."),
    curriculum_intro="Minimal lecture — maximum guided exploration with instructor checkpoints.",
    modules=[
        ("01", "Data onboarding", ["CSV hygiene", "pandas dtypes", "Missing values", "Lab: profile dataset"]),
        ("02", "EDA patterns", ["Groupbys", "pivot thinking", "Outliers", "Lab: genre & rating trends"]),
        ("03", "Visualization", ["matplotlib & seaborn", "Chart choice", "Lab: regional availability story"]),
        ("04", "Insight packaging", ["Narrative structure", "Executive summary", "Lab: present findings"])],
    labs_eyebrow="Workshop Labs",
    labs_head=("Live.", "Collaborative."),
    labs_intro="Teams rotate presenter role in afternoon stand-ups.",
    labs=[
        ("01", "Clean", "Standardise columns.", "lt-recon", "Data"),
        ("02", "Explore", "Top 5 business questions.", "lt-defend", "EDA"),
        ("03", "Visualise", "Three chart storyboard.", "lt-attack", "Viz"),
        ("04", "Present", "5-slide insight deck.", "lt-attack", "Story")],
    labs_footer="+ Optional homework: extend analysis with external API metadata.",
    exam_eyebrow="Assessment",
    exam_head=("Insight presentation.", "Practical."),
    exam_intro="Submit notebook + short slide deck; present key finding in 8 minutes.",
    exam_main=dict(name="Workshop rubric", rows=[
        ("Notebook", "Reproducible cells"),
        ("Charts", "Appropriate types & labels"),
        ("Insight", "Actionable recommendation"),
        ("Passing", '<span class="pass-highlight">Meets rubric</span>'),
        ("Retries", "Email revision within 7 days")]),
    exam_optional=None,
    pass_rate=96,
    pass_head_html='96% deliver insight deck<br><em>on time.</em>',
    pass_intro="We coach presentation — analysts fail when charts lack a headline, not when code is wrong.",
    pass_pills=["pandas", "seaborn", "Storytelling", "96% pass", "Workshop"],
    pass_compare=[("Passive webinars", "No artefact."), ("Nexperts", "Notebook + slides required.")],
    next_eyebrow="Continue learning",
    next_head=("Go deeper", "with certs."),
    next_steps_intro="Progress to SQL for Data Professionals, Python Bootcamp or PL-300.",
    next_steps=[("Before this", "Excel / basic Python", "Starter notebook provided.", "Entry →"), ("You are here", "Netflix Workshop", "Analytics storytelling.", "Currently viewing →"), ("Recommended next", "SQL / PL-300", "Enterprise BI depth.", "View SQL course →")],
    path_name="data analytics",
    path_chips=[("Excel", "prev"), ("Workshop", "you"), ("SQL", "next"), ("PL-300", "next")],
    salary_html='Analysts with Python storytelling: <strong style="color:#86efac">RM 4,500 – RM 8,500/month</strong> in KL.',
    reviews_eyebrow="Participant feedback",
    reviews_head=("Workshop", "highlights."),
    reviews_summary=("4.9", 54, 20, 4, 62),
    reviews=[
        ("★★★★★", "Best two-day intro to pandas I have attended — left with slides my manager actually used.", "rav-b", "YT", "Yasmin Taha", "Marketing analyst", "✓ Presented"),
        ("★★★★★", "Netflix angle made EDA fun — team still references the genre chart.", "rav-m", "BC", "Ben Chia", "Student", "✓ Presented"),
        ("★★★★", "Would enjoy a third day on SQL joins — still great value.", "rav-g", "RW", "Rina Wong", "Ops", "✓ Presented"),
        ("★★★★★", "Perfect warm-up before our corporate PL-300 cohort.", "rav-a", "TH", "Tan Hock", "L&D manager", "✓ Team booking")],
    price="RM 890", price_orig="RM 1,050", price_save="Save 15%",
    price_note="Per person · Group rates for 6+",
    sidebar_meta=[("Duration", "2 days / 16 hrs"), ("Next intake", "14 Oct 2026"), ("Format", "Virtual / On-site"), ("Level", "Beginner+"), ("Language", "English"), ("Cert body", "Nexperts Workshop"), ("Deliverable", '<span class="smeta-badge">Slides</span>')],
    whats_included=["Dataset", "Starter notebook", "Slide template", "Certificate of attendance"],
    verify_items=["Workshop attendance verification"],
    guarantee_text="Miss day two? Join the next public cohort once within 90 days (seat permitting).",
))
