# -*- coding: utf-8 -*-
"""EC-Council course data (CHFI v11, CPENT AI)."""
from _course_data import HERO_IMG, common_meta

BATCH = []

# 1. CHFI v11
BATCH.append(dict(
    slug="chfi-v11",
    title="CHFI v11",
    title_html='Computer Hacking Forensic Investigator<br><em>CHFI v11</em>',
    vendor_short="EC-Council", watermark="CHFI", crumb_vendor="EC-Council",
    subtitle="The forensics counterpart to CEH. Investigate digital crime scenes, preserve evidence, recover artefacts and write reports admissible in Malaysian courts.",
    badges=[("cb-vendor","EC-Council Authorized"),("cb-level","Intermediate"),("cb-new","v11 \u00b7 2026"),("cb-hot","Court-Admissible Skills")],
    hero_meta=common_meta("5 days / 40 hrs","Instructor-Led + iLabs","On-site \u00b7 Virtual \u00b7 Hybrid",97,"16 June 2026"),
    hero_img=HERO_IMG,
    quick_wins=[
        ("\U0001F50D","Digital crime scene mastery","Acquire, preserve and analyse evidence forensically"),
        ("\U0001F4BF","Disk and memory forensics","FTK, EnCase, Autopsy, Volatility \u2014 the analyst's toolkit"),
        ("\U0001F310","Network and cloud forensics","Live capture, log analysis, AWS/Azure incident artefacts"),
        ("\u2696\uFE0F","Court-admissible reports","Chain of custody, expert witness preparation, MY legal context"),
    ],
    overview_eyebrow="What this course is",
    overview_head=("CHFI is","forensic discipline."),
    overview_p1="CHFI v11 is the global standard for digital forensics analysts. Where CEH teaches you how attackers operate, CHFI teaches you how to reconstruct what attackers did \u2014 with the rigour and chain of custody required for legal proceedings.",
    overview_p2="At Nexperts, our CHFI lead has served as expert witness in three Malaysian commercial dispute cases and worked on a Cybersecurity Malaysia incident response engagement. The course is taught with the procedural rigour those cases demanded.",
    overview_quote="Forensic findings are only as good as your chain of custody. Lose that, and you lose the case \u2014 and the case is what we are here to win.",
    overview_p3="The v11 update adds cloud forensics (AWS, Azure, GCP), modern endpoint artefact analysis, and IoT/mobile evidence handling. We teach all three with current Malaysian legal context throughout.",
    who_for=[
        ("\U0001F50D","SOC analysts moving to IR","Incident response without forensics is incomplete. CHFI is the credential that closes that gap."),
        ("\U0001F46E","Law enforcement IT","PDRM Cyber Crime, MCMC investigators \u2014 CHFI is the international peer-recognised credential."),
        ("\U0001F3DB\uFE0F","Bank and financial fraud teams","BNM-regulated entities require demonstrable forensic capabilities for incident reporting."),
        ("\u2696\uFE0F","Compliance and audit","Understand exactly what evidence quality your security team can produce."),
        ("\U0001F4DA","CEH alumni","Forensics is the natural defensive complement to ethical hacking."),
        ("\U0001F393","Final-year cybersecurity students","CHFI graduates are scarce \u2014 and high demand in MY law enforcement and consultancies."),
    ],
    prereqs=[
        "CEH or 2+ years of cybersecurity experience",
        "Familiarity with Windows event logs and registry",
        "Basic Linux command-line fluency",
        "Understanding of TCP/IP networking",
    ],
    prereqs_note="No CEH? Ask us about our CEH \u2192 CHFI dual track.",
    curriculum_eyebrow="Course Curriculum",
    curriculum_head=("16 modules.","From acquisition to court."),
    curriculum_intro="CHFI v11 is delivered as a full investigation arc \u2014 from initial response and acquisition through artefact analysis to expert witness preparation.",
    modules=[
        ("01","Computer Forensics Fundamentals",[
            "Cybercrime classifications and applicable Malaysian law",
            "Investigator roles, ethics and CCTA scope",
            "Forensic readiness in Malaysian enterprises",
            "Volatile vs non-volatile evidence priority",
            "First responder responsibilities",
            "Lab: Document a crime-scene response timeline",
        ]),
        ("02","Search, Seizure & Acquisition",[
            "Search-and-seizure legal authority",
            "Order of volatility and acquisition order",
            "Write-blockers, hashing, forensic imaging",
            "Live system acquisition vs dead-box",
            "Cloud account preservation requests",
            "Lab: Image a running Windows system, validate hashes",
        ]),
        ("03","Disk, File System & OS Forensics",[
            "FAT, NTFS, ext4, APFS internals",
            "Deleted file recovery and unallocated analysis",
            "Windows registry forensic artefacts",
            "macOS and Linux artefact mapping",
            "Timeline construction across systems",
            "Lab: Build a 30-day timeline from a Windows image",
        ]),
        ("04","Network, Cloud & IoT Forensics",[
            "Network capture analysis with Wireshark and Zeek",
            "Cloud forensics \u2014 AWS CloudTrail, Azure Activity Logs",
            "IoT device artefact extraction",
            "Mobile forensics \u2014 iOS, Android, signal apps",
            "Email and messaging forensics",
            "Lab: Cloud incident reconstruction from logs",
        ]),
        ("05","Reporting & Expert Witness",[
            "Forensic report structure and standards",
            "Chain of custody documentation",
            "Expert witness preparation and cross-examination",
            "Malaysian admissibility requirements (Evidence Act)",
            "Working with prosecutors and defence",
            "Lab: Write a forensic report and present it under cross-examination",
        ]),
    ],
    labs_eyebrow="Hands-On iLabs",
    labs_head=("180 forensic labs.","Real images. Real cases."),
    labs_intro="EC-Council iLabs serves you 180 forensic challenges \u2014 disk images, memory dumps, network captures and cloud log archives. Every artefact is a real-case derivative.",
    labs=[
        ("01","Cold-Boot Acquisition","Image a running workstation without rebooting it. Preserve volatile RAM. Validate hashes.","lt-forensic","Acquisition"),
        ("02","Deleted File Recovery","Recover documents and emails deleted from an NTFS partition. Defend findings.","lt-forensic","Recovery"),
        ("03","Memory Forensics with Volatility","Identify malware, injected DLLs and exfiltration paths from a memory image.","lt-forensic","Memory"),
        ("04","Windows Registry Investigation","Build user activity timeline from registry hives \u2014 USB, MRU, ShimCache.","lt-forensic","Registry"),
        ("05","Network Capture Analysis","Reconstruct an attacker session from a 200MB pcap. Extract artefacts.","lt-forensic","Network"),
        ("06","Cloud Forensics \u2014 AWS","Compromised IAM role. Trace via CloudTrail. Identify data exfiltration to S3.","lt-forensic","Cloud"),
        ("07","Mobile Forensics","Extract artefacts from a locked Android device. Reconstruct messaging timeline.","lt-forensic","Mobile"),
        ("08","Forensic Report Writing","Take an investigation. Write a 12-page report admissible in Malaysian commercial court.","lt-defend","Reporting"),
        ("09","Mock Cross-Examination","Defend your forensic findings under simulated cross-examination by an instructor.","lt-defend","Court"),
    ],
    labs_footer="+ 171 additional iLabs forensic challenges. Lab access for 6 months post-course.",
    exam_eyebrow="Exam Information",
    exam_head=("One exam.","Forensic depth."),
    exam_intro="CHFI 312-49 is a 4-hour, 150-question exam covering all 16 forensic modules. The exam emphasises procedural correctness \u2014 do you preserve the evidence properly, document the chain, follow the legal requirements?",
    exam_main=dict(name="CHFI 312-49 Exam",rows=[
        ("Questions","150 multiple choice"),
        ("Duration","4 hours"),
        ("Passing score",'<span class="pass-highlight">70% (105/150)</span>'),
        ("Format","Pearson VUE / EC-Council"),
        ("Validity","3 years (ECE renewal)"),
        ("Industry avg pass rate",'<span class="fail-note">~66% first attempt</span>'),
        ("Nexperts pass rate",'<span class="pass-highlight">97% first attempt</span>'),
    ]),
    exam_optional=dict(name="Court & Legal Recognition",rows=[
        ("Malaysian admissibility","Aligned with Evidence Act 1950 (s.90A)"),
        ("Law enforcement","Recognised by PDRM Cyber Crime, MCMC"),
        ("Banking","Listed in BNM RMiT incident response baselines"),
        ("Stacks with","CEH \u2192 CHFI \u2192 CCSE / CCISO"),
        ("DoD","8140 approved digital forensic role"),
        ("Voucher","EC-Council exam voucher bundled"),
        ("Career fit","DFIR analyst, fraud investigator, expert witness"),
    ]),
    mock_title="Our CHFI 3-Mock Programme",
    mock_programme=[
        ("01","Procedural Mock","End of week 1. Tests acquisition order and chain of custody. Average score: 64%."),
        ("02","Artefact-Heavy Mock","Mid-course. Tests artefact identification and timeline reconstruction. Average score: 78%."),
        ("03","Final Clearance","Full 150-question simulation. 84%+ before booking. Average score: 88%."),
    ],
    pass_rate=97,
    pass_head_html='97% of our CHFI investigators<br>pass <em>on first attempt.</em>',
    pass_intro="The industry average for CHFI first-attempt pass rate is around 66%. Our 97% comes from 180 hands-on iLabs, real Malaysian case-derived investigations, and an instructor who has served as expert witness in three commercial cases.",
    pass_pills=["180 iLabs cases","Mock cross-examination","97% first attempt","Malaysian legal context","Free retake voucher"],
    pass_compare=[
        ("Industry average: ~66%","Most CHFI candidates fail on procedural questions \u2014 the order of volatility, the chain of custody, the legal authority. They learn artefacts but skip discipline."),
        ("Nexperts: 97%","We drill procedure first, artefacts second. We make you defend your findings under cross-examination. We don't book until your discipline is reflexive."),
    ],
    next_eyebrow="Your Certification Journey",
    next_head=("CHFI completes","the IR triangle."),
    next_steps_intro="CEH (offence) + CHFI (forensics) + ECIH (response) is the classic incident response triangle. From here you go management (CCISO) or specialise into expert-witness work.",
    next_steps=[
        ("Before this","CEH v13 AI","CEH gives you the attacker mindset. Without it, CHFI artefacts feel disconnected from intent.","View CEH \u2192"),
        ("You are here","CHFI v11","Court-admissible digital forensic investigator. Acquisition, analysis, reporting and expert witness ready.","Currently viewing \u2192"),
        ("Recommended next","ECIH or CCISO","ECIH adds structured incident response. CCISO moves you into security leadership.","View ECIH \u2192"),
    ],
    path_name="forensics & incident response",
    path_chips=[("Security+ / CEH","prev"),("CHFI","you"),("ECIH / CISA","next"),("CCISO","prev"),("Expert Witness","prev")],
    salary_html='Expected salary range after CHFI: <strong style="color:#86efac">RM 7,500 \u2013 RM 13,500/month</strong> for DFIR analyst and fraud investigator roles in Malaysia.',
    reviews_eyebrow="Student Reviews",
    reviews_head=("What our CHFI","graduates say."),
    reviews_summary=("4.9",91,7,2,89),
    reviews=[
        ("\u2605\u2605\u2605\u2605\u2605","The mock cross-examination was the most uncomfortable hour of my professional career \u2014 and the most useful. I have since defended a real engagement in court and the patterns held.","rav-b","NF","Naufal Faiz","Forensic Lead \u00b7 BDO Malaysia","\u2713 Passed first attempt \u00b7 142 / 150"),
        ("\u2605\u2605\u2605\u2605\u2605","I'd been doing IR informally for years. CHFI gave me the procedure and language to make my work admissible. Within a month, our IR reports went from 30 pages to 12 \u2014 and they were better.","rav-m","KS","Kamilah Suhaimi","DFIR Analyst \u00b7 RHB Bank","\u2713 Passed first attempt \u00b7 138 / 150"),
        ("\u2605\u2605\u2605\u2605\u2605","Memory forensics with Volatility is now part of my weekly toolkit. Two weeks after CHFI, I caught a credential-dumping attack we'd missed for three months.","rav-g","TY","Tony Yong","SOC Manager \u00b7 KPMG MY","\u2713 Passed first attempt \u00b7 145 / 150"),
        ("\u2605\u2605\u2605\u2605","Court admissibility under the Malaysian Evidence Act was new to me \u2014 even after 8 years in security. I now sit on my company's data breach response committee.","rav-a","SP","Suresh Pillai","Information Security Officer \u00b7 Petronas","\u2713 Passed first attempt \u00b7 134 / 150"),
    ],
    price="RM 4,800", price_orig="RM 5,500", price_save="Save 13%",
    price_note="Per person \u00b7 Includes EC-Council courseware, exam voucher, iLabs",
    sidebar_meta=[
        ("Duration","5 days / 40 hrs"),
        ("Next intake","16 June 2026"),
        ("Format","On-site \u00b7 Virtual"),
        ("Level","Intermediate"),
        ("Language","English"),
        ("Cert body","EC-Council"),
        ("Exam",'<span class="smeta-badge">Included</span>'),
    ],
    whats_included=[
        "EC-Council CHFI v11 official courseware",
        "EC-Council exam voucher (312-49)",
        "180-lab EC-Council iLabs access (6 months)",
        "3 full timed mock exams",
        "Mock cross-examination sessions",
        "Malaysian legal admissibility playbook",
        "Post-course instructor access (45 days)",
        "Free retake voucher (conditions apply)",
        "Digital badge via EC-Council Aspen",
    ],
    verify_items=[
        "Verifiable on EC-Council Aspen portal",
        "Digital badge via Credly",
        "DoD 8140 \u2014 Digital Forensic role",
        "Recognised by PDRM Cyber Crime, MCMC",
    ],
    guarantee_text="Hit our 84% mock threshold and don't pass first attempt? Retake voucher on us.",
))

# 2. CPENT AI
BATCH.append(dict(
    slug="cpent-ai",
    title="CPENT AI",
    title_html='Certified Penetration Testing Professional<br><em>CPENT AI</em>',
    vendor_short="EC-Council", watermark="CPENT", crumb_vendor="EC-Council",
    subtitle="EC-Council's advanced practical pentest credential. 24-hour live cyber range exam covering AD, IoT, cloud, AI attacks and binary exploitation. The CEH graduation step.",
    badges=[("cb-vendor","EC-Council Authorized"),("cb-level","Advanced"),("cb-new","v3 \u00b7 AI 2026"),("cb-hot","24h Live Range")],
    hero_meta=common_meta("8 days / 64 hrs","Instructor-Led + 24h Range Exam","On-site \u00b7 Hybrid",92,"23 June 2026"),
    hero_img=HERO_IMG,
    quick_wins=[
        ("\u2694\uFE0F","24-hour live range exam","Pure practical \u2014 no MCQ, no theory, only attacks"),
        ("\U0001F310","AD, IoT, cloud, AI surfaces","All four advanced attack surfaces with 2026 AI additions"),
        ("\U0001F50D","Binary exploitation","Buffer overflows, ROP chains, custom shellcode"),
        ("\U0001F4DD","Pentest report mastery","Range exam includes a full client-grade report"),
    ],
    overview_eyebrow="What this course is",
    overview_head=("CPENT AI is","CEH levelled up."),
    overview_p1="CPENT AI is EC-Council's advanced practical penetration testing credential. Unlike CEH (theory + practical) and PenTest+ (workflow + report), CPENT is pure practical \u2014 a 24-hour live cyber range exam where you compromise a fictional enterprise.",
    overview_p2="At Nexperts we run a structured 8-day prep cycle plus a full mock 24-hour range engagement. By the time you sit the real CPENT exam, you've done the equivalent under our coaching.",
    overview_quote="CPENT does not test what you know. It tests what you can do under fatigue, time pressure and a partial map of the target. That is what we drill.",
    overview_p3="CPENT v3 (AI 2026) adds AI-attack scenarios, prompt injection against deployed LLM endpoints, and adversarial ML \u2014 the modern surfaces every Malaysian pentester now sees in 2026 engagements.",
    who_for=[
        ("\u2694\uFE0F","CEH graduates","CPENT is the natural CEH graduation. CEH proved you can think like an attacker. CPENT proves you can be one."),
        ("\U0001F3AF","PenTest+ holders","Move from compliance-friendly testing into deeper offensive engagements."),
        ("\U0001F50D","OSCP candidates","CPENT and OSCP are complementary. CPENT adds AI, IoT and binary depth OSCP touches lightly."),
        ("\U0001F525","Red team interns","Stretch goal credential for red team progression in MY consultancies."),
        ("\U0001F310","AppSec engineers","Move beyond OWASP Top 10 into deeper exploitation."),
        ("\U0001F4DA","Senior security leads","Lead pentest engagements credibly with the most rigorous practical credential available."),
    ],
    prereqs=[
        "CEH v13 AI or 5+ years of offensive security experience",
        "Strong Linux + Windows command-line fluency",
        "Comfort with scripting in Python and Bash",
        "Experience with Burp Suite, Metasploit, BloodHound",
    ],
    prereqs_note="No CEH? Ask us about our CEH + CPENT 14-day intensive bundle.",
    curriculum_eyebrow="Course Curriculum",
    curriculum_head=("12 advanced domains.","Range-first delivery."),
    curriculum_intro="CPENT v3 covers everything from advanced AD attacks through binary exploitation, IoT attacks, cloud privilege escalation and the new AI-attack surfaces. We deliver each domain with a range exercise that mirrors the actual exam pattern.",
    modules=[
        ("01","Advanced Active Directory Attacks",[
            "Kerberoasting, AS-REP roasting, golden ticket",
            "DCSync, DCShadow and Mimikatz at scale",
            "BloodHound attack path automation",
            "Constrained delegation abuse",
            "Cross-forest attacks and trust abuse",
            "Lab: Compromise a 3-domain forest",
        ]),
        ("02","Binary Exploitation & Reverse Engineering",[
            "Stack-based buffer overflows",
            "Bypassing DEP, ASLR and stack canaries",
            "ROP chain construction",
            "Custom shellcode and encoders",
            "Reverse engineering with Ghidra and IDA Free",
            "Lab: Exploit a 32-bit and 64-bit Linux binary",
        ]),
        ("03","Cloud, Container & IaC Exploitation",[
            "AWS IAM privilege escalation chains",
            "Kubernetes pod escape and privilege escalation",
            "Terraform / IaC misconfiguration exploitation",
            "Service principal attacks in Azure",
            "Cross-cloud lateral movement",
            "Lab: Pivot from S3 misconfig to Domain Admin",
        ]),
        ("04","IoT, OT & Wireless Attacks",[
            "Embedded firmware extraction and analysis",
            "MQTT, CoAP and OT protocol attacks",
            "BLE and ZigBee security testing",
            "Wireless evil-twin and rogue AP attacks",
            "Hardware-level attack vectors",
            "Lab: Compromise an IoT device end-to-end",
        ]),
        ("05","AI Attacks \u2014 v3 New",[
            "Prompt injection against deployed LLM endpoints",
            "Adversarial ML \u2014 evasion and poisoning",
            "Model extraction and inversion attacks",
            "AI-assisted phishing and deepfake operations",
            "Defending against AI-driven adversaries",
            "Lab: Compromise an LLM-powered customer service bot",
        ]),
    ],
    labs_eyebrow="Hands-On Cyber Range",
    labs_head=("80 advanced labs.","Plus a full 24h mock exam."),
    labs_intro="CPENT requires range fluency. We run 80 structured labs across all 12 domains, then put you through a full 24-hour mock CPENT engagement before you sit the real one.",
    labs=[
        ("01","Forest Compromise","From a workstation foothold, walk to Enterprise Admin across 3 domains in 6 hours.","lt-attack","AD"),
        ("02","Stack Buffer Overflow","Exploit a 32-bit Linux binary. Get a shell. Bypass NX.","lt-attack","Binary"),
        ("03","ROP Chain Construction","Build a 12-gadget ROP chain. Defeat ASLR. Win remote code execution.","lt-attack","Binary"),
        ("04","S3-to-Admin Pivot","Find a misconfigured S3 bucket. Pivot through 4 IAM roles to administrative access.","lt-attack","Cloud"),
        ("05","Kubernetes Pod Escape","Escape from a containerised pod into the underlying node. Move laterally.","lt-attack","Container"),
        ("06","IoT Firmware Extraction","Extract firmware from a flash chip. Find hardcoded credentials. Compromise the device.","lt-attack","IoT"),
        ("07","LLM Prompt Injection","Compromise a deployed LLM customer service bot via prompt injection.","lt-attack","AI"),
        ("08","Mock 24-Hour Exam","Full simulated CPENT range engagement. We grade exactly as EC-Council does.","lt-attack","Final Mock"),
        ("09","Range Report Writing","Take your mock results. Write the full CPENT-grade engagement report.","lt-defend","Reporting"),
    ],
    labs_footer="+ 71 additional range tasks across all 12 domains. Range access for 90 days post-course.",
    exam_eyebrow="Exam Information",
    exam_head=("Pure practical.","24 hours. No theory."),
    exam_intro="CPENT is a 24-hour live-range engagement. There is no MCQ. You receive a target environment, an objective and a report template. EC-Council assessors grade your evidence and report.",
    exam_main=dict(name="CPENT v3 Range Exam",rows=[
        ("Format","24-hour practical range engagement"),
        ("Pass criteria","70% \u2014 EC-Council assessor-graded"),
        ("Master tier","90%+ awards CPENT Master"),
        ("Retake","2nd attempt allowed (separate fee)"),
        ("Validity","3 years (ECE renewal)"),
        ("Industry avg pass rate",'<span class="fail-note">~54% first attempt</span>'),
        ("Nexperts pass rate",'<span class="pass-highlight">92% first attempt</span>'),
    ]),
    exam_optional=dict(name="LPT Master Track",rows=[
        ("LPT requirement","Score 90%+ on CPENT range"),
        ("LPT recognition","Highest EC-Council practical credential"),
        ("Voucher","Bundled \u2014 EC-Council included"),
        ("Range access","90 days post-course"),
        ("Stacks with","CEH \u2192 CPENT \u2192 LPT Master"),
        ("Career impact","Senior pentester / red-team lead roles"),
        ("Salary uplift","Average 22\u201335% post-cert in MY"),
    ]),
    mock_title="Our CPENT Range Programme",
    mock_programme=[
        ("01","Domain Drills","Days 1\u20136. Per-domain practical labs with instructor walkthroughs. Average score: 68%."),
        ("02","Pre-Final Mock","Day 7. 8-hour mini-engagement covering 4 domains. Average score: 79%."),
        ("03","24-Hour Mock","Day 8. Full 24-hour mock engagement. Graded as EC-Council does. 80%+ before booking."),
    ],
    pass_rate=92,
    pass_head_html='92% of our CPENT candidates<br>pass <em>on first attempt.</em>',
    pass_intro="CPENT industry-wide first-attempt rate is approximately 54% \u2014 the lowest of any EC-Council credential. Our 92% comes from 80 structured labs, a full 24-hour mock engagement, and an instructor who has served as a CPENT subject matter advisor.",
    pass_pills=["80 advanced range labs","24-hour mock engagement","92% first attempt","LPT Master pathway","90-day post-course access"],
    pass_compare=[
        ("Industry average: ~54%","CPENT candidates often fail because they have never sat 24 hours under range pressure. They have skills but no endurance, and the report quality drops sharply after hour 16."),
        ("Nexperts: 92%","We run a real 24-hour mock engagement. We coach pacing, sleep strategy and report discipline. We don't let you sit CPENT until your endurance is proven."),
    ],
    next_eyebrow="Your Certification Journey",
    next_head=("CPENT is","the practical apex."),
    next_steps_intro="CPENT is the most demanding practical EC-Council credential. From here, the LPT Master adds prestige; CCISO moves you into leadership.",
    next_steps=[
        ("Before this","CEH v13 AI","CEH is the prerequisite. The 20-domain coverage of CEH is the foundation CPENT exploits.","View CEH \u2192"),
        ("You are here","CPENT v3 AI","Advanced practical pentester. AD, binary, cloud, IoT and AI attacks under 24-hour pressure.","Currently viewing \u2192"),
        ("Recommended next","LPT Master or CCISO","LPT Master scores 90%+ on CPENT. CCISO moves you into security leadership.","View LPT \u2192"),
    ],
    path_name="advanced offensive security",
    path_chips=[("CEH","prev"),("CPENT AI","you"),("LPT Master","next"),("CCISO","prev"),("Red Team Lead","prev")],
    salary_html='Expected salary range after CPENT: <strong style="color:#86efac">RM 10,000 \u2013 RM 18,000/month</strong> for senior pentester and red team lead roles in Malaysia.',
    reviews_eyebrow="Student Reviews",
    reviews_head=("What our CPENT","graduates say."),
    reviews_summary=("4.9",92,6,2,67),
    reviews=[
        ("\u2605\u2605\u2605\u2605\u2605","The 24-hour mock engagement on day 8 nearly broke me. The real exam two weeks later felt manageable because I had already done the equivalent. Scored 91 \u2014 LPT track.","rav-b","SI","Suhail Ismail","Senior Pentester \u00b7 Konsortium Logistik","\u2713 Passed first attempt \u00b7 91% \u2014 LPT Master"),
        ("\u2605\u2605\u2605\u2605\u2605","Binary exploitation was the gap I'd been avoiding for years. The Ghidra + ROP chain coaching turned it into something I now actually enjoy.","rav-m","CG","Caroline Gan","Red Team Lead \u00b7 Visa Worldpay","\u2713 Passed first attempt \u00b7 84%"),
        ("\u2605\u2605\u2605\u2605\u2605","The AI-attack module was wild. Compromising an LLM via prompt injection in a controlled lab was the most fun I've had in a course. Showed up in our real engagements three months later.","rav-g","RA","Ravi Anbumani","AppSec Lead \u00b7 GHL Systems","\u2713 Passed first attempt \u00b7 87%"),
        ("\u2605\u2605\u2605\u2605","Sleep strategy and pacing for the 24h exam is what I underestimated. Nexperts forced us to plan it. That alone was worth half the course fee.","rav-a","WL","Wee Lin Tan","Pentest Consultant \u00b7 Mandiant MY","\u2713 Passed first attempt \u00b7 76%"),
    ],
    price="RM 5,800", price_orig="RM 6,800", price_save="Save 15%",
    price_note="Per person \u00b7 Includes EC-Council range, voucher, 24h mock engagement",
    sidebar_meta=[
        ("Duration","8 days / 64 hrs"),
        ("Next intake","23 June 2026"),
        ("Format","On-site \u00b7 Hybrid"),
        ("Level","Advanced"),
        ("Language","English"),
        ("Cert body","EC-Council"),
        ("Exam",'<span class="smeta-badge">Included</span>'),
    ],
    whats_included=[
        "EC-Council CPENT v3 official courseware",
        "EC-Council exam voucher",
        "90-day cyber range access",
        "80 structured advanced labs",
        "Full 24-hour mock engagement",
        "Pacing &amp; endurance coaching",
        "Post-course instructor access (60 days)",
        "Range report templates &amp; reviews",
        "Digital badge via EC-Council Aspen",
    ],
    verify_items=[
        "Verifiable on EC-Council Aspen portal",
        "Digital badge via Credly",
        "DoD 8140 \u2014 Advanced Pentester role",
        "Pathway to LPT Master credential",
    ],
    guarantee_text="Complete the 24h mock and don't pass CPENT first attempt? Range access extended; second attempt voucher subsidised.",
))
