# -*- coding: utf-8 -*-
"""AWS course data (CCP, SAA, SAP)."""
from _course_data import HERO_IMG, common_meta
from _course_schema_aws_clf import AWS_CLF_SCHEMA_MARKUP

BATCH = []

# 1. AWS Cloud Practitioner
BATCH.append(dict(
    slug="aws-cloud-practitioner",
    seo_title="AWS Cloud Practitioner Essentials Training Malaysia | CLF-C02",
    seo_description="Join AWS Cloud Practitioner Essentials Training in Malaysia. Prepare for CLF-C02 certification with hands-on labs, exam prep, AWS sandbox, and expert instructors.",
    seo_keywords="AWS Cloud Practitioner, CLF-C02, AWS certification Malaysia, cloud practitioner training, AWS essentials, cloud computing course Malaysia",
    canonical_path="/courses/aws-cloud-practitioner",
    schema_markup=AWS_CLF_SCHEMA_MARKUP,
    title="AWS Cloud Practitioner",
    title_html='AWS Cloud Practitioner Essentials<br><em>Training in Malaysia (CLF-C02)</em>',
    vendor_short="AWS", watermark="AWS", crumb_vendor="AWS",
    subtitle="Build a strong foundation in cloud computing with AWS Cloud Practitioner Essentials Training in Malaysia \u2014 cloud concepts, core services, security, pricing and CLF-C02 exam preparation.",
    badges=[("cb-level","Foundation"),("cb-new","CLF-C02 \u00b7 2026"),("cb-hot","Entry-Level Cloud Cert")],
    hero_meta=common_meta("3 days / 24 hrs","Instructor-Led + AWS Sandbox","On-site \u00b7 Virtual \u00b7 Hybrid",98,"30 June 2026"),
    hero_img=HERO_IMG,
    quick_wins=[
        ("\u2601\uFE0F","Cloud fundamentals","Understand AWS Cloud concepts, global infrastructure and architecture"),
        ("\U0001F4B0","Billing & pricing literacy","Cost Explorer, Budgets, Pricing Calculator and support plans"),
        ("\U0001F510","Security foundations","Shared responsibility, IAM and AWS security best practices"),
        ("\U0001F680","Certification-ready","Hands-on labs, mock exams and CLF-C02 exam preparation"),
    ],
    overview_eyebrow="AWS Cloud Practitioner Essentials",
    overview_head=("Training in Malaysia", "(CLF-C02)."),
    overview_p1="Build a strong foundation in cloud computing with AWS Cloud Practitioner Essentials Training in Malaysia. This beginner-friendly AWS certification course is designed for individuals who want to understand cloud concepts, AWS services, security, architecture, pricing, billing and support models while preparing for the AWS Certified Cloud Practitioner (CLF-C02) exam.",
    overview_p2="Whether you are an IT professional, business analyst, project manager, sales executive, finance professional, student or career switcher, this AWS Cloud Practitioner training provides the essential cloud knowledge needed to confidently participate in cloud projects and digital transformation initiatives.",
    overview_quote="Cloud literacy is no longer optional. CLF-C02 proves you can speak credibly about AWS services, security and cost with technical and business stakeholders.",
    overview_p3="At Nexperts Academy, learners gain practical experience through instructor-led training, real-world examples, AWS sandbox environments, hands-on exercises, mock exams and certification-focused preparation aligned with the latest CLF-C02 exam objectives.",
    overview_sections=[
        {
            "eyebrow": "Why Choose AWS Cloud Practitioner Certification?",
            "eyebrow_class": "m",
            "paragraphs": [
                "The AWS Certified Cloud Practitioner certification validates your understanding of cloud computing fundamentals and demonstrates your ability to explain AWS Cloud concepts, security practices, pricing models and core AWS services.",
                "This certification is recognized globally and serves as the ideal starting point for advanced AWS certifications such as AWS Solutions Architect Associate, AWS Developer Associate, AWS SysOps Administrator Associate, AWS Data Engineer Associate, AWS Security Specialty and AWS Machine Learning Specialty.",
                "Organizations across Malaysia are increasingly adopting cloud technologies, making AWS Cloud Practitioner one of the most valuable entry-level cloud certifications available today.",
            ],
        },
        {
            "eyebrow": "What You Will Learn",
            "bullets": [
                "Cloud computing fundamentals",
                "AWS Global Infrastructure",
                "Amazon EC2 fundamentals",
                "Amazon S3 storage services",
                "Amazon RDS database services",
                "AWS Lambda serverless computing",
                "Virtual Private Cloud (VPC)",
                "AWS Identity and Access Management (IAM)",
                "AWS Shared Responsibility Model",
                "AWS Cloud Security best practices",
                "AWS Cost Explorer",
                "AWS Budgets",
                "AWS Pricing Calculator",
                "AWS Well-Architected Framework",
                "AWS Migration concepts",
                "AWS Billing and Pricing models",
                "AWS Support Plans",
                "AWS Generative AI services",
            ],
            "footer": "By the end of the course, you will be able to understand and discuss AWS cloud solutions with confidence while preparing effectively for the AWS Certified Cloud Practitioner exam.",
        },
        {
            "eyebrow": "AWS Cloud Practitioner Exam Details (CLF-C02)",
            "subtitle": "Exam Information",
            "bullets": [
                "Certification: AWS Certified Cloud Practitioner",
                "Exam Code: CLF-C02",
                "Question Format: Multiple Choice & Multiple Response",
                "Number of Questions: 65",
                "Exam Duration: 90 Minutes",
                "Delivery Provider: Pearson VUE",
                "Certification Validity: 3 Years",
            ],
            "footer": "The exam evaluates your knowledge of AWS Cloud concepts, security, technology services, billing, pricing and support.",
        },
        {
            "eyebrow": "Career Opportunities After AWS Cloud Practitioner Certification",
            "bullets": [
                "Cloud Support Associate",
                "Junior Cloud Engineer",
                "AWS Operations Associate",
                "Cloud Sales Specialist",
                "Technical Account Manager",
                "Infrastructure Analyst",
                "IT Support Engineer",
                "Cloud Consultant",
            ],
            "footer": "Many professionals use this certification as the first step toward becoming AWS Solutions Architects, Cloud Engineers, DevOps Engineers and Cloud Security Specialists.",
        },
        {
            "eyebrow": "Why Learn AWS Cloud Computing?",
            "paragraphs": [
                "Cloud computing continues to be one of the fastest-growing technology sectors worldwide. Organizations across Malaysia are increasingly migrating applications, databases and infrastructure to the cloud to improve scalability, security and operational efficiency.",
                "AWS remains the world's leading cloud platform, serving millions of customers globally across industries including finance, healthcare, manufacturing, education, telecommunications and government.",
            ],
            "bullets": [
                "Improve employability",
                "Enhance cloud literacy",
                "Support digital transformation initiatives",
                "Understand cloud security practices",
                "Reduce infrastructure costs",
                "Prepare for advanced AWS certifications",
            ],
        },
        {
            "eyebrow": "AWS Cloud Practitioner Training Features",
            "bullets": [
                "Instructor-Led Training",
                "Live Demonstrations",
                "AWS Sandbox Environment",
                "Hands-On Labs",
                "Certification-Focused Curriculum",
                "Practice Tests",
                "Mock Exams",
                "Course Materials",
                "Post-Training Support",
                "Certification Guidance",
            ],
            "footer": "Our training approach focuses on practical understanding rather than memorization, helping learners develop real-world cloud knowledge.",
        },
    ],
    who_for=[
        ("\U0001F4BB","IT support & sysadmin","Build cloud literacy to grow from help-desk and infrastructure roles."),
        ("\U0001F4CA","Business & finance teams","Understand AWS billing, pricing and cost allocation in plain language."),
        ("\U0001F468\u200D\U0001F4BC","Project & sales professionals","Lead cloud conversations with developers, architects and procurement."),
        ("\U0001F393","Students & career switchers","The fastest entry point into cloud \u2014 no prior AWS experience required."),
        ("\U0001F3DB\uFE0F","Government employees","Align with Malaysia's cloud-first and digital transformation initiatives."),
        ("\U0001F680","Pre-Associate track","Foundation step before SAA, Developer, SysOps or specialty AWS credentials."),
    ],
    prereqs=[
        "Basic computer and internet knowledge",
        "No prior AWS experience required",
        "Comfort with web-based dashboards",
        "No mandatory IT background",
    ],
    prereqs_note="No prior AWS experience is required. Basic computer literacy is sufficient.",
    curriculum_eyebrow="Syllabus",
    curriculum_head=("AWS Cloud Practitioner Syllabus", "2026."),
    curriculum_intro="Aligned to the AWS Certified Cloud Practitioner (CLF-C02) exam domains: Cloud Concepts, Security and Compliance, Cloud Technology and Services, and Billing, Pricing and Support.",
    modules=[
        ("01","Domain 1: Cloud Concepts (24%)",[
            "Define the AWS Cloud and its value proposition",
            "Cloud economics \u2014 capex vs opex and total cost of ownership",
            "AWS Cloud Adoption Framework (CAF)",
            "AWS Well-Architected Framework pillars",
            "Migration strategies \u2014 rehost, replatform, refactor and more",
            "Lab: Map a Malaysian use case to cloud value drivers",
        ]),
        ("02","Domain 3: Cloud Technology and Services (34%)",[
            "AWS Global Infrastructure \u2014 regions, AZs, edge locations",
            "Compute \u2014 EC2, Lambda, ECS and EKS overview",
            "Storage \u2014 S3, EBS, EFS and Glacier",
            "Networking \u2014 VPC, CloudFront, Route 53, Direct Connect",
            "Databases \u2014 RDS, DynamoDB and Aurora",
            "Analytics, AI and ML \u2014 QuickSight, SageMaker and Amazon Bedrock",
            "Lab: Deploy EC2, S3 and a serverless Lambda function",
        ]),
        ("03","Domain 2: Security and Compliance (30%)",[
            "AWS Shared Responsibility Model",
            "IAM users, groups, roles and policies",
            "Encryption with AWS KMS, S3 and EBS",
            "Compliance programs and AWS Artifact",
            "Security monitoring \u2014 CloudTrail and GuardDuty overview",
            "Lab: Configure IAM least privilege and secure an S3 bucket",
        ]),
        ("04","Domain 4: Billing, Pricing and Support (12%)",[
            "AWS pricing models \u2014 on-demand, Reserved Instances and Savings Plans",
            "AWS Free Tier and cost allocation tags",
            "Cost Explorer, AWS Budgets and Pricing Calculator",
            "AWS Support plans and Trusted Advisor",
            "AWS Billing and account management fundamentals",
            "Lab: Set up budgets, alerts and cost allocation",
        ]),
    ],
    labs_eyebrow="Hands-On AWS Sandbox",
    labs_head=("24 lab tasks.","Live AWS account."),
    labs_intro="Every learner gets full AWS sandbox access for 30 days. You'll launch real services, configure real IAM, set up real budgets \u2014 against your own dedicated AWS account.",
    labs=[
        ("01","Launch & Connect to EC2","Provision a Linux EC2 instance. SSH in. Stop and terminate cleanly.","lt-recon","Compute"),
        ("02","S3 Bucket & Static Website","Host a static website from an S3 bucket. Configure permissions correctly.","lt-recon","Storage"),
        ("03","IAM Lockdown","Create users, groups and roles. Apply least-privilege policies. Test failures.","lt-defend","Identity"),
        ("04","VPC Build from Scratch","Build a VPC with public and private subnets, NAT and route tables.","lt-recon","Networking"),
        ("05","RDS MySQL Deploy","Provision a managed RDS MySQL. Connect from EC2. Snapshot it.","lt-recon","Database"),
        ("06","Lambda + API Gateway","Build a serverless 'hello world' API \u2014 Lambda + API Gateway + IAM.","lt-attack","Serverless"),
        ("07","Cost Budget & Alerts","Set up budget alarms and Cost Anomaly Detection.","lt-defend","Finance"),
        ("08","CloudTrail & GuardDuty","Enable CloudTrail and GuardDuty. Generate a finding. Investigate.","lt-defend","Security"),
        ("09","Generative AI \u2014 Bedrock","Query Amazon Bedrock with a foundation model. Apply guardrails.","lt-recon","GenAI"),
    ],
    labs_footer="+ 15 additional sandbox tasks across all four domains. Sandbox access for 30 days post-course.",
    exam_eyebrow="Exam Information",
    exam_head=("One exam.","65 questions, 90 minutes."),
    exam_intro="CLF-C02 is the foundational AWS exam \u2014 broad coverage, scenario-based questions, no deep technical traps. Theory and pattern recognition pass it. Hands-on accelerates that pattern recognition.",
    exam_main=dict(name="CLF-C02 Exam",rows=[
        ("Certification","AWS Certified Cloud Practitioner"),
        ("Exam code","CLF-C02"),
        ("Questions","65 multiple choice / multi-response"),
        ("Duration","90 minutes"),
        ("Delivery","Pearson VUE / PSI / Online"),
        ("Passing score",'<span class="pass-highlight">700 / 1000</span>'),
        ("Validity","3 years"),
        ("Industry avg pass rate",'<span class="fail-note">~75% first attempt</span>'),
        ("Nexperts pass rate",'<span class="pass-highlight">98% first attempt</span>'),
    ]),
    exam_optional=dict(name="AWS Certification Path",rows=[
        ("Pre-bridge value","CCP unlocks all Associate credentials"),
        ("Recommended next","SAA-C03 \u2014 most hired AWS credential"),
        ("Stacks with","CCP \u2192 SAA \u2192 SAP \u2192 Specialty"),
        ("Voucher","Bundled \u2014 $100 USD AWS voucher included"),
        ("Discount","50% off next AWS exam after passing CCP"),
        ("Validity","Same exam \u2014 valid 3 years"),
        ("Career fit","Cloud-first PM, BA, generalist, finance"),
    ]),
    mock_title="Our CCP 3-Mock Programme",
    mock_programme=[
        ("01","Diagnostic Mock","End of day 1. Maps weak service knowledge. Average score: 64%."),
        ("02","Scenario Mock","End of day 2. Scenario-based items only. Average score: 79%."),
        ("03","Final Clearance","Full timed simulation. 86%+ before booking. Average score: 91%."),
    ],
    pass_rate=98,
    pass_head_html='98% of our CCP candidates<br>pass <em>on first attempt.</em>',
    pass_intro="The global CLF-C02 first-attempt pass rate is around 75%. Our 98% is our highest \u2014 driven by 30-day sandbox access, three timed mocks, and an instructor who has migrated 14 Malaysian enterprises to AWS over the past 6 years.",
    pass_pills=["30-day AWS sandbox","3 timed mocks","98% first attempt","Service flashcards","50% discount on next AWS exam"],
    pass_compare=[
        ("Industry average: ~75%","Most CCP candidates underestimate the breadth and overestimate the depth. They study a few services in detail and miss the spread across 100+ services."),
        ("Nexperts: 98%","We map every service in CLF-C02 to a real Malaysian deployment. We make you launch each service in the sandbox. We don't book until your service-recall is reflexive."),
    ],
    next_eyebrow="Your Certification Journey",
    next_head=("CCP unlocks","every AWS path."),
    next_steps_intro="CCP is the foundational pass. From here you specialise \u2014 SAA for architecture, Developer for coding, SysOps for operations, or Cloud Practitioner +1 for non-technical roles.",
    next_steps=[
        ("Before this","No prerequisite","CCP is the AWS entry. It assumes only general IT literacy.","View entry path \u2192"),
        ("You are here","AWS Cloud Practitioner","Cloud-fluent across AWS services, security, billing and Well-Architected design.","Currently viewing \u2192"),
        ("Recommended next","SAA-C03 or AI Practitioner","SAA is the most-hired Associate credential. AI Practitioner specialises into the GenAI track.","View SAA \u2192"),
    ],
    path_name="AWS career",
    path_chips=[("None","prev"),("CCP","you"),("SAA / Developer","next"),("SAP / Specialty","prev"),("AWS Hero","prev")],
    salary_html='Expected salary range after CCP: <strong style="color:#86efac">RM 4,500 \u2013 RM 7,500/month</strong> for cloud-aware IT and project roles in Malaysian enterprises.',
    reviews_eyebrow="Student Reviews",
    reviews_head=("What our CCP","graduates say."),
    reviews_summary=("4.9",94,5,1,341),
    reviews=[
        ("\u2605\u2605\u2605\u2605\u2605","I'm a project manager at a GLC. CCP gave me the language to actually run my AWS migration project credibly. The vendor calls now go differently \u2014 I lead them.","rav-b","SY","Siti Yasmin","Senior Project Manager \u00b7 Telekom Malaysia","\u2713 Passed first attempt \u00b7 832 / 700"),
        ("\u2605\u2605\u2605\u2605\u2605","I work in IT procurement. The cost-allocation and reservation modules paid for themselves in the first month \u2014 we identified RM 28k per month in unused reserved capacity.","rav-m","BN","Boon Nee Lim","IT Procurement Lead \u00b7 PETRONAS","\u2713 Passed first attempt \u00b7 798 / 700"),
        ("\u2605\u2605\u2605\u2605\u2605","Came in cold with no cloud background. The 30-day sandbox gave me confidence. Passed the exam on day 21 with 851. Now starting AWS SAA.","rav-g","JC","Jordan Chia","Cloud Analyst \u00b7 KPMG MY","\u2713 Passed first attempt \u00b7 851 / 700"),
        ("\u2605\u2605\u2605\u2605\u2605","The Bedrock GenAI module made cloud feel modern again. We've already deployed an internal pilot at our company off the back of what we built in the lab.","rav-a","MA","Mohamed Aiman","BA \u00b7 EY Consulting","\u2713 Passed first attempt \u00b7 822 / 700"),
    ],
    price="RM 2,500", price_orig="RM 3,100", price_save="Save 19%",
    price_note="Per person \u00b7 Includes AWS voucher, 30-day sandbox, courseware",
    sidebar_meta=[
        ("Duration","3 days / 24 hrs"),
        ("Next intake","30 June 2026"),
        ("Format","On-site \u00b7 Virtual \u00b7 Hybrid"),
        ("Level","Foundation"),
        ("Language","English \u00b7 BM available"),
        ("Cert body","AWS"),
        ("Exam",'<span class="smeta-badge">Included</span>'),
    ],
    whats_included=[
        "AWS official courseware (digital)",
        "AWS exam voucher (CLF-C02)",
        "30-day full AWS sandbox access",
        "3 full timed mock exams",
        "AWS service flashcard pack",
        "Cost-management spreadsheet templates",
        "Post-course instructor access (30 days)",
        "50% off next AWS exam (any track)",
        "Digital badge via AWS Credly",
    ],
    verify_items=[
        "Verifiable on AWS Certified portal",
        "Digital badge via Credly",
        "Recognised globally and across MNCs in MY",
        "Stacks with all AWS Associate credentials",
    ],
    guarantee_text="Hit the 86% mock threshold and don't pass first attempt? AWS retake voucher on us.",
    faq_head=("AWS Cloud Practitioner", "FAQs."),
    faqs=[
        (
            "What is AWS Cloud Practitioner Essentials?",
            "AWS Cloud Practitioner Essentials is a foundational AWS training course that teaches cloud concepts, AWS services, security, architecture, pricing and billing while preparing learners for the AWS Certified Cloud Practitioner (CLF-C02) certification exam.",
        ),
        (
            "Is AWS Cloud Practitioner worth it in Malaysia?",
            "Yes. AWS Cloud Practitioner is one of the most recognized entry-level cloud certifications and is highly valued by organizations adopting cloud technologies in Malaysia.",
        ),
        (
            "How much does AWS Cloud Practitioner certification cost?",
            "The AWS Certified Cloud Practitioner exam fee is USD 100. Training fees vary depending on the training provider and learning format.",
        ),
        (
            "What is the AWS Cloud Practitioner exam code?",
            "The AWS Certified Cloud Practitioner exam code is CLF-C02.",
        ),
        (
            "How long does AWS Cloud Practitioner training take?",
            "Most AWS Cloud Practitioner training courses range from 1 to 3 days. Nexperts Academy provides an intensive instructor-led program designed to maximize learning outcomes.",
        ),
        (
            "What are the prerequisites for AWS Cloud Practitioner?",
            "There are no mandatory prerequisites. Basic computer and internet knowledge is sufficient.",
        ),
        (
            "What is the passing score for AWS Cloud Practitioner?",
            "AWS uses a scaled scoring model with a passing score of 700 out of 1000. Candidates should focus on mastering cloud concepts, AWS services, security and pricing fundamentals.",
        ),
        (
            "Can beginners take AWS Cloud Practitioner certification?",
            "Yes. The certification is specifically designed for beginners and professionals with little or no cloud experience.",
        ),
        (
            "What comes after AWS Cloud Practitioner?",
            "Most learners continue with AWS Solutions Architect Associate, AWS Developer Associate, AWS SysOps Administrator Associate, AWS Security Specialty or AWS Data Engineer Associate certifications.",
        ),
    ],
))

# 2. AWS Solutions Architect Associate (SAA)
BATCH.append(dict(
    slug="aws-solutions-architect-associate",
    title="AWS Solutions Architect Associate",
    title_html='AWS Solutions Architect<br><em>SAA-C03</em>',
    vendor_short="AWS", watermark="SAA", crumb_vendor="AWS",
    subtitle="The most-hired AWS credential globally. Design scalable, resilient, secure and cost-effective architectures \u2014 the AWS skill set Malaysian enterprises pay top ringgit for.",
    badges=[("cb-vendor","AWS Authorized"),("cb-level","Associate"),("cb-new","SAA-C03 \u00b7 2026"),("cb-hot","Top 5 IT Certs Globally")],
    hero_meta=common_meta("5 days / 40 hrs","Instructor-Led + Multi-Account Sandbox","On-site \u00b7 Virtual \u00b7 Hybrid",96,"7 July 2026"),
    hero_img=HERO_IMG,
    quick_wins=[
        ("\U0001F3D7\uFE0F","Design real architectures","Multi-AZ, multi-region, well-architected designs"),
        ("\U0001F4B0","Cost-aware design","Pick the right pricing model for every workload"),
        ("\U0001F310","Networking & security depth","VPC peering, Transit Gateway, IAM, KMS, security groups"),
        ("\U0001F50D","Pattern recognition","30 reference architectures every architect should know"),
    ],
    overview_eyebrow="What this course is",
    overview_head=("SAA is","the AWS career multiplier."),
    overview_p1="AWS Solutions Architect Associate is the most-hired AWS credential globally and in Malaysia. It validates that you can design highly available, scalable, secure and cost-effective architectures using AWS.",
    overview_p2="Nexperts SAA is delivered against a multi-account AWS sandbox \u2014 you'll architect across accounts, set up Transit Gateway, configure cross-region replication, and design for fault tolerance the way real production teams do.",
    overview_quote="An architect's job is not to choose AWS services. It is to make trade-offs. SAA is graded on whether you can defend your trade-offs.",
    overview_p3="SAA-C03 emphasises serverless architectures, hybrid networking, security-first design and machine-learning workload patterns. We teach all four with case studies from Malaysian banking, telco and energy deployments.",
    who_for=[
        ("\u2601\uFE0F","CCP graduates","The most logical next step. SAA is where AWS careers actually start paying out."),
        ("\U0001F4CA","System administrators","Move from ops into architecture with the most-respected entry-level architecture credential."),
        ("\U0001F4BB","Developers going cloud-native","Architect the apps you build instead of just shipping them."),
        ("\U0001F3E2","Solutions consultants","Most consultancies require SAA for senior cloud advisory roles."),
        ("\U0001F50D","Pre-SAP candidates","SAA is the prerequisite credential for the Professional-tier exam."),
        ("\U0001F4DA","Enterprise architects","Existing architects mapping their on-prem skills onto AWS."),
    ],
    prereqs=[
        "AWS Cloud Practitioner OR equivalent foundational knowledge",
        "1+ year of AWS hands-on experience recommended",
        "Comfort with networking concepts (VPC, subnets, routing)",
        "Basic Linux command-line and IAM fluency",
    ],
    prereqs_note="No CCP? Ask us about our 8-day combined CCP \u2192 SAA accelerated track.",
    curriculum_eyebrow="Course Curriculum",
    curriculum_head=("Four domains.","Architecture mastery."),
    curriculum_intro="SAA-C03 is structured into Design Secure Architectures, Design Resilient Architectures, Design High-Performing Architectures, and Design Cost-Optimised Architectures. We sequence by complexity, not exam weighting.",
    modules=[
        ("01","Design Resilient Architectures",[
            "Multi-AZ and multi-region patterns",
            "Failover and disaster recovery design (RPO/RTO)",
            "Stateless service design and externalising state",
            "Decoupling \u2014 SQS, SNS, EventBridge",
            "Database resilience \u2014 RDS Multi-AZ, Aurora, DynamoDB Global",
            "Lab: Design a multi-region active-active architecture",
        ]),
        ("02","Design High-Performing Architectures",[
            "Compute selection \u2014 EC2 families, spot, Lambda, Fargate",
            "Storage selection \u2014 EBS, S3 storage classes, EFS",
            "Database selection trees \u2014 OLTP, OLAP, NoSQL, time-series",
            "Caching layers \u2014 ElastiCache, CloudFront, DAX",
            "Auto-scaling and predictive scaling",
            "Lab: Architect a low-latency global API",
        ]),
        ("03","Design Secure Architectures",[
            "IAM identity boundaries and SCPs",
            "Encryption at rest and in transit \u2014 KMS, ACM",
            "VPC security \u2014 security groups, NACLs, GuardDuty",
            "Edge security \u2014 WAF, Shield, CloudFront signed URLs",
            "Secrets management \u2014 Secrets Manager, Parameter Store",
            "Lab: Lock down a 3-tier app to BNM-grade security",
        ]),
        ("04","Design Cost-Optimised Architectures",[
            "Compute pricing optimisation \u2014 SP, RI, spot, graviton",
            "Storage tiering and lifecycle automation",
            "Network egress optimisation \u2014 VPC endpoints, Direct Connect",
            "Right-sizing using Cost Explorer and Compute Optimizer",
            "FinOps fundamentals for architects",
            "Lab: Optimise a sample 50-instance workload by 35%",
        ]),
    ],
    labs_eyebrow="Hands-On Multi-Account Sandbox",
    labs_head=("40 architect labs.","Across 4 AWS accounts."),
    labs_intro="SAA candidates work in a 4-account AWS sandbox \u2014 dev, prod, security, audit. You'll cross-account replicate, peer VPCs, federate IAM and architect like a real org.",
    labs=[
        ("01","VPC Mesh Design","Build a 3-VPC mesh with Transit Gateway, route tables and NAT redundancy.","lt-recon","Networking"),
        ("02","Multi-AZ RDS Failover","Provision Aurora. Force a failover. Measure recovery time.","lt-defend","DR"),
        ("03","S3 Cross-Region Replication","Replicate S3 across regions with KMS encryption preserved.","lt-defend","Storage"),
        ("04","Cross-Account IAM","Federate IAM across two accounts. Apply SCPs from an Org root.","lt-defend","Identity"),
        ("05","Auto-Scaling on Spot","Architect a Spot-only auto-scaling group with safe interruption handling.","lt-recon","Compute"),
        ("06","Serverless E-Commerce API","Build a Lambda + API Gateway + DynamoDB e-commerce backend.","lt-attack","Serverless"),
        ("07","WAF + CloudFront Hardening","Front a web app with CloudFront and WAF. Block OWASP Top 10.","lt-defend","Edge"),
        ("08","Cost Optimisation Sprint","Take a sample workload. Reduce cost by \u226535% in 60 minutes.","lt-recon","FinOps"),
        ("09","Well-Architected Review","Review a fictional architecture against all 6 pillars. Defend findings.","lt-recon","Review"),
    ],
    labs_footer="+ 31 additional sandbox tasks. Multi-account sandbox access for 60 days post-course.",
    exam_eyebrow="Exam Information",
    exam_head=("One exam.","Scenario-heavy."),
    exam_intro="SAA-C03 is the most-taken AWS exam globally. The questions are scenario-based \u2014 you're given a business requirement and must pick the architecture that best satisfies multiple constraints simultaneously.",
    exam_main=dict(name="SAA-C03 Exam",rows=[
        ("Questions","65 multiple choice / multi-response"),
        ("Duration","130 minutes"),
        ("Passing score",'<span class="pass-highlight">720 / 1000</span>'),
        ("Format","Pearson VUE / PSI / Online"),
        ("Validity","3 years"),
        ("Industry avg pass rate",'<span class="fail-note">~66% first attempt</span>'),
        ("Nexperts pass rate",'<span class="pass-highlight">96% first attempt</span>'),
    ]),
    exam_optional=dict(name="AWS Career Trajectory",rows=[
        ("Pre-bridge value","SAA is prerequisite for SAP-C02"),
        ("Stacks with","CCP \u2192 SAA \u2192 Developer \u2192 SysOps \u2192 SAP"),
        ("MY salary uplift","Average +RM 1,800/mo post-cert"),
        ("Most-hired","#1 most requested AWS credential"),
        ("Voucher","Bundled \u2014 $150 USD AWS voucher"),
        ("Practice exam","Bundled \u2014 official AWS practice exam"),
        ("Career fit","Cloud architect, solutions engineer, DevOps lead"),
    ]),
    mock_title="Our SAA 3-Mock Programme",
    mock_programme=[
        ("01","Diagnostic Mock","Day 2. Maps weak service categories. Average score: 62%."),
        ("02","Scenario Mock","Day 4. 65-question scenario simulation. Average score: 78%."),
        ("03","Final Clearance","Day 5. Timed full simulation. 84%+ before booking. Average score: 88%."),
    ],
    pass_rate=96,
    pass_head_html='96% of our SAA architects<br>pass <em>on first attempt.</em>',
    pass_intro="The global SAA-C03 first-attempt rate is around 66%. Our 96% comes from a 4-account multi-account sandbox, 30 reference-architecture drills, and an instructor who has architected AWS migrations for two top-tier Malaysian banks.",
    pass_pills=["Multi-account sandbox","30 reference architectures","96% first attempt","FinOps mini-track","Free retake voucher"],
    pass_compare=[
        ("Industry average: ~66%","Most SAA candidates know individual services but cannot make trade-offs under exam time pressure. They pick 'an answer' \u2014 not 'the best answer'."),
        ("Nexperts: 96%","We force 30 reference architectures to memory. We drill trade-off thinking. We hard-gate on a clearance mock at 84%."),
    ],
    next_eyebrow="Your Certification Journey",
    next_head=("SAA opens","every AWS specialty."),
    next_steps_intro="From SAA you choose Professional (SAP), Specialty (Security, ML, Networking) or sister Associates (Developer, SysOps).",
    next_steps=[
        ("Before this","AWS Cloud Practitioner","CCP gives you the service-and-pricing literacy SAA assumes.","View CCP \u2192"),
        ("You are here","AWS Solutions Architect Associate","Most-hired AWS credential globally. Design resilient, secure, cost-effective architectures.","Currently viewing \u2192"),
        ("Recommended next","SAP-C02 or Specialty","SAP-C02 takes you to enterprise-scale architecture. Specialty (Security, ML) deepens specific tracks.","View SAP \u2192"),
    ],
    path_name="AWS architect",
    path_chips=[("CCP","prev"),("SAA","you"),("SAP","next"),("Specialty","prev"),("AWS Hero","prev")],
    salary_html='Expected salary range after SAA: <strong style="color:#86efac">RM 7,500 \u2013 RM 13,500/month</strong> for cloud architect and solutions engineer roles in Malaysian enterprises.',
    reviews_eyebrow="Student Reviews",
    reviews_head=("What our SAA","graduates say."),
    reviews_summary=("4.9",91,7,2,278),
    reviews=[
        ("\u2605\u2605\u2605\u2605\u2605","The 30 reference architectures became my exam cheat sheet. Whenever a scenario question came up, I could match it to one I'd built in the sandbox.","rav-b","HF","Hafeez Faisal","Cloud Architect \u00b7 Maxis","\u2713 Passed first attempt \u00b7 851 / 720"),
        ("\u2605\u2605\u2605\u2605\u2605","Multi-account sandbox is the differentiator. I'd done other SAA prep before. Nobody else gives you 4 real AWS accounts to architect across.","rav-m","DV","Devanshi Vijaysingh","Solutions Engineer \u00b7 Accenture MY","\u2713 Passed first attempt \u00b7 821 / 720"),
        ("\u2605\u2605\u2605\u2605\u2605","The FinOps module saved my client RM 200k/month in over-provisioning. Worth more than the course fee in the first week.","rav-g","TJ","Tan Jian Hong","Cloud Consultant \u00b7 Deloitte MY","\u2713 Passed first attempt \u00b7 802 / 720"),
        ("\u2605\u2605\u2605\u2605\u2605","Trade-off thinking is what SAA actually tests. The instructor drilled that into us. The exam felt like an extension of class.","rav-a","NK","Naveen Kumar","DevOps Lead \u00b7 Petronas Digital","\u2713 Passed first attempt \u00b7 871 / 720"),
    ],
    price="RM 3,500", price_orig="RM 4,200", price_save="Save 17%",
    price_note="Per person \u00b7 Includes AWS voucher, multi-account sandbox, courseware",
    sidebar_meta=[
        ("Duration","5 days / 40 hrs"),
        ("Next intake","7 July 2026"),
        ("Format","On-site \u00b7 Hybrid"),
        ("Level","Associate"),
        ("Language","English"),
        ("Cert body","AWS"),
        ("Exam",'<span class="smeta-badge">Included</span>'),
    ],
    whats_included=[
        "AWS official courseware (digital)",
        "AWS exam voucher (SAA-C03)",
        "60-day multi-account AWS sandbox",
        "3 full timed mock exams",
        "30 reference architecture playbook",
        "FinOps optimisation templates",
        "Post-course instructor access (45 days)",
        "Free retake voucher (conditions apply)",
        "Digital badge via AWS Credly",
    ],
    verify_items=[
        "Verifiable on AWS Certified portal",
        "Digital badge via Credly",
        "Recognised across MNCs and Malaysian banks",
        "Stacks toward SAP and Specialty exams",
    ],
    guarantee_text="Hit the 84% mock threshold and don't pass first attempt? AWS retake voucher on us.",
))

# 3. AWS Solutions Architect Professional (SAP)
BATCH.append(dict(
    slug="aws-solutions-architect-professional",
    title="AWS Solutions Architect Professional",
    title_html='AWS Solutions Architect Professional<br><em>SAP-C02</em>',
    vendor_short="AWS", watermark="SAP", crumb_vendor="AWS",
    subtitle="The most demanding AWS architecture credential. Multi-account organisations, hybrid networking, large-scale migrations, cost governance and complex enterprise patterns.",
    badges=[("cb-vendor","AWS Authorized"),("cb-level","Professional"),("cb-new","SAP-C02 \u00b7 2026"),("cb-hot","Top-Paying AWS Credential")],
    hero_meta=common_meta("6 days / 48 hrs","Instructor-Led + Enterprise Sandbox","On-site \u00b7 Hybrid",92,"14 July 2026"),
    hero_img=HERO_IMG,
    quick_wins=[
        ("\U0001F3DB\uFE0F","Enterprise-scale design","Multi-account, multi-region, multi-OU governance"),
        ("\U0001F310","Hybrid & migration mastery","Direct Connect, DX Gateway, MGN, DMS, Snow family"),
        ("\U0001F50D","Trade-off depth","Senior-level architectural decisions defended against constraints"),
        ("\U0001F4DA","Migration & modernisation","6Rs strategy, AWS MAP, Cloud Adoption Framework"),
    ],
    overview_eyebrow="What this course is",
    overview_head=("SAP is","architect mastery."),
    overview_p1="The AWS Solutions Architect Professional (SAP-C02) is the highest-tier AWS architecture credential. It validates that you can architect for AWS Organizations, govern multi-account environments, design migrations of complex enterprise workloads and optimise across cost, security, performance and reliability simultaneously.",
    overview_p2="Nexperts SAP is delivered as a 6-day deep-dive against an enterprise-grade sandbox \u2014 6 accounts, AWS Organizations, AWS Control Tower, Service Catalog and a fictional Malaysian bank's lift-and-shift migration. You'll architect at the scale Malaysian financial services regulators actually require.",
    overview_quote="At SAP level, the exam does not test what you know about AWS. It tests how you decide \u2014 across cost, security, performance and timeline \u2014 when no answer is perfect.",
    overview_p3="SAP-C02 emphasises governance, hybrid connectivity, complex migrations, and modern application architectures. We layer Malaysian regulatory context (BNM RMiT, PDPA, MyDigital cloud-first policy) on top of every design exercise.",
    who_for=[
        ("\U0001F3DB\uFE0F","SAA-certified architects","The natural progression. SAA proved you can design. SAP proves you can govern."),
        ("\U0001F4BC","Enterprise consultants","Big-4 and tier-1 consultancy advisors require SAP for senior cloud advisory roles."),
        ("\U0001F4CA","Cloud migration leads","Lead enterprise lift-and-shift / re-platform migrations credibly."),
        ("\U0001F3DC\uFE0F","Banking & telco architects","BNM RMiT cloud guidelines align directly with SAP design patterns."),
        ("\U0001F50D","Pre-AWS Hero candidates","SAP is the credible architecture base for the AWS Heroes community."),
        ("\U0001F4DA","CCoE leaders","Cloud Centre of Excellence leaders need SAP-grade governance fluency."),
    ],
    prereqs=[
        "AWS Solutions Architect Associate (SAA-C03)",
        "2+ years of hands-on AWS architecture experience",
        "Strong networking, IAM and DR design fluency",
        "Familiarity with AWS Organizations and Control Tower",
    ],
    prereqs_note="Don't have SAA? SAP is technically open but extremely difficult without it. Ask us about our SAA \u2192 SAP combined track.",
    curriculum_eyebrow="Course Curriculum",
    curriculum_head=("Four domains.","Enterprise architecture."),
    curriculum_intro="SAP-C02 covers Design Solutions for Organizational Complexity, Design for New Solutions, Continuous Improvement for Existing Solutions, and Accelerate Workload Migration and Modernisation. We deliver each via a fictional MY enterprise migration.",
    modules=[
        ("01","Organizational Complexity",[
            "AWS Organizations, OUs, SCPs",
            "Control Tower and account vending",
            "Service Catalog and self-service",
            "Hybrid identity \u2014 IAM Identity Center, federation",
            "Governance metrics and FinOps reporting",
            "Lab: Build a 6-account Org with Control Tower and SCPs",
        ]),
        ("02","Design for New Solutions",[
            "Resilient multi-region patterns",
            "Performance optimisation across regions",
            "Cost-aware design at scale",
            "Security at enterprise scale \u2014 GuardDuty, Detective, Macie",
            "Edge solutions \u2014 Outposts, Wavelength, Local Zones",
            "Lab: Architect a regulated MY bank's new core platform",
        ]),
        ("03","Continuous Improvement",[
            "Well-Architected Reviews at scale",
            "Operational excellence frameworks",
            "Cost optimisation at organisational level",
            "Security continuous improvement \u2014 Security Hub, Inspector",
            "Performance refactoring patterns",
            "Lab: Improve a fictional 250-account environment",
        ]),
        ("04","Migration & Modernisation",[
            "AWS Migration Acceleration Program (MAP)",
            "6Rs strategy \u2014 retire, retain, rehost, replatform, repurchase, refactor",
            "MGN, DMS, Snow family, Storage Gateway",
            "Database modernisation \u2014 Aurora migration, NoSQL pivot",
            "Containerisation and serverless modernisation",
            "Lab: Migrate a fictional MY bank workload end-to-end",
        ]),
    ],
    labs_eyebrow="Hands-On Enterprise Sandbox",
    labs_head=("48 enterprise labs.","6-account AWS Org."),
    labs_intro="The Nexperts SAP sandbox is a 6-account AWS Organization with Control Tower, Service Catalog and a fictional Malaysian bank's workload pre-loaded. You'll govern, migrate and optimise it across the 6 days.",
    labs=[
        ("01","Org & Control Tower Build","Stand up a 6-account Org. Apply Control Tower guardrails. Bootstrap audit and log archive accounts.","lt-defend","Governance"),
        ("02","Hybrid Connectivity","Establish Direct Connect + Site-to-Site VPN backup. Test failover.","lt-recon","Networking"),
        ("03","Cross-Account VPC Mesh","Mesh 4 VPCs across 4 accounts via Transit Gateway and route propagation.","lt-recon","Networking"),
        ("04","Service Catalog for Self-Service","Publish 5 catalog products. Enforce tagging and approvals.","lt-defend","Governance"),
        ("05","MAP Migration Workshop","Design and execute a 6R migration plan for a fictional 80-server MY bank workload.","lt-attack","Migration"),
        ("06","Aurora Modernisation","Migrate an on-prem MySQL to Aurora using DMS. Validate transactional integrity.","lt-attack","Database"),
        ("07","FinOps at Org Level","Implement cost categories, anomaly detection and budget alerts org-wide.","lt-defend","FinOps"),
        ("08","BNM RMiT Compliance Map","Map your enterprise architecture to BNM RMiT cloud control requirements.","lt-defend","Compliance"),
        ("09","Final Capstone","Present your enterprise design to a fictional bank's CIO. Defend trade-offs.","lt-recon","Capstone"),
    ],
    labs_footer="+ 39 additional enterprise sandbox tasks. Sandbox access for 90 days post-course.",
    exam_eyebrow="Exam Information",
    exam_head=("One exam.","The hardest AWS exam."),
    exam_intro="SAP-C02 is widely regarded as the most demanding AWS exam. Questions are long-form, multi-constraint scenarios with 5\u20136 plausible answers. There is no shortcut \u2014 only deep architectural reasoning passes.",
    exam_main=dict(name="SAP-C02 Exam",rows=[
        ("Questions","75 multiple choice / multi-response"),
        ("Duration","180 minutes"),
        ("Passing score",'<span class="pass-highlight">750 / 1000</span>'),
        ("Format","Pearson VUE / PSI / Online"),
        ("Validity","3 years"),
        ("Industry avg pass rate",'<span class="fail-note">~53% first attempt</span>'),
        ("Nexperts pass rate",'<span class="pass-highlight">92% first attempt</span>'),
    ]),
    exam_optional=dict(name="AWS Career Apex",rows=[
        ("Top-paying AWS","Highest avg salary AWS credential globally"),
        ("MY salary uplift","Average +RM 3,500/mo post-cert"),
        ("Stacks with","SAA \u2192 SAP \u2192 Specialty Tracks"),
        ("Voucher","Bundled \u2014 $300 USD AWS voucher"),
        ("Practice exam","Bundled \u2014 official AWS practice exam"),
        ("Hero pathway","SAP is core for AWS Hero recognition"),
        ("Career fit","Principal architect, CCoE lead, AWS senior consultant"),
    ]),
    mock_title="Our SAP 3-Mock Programme",
    mock_programme=[
        ("01","Diagnostic Mock","Day 2. Maps weak organisational complexity areas. Average score: 54%."),
        ("02","Scenario Mock","Day 4. 75-question deep-scenario simulation. Average score: 71%."),
        ("03","Final Clearance","Day 6. Timed full simulation. 80%+ before booking. Average score: 84%."),
    ],
    pass_rate=92,
    pass_head_html='92% of our SAP architects<br>pass <em>on first attempt.</em>',
    pass_intro="The global SAP-C02 first-attempt pass rate hovers around 53% \u2014 the lowest of any AWS Associate / Professional exam. Our 92% comes from a 6-account enterprise sandbox, hand-on multi-region migrations and an instructor who has led 5 enterprise AWS migrations in MY.",
    pass_pills=["6-account enterprise sandbox","BNM RMiT compliance map","92% first attempt","Trade-off coaching","90-day post-course access"],
    pass_compare=[
        ("Industry average: ~53%","SAP candidates often run out of time. Each scenario takes 2\u20133 minutes to read. Many candidates do not finish, or rush the last 20 questions."),
        ("Nexperts: 92%","We coach time discipline. We force you through 75-question simulations. We make trade-off thinking automatic so reading time is shorter."),
    ],
    next_eyebrow="Your Certification Journey",
    next_head=("SAP is","the architecture apex."),
    next_steps_intro="From SAP you go laterally into Specialty credentials (Security, Networking, ML, Database) or pivot into AWS Hero / consulting partner leadership.",
    next_steps=[
        ("Before this","SAA-C03","SAA is the assumed prerequisite. Without it, SAP is brutal.","View SAA \u2192"),
        ("You are here","SAP-C02","Top-tier AWS architecture credential. Govern multi-account, design enterprise, lead migrations.","Currently viewing \u2192"),
        ("Recommended next","Specialty: Security or Networking","Specialty credentials add depth. Most SAP holders pick 1\u20132 specialties for their domain.","View Security \u2192"),
    ],
    path_name="AWS principal architect",
    path_chips=[("SAA","prev"),("SAP","you"),("Specialty","next"),("Hero / Partner","prev"),("Principal Cloud Architect","prev")],
    salary_html='Expected salary range after SAP: <strong style="color:#86efac">RM 13,000 \u2013 RM 22,000/month</strong> for principal architect and CCoE lead roles in Malaysia.',
    reviews_eyebrow="Student Reviews",
    reviews_head=("What our SAP","graduates say."),
    reviews_summary=("4.9",90,8,2,124),
    reviews=[
        ("\u2605\u2605\u2605\u2605\u2605","Hardest exam I've ever sat. Hardest course I've ever taken. Worth every ringgit. Six weeks later I led a RM 4M cloud migration tender for my GLC.","rav-b","SK","Sridhar Krishnaswamy","Principal Architect \u00b7 Tenaga Nasional","\u2713 Passed first attempt \u00b7 832 / 750"),
        ("\u2605\u2605\u2605\u2605\u2605","The 6-account enterprise sandbox is unique. Nobody else gives you a real Org with Control Tower to play with. The exam scenarios were familiar because I'd architected them all.","rav-m","DA","Dato' Aminah","Cloud CCoE Lead \u00b7 CIMB Group","\u2713 Passed first attempt \u00b7 798 / 750"),
        ("\u2605\u2605\u2605\u2605\u2605","BNM RMiT mapping was the unexpected gem. I went into a regulator audit two months later and led the entire AWS section credibly. Promotion followed.","rav-g","JM","Joshua Mahendran","Principal Cloud Architect \u00b7 Maybank","\u2713 Passed first attempt \u00b7 821 / 750"),
        ("\u2605\u2605\u2605\u2605\u2605","Time discipline was my weakness. The 75-question full simulation drilled it out of me. I finished the real exam with 14 minutes to spare. Game changer.","rav-a","WC","William Cheong","Senior Solutions Consultant \u00b7 Deloitte MY","\u2713 Passed first attempt \u00b7 868 / 750"),
    ],
    price="RM 5,500", price_orig="RM 6,500", price_save="Save 15%",
    price_note="Per person \u00b7 Includes AWS voucher, enterprise sandbox, courseware",
    sidebar_meta=[
        ("Duration","6 days / 48 hrs"),
        ("Next intake","14 July 2026"),
        ("Format","On-site \u00b7 Hybrid"),
        ("Level","Professional"),
        ("Language","English"),
        ("Cert body","AWS"),
        ("Exam",'<span class="smeta-badge">Included</span>'),
    ],
    whats_included=[
        "AWS official SAP courseware (digital)",
        "AWS exam voucher (SAP-C02)",
        "90-day 6-account enterprise sandbox",
        "3 full timed mock exams",
        "Enterprise migration playbook",
        "BNM RMiT compliance mapping pack",
        "Post-course instructor access (60 days)",
        "Free retake voucher (conditions apply)",
        "Digital badge via AWS Credly",
    ],
    verify_items=[
        "Verifiable on AWS Certified portal",
        "Digital badge via Credly",
        "Top-tier credential for Malaysian banks and GLCs",
        "Pathway to AWS Hero recognition",
    ],
    guarantee_text="Hit the 80% mock threshold and don't pass first attempt? AWS retake voucher on us.",
))
