# -*- coding: utf-8 -*-
"""ITIL / PM / DevOps course data (ITIL 4 Foundation, PMP, CKA)."""
from _course_data import HERO_IMG, common_meta

BATCH = []

# 1. ITIL 4 Foundation
BATCH.append(dict(
    slug="itil-4-foundation",
    title="ITIL 4 Foundation",
    title_html='ITIL 4<br><em>Foundation</em>',
    vendor_short="PeopleCert", watermark="ITIL", crumb_vendor="PeopleCert",
    subtitle="The world's most-adopted IT service management framework. ITIL 4 introduces the Service Value System, guiding principles and 34 management practices for modern IT operations.",
    badges=[("cb-vendor","PeopleCert ATO"),("cb-level","Foundation"),("cb-new","ITIL 4 \u00b7 2026"),("cb-hot","ITSM Standard")],
    hero_meta=common_meta("3 days / 24 hrs","Instructor-Led + Case Studies","On-site \u00b7 Virtual \u00b7 Hybrid",98,"22 September 2026"),
    hero_img=HERO_IMG,
    quick_wins=[
        ("\U0001F501","Service Value System","Service Value Chain, guiding principles, governance and improvement"),
        ("\U0001F4DC","34 management practices","From Incident, Change, Problem to Service Design and Knowledge"),
        ("\U0001F4CA","Modern ITSM thinking","DevOps, Lean, Agile integration with ITIL practices"),
        ("\U0001F3DB\uFE0F","Aligned with MY context","BNM RMiT, MyDigital, public-sector ITSM transformations"),
    ],
    overview_eyebrow="What this course is",
    overview_head=("ITIL 4 is","modern ITSM."),
    overview_p1="ITIL 4 Foundation is the world's most-adopted IT service management certification. It introduces the Service Value System (SVS), the seven Guiding Principles, four dimensions of service management, and 34 ITIL management practices.",
    overview_p2="Nexperts ITIL 4 is delivered with three deep MY case studies \u2014 a banking incident escalation, a public-sector change management transformation and a fintech problem management retrospective. Theory becomes practice.",
    overview_quote="ITIL 4 is not waterfall ITSM repackaged. It is a flexible operating model with DevOps and Agile integration. We coach the integration thinking, not just the practices.",
    overview_p3="The 2026 update strengthens DevOps integration, AI-augmented service desk patterns and continual improvement metrics. We teach with current MY enterprise ITSM transformation case studies throughout.",
    who_for=[
        ("\U0001F4BB","IT service desk staff","The credential most commonly required for L1/L2 service desk roles."),
        ("\U0001F4C8","Operations managers","Lead ITIL-aligned IT operations across application and infrastructure teams."),
        ("\U0001F4CB","Project / program managers","ITIL fluency complements PMP and Scrum credentials in IT contexts."),
        ("\U0001F3DB\uFE0F","Banking / GLC IT staff","BNM RMiT and MyDigital governance frameworks are ITIL-aligned."),
        ("\U0001F4DA","Pre-DevOps engineers","Modern DevOps culture builds on ITIL practices \u2014 not replaces them."),
        ("\U0001F393","Career switchers","ITIL Foundation is the lowest-barrier credential to enter the IT service domain."),
    ],
    prereqs=[
        "No formal prerequisite",
        "Familiarity with IT operations helpful",
        "Curiosity about service management thinking",
        "Comfort with English-language exam materials",
    ],
    prereqs_note="No IT background? ITIL Foundation is genuinely accessible. Ask us about our pre-ITIL primer.",
    curriculum_eyebrow="Course Curriculum",
    curriculum_head=("Five domains.","ITIL 4 end-to-end."),
    curriculum_intro="ITIL 4 Foundation covers Key Concepts, Guiding Principles, Four Dimensions, Service Value System and Management Practices. We deliver as a continuous transformation story, not a slide-deck.",
    modules=[
        ("01","Key Concepts of ITIL 4",[
            "Service value, products and services",
            "Outcomes, costs, risks and value definitions",
            "Service relationships \u2014 customer, user, sponsor",
            "Service offerings and contracts",
            "Value co-creation principle",
            "Lab: Map a banking service relationship across roles",
        ]),
        ("02","Guiding Principles",[
            "Focus on value",
            "Start where you are",
            "Progress iteratively with feedback",
            "Collaborate and promote visibility",
            "Optimise and automate",
            "Lab: Apply 3 guiding principles to a fintech case",
        ]),
        ("03","Four Dimensions of Service Management",[
            "Organisations and people",
            "Information and technology",
            "Partners and suppliers",
            "Value streams and processes",
            "External factors influencing all four",
            "Lab: Audit a service through the four-dimension lens",
        ]),
        ("04","Service Value System & Chain",[
            "ITIL Service Value System (SVS) overview",
            "Service Value Chain activities \u2014 plan, improve, engage, design, transition, obtain, deliver",
            "Continual Improvement model",
            "Governance, practices and inputs / outputs",
            "Demand and value-streams thinking",
            "Lab: Map a Service Value Chain for a public-sector portal",
        ]),
        ("05","ITIL Management Practices (selected)",[
            "Incident, Problem, Change, Service Request",
            "Service Desk and Service Level Management",
            "Configuration Management Database (CMDB)",
            "Information Security and Continual Improvement practices",
            "Modern integration \u2014 DevOps, Agile, Lean alignment",
            "Lab: Run a problem-management retrospective end-to-end",
        ]),
    ],
    labs_eyebrow="Hands-On Case Studies",
    labs_head=("3 deep case studies.","Realistic MY context."),
    labs_intro="Three deep case studies \u2014 a banking incident escalation, a public-sector change management transformation, and a fintech problem-management retrospective. You discuss, decide and defend in groups.",
    labs=[
        ("01","Banking Sev-1 Escalation","Run an incident from detection through resolution. Document timeline.","lt-defend","Incident"),
        ("02","Public-sector Change Migration","Plan a CR for a federal portal migration. Apply Change Authority levels.","lt-recon","Change"),
        ("03","Fintech Problem Retrospective","Run a problem retro after a recurring outage. Identify root cause.","lt-forensic","Problem"),
        ("04","CMDB Hygiene Sprint","Audit a CMDB. Identify 5 hygiene issues. Plan remediation.","lt-defend","Config"),
        ("05","SLA Negotiation","Negotiate a realistic SLA between IT and finance.","lt-recon","SLA"),
        ("06","Service Desk Escalation Tree","Design a 3-tier service desk escalation tree.","lt-defend","Service Desk"),
        ("07","Continual Improvement Plan","Run a CI workshop on a chronic issue. Document KPIs.","lt-recon","CI"),
        ("08","Service Value Stream Mapping","Map a value stream for a banking customer journey.","lt-recon","Value Stream"),
        ("09","Final Capstone","Pitch an ITIL transformation roadmap to a fictional CIO.","lt-recon","Capstone"),
    ],
    labs_footer="+ Group exercises throughout. Case-study workbooks for ongoing reference.",
    exam_eyebrow="Exam Information",
    exam_head=("One exam.","Concept-focused."),
    exam_intro="ITIL 4 Foundation is a 60-minute multiple-choice exam. The exam tests whether you can recall and apply ITIL concepts \u2014 not whether you've memorised process diagrams. Pattern recognition and clear thinking pass it.",
    exam_main=dict(name="ITIL 4 Foundation Exam",rows=[
        ("Questions","40 multiple choice"),
        ("Duration","60 minutes (75 with accommodations)"),
        ("Passing score",'<span class="pass-highlight">26 / 40 (65%)</span>'),
        ("Format","PeopleCert online proctored"),
        ("Validity","No expiration (Foundation level)"),
        ("Industry avg pass rate",'<span class="fail-note">~84% first attempt</span>'),
        ("Nexperts pass rate",'<span class="pass-highlight">98% first attempt</span>'),
    ]),
    exam_optional=dict(name="ITIL Career Path",rows=[
        ("Stacks with","ITIL 4 Foundation \u2192 Specialist / Strategist"),
        ("Pathways","Managing Professional / Strategic Leader"),
        ("Voucher","Bundled \u2014 PeopleCert voucher included"),
        ("Renewal","No expiration at Foundation level"),
        ("MY recognition","Required by MyDigital ITSM transformation"),
        ("Career fit","Service desk, ops manager, BA, project manager"),
        ("Industry depth","Required by big-4 consultancies for IT advisory"),
    ]),
    mock_title="Our ITIL 4 3-Mock Programme",
    mock_programme=[
        ("01","Diagnostic Mock","Day 1 evening. Maps weak practices. Average score: 73%."),
        ("02","Concept Mock","Day 2 evening. Concept-focused practice. Average score: 84%."),
        ("03","Final Clearance","Day 3. Full timed simulation. 80%+ before booking. Average score: 90%."),
    ],
    pass_rate=98,
    pass_head_html='98% of our ITIL 4 candidates<br>pass <em>on first attempt.</em>',
    pass_intro="The global ITIL 4 first-attempt rate is around 84%. Our 98% comes from three deep case studies that anchor the practices, an instructor with 18 years of MY ITSM transformation experience, and three timed mocks.",
    pass_pills=["Three MY case studies","18-year ITSM instructor","98% first attempt","BNM RMiT alignment","Free retake voucher"],
    pass_compare=[
        ("Industry average: ~84%","Most candidates pass but with low margins. They memorise the practice list without understanding how the Service Value Chain weaves them."),
        ("Nexperts: 98%","We force every concept through case-study application. The exam feels like a fourth case study by the time you sit it."),
    ],
    next_eyebrow="Your Certification Journey",
    next_head=("ITIL 4 leads to","Specialist or Strategist."),
    next_steps_intro="From ITIL 4 Foundation you choose Specialist (CDS, DSV, HVIT, DPI) toward Managing Professional, or Strategist (DITS) toward Strategic Leader.",
    next_steps=[
        ("Before this","No prerequisite","ITIL 4 Foundation is the entry point. It assumes only IT operations literacy.","View entry path \u2192"),
        ("You are here","ITIL 4 Foundation","ITSM-fluent. Service Value System, four dimensions, 34 practices and guiding principles.","Currently viewing \u2192"),
        ("Recommended next","ITIL 4 Specialist or Strategist","CDS / DSV / HVIT for ops, DPI for direction-setting, DITS for strategic leadership.","View ITIL Specialist \u2192"),
    ],
    path_name="ITIL practitioner",
    path_chips=[("None","prev"),("ITIL 4 Foundation","you"),("Specialist / Strategist","next"),("Managing Professional","prev"),("Strategic Leader","prev")],
    salary_html='Expected salary range after ITIL 4 Foundation: <strong style="color:#86efac">RM 4,800 \u2013 RM 8,500/month</strong> for service desk, ops and BA roles in Malaysian enterprises.',
    reviews_eyebrow="Student Reviews",
    reviews_head=("What our ITIL 4","graduates say."),
    reviews_summary=("4.9",96,3,1,418),
    reviews=[
        ("\u2605\u2605\u2605\u2605\u2605","Three case studies were the differentiator. Other ITIL prep is theory-only. Nexperts gave me real Sev-1 banking escalations to work through. Six weeks later, I led one for real.","rav-b","ZA","Zaireen Adnan","Service Desk Manager \u00b7 Bank Islam","\u2713 Passed first attempt \u00b7 36 / 26"),
        ("\u2605\u2605\u2605\u2605\u2605","DevOps integration thinking was unexpected. I came in expecting waterfall ITIL. Left with a much more nuanced view that bridges DevOps fluently.","rav-m","GH","Ghulam Husaini","Ops Lead \u00b7 PETRONAS","\u2713 Passed first attempt \u00b7 34 / 26"),
        ("\u2605\u2605\u2605\u2605\u2605","Public-sector change case was eye-opening. We're rolling out a federal portal next quarter and the case study made me the de-facto change authority for the team.","rav-g","NS","Nurfatin Suriani","BA \u00b7 Talent Corp","\u2713 Passed first attempt \u00b7 38 / 26"),
        ("\u2605\u2605\u2605\u2605\u2605","Service Value Chain finally clicked. I'd read the book three times \u2014 nothing stuck. Three days of case-study practice, and now I can map a value stream from memory.","rav-a","KL","Kah Loon Tan","Project Manager \u00b7 Allianz MY","\u2713 Passed first attempt \u00b7 35 / 26"),
    ],
    price="RM 2,400", price_orig="RM 2,900", price_save="Save 17%",
    price_note="Per person \u00b7 Includes PeopleCert voucher, case-study workbooks, courseware",
    sidebar_meta=[
        ("Duration","3 days / 24 hrs"),
        ("Next intake","22 September 2026"),
        ("Format","On-site \u00b7 Virtual \u00b7 Hybrid"),
        ("Level","Foundation"),
        ("Language","English \u00b7 BM available"),
        ("Cert body","PeopleCert / AXELOS"),
        ("Exam",'<span class="smeta-badge">Included</span>'),
    ],
    whats_included=[
        "PeopleCert / AXELOS official ITIL 4 courseware",
        "PeopleCert exam voucher",
        "Three deep MY case-study workbooks",
        "3 full timed mock exams",
        "Service Value Chain reference card",
        "BNM RMiT and MyDigital alignment notes",
        "Post-course instructor access (30 days)",
        "Free retake voucher (conditions apply)",
        "Digital badge via PeopleCert",
    ],
    verify_items=[
        "Verifiable on PeopleCert portal",
        "Digital badge via Credly",
        "Required by MyDigital and BNM RMiT alignment",
        "Pathway to ITIL Managing Professional / Strategic Leader",
    ],
    guarantee_text="Hit the 80% mock threshold and don't pass first attempt? PeopleCert retake voucher on us.",
))


# 2. PMP
BATCH.append(dict(
    slug="pmp",
    title="PMP",
    title_html='Project Management<br><em>Professional (PMP)\u00ae</em>',
    vendor_short="PMI", watermark="PMP", crumb_vendor="PMI",
    subtitle="The most-recognised project management credential globally. People, Process and Business Environment domains \u2014 covering predictive, agile and hybrid project delivery.",
    badges=[("cb-vendor","PMI Authorized ATP"),("cb-level","Professional"),("cb-new","2026 ECO"),("cb-hot","Top PM Hire")],
    hero_meta=common_meta("5 days / 35 contact hrs","Instructor-Led + Case Sims","On-site \u00b7 Virtual",95,"29 September 2026"),
    hero_img=HERO_IMG,
    quick_wins=[
        ("\U0001F465","People domain mastery","Lead, motivate, support team performance through PM lifecycle"),
        ("\u2699\uFE0F","Process domain depth","Predictive, agile and hybrid project execution"),
        ("\U0001F30F","Business environment","Strategy alignment, value delivery, organisational change"),
        ("\u2705","35 PDU contact hours","Eligibility prerequisite covered \u2014 ready to apply day-one"),
    ],
    overview_eyebrow="What this course is",
    overview_head=("PMP is","the PM credential."),
    overview_p1="The PMP\u00ae certification is the world's most-recognised project management credential. PMI's 2026 Examination Content Outline (ECO) covers People (42%), Process (50%) and Business Environment (8%) domains \u2014 spanning predictive, agile and hybrid delivery.",
    overview_p2="Nexperts PMP delivers the 35 contact hours of project management education that PMI requires for exam eligibility. We focus on case-driven application, not memorising the PMBOK Guide. Three half-day case-study sims simulate full project lifecycles.",
    overview_quote="PMP is not a process exam. It is a behavioural exam. Most questions ask 'what would you do' \u2014 and the right answer almost always centres on people leadership.",
    overview_p3="The 2026 ECO continues PMI's people-leadership emphasis with deeper agile and hybrid coverage. We teach with current MY project case studies \u2014 banking transformations, GLC ERP rollouts and government IT modernisation.",
    who_for=[
        ("\U0001F4CB","Project managers \u2265 3 years","The natural credential. PMP solidifies the role and accelerates senior promotions."),
        ("\U0001F4BC","Program managers","Multi-project portfolios benefit from PMP-level discipline and language."),
        ("\U0001F3DB\uFE0F","Banking / GLC PMs","BNM and Bursa-listed enterprises increasingly require PMP for senior PM roles."),
        ("\U0001F4CA","Construction PMs","CIDB-aligned construction firms require PMI credentials for project leadership."),
        ("\U0001F4DA","Pre-PgMP candidates","PMP is the natural runway to PMI's program management track."),
        ("\U0001F50D","Cross-industry PMs","Manufacturing, healthcare, telco, retail \u2014 PMP is industry-agnostic."),
    ],
    prereqs=[
        "Bachelor's + 36 months PM experience + 35 contact hours, OR",
        "Diploma + 60 months PM experience + 35 contact hours",
        "PMI membership recommended (~ USD 139 / year)",
        "Comfort with English-language exam materials",
    ],
    prereqs_note="35 contact hours are covered by this course. We help you prepare your PMI application portfolio too.",
    curriculum_eyebrow="Course Curriculum",
    curriculum_head=("Three domains.","People, Process, Business."),
    curriculum_intro="The 2026 ECO splits content into People (42%), Process (50%) and Business Environment (8%). We deliver against three case-study sims spanning predictive, agile and hybrid delivery.",
    modules=[
        ("01","People Domain (42%)",[
            "Manage conflict, lead a team, support team performance",
            "Empower team members and stakeholders",
            "Build shared understanding, address impediments",
            "Promote team performance through emotional intelligence",
            "Mentor relevant stakeholders",
            "Lab: Run a team conflict resolution role-play",
        ]),
        ("02","Process Domain (50%)",[
            "Plan and manage scope, schedule, budget and resources",
            "Plan and manage quality, risk and procurement",
            "Manage project changes, integrate project activities",
            "Plan and manage communications and engagement",
            "Establish project governance and lessons-learned",
            "Lab: Run a hybrid sprint plan + waterfall milestone plan",
        ]),
        ("03","Business Environment (8%)",[
            "Plan and manage project compliance",
            "Evaluate and deliver project benefits and value",
            "Evaluate and address external business environment changes",
            "Support organisational change",
            "Manage project compliance with regulatory and BNM RMiT context",
            "Lab: Build a value-delivery report for a fictional CFO",
        ]),
        ("04","Predictive, Agile and Hybrid Models",[
            "Predictive (waterfall) project delivery",
            "Agile delivery \u2014 Scrum, Kanban, XP, hybrid models",
            "Tailoring approach to project characteristics",
            "Disciplined Agile (DA) and SAFe overview",
            "Choosing predictive vs agile vs hybrid",
            "Lab: Tailor a delivery approach for 3 fictional MY projects",
        ]),
        ("05","PMP Exam Strategy & Application",[
            "PMI ATP exam preparation methodology",
            "Question-pattern recognition and trap-spotting",
            "PMI Code of Ethics and Professional Conduct",
            "PMP application portfolio preparation",
            "PDU and renewal cycle planning",
            "Lab: Submit a mock PMI application together",
        ]),
    ],
    labs_eyebrow="Hands-On Case Sims",
    labs_head=("3 case sims.","Live project simulation."),
    labs_intro="Three half-day case sims \u2014 a banking digital transformation, a GLC ERP rollout and a government IT modernisation. You play PM, defend decisions, and earn lessons learned.",
    labs=[
        ("01","Banking Digital Transformation","Lead a 12-month digital banking program. Manage 5 vendors, 30 stakeholders.","lt-recon","Sim 1"),
        ("02","GLC ERP Rollout","Manage a 18-month ERP go-live. Handle change, training, cutover.","lt-recon","Sim 2"),
        ("03","Government IT Modernisation","Lead a 24-month federal modernisation. Handle compliance, communications.","lt-recon","Sim 3"),
        ("04","PMP Question Drills","Daily 30-question pattern drills with debrief.","lt-attack","Drills"),
        ("05","Stakeholder Mapping","Map a 30-stakeholder ecosystem with influence/interest grid.","lt-recon","Stakeholders"),
        ("06","Risk Register","Build a 25-row risk register with scoring and response strategies.","lt-defend","Risk"),
        ("07","Earned Value Management","Apply EVM to a 6-month project. Compute SPI, CPI, EAC.","lt-attack","EVM"),
        ("08","Hybrid Sprint Plan","Build a hybrid waterfall + sprint plan for a fintech case.","lt-recon","Hybrid"),
        ("09","Application Workshop","PMI application portfolio together \u2014 ready to submit.","lt-recon","Application"),
    ],
    labs_footer="+ Daily question drills. Case-study workbooks for ongoing reference.",
    exam_eyebrow="Exam Information",
    exam_head=("One exam.","Behavioural-heavy."),
    exam_intro="The PMP exam is 180 questions across People, Process and Business Environment. The exam is heavily behavioural \u2014 most questions ask 'what would you do' rather than 'what is the formula'. Pattern recognition and clear PM judgement pass it.",
    exam_main=dict(name="PMP Exam (2026 ECO)",rows=[
        ("Questions","180 multi-format"),
        ("Duration","230 minutes (incl. 2 breaks)"),
        ("Passing score",'<span class="pass-highlight">Variable (proficient across domains)</span>'),
        ("Format","Pearson VUE / Online proctor"),
        ("Validity","3 years (60 PDU renewal)"),
        ("Industry avg pass rate",'<span class="fail-note">~67% first attempt</span>'),
        ("Nexperts pass rate",'<span class="pass-highlight">95% first attempt</span>'),
    ]),
    exam_optional=dict(name="PMP Career Path",rows=[
        ("Stacks with","CAPM \u2192 PMP \u2192 PgMP / PfMP"),
        ("MY salary uplift","Average +RM 2,000/mo post-cert"),
        ("Voucher","PMI member rate USD 405 (covered separately)"),
        ("Application","We help you submit \u2014 included in fee"),
        ("Renewal","60 PDUs over 3 years"),
        ("Industry depth","Universally recognised across MY industries"),
        ("Career fit","Senior PM, program manager, PMO lead"),
    ]),
    mock_title="Our PMP 4-Mock Programme",
    mock_programme=[
        ("01","Diagnostic Mock","Day 2. Maps weak domains. Average score: 62%."),
        ("02","People-Heavy Mock","Day 3. People-domain focus. Average score: 76%."),
        ("03","Process-Heavy Mock","Day 4. Process-domain focus. Average score: 79%."),
        ("04","Final Clearance","Day 5. Full 180-question simulation. 80%+ before booking. Average score: 87%."),
    ],
    pass_rate=95,
    pass_head_html='95% of our PMP candidates<br>pass <em>on first attempt.</em>',
    pass_intro="The global PMP first-attempt rate is around 67%. Our 95% comes from three case sims, four timed mocks, daily 30-question pattern drills, and an instructor with 22 years of MY project leadership experience.",
    pass_pills=["Three case sims","Daily question drills","95% first attempt","Application included","Free retake voucher"],
    pass_compare=[
        ("Industry average: ~67%","Most candidates over-prepare on the formulas (EVM, networks) and under-prepare on the behavioural People-domain questions \u2014 which are 42% of the exam."),
        ("Nexperts: 95%","We make People-domain pattern recognition a daily drill. We hard-gate at 80% before letting you book. By exam day, behavioural questions feel familiar."),
    ],
    next_eyebrow="Your Certification Journey",
    next_head=("PMP unlocks","program leadership."),
    next_steps_intro="From PMP you specialise into program management (PgMP), portfolio management (PfMP), agile (PMI-ACP / Disciplined Agile) or risk (PMI-RMP).",
    next_steps=[
        ("Before this","CAPM (optional)","CAPM is PMI's associate-level credential. Many PMs skip it and go straight to PMP.","View CAPM \u2192"),
        ("You are here","PMP","Senior project manager. Predictive, agile and hybrid delivery across People, Process and Business Environment domains.","Currently viewing \u2192"),
        ("Recommended next","PgMP or PMI-ACP","PgMP scales into program management. PMI-ACP specialises into agile delivery.","View PgMP \u2192"),
    ],
    path_name="PMI program leader",
    path_chips=[("CAPM","prev"),("PMP","you"),("PgMP / PMI-ACP","next"),("PfMP","prev"),("PMI Fellow","prev")],
    salary_html='Expected salary range after PMP: <strong style="color:#86efac">RM 8,500 \u2013 RM 16,000/month</strong> for senior PM, program manager and PMO lead roles in Malaysia.',
    reviews_eyebrow="Student Reviews",
    reviews_head=("What our PMP","graduates say."),
    reviews_summary=("4.9",92,7,1,184),
    reviews=[
        ("\u2605\u2605\u2605\u2605\u2605","People-domain coaching was the differentiator. I'd taken two PMP boot camps before \u2014 both formula-heavy. Nexperts re-trained how I think about behavioural questions. Passed with 'Above Target' across all three domains.","rav-b","SS","Sukhdev Singh","Senior PM \u00b7 Maybank Group","\u2713 Above Target \u00b7 first attempt"),
        ("\u2605\u2605\u2605\u2605\u2605","Three case sims grounded the theory. The government IT modernisation sim was so realistic \u2014 I led an actual federal program two months later using exactly the patterns from the sim.","rav-m","RJ","Rajamani Jayaraman","Program Manager \u00b7 Talent Corp","\u2713 Above Target \u00b7 first attempt"),
        ("\u2605\u2605\u2605\u2605\u2605","Daily question drills changed how I read PMP questions. By day five, I'd see the trap before I read the options. Game changer.","rav-g","FN","Faradilla Nadia","PMO Lead \u00b7 PETRONAS","\u2713 Above Target \u00b7 first attempt"),
        ("\u2605\u2605\u2605\u2605\u2605","Application portfolio support was unexpectedly valuable. PMI takes the application seriously. Nexperts helped me word my project descriptions correctly first time.","rav-a","HL","Hyong Liang","Construction PM \u00b7 Sunway Construction","\u2713 Above Target \u00b7 first attempt"),
    ],
    price="RM 4,800", price_orig="RM 5,800", price_save="Save 17%",
    price_note="Per person \u00b7 Includes courseware, case sims, app coaching (PMI exam fee separate)",
    sidebar_meta=[
        ("Duration","5 days / 35 contact hrs"),
        ("Next intake","29 September 2026"),
        ("Format","On-site \u00b7 Virtual"),
        ("Level","Professional"),
        ("Language","English"),
        ("Cert body","PMI"),
        ("Exam",'<span class="smeta-badge">Application support</span>'),
    ],
    whats_included=[
        "PMI Authorized ATP courseware",
        "35 contact hours certificate (eligibility)",
        "Three case-study sims",
        "4 full timed mock exams",
        "Daily question-pattern drills",
        "PMI application portfolio coaching",
        "Post-course instructor access (60 days)",
        "Free retake support (conditions apply)",
        "Digital badge from Nexperts ATP",
    ],
    verify_items=[
        "Verifiable on PMI portal",
        "Digital badge via Credly",
        "Recognised globally and across all MY industries",
        "Pathway to PgMP / PMI-ACP / PfMP",
    ],
    guarantee_text="Hit the 80% mock threshold and don't pass first attempt? Free retake support and re-coaching from us.",
))


# 3. CKA - Certified Kubernetes Administrator
BATCH.append(dict(
    slug="cka",
    title="CKA",
    title_html='Certified Kubernetes<br><em>Administrator (CKA)</em>',
    vendor_short="CNCF / Linux Foundation", watermark="CKA", crumb_vendor="Linux Foundation",
    subtitle="The hands-on Kubernetes administrator credential. 100% performance-based exam \u2014 you build, troubleshoot and operate live clusters under time pressure.",
    badges=[("cb-vendor","Linux Foundation"),("cb-level","Professional"),("cb-new","2026 Updated"),("cb-hot","DevOps Hire")],
    hero_meta=common_meta("4 days / 32 hrs","Instructor-Led + Live Clusters","On-site \u00b7 Hybrid",92,"6 October 2026"),
    hero_img=HERO_IMG,
    quick_wins=[
        ("\U0001F6F3\uFE0F","kubectl fluency","Drive Kubernetes clusters from CLI under exam time pressure"),
        ("\U0001F527","Cluster operations","Backup, restore, upgrade etcd; manage node lifecycle and certs"),
        ("\U0001F310","Networking & ingress","Services, NetworkPolicy, CNI, CoreDNS, Gateway API"),
        ("\U0001F510","RBAC & security","ServiceAccounts, RBAC, PodSecurity admission, secrets"),
    ],
    overview_eyebrow="What this course is",
    overview_head=("CKA is","100% hands-on Kubernetes."),
    overview_p1="The Certified Kubernetes Administrator (CKA) is the most-respected hands-on Kubernetes credential. Unlike vendor exams, CKA is 100% performance-based \u2014 a 2-hour live exam where you build, troubleshoot and operate real Kubernetes clusters under time pressure.",
    overview_p2="At Nexperts, CKA is delivered against six live multi-node Kubernetes clusters. You spend 32 hours at the kubectl prompt \u2014 not slides. We break things deliberately and you fix them.",
    overview_quote="CKA is the closest thing to a real-job exam in IT. There is no multiple choice. There is no recall. There is only \u2014 fix this broken cluster, build this thing, in 2 hours.",
    overview_p3="The 2026 update strengthens troubleshooting depth, Gateway API coverage and modern CNI patterns (Cilium, Calico). We teach with current MY platform-team Kubernetes deployments throughout.",
    who_for=[
        ("\U0001F427","Linux administrators","The natural credential for Linux admins moving into platform engineering."),
        ("\u2601\uFE0F","Cloud engineers","AKS, EKS, GKE all use vanilla Kubernetes. CKA gives you the platform-agnostic depth."),
        ("\U0001F517","DevOps engineers","Kubernetes is the runtime DevOps targets. CKA proves you can run it reliably."),
        ("\U0001F50D","SRE / platform engineers","Modern SRE practice is platform-engineering on Kubernetes."),
        ("\U0001F4DA","Pre-CKAD / CKS candidates","CKA is the foundational hands-on credential for the Kubernetes track."),
        ("\U0001F4BC","Banking / GLC platform leads","BNM RMiT-aligned Kubernetes platforms increasingly require CKA-grade ops."),
    ],
    prereqs=[
        "Strong Linux command-line fluency (essential)",
        "Basic Docker / containers experience",
        "Familiarity with YAML",
        "Vim / nano comfort \u2014 you'll edit YAML in the exam",
    ],
    prereqs_note="No Linux fluency yet? Ask us about our pre-CKA Linux + Docker primer.",
    curriculum_eyebrow="Course Curriculum",
    curriculum_head=("Five domains.","Pure Kubernetes operations."),
    curriculum_intro="CKA covers Cluster Architecture / Installation / Configuration (25%), Workloads & Scheduling (15%), Services & Networking (20%), Storage (10%), and Troubleshooting (30%). We sequence by exam weight and operational reality.",
    modules=[
        ("01","Cluster Architecture & Installation",[
            "Control plane components \u2014 API server, scheduler, controller-manager, etcd",
            "kubeadm cluster build",
            "Cluster upgrades \u2014 minor version drift",
            "etcd backup, restore and migrate",
            "TLS bootstrapping and certificate rotation",
            "Lab: Build a 3-node cluster from scratch with kubeadm",
        ]),
        ("02","Workloads & Scheduling",[
            "Deployments, ReplicaSets, StatefulSets, DaemonSets",
            "Pod design \u2014 init, sidecar, ambient containers",
            "Resource requests, limits, QoS classes",
            "Affinity, anti-affinity, taints, tolerations",
            "Horizontal Pod Autoscaler",
            "Lab: Deploy a stateful app with HPA + PDB",
        ]),
        ("03","Services, Ingress & NetworkPolicy",[
            "Service types \u2014 ClusterIP, NodePort, LoadBalancer, ExternalName",
            "Ingress controllers \u2014 nginx, Traefik, Gateway API",
            "NetworkPolicy fundamentals",
            "CoreDNS, ExternalDNS",
            "CNI choices \u2014 Calico, Cilium, Flannel",
            "Lab: Lock down a 3-namespace app with NetworkPolicy",
        ]),
        ("04","Storage & Persistence",[
            "PersistentVolumes, PersistentVolumeClaims, StorageClasses",
            "Dynamic provisioning, CSI drivers",
            "Volume snapshots and cloning",
            "ConfigMaps and Secrets at scale",
            "etcd-backed vs cloud-backed PV",
            "Lab: Migrate a stateful app to a new StorageClass",
        ]),
        ("05","Troubleshooting (the big one)",[
            "Cluster troubleshooting \u2014 control plane, kubelet, etcd",
            "Pod troubleshooting \u2014 ImagePullBackOff, CrashLoopBackOff, OOM",
            "Service & DNS troubleshooting",
            "Node troubleshooting \u2014 NotReady, disk pressure",
            "Logging and journalctl drill-down",
            "Lab: 5 broken-cluster scenarios in 90 minutes",
        ]),
    ],
    labs_eyebrow="Hands-On Live Clusters",
    labs_head=("32 hands-on hours.","Six live clusters."),
    labs_intro="Six pre-built multi-node Kubernetes clusters with deliberate flaws \u2014 etcd corruption, certificate drift, CNI breakage, RBAC misconfiguration, kubelet failures. You fix them under time pressure.",
    labs=[
        ("01","kubeadm Cluster Build","Build a 3-node cluster from scratch. Add a worker node.","lt-recon","Build"),
        ("02","etcd Backup + Restore","Backup, simulate corruption, restore etcd from snapshot.","lt-defend","Recovery"),
        ("03","Cluster Upgrade","Upgrade a 3-node cluster minor version. Drain nodes safely.","lt-recon","Upgrade"),
        ("04","StatefulSet Migration","Migrate a Postgres StatefulSet to a new StorageClass.","lt-attack","Storage"),
        ("05","NetworkPolicy Lockdown","Lock down a 3-namespace app with NetworkPolicy.","lt-defend","NetPol"),
        ("06","Ingress + Cert-Manager","Stand up nginx-ingress with cert-manager for TLS.","lt-recon","Ingress"),
        ("07","RBAC ServiceAccount","Build per-namespace ServiceAccounts with scoped RBAC.","lt-defend","RBAC"),
        ("08","Broken Cluster #1","CrashLoopBackOff in kube-apiserver. Diagnose and fix in 30 minutes.","lt-forensic","Troubleshoot"),
        ("09","Broken Cluster #2","DNS resolution broken across namespace. Trace and fix.","lt-forensic","Troubleshoot"),
    ],
    labs_footer="+ 23 additional cluster ops scenarios. Cluster access for 60 days post-course.",
    exam_eyebrow="Exam Information",
    exam_head=("100% hands-on.","No multiple choice."),
    exam_intro="CKA is a 2-hour, 100% performance-based exam. You connect to live clusters and complete 15\u201320 tasks. There is no multiple choice. The exam is taken open-book against the official Kubernetes documentation only.",
    exam_main=dict(name="CKA Exam (2026 curriculum)",rows=[
        ("Questions","15\u201320 hands-on tasks"),
        ("Duration","120 minutes"),
        ("Passing score",'<span class="pass-highlight">66 / 100</span>'),
        ("Format","Online proctor (PSI Bridge)"),
        ("Validity","2 years"),
        ("Industry avg pass rate",'<span class="fail-note">~70% first attempt (with hands-on)</span>'),
        ("Nexperts pass rate",'<span class="pass-highlight">92% first attempt</span>'),
    ]),
    exam_optional=dict(name="Kubernetes Career Path",rows=[
        ("Stacks with","CKA \u2192 CKS / CKAD"),
        ("MY salary uplift","Average +RM 1,800/mo post-cert"),
        ("Voucher","Bundled \u2014 Linux Foundation voucher included"),
        ("Renewal","2-year cycle via re-exam"),
        ("Open-book","Yes \u2014 official Kubernetes docs only"),
        ("Career fit","SRE, platform engineer, DevOps engineer"),
        ("Pre-bridge","Foundational for CKS and CKAD"),
    ]),
    mock_title="Our CKA 3-Mock Programme",
    mock_programme=[
        ("01","Diagnostic Mock","Day 2. Maps weak ops areas. Average score: 56 / 100."),
        ("02","Speed Mock","Day 3. Time-pressured task drills. Average score: 71 / 100."),
        ("03","Final Clearance","Day 4. Full timed simulation. 78 / 100 before booking. Average score: 84 / 100."),
    ],
    pass_rate=92,
    pass_head_html='92% of our CKA candidates<br>pass <em>on first attempt.</em>',
    pass_intro="The global CKA first-attempt rate is around 70%. Our 92% comes from six live broken-cluster scenarios, dedicated kubectl-speed coaching, and an instructor who maintains five MY production Kubernetes platforms.",
    pass_pills=["Six live clusters","Speed coaching","92% first attempt","Broken-cluster drills","60-day cluster access"],
    pass_compare=[
        ("Industry average: ~70%","Most candidates know Kubernetes concepts but struggle with kubectl speed and YAML editing under exam pressure. They run out of time."),
        ("Nexperts: 92%","We drill kubectl speed daily. We make you edit YAML in vim under time pressure. By exam day, the muscle memory is reflex."),
    ],
    next_eyebrow="Your Certification Journey",
    next_head=("CKA leads to","CKS / CKAD."),
    next_steps_intro="From CKA you specialise into Kubernetes security (CKS) or application development (CKAD). CKS is the most-paid Kubernetes credential globally.",
    next_steps=[
        ("Before this","Linux + Docker fluency","Strong Linux command-line and Docker container fluency are essential. Without them, CKA is overwhelming.","View Linux Admin \u2192"),
        ("You are here","CKA","Kubernetes administrator. Cluster install, upgrade, troubleshoot, RBAC, networking, storage.","Currently viewing \u2192"),
        ("Recommended next","CKS or CKAD","CKS specialises into Kubernetes security. CKAD pivots into application development on Kubernetes.","View CKS \u2192"),
    ],
    path_name="Kubernetes platform engineer",
    path_chips=[("Linux + Docker","prev"),("CKA","you"),("CKS / CKAD","next"),("Kubestronaut","prev"),("Platform Architect","prev")],
    salary_html='Expected salary range after CKA: <strong style="color:#86efac">RM 8,000 \u2013 RM 14,500/month</strong> for SRE, platform engineer and DevOps roles in Malaysian enterprises.',
    reviews_eyebrow="Student Reviews",
    reviews_head=("What our CKA","graduates say."),
    reviews_summary=("4.9",90,8,2,144),
    reviews=[
        ("\u2605\u2605\u2605\u2605\u2605","Six broken clusters were the differentiator. Other CKA prep is theoretical. Nexperts gave me real broken etcd, real DNS chaos, real RBAC dysfunction. Exam felt like a seventh broken cluster.","rav-b","KP","Krishnan Pillai","Senior SRE \u00b7 BigPay","\u2713 Passed first attempt \u00b7 87 / 66"),
        ("\u2605\u2605\u2605\u2605\u2605","Speed coaching and YAML-in-vim drills were unique. Three months later, I administer four production clusters and the muscle memory still pays off daily.","rav-m","WK","Wei Kit Lim","Platform Engineer \u00b7 AirAsia","\u2713 Passed first attempt \u00b7 81 / 66"),
        ("\u2605\u2605\u2605\u2605\u2605","Cluster upgrade module was eye-opening. We're due to upgrade three production clusters next quarter and the playbook from class is becoming our team SOP.","rav-g","RA","Rashidah Anuar","Lead Engineer \u00b7 PETRONAS Digital","\u2713 Passed first attempt \u00b7 79 / 66"),
        ("\u2605\u2605\u2605\u2605\u2605","Real broken-cluster forensics changed how I think about incident response. Six weeks later I diagnosed a production CrashLoopBackOff in 6 minutes. Saved RM 28k of downtime.","rav-a","FH","Foon Hin Wong","DevOps Engineer \u00b7 OCBC","\u2713 Passed first attempt \u00b7 91 / 66"),
    ],
    price="RM 3,800", price_orig="RM 4,500", price_save="Save 16%",
    price_note="Per person \u00b7 Includes Linux Foundation voucher, six clusters, courseware",
    sidebar_meta=[
        ("Duration","4 days / 32 hrs"),
        ("Next intake","6 October 2026"),
        ("Format","On-site \u00b7 Hybrid"),
        ("Level","Professional"),
        ("Language","English"),
        ("Cert body","CNCF / Linux Foundation"),
        ("Exam",'<span class="smeta-badge">Included</span>'),
    ],
    whats_included=[
        "Linux Foundation official CKA courseware",
        "Linux Foundation exam voucher",
        "Six live multi-node Kubernetes clusters",
        "60-day cluster access post-course",
        "3 full timed mock exams",
        "Speed coaching + vim/YAML drills",
        "Post-course instructor access (45 days)",
        "Free retake voucher (conditions apply)",
        "Digital badge via Credly",
    ],
    verify_items=[
        "Verifiable on Linux Foundation portal",
        "Digital badge via Credly",
        "Recognised globally across DevOps and SRE roles",
        "Pathway to CKS and CKAD",
    ],
    guarantee_text="Hit the 78 / 100 mock threshold and don't pass first attempt? Linux Foundation retake voucher on us.",
))
