# -*- coding: utf-8 -*-
"""Artificial Intelligence and AI & Machine Learning courses for Malaysia (2026)."""
from _course_batch_ai_ds_short import _course

BATCH = []


def _finish(course, **extra):
    course.update(extra)
    return course


BATCH.append(
    _finish(
        _course(
            slug="artificial-intelligence-ai-course-malaysia",
            title="Artificial Intelligence (AI) Course Malaysia",
            title_html="Artificial Intelligence (AI)<br><em>Course Malaysia</em>",
            watermark="AI Course",
            subtitle="Learn AI from fundamentals to real-world applications — Python, Machine Learning, Generative AI, LLMs, RAG, automation and an introduction to AI agents.",
            level="Beginner to Intermediate",
            badge_extra="AI 2026",
            duration="40 hours",
            intake="3 Nov 2026",
            price="RM 4,500",
            price_orig="RM 5,600",
            price_save="Save 20%",
            overview_head=("Learn AI from", "fundamentals to applications."),
            overview_p1="Artificial Intelligence is changing how businesses analyse data, create content, automate work, develop applications and make decisions. This practical, instructor-led programme takes you from AI fundamentals and Python into Machine Learning, Deep Learning concepts, Generative AI, Large Language Models, RAG, automation and an introduction to AI agents.",
            overview_p2="No prior AI or Machine Learning experience is required. You learn through instructor demonstrations, guided labs and practical projects.",
            modules=[
                ("01", "Introduction to Artificial Intelligence", [
                    "What is Artificial Intelligence?",
                    "Evolution of AI",
                    "AI vs automation",
                    "AI vs Machine Learning",
                    "Machine Learning vs Deep Learning",
                    "Generative AI",
                    "Large Language Models",
                    "Introduction to AI agents",
                    "Where AI is being used today",
                    "Lab: match business problems to the right AI approach",
                ]),
                ("02", "Python Fundamentals for AI", [
                    "Introduction to Python",
                    "Variables and data types",
                    "Lists and dictionaries",
                    "Conditions, loops and functions",
                    "Working with files",
                    "Python libraries and Jupyter Notebook",
                    "Introduction to NumPy and Pandas",
                    "Lab: load, explore and manipulate a real dataset",
                ]),
                ("03", "Data for Artificial Intelligence", [
                    "Structured and unstructured data",
                    "Data collection and data quality",
                    "Missing values and duplicates",
                    "Data cleaning and feature selection",
                    "Exploratory data analysis",
                    "Basic data visualisation",
                    "Preparing data for Machine Learning",
                    "Lab: clean and analyse a dataset with Python and Pandas",
                ]),
                ("04", "Machine Learning Fundamentals", [
                    "What is Machine Learning?",
                    "Features and labels",
                    "Training and testing data",
                    "Supervised and unsupervised learning",
                    "Model training and predictions",
                    "Overfitting and underfitting",
                    "Introduction to scikit-learn",
                    "Lab: train your first Machine Learning model",
                ]),
                ("05", "Regression and Predictive AI", [
                    "Introduction to regression",
                    "Linear regression and multiple features",
                    "Training a regression model",
                    "Making predictions",
                    "MAE, MSE and RMSE",
                    "Project: predict a real-world numerical outcome",
                ]),
                ("06", "Classification", [
                    "Classification problems",
                    "Logistic regression",
                    "Decision trees and random forests",
                    "K-Nearest Neighbours",
                    "Confusion matrix, accuracy, precision, recall and F1",
                    "Project: churn, lead, spam or response classification",
                ]),
                ("07", "Unsupervised Learning and Clustering", [
                    "What is unsupervised learning?",
                    "Clustering and K-Means",
                    "Similarity and pattern discovery",
                    "Customer segmentation",
                    "Introduction to dimensionality reduction",
                    "Project: segment customers from behavioural data",
                ]),
                ("08", "Neural Networks and Deep Learning", [
                    "What is a neural network?",
                    "Layers, activation functions and loss",
                    "Training, epochs and deep networks",
                    "Introduction to PyTorch / TensorFlow",
                    "Applications of Deep Learning",
                    "Lab: build a simple neural-network model",
                ]),
                ("09", "Natural Language Processing", [
                    "Introduction to NLP",
                    "Text preprocessing and tokenisation",
                    "Text classification and sentiment analysis",
                    "Embeddings and semantic similarity",
                    "Traditional NLP vs modern LLMs",
                    "Project: text or sentiment analysis application",
                ]),
                ("10", "Generative AI and Large Language Models", [
                    "What is Generative AI?",
                    "How Large Language Models work",
                    "Tokens, context windows and prompting",
                    "Temperature, structured outputs and hallucinations",
                    "Embeddings and enterprise LLM applications",
                    "Lab: extraction, classification, summary or Q&A",
                ]),
                ("11", "Building AI Applications", [
                    "AI application architecture",
                    "APIs and connecting applications to models",
                    "User inputs and structured AI responses",
                    "Backend and frontend concepts",
                    "Integrating external AI services",
                    "Project: a simple working AI-powered application",
                ]),
                ("12", "Retrieval-Augmented Generation (RAG)", [
                    "Limitations of LLM knowledge",
                    "Documents, chunking and embeddings",
                    "Vector search and semantic retrieval",
                    "Grounding LLM responses",
                    "Knowledge-base applications",
                    "Project: an AI knowledge assistant over supplied documents",
                ]),
                ("13", "AI Automation and AI Agents", [
                    "Traditional vs AI-powered automation",
                    "Intelligent workflows, APIs and tool calling",
                    "Multi-step workflows, memory and state",
                    "Human-in-the-loop approval",
                    "Agent loops and agentic AI fundamentals",
                    "Lab: request, retrieve, decide and act workflow",
                ]),
                ("14", "Responsible AI, Security and Ethics", [
                    "Confidential information and data protection",
                    "Bias, fairness, hallucinations and explainability",
                    "Intellectual property and AI security risks",
                    "Shadow AI, permissions and access control",
                    "Human oversight",
                    "Activity: review an AI app for privacy and accuracy",
                ]),
                ("15", "Final AI Capstone Project", [
                    "Problem identification",
                    "Data, AI approach and development",
                    "Testing, evaluation and presentation",
                    "Example: knowledge assistant, churn, documents or sales",
                    "Present and demonstrate the final project",
                ]),
            ],
            labs=[
                ("01", "Python data", "Load, clean and analyse a real dataset.", "lt-recon", "Data"),
                ("02", "ML models", "Regression, classification and clustering.", "lt-defend", "ML"),
                ("03", "Gen AI", "LLM app, RAG assistant and a simple agent workflow.", "lt-attack", "AI"),
                ("04", "Capstone", "End-to-end AI solution you can present.", "lt-recon", "Project"),
            ],
            quick_wins=[
                ("🧠", "AI foundations", "ML, Deep Learning, Gen AI and agents"),
                ("🐍", "Python practice", "Data, models and a working AI app"),
                ("📚", "RAG and LLMs", "Ground answers in your documents"),
                ("🛡️", "Responsible AI", "Privacy, security and human oversight"),
            ],
            who_for=[
                ("🌱", "Beginners", "Start Artificial Intelligence with no prior ML experience."),
                ("💼", "Professionals", "Upskill for AI work in your current role."),
                ("💻", "Developers", "Add Machine Learning, LLMs and AI apps to your stack."),
                ("📊", "Analysts", "Move from reports into models and intelligent apps."),
                ("🎓", "Graduates", "A structured path into practical AI."),
                ("🚀", "Founders", "Understand AI products, RAG and automation."),
            ],
            prereqs=[
                "Basic computer literacy",
                "No previous AI or Machine Learning experience required",
                "Programming is helpful but not mandatory — essential Python is taught in class",
            ],
            path_chips=[("AI Course", "you"), ("AI + ML", "next"), ("Agentic AI", "next")],
            path_name="artificial intelligence",
            salary_html='Practical AI skills support analyst, developer and junior AI roles in Malaysia, often in the <strong style="color:#86efac">RM 4,500 – RM 9,000/month</strong> range as the portfolio grows.',
            next_steps=[
                ("Before this", "Computer literacy", "No prior AI experience required.", "Start here →"),
                ("You are here", "AI Course Malaysia", "Fundamentals through modern AI applications.", "Currently viewing →"),
                ("Recommended next", "Agentic AI Engineering", "Tools, RAG, workflows and multi-step agents.", "Continue →"),
            ],
        ),
        seo_title="Artificial Intelligence (AI) Course Malaysia | AI Training | Nexperts Academy",
        seo_description="Learn Artificial Intelligence in Malaysia with instructor-led, hands-on training. Cover Python, Machine Learning, Deep Learning, Generative AI, LLMs, RAG and AI applications.",
        seo_keywords="AI Course Malaysia, Artificial Intelligence Course Malaysia, AI Training Malaysia, Artificial Intelligence Training, AI Classes Malaysia, AI Course for Beginners, AI Training Course, Machine Learning, Python for AI, Deep Learning, Generative AI, Large Language Models, RAG, AI Agents",
        overview_p3="This is broader than ChatGPT and prompting. Modern AI work needs data, Machine Learning, Generative AI, Large Language Models and intelligent applications working together. HRD Corp claim support is available for eligible employers.",
        curriculum_head=("Fifteen modules.", "From foundations to a capstone."),
        curriculum_intro="The syllabus moves from AI fundamentals and Python through Machine Learning, Deep Learning, NLP, Generative AI, RAG, automation, agents and a final project.",
        labs_intro="You leave with a portfolio: data work, models, an LLM application, a RAG assistant and a capstone demonstration.",
        exam_intro="Complete the guided labs and the final capstone to earn the Nexperts Academy Professional Certificate in Artificial Intelligence.",
        whats_included=[
            "40 hours of instructor-led training",
            "Hands-on labs and project files",
            "Python, ML, LLM and RAG exercises",
            "Nexperts Academy Professional Certificate in Artificial Intelligence",
        ],
        guarantee_text="Attend the labs and complete the capstone checklist — instructors help you finish and present the project.",
        sidebar_meta=[
            ("Duration", "40 hours"),
            ("Next intake", "3 Nov 2026"),
            ("Format", "Classroom · Virtual · Hybrid"),
            ("Level", "Beginner to Intermediate"),
            ("Language", "English"),
            ("Cert body", "Nexperts Academy"),
            ("Exam", '<span class="smeta-badge">Capstone</span>'),
        ],
        faqs=[
            ("Is this AI course suitable for beginners?", "Yes. The programme begins with Artificial Intelligence fundamentals and introduces the Python concepts required for later modules. Previous AI or Machine Learning experience is not required."),
            ("Do I need programming experience?", "Previous programming knowledge is helpful but not mandatory. Essential Python concepts used during the programme are introduced as part of the training."),
            ("Does this course cover Machine Learning?", "Yes. You work with supervised and unsupervised Machine Learning, regression, classification, clustering, model evaluation and practical projects."),
            ("Does the course cover Deep Learning?", "Yes. The programme introduces neural networks and Deep Learning fundamentals, with practical exposure to a modern Deep Learning framework."),
            ("Does this course include Generative AI?", "Yes. You cover Generative AI, Large Language Models, prompting, embeddings and practical LLM applications."),
            ("Will I learn ChatGPT and other LLM technologies?", "The programme teaches the concepts and techniques used with modern Large Language Models, rather than focusing on a single product. Specific platforms may be used in the labs."),
            ("Does the course cover AI agents?", "Yes. You are introduced to AI automation, tool calling, intelligent workflows and AI agents. Further specialisation is available in Agentic AI Engineering."),
            ("Is this the same as the Agentic AI Engineering course?", "No. This course is broader: AI, Python, Machine Learning, Deep Learning, Generative AI and modern applications. Agentic AI Engineering is the advanced path for RAG systems, workflows and agents that run multi-step tasks."),
            ("Will I receive a certificate?", "Yes. Participants who complete the programme requirements receive a Nexperts Academy Professional Certificate in Artificial Intelligence."),
            ("Is the training available for companies?", "Yes. Instructor-led corporate AI training can be delivered for teams and organisations."),
        ],
        overview_sections=[
            {
                "eyebrow": "Artificial Intelligence Training in Malaysia",
                "intro": "A structured journey from AI fundamentals to applications you can demonstrate.",
                "bullets": [
                    "Artificial Intelligence fundamentals and Python for AI",
                    "Data preparation, Machine Learning, regression and classification",
                    "Unsupervised learning and Deep Learning fundamentals",
                    "Natural Language Processing, Generative AI and Large Language Models",
                    "AI applications, RAG, automation and an introduction to AI agents",
                    "Responsible AI, privacy and security",
                ],
            },
            {
                "eyebrow": "Hands-On AI Projects",
                "intro": "This is not a theory-only AI course. You build a portfolio during the programme.",
                "bullets": [
                    "Python data analysis and Machine Learning model development",
                    "Regression, classification and customer segmentation",
                    "Neural-network fundamentals and NLP",
                    "Generative AI, LLM applications and RAG",
                    "AI automation, an introduction to AI agents, and a final capstone",
                ],
            },
            {
                "eyebrow": "Technologies and tools",
                "paragraphs": ["You gain exposure to tools commonly used in modern AI development. Platforms may be updated as the technology changes."],
                "bullets": [
                    "Python, Jupyter Notebook, NumPy, Pandas and Matplotlib",
                    "scikit-learn and PyTorch or TensorFlow",
                    "Large Language Models, LLM APIs, embeddings and vector databases",
                    "RAG and Git / GitHub",
                ],
            },
            {
                "eyebrow": "AI Course Certification",
                "paragraphs": [
                    "On successful completion you receive the Nexperts Academy Professional Certificate in Artificial Intelligence.",
                    "The certificate recognises instructor-led training and practical coursework in Artificial Intelligence.",
                ],
            },
            {
                "eyebrow": "AI Learning Path",
                "intro": "After this programme you can continue into the area that matches your goal.",
                "skill_groups": [
                    ("AI and Machine Learning", ["Predictive models, Machine Learning, Deep Learning and further model development."]),
                    ("AI-powered software development", ["Using modern AI development tools to build software and applications."]),
                    ("Agentic AI Engineering", ["Applications that use tools, knowledge, context and multi-step workflows."]),
                ],
                "footer": 'Traditional AI can analyse, predict and generate. Agentic systems can also retrieve information, use tools and run multi-step workflows. Continue with <a href="/courses/agentic-ai">Agentic AI Engineering</a>.',
            },
        ],
    )
)

BATCH.append(
    _finish(
        _course(
            slug="ai-machine-learning-course-malaysia",
            title="Artificial Intelligence &amp; Machine Learning Course Malaysia",
            title_html="Artificial Intelligence &amp;<br><em>Machine Learning Course Malaysia</em>",
            watermark="AI & ML",
            subtitle="Build practical Machine Learning models with Python — data preparation, regression, classification, clustering, evaluation and neural networks in 40 hours.",
            level="Beginner to Intermediate",
            badge_extra="AI 2026",
            duration="5 days / 40 hrs",
            intake="17 Nov 2026",
            price="RM 5,500",
            price_orig="RM 6,800",
            price_save="Save 19%",
            overview_head=("Build practical", "Machine Learning models."),
            overview_p1="Learn how machines learn from data and build practical Machine Learning solutions using Python. The programme covers fundamentals, data preparation, supervised learning, regression, classification, unsupervised learning, clustering, model evaluation and neural networks.",
            overview_p2="The workflow is: understand the problem, prepare the data, select a model, train, evaluate, improve and predict. You work with real datasets throughout the five days.",
            modules=[
                ("01", "AI and Machine Learning Fundamentals", [
                    "What is Artificial Intelligence and Machine Learning?",
                    "AI vs Machine Learning vs Deep Learning",
                    "Generative AI vs predictive AI",
                    "Features, labels, training and prediction",
                    "Supervised and unsupervised learning",
                    "Real-world Machine Learning applications",
                ]),
                ("02", "Python for Machine Learning", [
                    "Python for AI and ML",
                    "Jupyter Notebook",
                    "Variables, lists, dictionaries, conditions and loops",
                    "Functions",
                    "NumPy, Pandas and DataFrames",
                    "Importing datasets",
                ]),
                ("03", "Preparing Data for Machine Learning", [
                    "Datasets, features and target variables",
                    "Missing values, duplicates and categorical variables",
                    "Encoding, scaling, normalisation and standardisation",
                    "Exploratory data analysis and visualisation",
                    "Train/test split",
                    "Lab: import, clean and prepare a real dataset",
                ]),
                ("04", "Supervised Learning and Linear Regression", [
                    "Supervised learning workflow",
                    "Simple and multiple linear regression",
                    "Coefficients and predictions",
                    "MAE, MSE, RMSE and R²",
                    "Project: property, sales, spending or demand prediction",
                ]),
                ("05", "Classification Algorithms", [
                    "Binary and multi-class classification",
                    "Logistic regression",
                    "K-Nearest Neighbours, decision trees and random forests",
                    "Introduction to Support Vector Machines",
                    "Regression vs classification",
                ]),
                ("06", "Evaluating and Improving Models", [
                    "Confusion matrix, precision, recall and F1",
                    "Classification thresholds",
                    "Underfitting, overfitting, bias and variance",
                    "Cross-validation, feature selection and hyperparameters",
                    "Project: compare models for churn, leads, spam or response",
                ]),
                ("07", "Unsupervised Learning and K-Means", [
                    "Unlabelled data and pattern discovery",
                    "Distance, similarity and clustering",
                    "K-Means, centroids, inertia and the elbow method",
                    "Project: customer segmentation",
                    "Hierarchical clustering, anomaly detection and PCA concepts",
                ]),
                ("08", "Neural Networks and Deep Learning", [
                    "Neurons, layers, weights and activation functions",
                    "Forward propagation, loss, epochs and backpropagation",
                    "TensorFlow / Keras or PyTorch workflow",
                    "Lab: a simple neural-network classifier",
                    "Predictive AI vs Generative AI and when to use each",
                ]),
                ("09", "End-to-End Machine Learning Capstone", [
                    "Define the problem and understand the data",
                    "Prepare features and choose an approach",
                    "Train, evaluate and improve the model",
                    "Present the results and a business application",
                    "Examples: churn, sales, segmentation, attrition or anomaly detection",
                ]),
            ],
            labs=[
                ("01", "Prepare data", "Clean and explore a real dataset with Python.", "lt-recon", "EDA"),
                ("02", "Regression", "Predict a numerical outcome and score it.", "lt-defend", "Predict"),
                ("03", "Classification", "Compare algorithms and pick a winner.", "lt-attack", "Classify"),
                ("04", "Clustering", "Segment customers with K-Means.", "lt-recon", "Cluster"),
                ("05", "Neural net", "Train a basic neural-network model.", "lt-defend", "DL"),
                ("06", "Capstone", "Raw data to a trained, evaluated model.", "lt-attack", "Project"),
            ],
            quick_wins=[
                ("📊", "Real models", "Regression, classification and clustering"),
                ("🐍", "Python ML", "NumPy, Pandas and scikit-learn"),
                ("🎯", "Evaluation", "Choose metrics that match the problem"),
                ("🧠", "Neural nets", "A first Deep Learning model"),
            ],
            who_for=[
                ("💻", "Developers", "First practical Machine Learning models."),
                ("🖥️", "IT and engineers", "Apply ML to technical and business data."),
                ("📊", "Analysts", "Move from dashboards to predictions."),
                ("🎓", "Graduates", "A 40-hour hands-on ML foundation."),
                ("🔄", "Career switchers", "Portfolio projects across the ML workflow."),
                ("🚀", "Founders", "See where predictive models fit a product."),
            ],
            prereqs=[
                "Basic computer literacy",
                "Programming is helpful but not mandatory — required Python is taught in class",
                "Basic maths and statistics help; advanced mathematics is not required",
            ],
            path_chips=[("AI + ML", "you"), ("Deep Learning", "next"), ("Agentic AI", "next")],
            path_name="machine learning",
            salary_html='Hands-on Machine Learning supports junior data and ML roles in Malaysia, commonly <strong style="color:#86efac">RM 4,500 – RM 9,000/month</strong> with a project portfolio.',
            next_steps=[
                ("Before this", "Computer literacy", "Python basics are taught in class.", "Start here →"),
                ("You are here", "AI and Machine Learning", "Models, metrics and a capstone.", "Currently viewing →"),
                ("Recommended next", "Deep Learning or Agentic AI", "Neural nets, or LLM apps and agents.", "Continue →"),
            ],
        ),
        seo_title="Artificial Intelligence &amp; Machine Learning Course Malaysia | Nexperts Academy",
        seo_description="Learn Artificial Intelligence and Machine Learning in Malaysia with 40 hours of instructor-led hands-on training. Build practical Python ML models using regression, classification, clustering and neural networks.",
        seo_keywords="AI Machine Learning Course Malaysia, Artificial Intelligence and Machine Learning Course, AI and Machine Learning Training, AI ML Course Malaysia, Machine Learning Course Malaysia, Machine Learning with Python, Artificial Intelligence Machine Learning Training",
        overview_p3="This programme goes deeper on Machine Learning than a general AI survey: data, algorithms, training, prediction, classification, clustering and evaluation. Generative AI is introduced for context. HRD Corp claim support is available for eligible employers.",
        curriculum_head=("Five days.", "A complete ML workflow."),
        curriculum_intro="Day 1 builds AI, Python and data foundations. Days 2 to 4 cover regression, classification, model improvement and clustering. Day 5 introduces neural networks and the capstone.",
        labs_intro="Five guided projects plus a final capstone, from raw data to a trained and evaluated model.",
        exam_intro="Complete the labs and the end-to-end capstone to earn the Nexperts Academy Professional Certificate in Artificial Intelligence and Machine Learning.",
        whats_included=[
            "5 days / 40 hours of instructor-led training",
            "Hands-on datasets, labs and project files",
            "Python, scikit-learn and a Deep Learning framework",
            "Nexperts Academy Professional Certificate in Artificial Intelligence and Machine Learning",
        ],
        guarantee_text="Work through the lab checklist and the capstone — instructors help you train, evaluate and present the model.",
        sidebar_meta=[
            ("Duration", "5 days / 40 hrs"),
            ("Next intake", "17 Nov 2026"),
            ("Format", "Classroom · Virtual · Hybrid"),
            ("Level", "Beginner to Intermediate"),
            ("Language", "English"),
            ("Cert body", "Nexperts Academy"),
            ("Exam", '<span class="smeta-badge">Capstone</span>'),
        ],
        faqs=[
            ("Is this course suitable for beginners?", "Yes. It starts with AI and Machine Learning fundamentals, then moves into practical model development."),
            ("Do I need Python experience?", "Previous Python experience is helpful but not mandatory. The programme introduces the Python concepts and libraries required for the exercises."),
            ("Is this a practical Machine Learning course?", "Yes. You work with Python, datasets and Machine Learning libraries throughout, and complete multiple exercises and projects."),
            ("What is the difference between this course and the Artificial Intelligence Course?", "The Artificial Intelligence course gives broader exposure, including Generative AI, LLMs, RAG and modern AI applications. This programme goes deeper on Machine Learning: data, algorithms, training, prediction, classification, clustering and evaluation."),
            ("What is the difference between this and Agentic AI Engineering?", "Machine Learning teaches systems to find patterns and make predictions from data. Agentic AI Engineering develops applications and agents that work with LLMs, knowledge sources, APIs, tools and multi-step workflows."),
            ("Does this programme cover Generative AI?", "Generative AI and Large Language Models are introduced so you can place traditional Machine Learning in the modern AI landscape. The primary focus is Machine Learning."),
            ("Will I build actual Machine Learning models?", "Yes. You build regression, classification and clustering models, and a first neural network."),
        ],
        overview_sections=[
            {
                "eyebrow": "Learning outcomes",
                "intro": "After 40 hours you should be able to take a dataset through a complete Machine Learning project.",
                "bullets": [
                    "Explain AI and Machine Learning concepts",
                    "Prepare data and run exploratory analysis",
                    "Build regression, classification and clustering models",
                    "Choose metrics and address overfitting",
                    "Understand neural networks and build a basic model in Python",
                ],
            },
            {
                "eyebrow": "Hands-on projects",
                "bullets": [
                    "Data preparation and exploratory data analysis",
                    "Regression and numerical prediction",
                    "Classification and model comparison",
                    "Customer segmentation with clustering",
                    "A basic neural network",
                    "End-to-end Machine Learning capstone",
                ],
            },
            {
                "eyebrow": "Technologies and tools",
                "bullets": [
                    "Python and Jupyter Notebook",
                    "NumPy, Pandas and Matplotlib",
                    "scikit-learn",
                    "TensorFlow / Keras or PyTorch",
                    "Git / GitHub",
                ],
                "footer": "Tools may be updated to match current industry practice.",
            },
            {
                "eyebrow": "Certification",
                "paragraphs": [
                    "Participants who complete the programme requirements receive the Nexperts Academy Professional Certificate in Artificial Intelligence and Machine Learning.",
                ],
            },
            {
                "eyebrow": "Continue your AI learning journey",
                "skill_groups": [
                    ("Advanced Machine Learning and Deep Learning", ["Neural networks, computer vision, NLP and further model work."]),
                    ("AI Engineering and Agentic AI", ["LLM applications, RAG, tools, APIs, workflows and agents."]),
                    ("AI-powered software development", ["Using modern AI tools to build software faster."]),
                ],
                "footer": 'Continue into <a href="/courses/artificial-intelligence-ai-course-malaysia">the Artificial Intelligence course</a> for Generative AI and RAG, or <a href="/courses/agentic-ai">Agentic AI Engineering</a> for multi-step agents.',
            },
        ],
    )
)

BATCH.append(
    _finish(
        _course(
            slug="generative-ai-workplace-productivity",
            title="Generative AI for Workplace Productivity &amp; Business Automation",
            title_html="Generative AI for Workplace Productivity<br><em>&amp; Business Automation</em>",
            watermark="Work AI",
            subtitle="A two-day, hands-on programme for working professionals — prompt with intent, speed up everyday work, design AI-assisted workflows and use AI responsibly.",
            level="All levels",
            badge_extra="Workplace",
            duration="2 days",
            intake="24 Nov 2026",
            price="RM 2,500",
            price_orig="RM 3,200",
            price_save="Save 22%",
            overview_head=("What could your team", "do differently on Monday?"),
            overview_p1="This programme follows a simple journey: Understand, Prompt, Apply, Analyse, Automate, Govern. About 30% of the time is concept and 70% is practical work.",
            overview_p2="You practise with department scenarios, reusable prompts and a workflow you can take back to work. The emphasis is productivity and transformation, not a list of theory modules.",
            modules=[
                ("01", "Understand AI", [
                    "Generative AI and large language models in plain business language",
                    "What these tools can and cannot do",
                    "Hallucinations and where human judgement stays in charge",
                ]),
                ("02", "Prompt Professionally", [
                    "Context, objective and audience",
                    "Examples, constraints and output formats",
                    "Iteration and reusable prompt structures",
                ]),
                ("03", "Work Faster", [
                    "Emails, reports, proposals and presentations",
                    "Meetings, summaries and research",
                    "SOPs and business documentation",
                ]),
                ("04", "Apply AI by Department", [
                    "HR, Finance, Sales and Marketing",
                    "Operations, Administration and Customer Service",
                    "Management use cases",
                ]),
                ("05", "Work With Data", [
                    "Interpret tables",
                    "Support spreadsheet work and develop formulas",
                    "Identify patterns and turn information into business insight",
                ]),
                ("06", "Design AI-Assisted Workflows", [
                    "Find repetitive work worth assisting",
                    "Map Input, AI assistance, human review and output",
                    "A workflow you can run after class",
                ]),
                ("07", "Use AI Responsibly", [
                    "Confidential, personal and customer data",
                    "Intellectual property, bias and hallucinations",
                    "Verification and organisational governance",
                ]),
                ("08", "Build Your AI Toolkit", [
                    "Role-specific reusable prompts",
                    "Practical use cases for your job",
                    "One AI-assisted workflow to take back to work",
                ]),
            ],
            labs=[
                ("01", "Emails and reports", "Draft, then refine tone, decisions and action points.", "lt-recon", "Write"),
                ("02", "Slides and meetings", "Build a storyline and turn notes into owners and deadlines.", "lt-defend", "Meet"),
                ("03", "Sheets and SOPs", "Shape formulas and a first-draft procedure for review.", "lt-attack", "Ops"),
                ("04", "Your toolkit", "Leave with prompts, use cases, one workflow and a verification checklist.", "lt-recon", "Apply"),
            ],
            quick_wins=[
                ("✉️", "Faster drafts", "Emails, reports and proposals with a strong first pass"),
                ("🧭", "Better prompts", "Reusable structures instead of random prompting"),
                ("🔁", "Workflows", "Input, AI assistance, human review, output"),
                ("🛡️", "Responsible use", "A verification checklist for work data"),
            ],
            who_for=[
                ("👥", "HR and admin", "Policies, notes, SOPs and internal communication."),
                ("💰", "Finance", "Summaries, spreadsheet support and clearer explanations."),
                ("📈", "Sales and marketing", "Proposals, campaigns and customer responses."),
                ("🏢", "Operations", "Recurring processes and follow-up workflows."),
                ("🎧", "Customer service", "Reusable responses that still sound human."),
                ("🧭", "Managers", "Research, decision notes and team briefings."),
            ],
            prereqs=[
                "No programming or AI background required",
                "Bring a real task from your role",
                "A work-approved AI tool or one provided in class",
            ],
            path_chips=[("Workplace AI", "you"), ("AI Course", "next"), ("Agentic AI", "next")],
            path_name="workplace AI",
            salary_html='Teams that can use AI well in daily work protect time for higher-value tasks. This programme is built for the job you already have.',
            next_steps=[
                ("Before this", "A real work task", "Bring an email, report or recurring process.", "Start here →"),
                ("You are here", "Workplace Generative AI", "Prompts, scenarios and one workflow.", "Currently viewing →"),
                ("Recommended next", "AI Course Malaysia", "Go deeper into models, RAG and applications.", "Continue →"),
            ],
        ),
        seo_title="Generative AI for Workplace Productivity &amp; Business Automation | Nexperts Academy",
        seo_description="Two-day instructor-led Generative AI training for workplace productivity and business automation. Build professional prompts, department use cases, AI-assisted workflows and responsible-use habits.",
        seo_keywords="Generative AI for workplace productivity, business automation, AI training Malaysia, prompt engineering for work, AI workflows, responsible AI",
        overview_p3="Hands-on exercises, department scenarios, prompt building, workflow design and responsible-AI decisions. HRD Corp claim support is available for eligible employers.",
        curriculum_head=("Eight practical sessions.", "Built around your work."),
        curriculum_intro="You move from plain-language AI, through professional prompting and department scenarios, into data, workflows, governance and a personal toolkit.",
        labs_intro="Each exercise replaces a slow task with a reviewed AI-assisted version you can reuse.",
        exam_intro="You finish with a personal prompt library, department use cases, one AI-assisted workflow and a responsible-AI verification checklist.",
        whats_included=[
            "2 days of instructor-led workplace training",
            "Personal AI prompt library",
            "Department-specific use cases and reusable prompt frameworks",
            "One AI-assisted workflow and a responsible-AI verification checklist",
        ],
        guarantee_text="Bring a real task. You leave with prompts and a workflow your team can review on Monday.",
        sidebar_meta=[
            ("Duration", "2 days"),
            ("Next intake", "24 Nov 2026"),
            ("Format", "Classroom · Virtual · Hybrid"),
            ("Level", "All levels"),
            ("Language", "English"),
            ("Cert body", "Nexperts Academy"),
            ("Exam", '<span class="smeta-badge">Toolkit</span>'),
        ],
        faqs=[
            ("Who is this for?", "Working professionals in HR, finance, sales, marketing, operations, administration, customer service and management. No programming background is required."),
            ("How is the time split?", "About 30% concept and 70% practical exercises, department scenarios, prompt building and workflow design."),
            ("Will this turn my team into AI developers?", "No. The programme is about doing current work faster and more consistently, with a human still reviewing the output."),
            ("What do participants leave with?", "A personal prompt library, department-specific use cases, reusable workplace prompt frameworks, one AI-assisted workflow and a responsible-AI verification checklist."),
            ("Does it cover confidential data?", "Yes. You work through confidential information, personal and customer data, intellectual property, bias, hallucinations, verification and organisational governance."),
        ],
        overview_sections=[
            {
                "eyebrow": "Today versus with this programme",
                "intro": "The same tasks, with a faster and more consistent first pass.",
                "comparison_table": {
                    "headers": ["Task", "Today", "With this programme"],
                    "rows": [
                        ["Important email", "45 minutes drafting", "A strong first draft, then refine tone and accuracy"],
                        ["30-page report", "Slow reading", "Decisions, risks, questions and action points"],
                        ["Blank presentation", "Starting from scratch", "Storyline, structure and talking points"],
                        ["Meeting notes", "Manual organising", "Actions, owners, deadlines and follow-ups"],
                        ["Spreadsheet formulas", "Trial and error", "Develop, explain and troubleshoot with AI assistance"],
                        ["New SOP", "A blank page", "A structured first draft for human review"],
                        ["Customer responses", "Rewriting the same replies", "Reusable frameworks that do not sound robotic"],
                        ["Initial research", "Hours of reading", "Compare and synthesise information faster"],
                        ["Prompting", "Inconsistent results", "Professional, reusable prompt frameworks"],
                        ["Weekly process", "The same steps every week", "Spots where an AI-assisted workflow fits"],
                    ],
                },
            },
            {
                "eyebrow": "What participants leave with",
                "bullets": [
                    "Personal AI prompt library",
                    "Department-specific AI use cases",
                    "Reusable workplace prompt frameworks",
                    "One AI-assisted workflow",
                    "Responsible-AI verification checklist",
                    "Practical techniques usable immediately",
                ],
            },
        ],
    )
)
