# -*- coding: utf-8 -*-
"""Legacy Wix-indexed bootcamp & skill pages — served at root URLs for SEO continuity."""
from _course_data import HERO_IMG, common_meta

BATCH = []

BATCH.append(dict(
    slug="ai-ml-bootcamp",
    title="AI & Machine Learning Bootcamp",
    title_html='AI &amp; Machine Learning<br><em>Bootcamp</em>',
    vendor_short="Nexperts Skill", watermark="AI/ML", crumb_vendor="Bootcamps",
    subtitle="Python, scikit-learn, model evaluation, responsible AI and a capstone you can demo — structured for Malaysian teams moving from spreadsheets to production-minded ML literacy in five intensive days.",
    badges=[("cb-vendor", "Nexperts Bootcamp"), ("cb-level", "Intermediate"), ("cb-new", "2026 Cohort"), ("cb-hot", "AI Track")],
    hero_meta=common_meta("5 days / 40 hrs", "Instructor-Led + GPU Labs", "On-site · Virtual · Hybrid", 92, "9 Sep 2026"),
    hero_img=HERO_IMG,
    quick_wins=[
        ("🧠", "ML workflow", "Problem framing → features → train → evaluate"),
        ("🐍", "Python stack", "NumPy, pandas, scikit-learn patterns that scale"),
        ("📊", "Model quality", "Metrics that executives trust, not just accuracy"),
        ("🛡️", "Responsible AI", "Bias checks, explainability basics, deployment guardrails"),
    ],
    overview_eyebrow="What this bootcamp is",
    overview_head=("From curiosity", "to credible ML."),
    overview_p1="Organisations across banking, telco and GLCs are expected to pilot AI — but most teams stall at slide decks. This bootcamp gives practitioners a coached path from raw data to a defended model narrative, using datasets shaped for Malaysian business contexts.",
    overview_p2="You will not be asked to memorise algorithms in isolation. Every module ends in a lab checkpoint with instructor review, mirroring how data science leads run sprint reviews.",
    overview_p3="Graduates typically continue with Microsoft AI-102, DP-100 or AWS Machine Learning Specialty depending on cloud standardisation.",
    who_for=[
        ("📊", "Analysts upskilling", "You already work in Excel/SQL and need ML vocabulary."),
        ("💻", "Developers pivoting", "You can code but have not shipped models."),
        ("📈", "Product & strategy", "You sponsor AI initiatives and need literacy."),
        ("🏦", "Enterprise cohorts", "Closed-team pricing with HRD Corp paperwork."),
        ("🎓", "STEM graduates", "Portfolio piece for data roles."),
        ("🧪", "Innovation labs", "Rapid prototyping before vendor PoCs."),
    ],
    prereqs=["Comfortable with Python basics (loops, functions)", "Familiarity with spreadsheets or SQL helpful", "Laptop with 16 GB RAM recommended"],
    prereqs_note="Optional Python refresher module available one week before start — ask enrolment.",
    curriculum_eyebrow="Bootcamp Curriculum",
    curriculum_head=("Five days.", "Sprint cadence."),
    curriculum_intro="Morning concept, afternoon lab, evening optional office hours for capstone teams.",
    modules=[
        ("01", "ML foundations", ["Supervised vs unsupervised", "Train/validation/test discipline", "Feature thinking", "Baseline models", "Lab: churn dataset baseline"]),
        ("02", "Data engineering lite", ["pandas pipelines", "Missing data strategies", "Encoding categoricals", "Leakage traps", "Lab: clean retail transactions"]),
        ("03", "Model families", ["Tree ensembles", "Linear models", "When to escalate complexity", "Hyperparameter intuition", "Lab: compare three estimators"]),
        ("04", "Evaluation & storytelling", ["Precision/recall trade-offs", "ROC & business thresholds", "Error analysis", "Executive summary slides", "Lab: defend metric choice"]),
        ("05", "Capstone & responsible AI", ["Bias & fairness checks", "Model cards intro", "Deployment patterns overview", "Demo rehearsal", "Lab: capstone presentation"]),
    ],
    labs_eyebrow="GPU-Ready Labs",
    labs_head=("Sandboxed.", "Reviewed."),
    labs_intro="Labs run on managed notebooks — no local CUDA setup required on day one.",
    labs=[
        ("01", "Baseline sprint", "Ship first model in 90 minutes.", "lt-recon", "ML"),
        ("02", "Feature store mindset", "Reproducible transforms.", "lt-defend", "Data"),
        ("03", "Ensemble bake-off", "Pick winner with evidence.", "lt-attack", "Models"),
        ("04", "Threshold workshop", "Align metrics to business cost.", "lt-recon", "Story"),
        ("05", "Capstone defense", "10-minute live demo.", "lt-attack", "Demo"),
    ],
    labs_footer="+ Mentor feedback on Git commit hygiene and README quality.",
    exam_eyebrow="Assessment",
    exam_head=("Capstone defense.", "Hiring-ready artefact."),
    exam_intro="Passing requires reproducible notebook, metric justification and live Q&A.",
    exam_main=dict(name="Capstone rubric", rows=[
        ("Notebook", "Runs end-to-end without manual hacks"),
        ("Metrics", "Appropriate for stated business goal"),
        ("Narrative", "Clear storyline for non-technical sponsor"),
        ("Passing", '<span class="pass-highlight">Meets rubric</span>'),
        ("Resit", "One coached revision week"),
    ]),
    exam_optional=None,
    mock_programme=[("01", "Metric drill", "Pick KPI before algorithm."), ("02", "Dry-run demo", "Peer critique."), ("03", "Executive Q&A", "Stress questions.")],
    pass_rate=92,
    pass_head_html='92% complete capstone<br><em>first attempt.</em>',
    pass_intro="We enforce reproducibility — the difference between a notebook demo and a production candidate.",
    pass_pills=["scikit-learn", "Capstone", "Responsible AI", "92% pass", "Mentors"],
    pass_compare=[("Video-only courses", "No reviewed artefact."), ("Nexperts", "Defended capstone + mentor sign-off.")],
    next_eyebrow="Your AI path",
    next_head=("Stack with", "cloud AI certs."),
    next_steps_intro="Continue with AI-102, DP-100 or AWS MLS depending on your platform strategy.",
    next_steps=[("Before this", "Python basics", "Bootcamp includes refresher pointers.", "Python →"), ("You are here", "AI/ML Bootcamp", "Practitioner literacy track.", "Currently viewing →"), ("Recommended next", "AI-102 / DP-100", "Operationalise on Azure.", "View AI-102 →")],
    path_name="data & AI",
    path_chips=[("Python", "prev"), ("AI/ML Bootcamp", "you"), ("AI-102", "next"), ("DP-100", "next")],
    salary_html='Data & AI analysts in KL: <strong style="color:#86efac">RM 5,500 – RM 11,000/month</strong> depending on portfolio depth.',
    reviews_eyebrow="Graduate voices",
    reviews_head=("What bootcamp", "graduates say."),
    reviews_summary=("4.8", 96, 22, 6, 118),
    reviews=[
        ("★★★★★", "Capstone review felt like a real sprint demo — prepared me for internal AI guild presentations.", "rav-b", "NS", "Nurul Syafiq", "Banking analyst", "✓ Capstone"),
        ("★★★★★", "Finally understood why my first model looked great in training but failed in production.", "rav-m", "KT", "Kevin Tan", "Engineer", "✓ Capstone"),
        ("★★★★", "Intense week — arrive rested.", "rav-g", "LM", "Li Mei", "Consultant", "✓ Capstone"),
        ("★★★★★", "Responsible AI module should be mandatory everywhere.", "rav-a", "AR", "Amir Rahman", "Product lead", "✓ Capstone"),
    ],
    price="RM 3,800", price_orig="RM 4,200", price_save="Save 10%",
    price_note="Per person · HRD Corp claim support available",
    sidebar_meta=[("Duration", "5 days / 40 hrs"), ("Next intake", "9 Sep 2026"), ("Format", "Hybrid"), ("Level", "Intermediate"), ("Language", "English"), ("Cert body", "Nexperts Skill"), ("Exam", '<span class="smeta-badge">Capstone</span>')],
    whats_included=["Lab environment", "Datasets", "Capstone coaching", "Certificate", "Slack mentor access"],
    verify_items=["Nexperts bootcamp verification ID", "Capstone repo tag archived"],
    guarantee_text="Complete all labs + fail capstone? One complimentary remediation session.",
))

BATCH.append(dict(
    slug="cyber-security-bootcamp",
    title="Cyber Security Bootcamp",
    title_html='Cyber Security<br><em>Bootcamp</em>',
    vendor_short="Nexperts Skill", watermark="SEC", crumb_vendor="Bootcamps",
    subtitle="Hands-on blue-team and ethical-hacking fundamentals — reconnaissance, hardening, detection, incident response and safe lab tradecraft for Malaysian enterprises building their first security champions.",
    badges=[("cb-vendor", "Nexperts Bootcamp"), ("cb-level", "Foundation → Intermediate"), ("cb-new", "SOC Ready"), ("cb-hot", "Security")],
    hero_meta=common_meta("5 days / 40 hrs", "Range Labs + Tabletops", "On-site · Virtual · Hybrid", 94, "16 Sep 2026"),
    hero_img=HERO_IMG,
    quick_wins=[
        ("🛡️", "Defensive core", "Asset inventory, patching priorities, hardening baselines"),
        ("🔍", "Detection", "Log sources, alert triage, MITRE mapping intro"),
        ("⚔️", "Offensive lens", "Safe recon & vuln scanning in isolated range"),
        ("🚨", "IR tabletop", "Containment decisions with MY regulatory context"),
    ],
    overview_eyebrow="What this bootcamp is",
    overview_head=("Security skills", "you can prove."),
    overview_p1="Cyber hiring in Malaysia increasingly tests practical judgement, not acronym collection. This bootcamp blends defensive operations with ethical offensive labs so you understand both sides of an attack chain — in a legal, isolated environment.",
    overview_p2="Instructors run SOC programmes for regional enterprises; scenarios reference BNM RMiT expectations, PDPA breach notification thinking and common phishing patterns seen in MY inboxes.",
    overview_p3="Many graduates continue to CEH, CompTIA Security+ or SC-200 depending on role target.",
    who_for=[
        ("🖥️", "IT administrators", "You are the accidental security team."),
        ("🎓", "Career switchers", "Need portfolio-friendly labs."),
        ("🏢", "GRC & risk", "You want technical empathy."),
        ("👥", "Corporate cohorts", "Build a champion network."),
        ("🔐", "Junior analysts", "Accelerate before cert exams."),
        ("📡", "Network engineers", "Extend into security operations."),
    ],
    prereqs=["Basic TCP/IP and OS familiarity", "No prior security certification required", "Signed acceptable-use policy for range labs"],
    prereqs_note="Laptop with admin rights for VPN range access — details emailed pre-course.",
    curriculum_eyebrow="Bootcamp Curriculum",
    curriculum_head=("Five days.", "Range to tabletop."),
    curriculum_intro="Every offensive technique is paired with a defensive countermeasure discussion.",
    modules=[
        ("01", "Security landscape", ["Threat actors in MY", "Kill chain overview", "Policy & governance touchpoints", "Lab: asset discovery"]),
        ("02", "Hardening & vuln mgmt", ["Patch prioritisation", "CIS benchmarks intro", "Vulnerability scanning ethics", "Lab: harden Windows/Linux"]),
        ("03", "Detection engineering lite", ["Log sources", "Sigma rules intro", "Alert triage playbook", "Lab: find malicious sign-in"]),
        ("04", "Ethical offensive labs", ["Recon methodology", "Safe scanning", "Exploit concepts (isolated)", "Lab: pivot in range only"]),
        ("05", "Incident response", ["Tabletop facilitation", "Containment trade-offs", "Comms & evidence", "Lab: IR simulation"]),
    ],
    labs_eyebrow="Range Labs",
    labs_head=("Isolated.", "Legal."),
    labs_intro="All offensive labs occur in Nexperts-hosted ranges — no scanning of production networks.",
    labs=[
        ("01", "Asset map", "Document crown jewels.", "lt-recon", "GRC"),
        ("02", "Hardening sprint", "Close critical findings.", "lt-defend", "Ops"),
        ("03", "Detection hunt", "Triage realistic alerts.", "lt-recon", "SOC"),
        ("04", "Range mission", "Controlled attack path.", "lt-attack", "Red"),
        ("05", "IR tabletop", "Executive briefing.", "lt-attack", "IR"),
    ],
    labs_footer="+ Range VPN credentials revoked automatically after bootcamp.",
    exam_eyebrow="Assessment",
    exam_head=("Practical + tabletop.", "Role-ready."),
    exam_intro="Passing requires range lab completion and facilitated IR tabletop participation.",
    exam_main=dict(name="Bootcamp assessment", rows=[
        ("Range labs", "All checkpoints signed by instructor"),
        ("Tabletop", "Clear containment rationale"),
        ("Ethics", "Acceptable-use compliance"),
        ("Passing", '<span class="pass-highlight">Meets rubric</span>'),
        ("Resit", "Range remediation day"),
    ]),
    exam_optional=None,
    pass_rate=94,
    pass_head_html='94% complete bootcamp<br><em>requirements.</em>',
    pass_intro="We optimise for judgement under pressure — what SOC hiring managers actually test.",
    pass_pills=["Range labs", "Tabletop", "MITRE intro", "94% pass", "MY context"],
    pass_compare=[("Theory-only courses", "No safe offensive exposure."), ("Nexperts", "Balanced blue/red with IR.")],
    next_eyebrow="Your security path",
    next_head=("Certify", "the skills."),
    next_steps_intro="Continue with CEH for offensive depth, Security+ for breadth, or SC-200 for Microsoft SOC.",
    next_steps=[("Before this", "Networking basics", "CCNA knowledge helps but not required.", "CCNA →"), ("You are here", "Cyber Bootcamp", "Practitioner foundation.", "Currently viewing →"), ("Recommended next", "CEH / Security+", "Pick offensive or broad cert.", "View CEH →")],
    path_name="cybersecurity",
    path_chips=[("IT Ops", "prev"), ("Cyber Bootcamp", "you"), ("CEH", "next"), ("SC-200", "next")],
    salary_html='Security analysts in KL: <strong style="color:#86efac">RM 5,000 – RM 10,500/month</strong> depending on SOC vs GRC track.',
    reviews_eyebrow="Graduate voices",
    reviews_head=("What defenders", "say."),
    reviews_summary=("4.9", 112, 24, 4, 132),
    reviews=[
        ("★★★★★", "Tabletop on day 5 was the most realistic IR exercise I have attended locally.", "rav-b", "FZ", "Farid Zainal", "IT manager", "✓ Completed"),
        ("★★★★★", "Range labs demystified what our pentest reports actually mean.", "rav-m", "JC", "Jessica Chua", "Sysadmin", "✓ Completed"),
        ("★★★★", "Packed week — worth it.", "rav-g", "HP", "Hafiz Prakash", "Graduate", "✓ Completed"),
        ("★★★★★", "Instructor mapped alerts to MITRE without hand-waving.", "rav-a", "WL", "Wong Li", "SOC L1", "✓ Completed"),
    ],
    price="RM 3,600", price_orig="RM 4,000", price_save="Save 10%",
    price_note="Per person · Includes range access for bootcamp duration",
    sidebar_meta=[("Duration", "5 days / 40 hrs"), ("Next intake", "16 Sep 2026"), ("Format", "Hybrid"), ("Level", "Foundation+"), ("Language", "English"), ("Cert body", "Nexperts Skill"), ("Exam", '<span class="smeta-badge">Practical</span>')],
    whats_included=["Range access", "Lab guides", "Tabletop materials", "Certificate"],
    verify_items=["Nexperts bootcamp verification", "Range completion log"],
    guarantee_text="Miss a lab checkpoint? Attend remediation Friday within 30 days.",
))

BATCH.append(dict(
    slug="android-development",
    title="Android Development",
    title_html='Android<br><em>Development</em>',
    vendor_short="Nexperts Skill", watermark="AND", crumb_vendor="Mobile Dev",
    subtitle="Kotlin, Jetpack Compose, MVVM architecture, REST integration and Play Store readiness — build and ship a portfolio app with Malaysian fintech and logistics UX patterns in six coached days.",
    badges=[("cb-vendor", "Nexperts Skill"), ("cb-level", "Beginner → Intermediate"), ("cb-new", "Compose 2026"), ("cb-hot", "Mobile")],
    hero_meta=common_meta("6 days / 48 hrs", "Project Labs + Code Review", "On-site · Virtual · Hybrid", 90, "23 Sep 2026"),
    hero_img=HERO_IMG,
    quick_wins=[
        ("📱", "Modern UI", "Jetpack Compose layouts & state"),
        ("🏗️", "Architecture", "MVVM, repositories, testable layers"),
        ("🌐", "APIs", "Retrofit, auth tokens, error UX"),
        ("🚀", "Ship", "Release build, signing basics, Play checklist"),
    ],
    overview_eyebrow="What this course is",
    overview_head=("Ship an Android app", "employers can install."),
    overview_p1="Mobile roles in Malaysia increasingly require a GitHub repo or Play Store listing — not tutorial certificates. You will build a booking-style app (anonymised MY fintech brief) with code reviews mirroring industry PR feedback.",
    overview_p2="We emphasise maintainability: dependency injection patterns, navigation graphs and instrumentation tests at the right depth for junior interviews.",
    overview_p3="Graduates often pair this with full-stack web or Kotlin backend modules for product teams.",
    who_for=[
        ("💻", "Java developers", "Pivoting to Kotlin mobile."),
        ("🎓", "CS graduates", "Need a portfolio app."),
        ("🏢", "Product squads", "Upskill internal builders."),
        ("🔄", "Career switchers", "After our Python bootcamp."),
        ("📱", "Freelancers", "Deliver client apps professionally."),
        ("👥", "Corporate cohorts", "Custom briefs available."),
    ],
    prereqs=["Basic programming (any language)", "Android Studio installed", "GitHub account"],
    prereqs_note="Pre-course setup checklist includes emulator or physical device guidance.",
    curriculum_eyebrow="Course Curriculum",
    curriculum_head=("Six days.", "Compose-first."),
    curriculum_intro="Each day merges concept, live coding and PR-style review.",
    modules=[
        ("01", "Kotlin & tooling", ["Language essentials", "Android Studio workflow", "Gradle basics", "Lab: Hello Compose"]),
        ("02", "Compose UI", ["Layouts", "State hoisting", "Theming", "Lab: multi-screen flow"]),
        ("03", "Architecture", ["ViewModel", "Repository", "Coroutines intro", "Lab: offline-first list"]),
        ("04", "Networking", ["REST integration", "Auth headers", "Error states", "Lab: live API module"]),
        ("05", "Quality & tests", ["Unit tests", "UI tests intro", "Crashlytics mindset", "Lab: stabilise build"]),
        ("06", "Capstone ship", ["Signing overview", "Play Console checklist", "Demo rehearsal", "Lab: store-ready build"]),
    ],
    labs_eyebrow="Project Labs",
    labs_head=("PR by PR.", "Reviewed."),
    labs_intro="Instructors tag release checkpoints in your repo like a real sprint.",
    labs=[
        ("01", "Compose shell", "Navigation skeleton.", "lt-recon", "UI"),
        ("02", "State lab", "Form validation UX.", "lt-defend", "UI"),
        ("03", "API slice", "Authenticated fetch.", "lt-attack", "API"),
        ("04", "Test harness", "Critical path tests.", "lt-recon", "QA"),
        ("05", "Release candidate", "Signed debug build.", "lt-attack", "Ship"),
        ("06", "Demo", "Play listing draft.", "lt-attack", "Capstone"),
    ],
    labs_footer="+ Kotlin style guide review on final PR.",
    exam_eyebrow="Assessment",
    exam_head=("App demo + repo.", "Portfolio piece."),
    exam_intro="Passing requires installable build, README and 10-minute demo.",
    exam_main=dict(name="Capstone rubric", rows=[
        ("Build", "Installs without manual steps"),
        ("Architecture", "Clear separation of concerns"),
        ("UX", "Handles loading/error states"),
        ("Passing", '<span class="pass-highlight">Meets rubric</span>'),
        ("Resit", "One remediation sprint"),
    ]),
    exam_optional=None,
    pass_rate=90,
    pass_head_html='90% ship portfolio app<br><em>on schedule.</em>',
    pass_intro="We enforce release hygiene — the gap between tutorial apps and hireable engineers.",
    pass_pills=["Kotlin", "Compose", "MVVM", "90% ship", "Code review"],
    pass_compare=[("Video courses", "No reviewed repo."), ("Nexperts", "PR reviews + demo defense.")],
    next_eyebrow="Your mobile path",
    next_head=("Expand to", "full product stack."),
    next_steps_intro="Pair with full-stack web or iOS for cross-platform product teams.",
    next_steps=[("Before this", "Programming basics", "Python bootcamp recommended.", "Python →"), ("You are here", "Android Development", "Mobile engineering track.", "Currently viewing →"), ("Recommended next", "Full Stack Web", "Own the API layer too.", "View Full Stack →")],
    path_name="mobile engineering",
    path_chips=[("Kotlin", "prev"), ("Android", "you"), ("Full Stack", "next"), ("iOS", "next")],
    salary_html='Android developers in KL: <strong style="color:#86efac">RM 4,800 – RM 9,500/month</strong> depending on portfolio.',
    reviews_eyebrow="Student reviews",
    reviews_head=("What our mobile", "builders say."),
    reviews_summary=("4.7", 74, 18, 8, 86),
    reviews=[
        ("★★★★★", "PR feedback on my ViewModel layer was worth the course fee alone.", "rav-b", "DA", "Daniel Arif", "Career switch", "✓ Portfolio"),
        ("★★★★", "Fast pace — Compose clicked on day 3.", "rav-m", "SY", "Siti Yusof", "Developer", "✓ Portfolio"),
        ("★★★★★", "Finally published an internal test track build.", "rav-g", "VK", "Vikram Kumar", "Consultant", "✓ Portfolio"),
        ("★★★★★", "Demo day felt like a real sprint review.", "rav-a", "NC", "Nadia Chan", "Graduate", "✓ Portfolio"),
    ],
    price="RM 3,400", price_orig="RM 3,800", price_save="Save 11%",
    price_note="Per person · Emulator setup support included",
    sidebar_meta=[("Duration", "6 days / 48 hrs"), ("Next intake", "23 Sep 2026"), ("Format", "Hybrid"), ("Level", "Beginner+"), ("Language", "English"), ("Cert body", "Nexperts Skill"), ("Exam", '<span class="smeta-badge">Capstone</span>')],
    whats_included=["Repo templates", "Code reviews", "Play checklist", "Certificate"],
    verify_items=["Nexperts verification", "Repo release tag"],
    guarantee_text="Complete labs but fail demo? One coached remediation week.",
))

BATCH.append(dict(
    slug="django",
    title="Django Web Development",
    title_html='Django Web<br><em>Development</em>',
    vendor_short="Nexperts Skill", watermark="DJG", crumb_vendor="Programming",
    subtitle="Python Django — models, admin, REST APIs, authentication, deployment and security defaults — build a production-shaped web app for Malaysian SME operations in five days.",
    badges=[("cb-vendor", "Nexperts Skill"), ("cb-level", "Intermediate"), ("cb-new", "Django 5.x"), ("cb-hot", "Backend")],
    hero_meta=common_meta("5 days / 40 hrs", "Instructor-Led + Labs", "On-site · Virtual · Hybrid", 93, "30 Sep 2026"),
    hero_img=HERO_IMG,
    quick_wins=[
        ("🐍", "Django ORM", "Models, migrations, queries that scale"),
        ("🔐", "Auth", "Users, permissions, session hardening"),
        ("📡", "DRF APIs", "Serializers, validation, versioning"),
        ("☁️", "Deploy", "Gunicorn, env config, static files"),
    ],
    overview_eyebrow="What this course is",
    overview_head=("Backend apps", "with Django discipline."),
    overview_p1="Django remains the fastest path from idea to maintainable admin-backed systems — ideal for internal tools, membership portals and B2B APIs common in Malaysian enterprises.",
    overview_p2="You will implement a multi-tenant-style operations portal (anonymised logistics brief) with tests on critical paths and a deployment checklist suitable for Azure App Service or similar PaaS.",
    overview_p3="Graduates often continue with Docker, AZ-204 or full-stack front-end modules.",
    who_for=[
        ("🐍", "Python developers", "Ready for web frameworks."),
        ("💻", "Full-stack learners", "After our Python bootcamp."),
        ("🏢", "Internal IT", "Building admin systems."),
        ("🎓", "Graduates", "Portfolio backend project."),
        ("📊", "Data engineers", "Need service layer skills."),
        ("👥", "Teams", "Standardise Django patterns."),
    ],
    prereqs=["Solid Python fundamentals", "Git basics", "SQL awareness helpful"],
    prereqs_note="Virtualenv setup guide sent before day one.",
    curriculum_eyebrow="Course Curriculum",
    curriculum_head=("Five days.", "ORM to deploy."),
    curriculum_intro="Security and testing are woven into every module, not bolted on last.",
    modules=[
        ("01", "Django foundations", ["Project layout", "Models & migrations", "Admin customization", "Lab: domain models"]),
        ("02", "Views & templates", ["Class-based views", "Forms", "Messages framework", "Lab: staff workflows"]),
        ("03", "DRF APIs", ["Serializers", "Permissions", "Pagination", "Lab: mobile-ready API"]),
        ("04", "Auth & security", ["User models", "CSRF, XSS awareness", "Settings hygiene", "Lab: role-based access"]),
        ("05", "Testing & deploy", ["pytest-django", "CI smoke tests", "Deploy checklist", "Lab: production config"]),
    ],
    labs_eyebrow="Backend Labs",
    labs_head=("Production-shaped.", "Reviewed."),
    labs_intro="Labs emphasise maintainable settings splits and secret management.",
    labs=[
        ("01", "Models", "Schema + migrations.", "lt-recon", "ORM"),
        ("02", "Admin", "Operations console.", "lt-defend", "UX"),
        ("03", "API", "Versioned endpoints.", "lt-attack", "API"),
        ("04", "Security", "Permissions matrix.", "lt-recon", "Sec"),
        ("05", "Deploy", "Green CI + live URL.", "lt-attack", "Ops"),
    ],
    labs_footer="+ Sample GitHub Actions workflow for test gate.",
    exam_eyebrow="Assessment",
    exam_head=("App + API demo.", "Maintainable codebase."),
    exam_intro="Passing requires deployed URL, passing tests and architecture walkthrough.",
    exam_main=dict(name="Project rubric", rows=[
        ("Tests", "Critical paths covered"),
        ("Security", "No secrets in repo"),
        ("API", "Documented endpoints"),
        ("Passing", '<span class="pass-highlight">Meets rubric</span>'),
        ("Resit", "Remediation sprint"),
    ]),
    exam_optional=None,
    pass_rate=93,
    pass_head_html='93% pass project review<br><em>first submission.</em>',
    pass_intro="We coach settings discipline — where junior Django projects usually fail audits.",
    pass_pills=["Django", "DRF", "Deploy", "93% pass", "pytest"],
    pass_compare=[("Tutorial clones", "No deploy or tests."), ("Nexperts", "Live URL + reviewed PRs.")],
    next_eyebrow="Your backend path",
    next_head=("Add front-end", "or cloud."),
    next_steps_intro="Continue with React full-stack, Docker or Azure developer certifications.",
    next_steps=[("Before this", "Python Bootcamp", "Recommended foundation.", "Python →"), ("You are here", "Django Web Dev", "Backend engineering.", "Currently viewing →"), ("Recommended next", "Docker / AZ-204", "Scale and ship in cloud.", "View Docker →")],
    path_name="Python engineering",
    path_chips=[("Python", "prev"), ("Django", "you"), ("Docker", "next"), ("Full Stack", "next")],
    salary_html='Python web developers in KL: <strong style="color:#86efac">RM 5,200 – RM 10,000/month</strong>.',
    reviews_eyebrow="Student reviews",
    reviews_head=("What Django", "graduates say."),
    reviews_summary=("4.8", 68, 20, 6, 82),
    reviews=[
        ("★★★★★", "DRF module finally made serializers click — shipped internal API same month.", "rav-b", "HL", "Hui Ling", "Developer", "✓ Passed"),
        ("★★★★★", "Deploy checklist saved us from a classic settings.py production leak.", "rav-m", "RA", "Ravi Anand", "IT lead", "✓ Passed"),
        ("★★★★", "Would love one more day on async — still excellent.", "rav-g", "KO", "Ken Ooi", "Analyst", "✓ Passed"),
        ("★★★★★", "Code reviews were strict in the best way.", "rav-a", "MS", "Michelle Sim", "Graduate", "✓ Passed"),
    ],
    price="RM 2,900", price_orig="RM 3,200", price_save="Save 9%",
    price_note="Per person · HRD Corp paperwork assistance",
    sidebar_meta=[("Duration", "5 days / 40 hrs"), ("Next intake", "30 Sep 2026"), ("Format", "Hybrid"), ("Level", "Intermediate"), ("Language", "English"), ("Cert body", "Nexperts Skill"), ("Exam", '<span class="smeta-badge">Project</span>')],
    whats_included=["Templates", "pytest starter", "Deploy guide", "Certificate"],
    verify_items=["Nexperts verification", "Deployed URL archived"],
    guarantee_text="Fail project review? One coached revision cycle included.",
))

BATCH.append(dict(
    slug="ios-development",
    title="iOS Development",
    title_html='iOS<br><em>Development</em>',
    vendor_short="Nexperts Skill", watermark="iOS", crumb_vendor="Mobile Dev",
    subtitle="Swift, SwiftUI, MVVM, networking and TestFlight distribution — design and ship an iPhone app with Apple Human Interface Guidelines and Malaysian consumer UX expectations in six days.",
    badges=[("cb-vendor", "Nexperts Skill"), ("cb-level", "Beginner → Intermediate"), ("cb-new", "SwiftUI 2026"), ("cb-hot", "Mobile")],
    hero_meta=common_meta("6 days / 48 hrs", "Xcode Labs + Reviews", "On-site · Virtual · Hybrid", 89, "7 Oct 2026"),
    hero_img=HERO_IMG,
    quick_wins=[
        ("📱", "SwiftUI", "Declarative UI, navigation, previews"),
        ("🏗️", "MVVM", "Observable models, dependency flow"),
        ("🌐", "Networking", "URLSession, async/await, Codable"),
        ("✈️", "TestFlight", "Archive, upload, beta feedback loop"),
    ],
    overview_eyebrow="What this course is",
    overview_head=("Build for iPhone", "with confidence."),
    overview_p1="iOS talent in Malaysia is concentrated in fintech, super-apps and enterprise mobility programmes. This course gives you a credible SwiftUI portfolio piece with mentor reviews on architecture and App Store readiness.",
    overview_p2="Mac hardware is required — we provide setup guidance for Apple Silicon and Intel Macs, plus simulator tuning for performance.",
    overview_p3="Pair with Android development for cross-platform product squads or full-stack for end-to-end ownership.",
    who_for=[
        ("💻", "Developers", "New to Apple ecosystem."),
        ("🎓", "Graduates", "Targeting mobile roles."),
        ("🏢", "Enterprise mobility", "Internal app teams."),
        ("🔄", "Android devs", "Add iOS parity skills."),
        ("📱", "Designers who code", "SwiftUI fluency."),
        ("👥", "Cohorts", "Corporate pricing available."),
    ],
    prereqs=["Programming fundamentals", "Mac with Xcode 15+", "Apple Developer account (free tier OK)"],
    prereqs_note="Windows-only learners should discuss remote Mac lab options with enrolment.",
    curriculum_eyebrow="Course Curriculum",
    curriculum_head=("Six days.", "SwiftUI-first."),
    curriculum_intro="Apple platform conventions are taught alongside cross-platform engineering judgement.",
    modules=[
        ("01", "Swift essentials", ["Types & optionals", "Structs vs classes", "Closures", "Lab: language drills"]),
        ("02", "SwiftUI basics", ["Layouts", "State", "NavigationStack", "Lab: onboarding flow"]),
        ("03", "MVVM & data", ["ObservableObject", "Repository pattern", "Persistence intro", "Lab: offline cache"]),
        ("04", "Networking", ["REST with async/await", "Error UX", "Auth tokens", "Lab: live feed screen"]),
        ("05", "Quality", ["Unit tests", "UI tests snapshot intro", "Accessibility", "Lab: polish pass"]),
        ("06", "Ship", ["Archive & upload", "TestFlight", "Demo day", "Lab: beta build"]),
    ],
    labs_eyebrow="Xcode Labs",
    labs_head=("Simulator to", "TestFlight."),
    labs_intro="Evening office hours for signing & provisioning questions.",
    labs=[
        ("01", "SwiftUI shell", "Tab navigation.", "lt-recon", "UI"),
        ("02", "State", "Forms & validation.", "lt-defend", "UI"),
        ("03", "API", "Decodable models.", "lt-attack", "API"),
        ("04", "A11y", "VoiceOver pass.", "lt-recon", "UX"),
        ("05", "Archive", "TestFlight upload.", "lt-attack", "Ship"),
        ("06", "Demo", "App Store story.", "lt-attack", "Capstone"),
    ],
    labs_footer="+ Provisioning profile troubleshooting clinic on day 5.",
    exam_eyebrow="Assessment",
    exam_head=("TestFlight + demo.", "Portfolio."),
    exam_intro="Installable beta build, README and live demo required.",
    exam_main=dict(name="Capstone rubric", rows=[
        ("Build", "TestFlight or ad-hoc install works"),
        ("Architecture", "MVVM boundaries clear"),
        ("UX", "Loading/error states handled"),
        ("Passing", '<span class="pass-highlight">Meets rubric</span>'),
        ("Resit", "One remediation week"),
    ]),
    exam_optional=None,
    pass_rate=89,
    pass_head_html='89% reach TestFlight<br><em>milestone.</em>',
    pass_intro="Provisioning issues are normal — we budget mentor time specifically for signing blockers.",
    pass_pills=["SwiftUI", "MVVM", "TestFlight", "89% ship", "Mentors"],
    pass_compare=[("Mac-less tutorials", "No signing reality."), ("Nexperts", "TestFlight milestone required.")],
    next_eyebrow="Your Apple path",
    next_head=("Cross-platform", "options."),
    next_steps_intro="Add Android for product parity or backend Django for full ownership.",
    next_steps=[("Before this", "Programming basics", "Any language background OK.", "Entry →"), ("You are here", "iOS Development", "Apple mobile track.", "Currently viewing →"), ("Recommended next", "Android Dev", "Two-platform product teams.", "View Android →")],
    path_name="mobile engineering",
    path_chips=[("Swift", "prev"), ("iOS", "you"), ("Android", "next"), ("Full Stack", "next")],
    salary_html='iOS developers in KL: <strong style="color:#86efac">RM 5,000 – RM 11,000/month</strong> at product companies.',
    reviews_eyebrow="Student reviews",
    reviews_head=("What iOS", "graduates say."),
    reviews_summary=("4.7", 62, 16, 8, 74),
    reviews=[
        ("★★★★★", "TestFlight upload on day 6 — first time I felt job-ready for mobile.", "rav-b", "JT", "Jason Teo", "Engineer", "✓ TestFlight"),
        ("★★★★", "Provisioning section was painful but necessary — mentors stayed late.", "rav-m", "AN", "Aina Nasir", "Designer-dev", "✓ TestFlight"),
        ("★★★★★", "SwiftUI previews sped up my iteration massively.", "rav-g", "PL", "Pang Li", "Graduate", "✓ TestFlight"),
        ("★★★★", "Solid — want advanced Core Data module next.", "rav-a", "IB", "Ibrahim Bakri", "Consultant", "✓ TestFlight"),
    ],
    price="RM 3,500", price_orig="RM 3,900", price_save="Save 10%",
    price_note="Per person · Mac required",
    sidebar_meta=[("Duration", "6 days / 48 hrs"), ("Next intake", "7 Oct 2026"), ("Format", "Hybrid"), ("Level", "Beginner+"), ("Language", "English"), ("Cert body", "Nexperts Skill"), ("Exam", '<span class="smeta-badge">Capstone</span>')],
    whats_included=["Xcode templates", "Signing guide", "TestFlight checklist", "Certificate"],
    verify_items=["Nexperts verification", "TestFlight build noted"],
    guarantee_text="Stuck on signing after course? 30-day Slack support included.",
))

BATCH.append(dict(
    slug="netflix-data-analysis",
    title="Netflix Data Analysis Workshop",
    title_html='Netflix Data Analysis<br><em>with Python</em>',
    vendor_short="Nexperts Workshop", watermark="NFLX", crumb_vendor="Workshops",
    subtitle="Hands-on workshop using pandas, matplotlib and seaborn on a Netflix catalogue dataset — exploratory analysis, visual storytelling and executive-ready insights in two intensive days.",
    badges=[("cb-vendor", "Workshop"), ("cb-level", "Beginner+"), ("cb-new", "Data Story"), ("cb-hot", "Analytics")],
    hero_meta=common_meta("2 days / 16 hrs", "Workshop + Live Notebooks", "On-site · Virtual", 96, "14 Oct 2026"),
    hero_img=HERO_IMG,
    quick_wins=[
        ("🐼", "pandas fluency", "Filter, group, merge at speed"),
        ("📊", "Visuals", "Charts that answer business questions"),
        ("🎬", "Domain story", "Content strategy metrics that resonate"),
        ("📑", "Deliverable", "Slide-ready insight pack"),
    ],
    overview_eyebrow="What this workshop is",
    overview_head=("Turn streaming data", "into decisions."),
    overview_p1="Inspired by our popular community session, this workshop walks analysts through a real Netflix-style catalogue dataset — genres, ratings, release trends and regional availability — to practice the exact pandas patterns used in Malaysian media and e-commerce analytics teams.",
    overview_p2="You leave with a cleaned notebook and a five-slide insight narrative suitable for stakeholder meetings.",
    overview_p3="Ideal warm-up before SQL for Data Professionals, PL-300 or our Python bootcamp.",
    who_for=[
        ("📊", "Analysts", "Excel power users moving to Python."),
        ("🎓", "Students", "Portfolio notebook for internships."),
        ("📈", "Marketing", "Campaign analysts exploring data stories."),
        ("💼", "Managers", "Hands-on literacy, not theory."),
        ("🏢", "Teams", "Fun team-building with skills."),
        ("🧪", "Hackathon fans", "Structured version of our community lab."),
    ],
    prereqs=["Basic Python or completion of Python Bootcamp day 1-2 material", "Laptop with Jupyter or VS Code"],
    prereqs_note="Dataset and starter notebook provided — no install friction on corporate networks.",
    curriculum_eyebrow="Workshop Agenda",
    curriculum_head=("Two days.", "Notebook to slides."),
    curriculum_intro="Minimal lecture — maximum guided exploration with instructor checkpoints.",
    modules=[
        ("01", "Data onboarding", ["CSV hygiene", "pandas dtypes", "Missing values", "Lab: profile dataset"]),
        ("02", "EDA patterns", ["Groupbys", "pivot thinking", "Outliers", "Lab: genre & rating trends"]),
        ("03", "Visualization", ["matplotlib & seaborn", "Chart choice", "Lab: regional availability story"]),
        ("04", "Insight packaging", ["Narrative structure", "Executive summary", "Lab: present findings"]),
    ],
    labs_eyebrow="Workshop Labs",
    labs_head=("Live.", "Collaborative."),
    labs_intro="Teams rotate presenter role in afternoon stand-ups.",
    labs=[
        ("01", "Clean", "Standardise columns.", "lt-recon", "Data"),
        ("02", "Explore", "Top 5 business questions.", "lt-defend", "EDA"),
        ("03", "Visualise", "Three chart storyboard.", "lt-attack", "Viz"),
        ("04", "Present", "5-slide insight deck.", "lt-attack", "Story"),
    ],
    labs_footer="+ Optional homework: extend analysis with external API metadata.",
    exam_eyebrow="Assessment",
    exam_head=("Insight presentation.", "Practical."),
    exam_intro="Submit notebook + short slide deck; present key finding in 8 minutes.",
    exam_main=dict(name="Workshop rubric", rows=[
        ("Notebook", "Reproducible cells"),
        ("Charts", "Appropriate types & labels"),
        ("Insight", "Actionable recommendation"),
        ("Passing", '<span class="pass-highlight">Meets rubric</span>'),
        ("Retries", "Email revision within 7 days"),
    ]),
    exam_optional=None,
    pass_rate=96,
    pass_head_html='96% deliver insight deck<br><em>on time.</em>',
    pass_intro="We coach presentation — analysts fail when charts lack a headline, not when code is wrong.",
    pass_pills=["pandas", "seaborn", "Storytelling", "96% pass", "Workshop"],
    pass_compare=[("Passive webinars", "No artefact."), ("Nexperts", "Notebook + slides required.")],
    next_eyebrow="Continue learning",
    next_head=("Go deeper", "with certs."),
    next_steps_intro="Progress to SQL for Data Professionals, Python Bootcamp or PL-300.",
    next_steps=[("Before this", "Excel / basic Python", "Starter notebook provided.", "Entry →"), ("You are here", "Netflix Workshop", "Analytics storytelling.", "Currently viewing →"), ("Recommended next", "SQL / PL-300", "Enterprise BI depth.", "View SQL course →")],
    path_name="data analytics",
    path_chips=[("Excel", "prev"), ("Workshop", "you"), ("SQL", "next"), ("PL-300", "next")],
    salary_html='Analysts with Python storytelling: <strong style="color:#86efac">RM 4,500 – RM 8,500/month</strong> in KL.',
    reviews_eyebrow="Participant feedback",
    reviews_head=("Workshop", "highlights."),
    reviews_summary=("4.9", 54, 20, 4, 62),
    reviews=[
        ("★★★★★", "Best two-day intro to pandas I have attended — left with slides my manager actually used.", "rav-b", "YT", "Yasmin Taha", "Marketing analyst", "✓ Presented"),
        ("★★★★★", "Netflix angle made EDA fun — team still references the genre chart.", "rav-m", "BC", "Ben Chia", "Student", "✓ Presented"),
        ("★★★★", "Would enjoy a third day on SQL joins — still great value.", "rav-g", "RW", "Rina Wong", "Ops", "✓ Presented"),
        ("★★★★★", "Perfect warm-up before our corporate PL-300 cohort.", "rav-a", "TH", "Tan Hock", "L&D manager", "✓ Team booking"),
    ],
    price="RM 890", price_orig="RM 1,050", price_save="Save 15%",
    price_note="Per person · Group rates for 6+",
    sidebar_meta=[("Duration", "2 days / 16 hrs"), ("Next intake", "14 Oct 2026"), ("Format", "Virtual / On-site"), ("Level", "Beginner+"), ("Language", "English"), ("Cert body", "Nexperts Workshop"), ("Deliverable", '<span class="smeta-badge">Slides</span>')],
    whats_included=["Dataset", "Starter notebook", "Slide template", "Certificate of attendance"],
    verify_items=["Workshop attendance verification"],
    guarantee_text="Miss day two? Join the next public cohort once within 90 days (seat permitting).",
))
