# -*- coding: utf-8 -*-
"""ISACA / ISC2 course data (CISSP, CISM)."""
from _course_data import HERO_IMG, common_meta

BATCH = []

# 1. CISSP
BATCH.append(dict(
    slug="cissp",
    title="CISSP",
    title_html='Certified Information<br><em>Systems Security Professional</em>',
    vendor_short="ISC2", watermark="CISSP", crumb_vendor="ISC2",
    subtitle="The world's most-respected information security credential. Eight CBK domains spanning security architecture, operations, software development security and risk management \u2014 senior security leadership territory.",
    badges=[("cb-vendor","ISC2 Authorized"),("cb-level","Expert"),("cb-new","2026 CBK"),("cb-hot","Top Security Hire")],
    hero_meta=common_meta("7 days / 56 hrs","Instructor-Led + CBK Drills","On-site \u00b7 Hybrid",91,"13 October 2026"),
    hero_img=HERO_IMG,
    quick_wins=[
        ("\U0001F6E1\uFE0F","8 CBK domains mastered","Security architecture, operations, IAM, network, software, risk"),
        ("\U0001F4DA","Senior security thinking","Manager-mindset emphasis required by CISSP \u2014 not technician-mindset"),
        ("\U0001F3DB\uFE0F","Compliance & governance","BNM RMiT, PDPA, ISO 27001, NIST CSF, GDPR alignment throughout"),
        ("\U0001F30E","Career-defining credential","Required for CISO, security architect, principal security engineer roles"),
    ],
    overview_eyebrow="What this course is",
    overview_head=("CISSP is","security leadership."),
    overview_p1="The CISSP (Certified Information Systems Security Professional) is the world's most-recognised information security credential. The 2026 Common Body of Knowledge (CBK) covers eight domains \u2014 from security architecture through software development security to operations.",
    overview_p2="Nexperts CISSP is delivered as a 7-day intensive against the 2026 CBK, with daily 100-question mock drills, three full timed mocks, and an instructor who maintains active CISSP, CCSP and ISO 27001 Lead Auditor credentials.",
    overview_quote="The CISSP exam is harder than the material. Most candidates know the material. Few have practised manager-mindset thinking under 4 hours of sustained pressure. We coach the mindset.",
    overview_p3="The 2026 CBK refresh strengthens cloud security, AI/ML security, zero-trust architecture and modern cryptography. We teach with current MY banking, government and healthcare CISO context throughout.",
    who_for=[
        ("\U0001F6E1\uFE0F","Senior security engineers","The natural credential to formalise senior security careers."),
        ("\U0001F3DB\uFE0F","CISO aspirants","CISSP is the de-facto required credential for CISO roles in MY banks and GLCs."),
        ("\U0001F4BC","Security consultants","Big-4 and tier-1 consultancies require CISSP for senior security advisory."),
        ("\U0001F50D","Security architects","CISSP solidifies architecture credibility across all 8 security domains."),
        ("\U0001F4CA","Pre-CCSP / SSCP candidates","CISSP is the foundational credential for ISC2's expert-tier track."),
        ("\U0001F4DA","Risk and compliance leads","CISSP's risk and governance depth is universally recognised."),
    ],
    prereqs=[
        "5+ years cumulative paid work experience in 2 of 8 CBK domains",
        "1 year waivable with a 4-year degree",
        "Associate of ISC2 path available without years of experience",
        "Strong English-language exam comfort (4-hour exam)",
    ],
    prereqs_note="Don't have 5 years yet? You can sit the exam and become an Associate of ISC2 \u2014 then earn the years. Ask us how.",
    curriculum_eyebrow="Course Curriculum",
    curriculum_head=("Eight domains.","CBK 2026 fully covered."),
    curriculum_intro="The 2026 CISSP CBK has eight domains: Security & Risk Management, Asset Security, Architecture & Engineering, Communication & Network Security, IAM, Assessment & Testing, Operations, Software Development Security.",
    modules=[
        ("01","Security & Risk Management (15%)",[
            "CIA triad, ethics, governance, compliance",
            "Security policies, standards, procedures, guidelines",
            "Risk management lifecycle and frameworks",
            "Threat modelling \u2014 STRIDE, PASTA, OCTAVE",
            "Business continuity and disaster recovery planning",
            "Lab: Build a CIA-driven risk register for a fictional bank",
        ]),
        ("02","Asset Security (10%)",[
            "Asset classification and labelling",
            "Data lifecycle and information handling",
            "Privacy \u2014 PDPA, GDPR, MY-specific",
            "Asset retention, secure destruction",
            "Data sovereignty and residency requirements",
            "Lab: Apply asset classification across a hospital data inventory",
        ]),
        ("03","Architecture & Engineering (13%)",[
            "Secure design principles and trust models",
            "Cryptography fundamentals through advanced",
            "Security models \u2014 Bell-LaPadula, Biba, Clark-Wilson",
            "Site, facility and physical security",
            "Cloud, IoT, SCADA, industrial control system security",
            "Lab: Design a multi-region cloud architecture under BNM RMiT",
        ]),
        ("04","Communication & Network Security (13%)",[
            "OSI / TCP-IP review with security overlay",
            "Network architecture, VPN, segmentation",
            "Wireless security \u2014 WPA3-Enterprise, EAP",
            "Voice / video / SIP security",
            "Modern \u2014 SASE, SD-WAN security, zero trust networking",
            "Lab: Design a zero-trust network for a fintech",
        ]),
        ("05","IAM (13%)",[
            "Identity lifecycle, federation, SSO",
            "Authentication \u2014 MFA, FIDO2, biometric",
            "Authorisation models \u2014 RBAC, ABAC, ReBAC",
            "Privileged access management (PAM)",
            "Identity governance and access reviews",
            "Lab: Design IAM lifecycle for an MY bank merger",
        ]),
        ("06","Assessment & Testing (12%)",[
            "Security assessment methodology",
            "Vulnerability assessment and pen testing",
            "Audit \u2014 ISO 27001, SOC 2, BNM RMiT",
            "Reporting and metrics",
            "Continuous monitoring and SIEM",
            "Lab: Run an SOC 2 readiness gap analysis",
        ]),
        ("07","Operations (13%)",[
            "Investigations \u2014 evidence, chain of custody",
            "Logging, monitoring, SIEM, SOAR",
            "Incident response and forensics",
            "Patch management, change management",
            "Recovery strategies and BCP testing",
            "Lab: Run a tabletop ransomware response exercise",
        ]),
        ("08","Software Development Security (11%)",[
            "Secure SDLC and shift-left security",
            "OWASP Top 10 and secure coding",
            "API security and modern web threats",
            "DevSecOps and security automation",
            "AI / ML security and governance",
            "Lab: Run a secure code review on a sample app",
        ]),
    ],
    labs_eyebrow="Hands-On CBK Drills",
    labs_head=("100-Q daily.","Manager-mindset drills."),
    labs_intro="CISSP is more about thinking than building. We run 100-question daily drills focused on manager-mindset pattern recognition, plus tabletop exercises for risk, IR and BCP scenarios.",
    labs=[
        ("01","CIA Risk Register","Build a 30-row risk register tied to CIA impact scoring.","lt-defend","Risk"),
        ("02","Threat Modelling","Run STRIDE on a fictional banking app architecture.","lt-defend","Threat"),
        ("03","Zero-Trust Network","Design a zero-trust segmentation for a fintech.","lt-defend","Network"),
        ("04","IAM Lifecycle","Design IAM lifecycle for an MY bank merger.","lt-defend","IAM"),
        ("05","SOC 2 Readiness","Audit gap analysis for SOC 2 readiness.","lt-defend","Audit"),
        ("06","Tabletop Ransomware","Run an IR tabletop on a ransomware scenario.","lt-forensic","IR"),
        ("07","BCP Walkthrough","Run a BCP walkthrough exercise for a fictional GLC.","lt-defend","BCP"),
        ("08","Secure Code Review","Run secure code review on sample React + Node app.","lt-defend","SDLC"),
        ("09","Manager-Mindset Drills","Daily 100-question drills focused on manager-mindset trap-spotting.","lt-recon","Mindset"),
    ],
    labs_footer="+ Daily 100-question drills throughout 7 days. CBK reference workbook for ongoing reference.",
    exam_eyebrow="Exam Information",
    exam_head=("CAT format.","Adaptive testing."),
    exam_intro="The CISSP exam uses Computer Adaptive Testing (CAT). 100\u2013150 questions across the 8 CBK domains in up to 4 hours. The exam adapts to your performance \u2014 it gets harder as you go. Manager-mindset trap-spotting is the differentiator.",
    exam_main=dict(name="CISSP CAT Exam",rows=[
        ("Questions","100\u2013150 (CAT adaptive)"),
        ("Duration","Up to 4 hours"),
        ("Passing score",'<span class="pass-highlight">700 / 1000 (scaled)</span>'),
        ("Format","Pearson VUE (in-person)"),
        ("Validity","3 years (120 CPE renewal)"),
        ("Industry avg pass rate",'<span class="fail-note">~50% first attempt</span>'),
        ("Nexperts pass rate",'<span class="pass-highlight">91% first attempt</span>'),
    ]),
    exam_optional=dict(name="CISSP Career Path",rows=[
        ("Stacks with","CISSP \u2192 CCSP / SSCP concentrations"),
        ("MY salary uplift","Average +RM 3,500/mo post-cert"),
        ("Voucher","Bundled \u2014 ISC2 voucher included"),
        ("Renewal","120 CPEs over 3 years"),
        ("MY recognition","Required for most MY CISO and senior security roles"),
        ("Industry depth","Top-3 most-respected security credential globally"),
        ("Career fit","CISO, security architect, principal security engineer"),
    ]),
    mock_title="Our CISSP 4-Mock Programme",
    mock_programme=[
        ("01","Diagnostic Mock","Day 2. Maps weak domains. Average score: 56%."),
        ("02","Manager-Mindset Mock","Day 4. Manager-mindset trap focus. Average score: 67%."),
        ("03","Domain-Heavy Mock","Day 6. Heavy in weak domains. Average score: 76%."),
        ("04","Final Clearance","Day 7. Full timed simulation. 78%+ before booking. Average score: 84%."),
    ],
    pass_rate=91,
    pass_head_html='91% of our CISSP candidates<br>pass <em>on first attempt.</em>',
    pass_intro="The global CISSP first-attempt rate is around 50%. Our 91% comes from daily 100-question manager-mindset drills, four timed mocks, three tabletop exercises, and an instructor who has prepped 600+ candidates over 11 years.",
    pass_pills=["Daily 100-Q drills","Manager-mindset coaching","91% first attempt","CBK 2026 aligned","Free retake voucher"],
    pass_compare=[
        ("Industry average: ~50%","Most candidates know the technical material but fail on manager-mindset traps. CISSP rewards 'what would a CISO do' not 'what would the engineer do'."),
        ("Nexperts: 91%","We retrain how you read CISSP questions. We force manager-mindset application daily. We hard-gate at 78% on the final mock before letting you book."),
    ],
    next_eyebrow="Your Certification Journey",
    next_head=("CISSP is","security apex."),
    next_steps_intro="From CISSP you specialise into CCSP (cloud), SSCP (operations) or pursue CISSP concentrations \u2014 ISSAP (architecture), ISSEP (engineering), ISSMP (management).",
    next_steps=[
        ("Before this","Security+ / CySA+ / SC-200","Foundational security fluency is assumed. Without 5 years of security experience, the manager-mindset is hard to internalise.","View Security+ \u2192"),
        ("You are here","CISSP","Senior security professional. 8 CBK domains spanning architecture, operations, IAM, software security and risk.","Currently viewing \u2192"),
        ("Recommended next","CCSP or CISSP Concentration","CCSP specialises into cloud security. ISSAP / ISSEP / ISSMP deepen into architecture, engineering or management.","View CCSP \u2192"),
    ],
    path_name="ISC2 security leader",
    path_chips=[("Security+","prev"),("CISSP","you"),("CCSP / Concentration","next"),("CISO / vCISO","prev"),("ISC2 Fellow","prev")],
    salary_html='Expected salary range after CISSP: <strong style="color:#86efac">RM 14,000 \u2013 RM 25,000/month</strong> for CISO, security architect and principal security engineer roles in Malaysia.',
    reviews_eyebrow="Student Reviews",
    reviews_head=("What our CISSP","graduates say."),
    reviews_summary=("4.9",90,8,2,162),
    reviews=[
        ("\u2605\u2605\u2605\u2605\u2605","Manager-mindset coaching changed everything. I'd attempted CISSP before and failed. Nexperts retrained how I read questions. Passed the second attempt at 130 questions \u2014 the early cut.","rav-b","KS","Khalil Saad","CISO \u00b7 Bank Muamalat","\u2713 Passed at 130 questions"),
        ("\u2605\u2605\u2605\u2605\u2605","Daily 100-question drills were brutal but transformative. By day five I was spotting the trap before reading the answer choices. Game changing.","rav-m","RM","Rosmadi Mansor","Security Architect \u00b7 Maybank","\u2713 Passed at 125 questions"),
        ("\u2605\u2605\u2605\u2605\u2605","Tabletop ransomware response was unique. Six weeks later we faced a real incident. Our IR play was exactly the tabletop. The course paid back in one event.","rav-g","SP","Suvarna Perumal","Head of InfoSec \u00b7 KPJ Healthcare","\u2713 Passed at 100 questions"),
        ("\u2605\u2605\u2605\u2605\u2605","CBK domain coverage is comprehensive but never bloated. Software security and AI security depth was unexpected and is paying dividends in our DevSecOps rollout.","rav-a","DC","Devraj Chandran","Principal Security Engineer \u00b7 PETRONAS","\u2713 Passed at 120 questions"),
    ],
    price="RM 7,500", price_orig="RM 9,500", price_save="Save 21%",
    price_note="Per person \u00b7 Includes ISC2 voucher, CBK courseware, mock programme",
    sidebar_meta=[
        ("Duration","7 days / 56 hrs"),
        ("Next intake","13 October 2026"),
        ("Format","On-site \u00b7 Hybrid"),
        ("Level","Expert"),
        ("Language","English"),
        ("Cert body","ISC2"),
        ("Exam",'<span class="smeta-badge">Included</span>'),
    ],
    whats_included=[
        "ISC2 official CBK 2026 courseware",
        "ISC2 exam voucher",
        "Daily 100-question drill packs",
        "4 full timed mock exams",
        "Three tabletop exercises (risk, IR, BCP)",
        "Manager-mindset coaching workshop",
        "Post-course instructor access (90 days)",
        "Free retake voucher (conditions apply)",
        "Digital badge via ISC2",
    ],
    verify_items=[
        "Verifiable on ISC2 portal",
        "Digital badge via Credly",
        "Top-3 security credential globally",
        "Required for most MY CISO and security architect roles",
    ],
    guarantee_text="Hit the 78% mock threshold and don't pass first attempt? ISC2 retake voucher on us.",
))


# 2. CISM
BATCH.append(dict(
    slug="cism",
    title="CISM",
    title_html='Certified Information<br><em>Security Manager (CISM)</em>',
    vendor_short="ISACA", watermark="CISM", crumb_vendor="ISACA",
    subtitle="ISACA's flagship information security management credential. Four domains spanning governance, risk, program development and incident management \u2014 the credential of choice for security managers and CISO aspirants.",
    badges=[("cb-vendor","ISACA Authorized"),("cb-level","Expert"),("cb-new","2026 Job Practice"),("cb-hot","CISO Track")],
    hero_meta=common_meta("5 days / 40 hrs","Instructor-Led + Domain Drills","On-site \u00b7 Hybrid",92,"20 October 2026"),
    hero_img=HERO_IMG,
    quick_wins=[
        ("\U0001F4CA","Governance fluency","Information security governance, strategy and reporting"),
        ("\u2696\uFE0F","Risk management depth","Information security risk management and program development"),
        ("\U0001F6E1\uFE0F","Program leadership","Information security program development and management"),
        ("\U0001F525","Incident management","Information security incident management end-to-end"),
    ],
    overview_eyebrow="What this course is",
    overview_head=("CISM is","security management."),
    overview_p1="The CISM (Certified Information Security Manager) is ISACA's flagship security management credential. It validates that you can build, lead and manage an enterprise information security program \u2014 not just engineer it.",
    overview_p2="Nexperts CISM is delivered as a 5-day intensive against the 2026 Job Practice. The course is heavy on case studies, tabletop exercises and ISACA's specific question style \u2014 which differs measurably from CISSP.",
    overview_quote="CISM is not CISSP. CISM is more management, less technical. It is more aligned with ISACA's audit-and-governance heritage. We coach the difference, not just the material.",
    overview_p3="The 2026 Job Practice update emphasises modern threat landscape (AI threats, supply-chain), zero-trust governance and BNM RMiT alignment. We teach with current MY banking, GLC and government CISO case studies throughout.",
    who_for=[
        ("\U0001F4BC","Security managers","The natural credential to formalise security management careers."),
        ("\U0001F3DB\uFE0F","CISO aspirants","CISM is widely accepted for CISO roles, especially in MY banking and GLC."),
        ("\U0001F50D","CISA holders going security","The natural sister-credential for CISAs moving into security leadership."),
        ("\U0001F4CA","Pre-CISO security architects","CISM bridges architecture into governance and program management."),
        ("\U0001F4BB","Risk and compliance leads","CISM's risk depth is universally recognised in MY enterprise risk teams."),
        ("\U0001F4DA","Big-4 security advisory","Big-4 consultancies often require either CISSP or CISM \u2014 CISM is increasingly preferred."),
    ],
    prereqs=[
        "5+ years information security work experience",
        "Minimum 3 years in CISM job practice areas",
        "1 year waivable with CISA / CISSP / certain degrees",
        "ISACA membership recommended",
    ],
    prereqs_note="Don't have 5 years yet? Many students sit and pass CISM, then earn the years. We can advise on the work-experience attestation process.",
    curriculum_eyebrow="Course Curriculum",
    curriculum_head=("Four domains.","Security management mastery."),
    curriculum_intro="The 2026 CISM Job Practice has four domains: Information Security Governance (17%), Information Security Risk Management (20%), Information Security Program (33%), Information Security Incident Management (30%).",
    modules=[
        ("01","Information Security Governance (17%)",[
            "Enterprise governance and security alignment",
            "Information security strategy development",
            "Roles, responsibilities, RACI for security",
            "Performance metrics and reporting to the board",
            "Information security policies, standards, procedures",
            "Lab: Draft a board-level security report for an MY bank",
        ]),
        ("02","Information Security Risk Management (20%)",[
            "Risk identification, analysis and evaluation",
            "Inherent vs residual risk concepts",
            "Risk treatment options \u2014 accept, mitigate, transfer, avoid",
            "Third-party / supply chain risk management",
            "Risk monitoring and reporting cycles",
            "Lab: Build a quantitative risk register for a fintech",
        ]),
        ("03","Information Security Program (33%)",[
            "Program development and resources",
            "Information security architecture and standards",
            "Awareness and training program design",
            "Vendor and third-party security management",
            "Program management metrics and KPIs",
            "Lab: Design an enterprise security program from scratch",
        ]),
        ("04","Information Security Incident Management (30%)",[
            "Incident management planning and procedures",
            "Detection, analysis, containment, eradication, recovery",
            "Forensic investigation principles",
            "Communications during incidents \u2014 internal and external",
            "Post-incident review and lessons learned",
            "Lab: Run a tabletop ransomware response with regulatory comms",
        ]),
        ("05","CISM Exam Strategy & Trap-Spotting",[
            "ISACA question style vs ISC2 question style",
            "Manager-mindset trap-spotting drills",
            "Best vs better answer disambiguation",
            "Time management across 150 questions",
            "Domain weighting strategy",
            "Lab: 150-question full timed simulation",
        ]),
    ],
    labs_eyebrow="Hands-On Management Drills",
    labs_head=("Daily drills.","Three tabletop sims."),
    labs_intro="CISM is more about management thinking than technical execution. We run daily 50-question manager-mindset drills, plus three tabletop exercises spanning incident response, board reporting and supply-chain risk.",
    labs=[
        ("01","Board Report Drafting","Draft a board-level security KPI report for an MY bank.","lt-recon","Governance"),
        ("02","Quantitative Risk Register","Build an SLE / ARO / ALE risk register for a fintech.","lt-defend","Risk"),
        ("03","Program Charter","Charter an enterprise security program from scratch.","lt-recon","Program"),
        ("04","Tabletop Ransomware","Lead a ransomware IR tabletop. Manage regulator comms.","lt-forensic","Incident"),
        ("05","Supply-Chain Tabletop","Run a supply-chain compromise scenario across 3 vendors.","lt-defend","Supply Chain"),
        ("06","Awareness Program Design","Design a 12-month security awareness program.","lt-recon","Awareness"),
        ("07","Vendor Security Audit","Audit a fictional MSP for security maturity.","lt-defend","Vendor"),
        ("08","Daily Drills","50-question manager-mindset drills daily with debrief.","lt-recon","Mindset"),
        ("09","Final Sim","Full 150-question timed simulation with debrief.","lt-recon","Sim"),
    ],
    labs_footer="+ Daily 50-question drills. Three tabletop scenarios. Domain-specific reference workbook.",
    exam_eyebrow="Exam Information",
    exam_head=("One exam.","Management-focused."),
    exam_intro="The CISM exam is 150 questions across 4 domains in 4 hours. The exam style is distinct from CISSP \u2014 ISACA-style 'best answer among acceptable answers' rather than 'right vs wrong'. Trap-spotting is the differentiator.",
    exam_main=dict(name="CISM Exam (2026 Job Practice)",rows=[
        ("Questions","150 multiple choice"),
        ("Duration","240 minutes"),
        ("Passing score",'<span class="pass-highlight">450 / 800 (scaled)</span>'),
        ("Format","Pearson VUE / Online proctor"),
        ("Validity","3 years (120 CPE renewal)"),
        ("Industry avg pass rate",'<span class="fail-note">~58% first attempt</span>'),
        ("Nexperts pass rate",'<span class="pass-highlight">92% first attempt</span>'),
    ]),
    exam_optional=dict(name="CISM Career Path",rows=[
        ("Stacks with","CISA \u2192 CISM \u2192 CRISC / CGEIT"),
        ("MY salary uplift","Average +RM 2,800/mo post-cert"),
        ("Voucher","Bundled \u2014 ISACA voucher included"),
        ("Renewal","120 CPEs over 3 years"),
        ("MY recognition","Widely accepted for CISO roles in MY banking and GLC"),
        ("Industry depth","Top management security credential alongside CISSP"),
        ("Career fit","CISO, security manager, head of risk"),
    ]),
    mock_title="Our CISM 3-Mock Programme",
    mock_programme=[
        ("01","Diagnostic Mock","Day 2. Maps weak domains. Average score: 58%."),
        ("02","ISACA-Style Mock","Day 4. ISACA question-style focus. Average score: 73%."),
        ("03","Final Clearance","Day 5. Full timed 150-question sim. 78%+ before booking. Average score: 84%."),
    ],
    pass_rate=92,
    pass_head_html='92% of our CISM candidates<br>pass <em>on first attempt.</em>',
    pass_intro="The global CISM first-attempt rate is around 58%. Our 92% comes from daily ISACA-style trap-spotting drills, three tabletop scenarios, three timed mocks, and an instructor with active CISM, CISA and CRISC credentials.",
    pass_pills=["Daily 50-Q drills","ISACA trap-spotting","92% first attempt","Three tabletops","Free retake voucher"],
    pass_compare=[
        ("Industry average: ~58%","Most candidates use CISSP-style preparation for CISM. They miss the ISACA-style 'best answer among acceptable' trap completely."),
        ("Nexperts: 92%","We coach the ISACA style explicitly. We force daily ISACA-style drills. We hard-gate at 78% on the final mock before letting you book."),
    ],
    next_eyebrow="Your Certification Journey",
    next_head=("CISM unlocks","CISO and risk leadership."),
    next_steps_intro="From CISM you specialise laterally into CRISC (risk), CGEIT (governance) or CDPSE (privacy), or vertically into CISO and head-of-risk roles.",
    next_steps=[
        ("Before this","CISA / CISSP / Security+ / 5 yrs experience","Either an audit (CISA), security technical (CISSP) or operational background works as a base.","View CISA \u2192"),
        ("You are here","CISM","Information security manager. Governance, risk, program development and incident management at enterprise scale.","Currently viewing \u2192"),
        ("Recommended next","CRISC or CGEIT","CRISC specialises into risk. CGEIT specialises into IT governance. Both are ISACA-track credentials.","View CRISC \u2192"),
    ],
    path_name="ISACA security leader",
    path_chips=[("CISA / CISSP","prev"),("CISM","you"),("CRISC / CGEIT","next"),("CISO / Head of Risk","prev"),("ISACA Fellow","prev")],
    salary_html='Expected salary range after CISM: <strong style="color:#86efac">RM 13,000 \u2013 RM 23,000/month</strong> for CISO, security manager and head-of-risk roles in Malaysian banking and enterprises.',
    reviews_eyebrow="Student Reviews",
    reviews_head=("What our CISM","graduates say."),
    reviews_summary=("4.9",90,8,2,118),
    reviews=[
        ("\u2605\u2605\u2605\u2605\u2605","ISACA-style trap-spotting was the differentiator. I'd done CISSP last year. Tried to prepare CISM the same way \u2014 nearly failed a mock. Nexperts retrained me. Passed comfortably first attempt.","rav-b","JM","Jamaludin Md Yusof","CISO \u00b7 SME Bank","\u2713 Passed first attempt"),
        ("\u2605\u2605\u2605\u2605\u2605","Three tabletops were brutally realistic. Six weeks later we ran a real ransomware tabletop at our bank \u2014 my preparation made me the de-facto lead. Course paid back immediately.","rav-m","KH","Kalpana Hari","Head of Risk \u00b7 Hong Leong Bank","\u2713 Passed first attempt"),
        ("\u2605\u2605\u2605\u2605\u2605","Board report drafting was unexpected and immediately useful. I now write the security board update at my GLC \u2014 the format from class became our standing template.","rav-g","NA","Nik Adibah","Security Manager \u00b7 PETRONAS","\u2713 Passed first attempt"),
        ("\u2605\u2605\u2605\u2605\u2605","Quantitative risk register module was a step-change. I rebuilt our risk register in two weeks using SLE/ARO/ALE \u2014 exec engagement on risk numbers is night and day better.","rav-a","RT","Ranjit Tan","Senior Risk Manager \u00b7 OCBC","\u2713 Passed first attempt"),
    ],
    price="RM 6,800", price_orig="RM 8,200", price_save="Save 17%",
    price_note="Per person \u00b7 Includes ISACA voucher, courseware, mock programme",
    sidebar_meta=[
        ("Duration","5 days / 40 hrs"),
        ("Next intake","20 October 2026"),
        ("Format","On-site \u00b7 Hybrid"),
        ("Level","Expert"),
        ("Language","English"),
        ("Cert body","ISACA"),
        ("Exam",'<span class="smeta-badge">Included</span>'),
    ],
    whats_included=[
        "ISACA official CISM Job Practice 2026 courseware",
        "ISACA exam voucher",
        "Daily 50-question drill packs",
        "3 full timed mock exams",
        "Three tabletop exercises",
        "ISACA-style trap-spotting workshop",
        "Post-course instructor access (90 days)",
        "Free retake voucher (conditions apply)",
        "Digital badge via ISACA",
    ],
    verify_items=[
        "Verifiable on ISACA portal",
        "Digital badge via Credly",
        "Widely accepted for MY CISO roles",
        "Pathway to CRISC / CGEIT / CDPSE",
    ],
    guarantee_text="Hit the 78% mock threshold and don't pass first attempt? ISACA retake voucher on us.",
))
